[#ch1, short="La Posesión de la Fe Viva y Sus Frutos"]
== Capítulo 1. La Posesión de la Fe Viva y Sus Frutos / Y Cómo Difiere de la Fe Muerta del Mundo

Puesto que la verdadera fe es el único fundamento de la felicidad eterna del hombre,
y lo único que le permite a la criatura tener entrada a
su Creador (porque "`sin fe es imposible agradar a Dios`"^
footnote:[Hebreos 11:6]),
y habiendo encontrado por experiencia cómo la fe verdadera y viva (que tiene
el poder vivo) difiere grandemente de esa fe que está muerta y sin dicho poder,
y además viendo cómo muchos en este día están en reposo en una fe muerta,
con sus almas en la tumba--por todo esto,
me siento movido en amor a declarar algo respecto a la verdadera fe de Cristo,
la cual he encontrado eficaz para salvar y reconciliar con Dios.

Primero, hablaré un poco sobre la fe (o creencia) que he visto en el mundo,
la cual es una fe externa,
que solo tiene como fundamento la historia que las
Escrituras relatan acerca de Dios y de Cristo,
y acerca de lo que Cristo hizo en ese cuerpo que los Judíos crucificaron
en Jerusalén. Esta es una fe que no Lo conoce en el Espíritu,
ni cree en Él como el Emanuel para todas las generaciones,
y por lo tanto no hace que el creyente sea conforme a Él,
lo cual ocurre por medio de Su venida otra vez en el mismo Espíritu y poder,
que obra en ellos la misma voluntad, mente,
afectos y obediencia al Padre (según la medida de
cada uno) que estaban en Él--el verdadero Ejemplo,
Autor, Hacedor y Consumador de la fe verdadera y viva.

De esta fe muerta (que tiene una variedad de apariencias
según las diversas opiniones de los hombres),
vienen todos los espíritus inmundos que viven en toda clase
de abominación que se pueda mencionar en el mundo.
Todo tipo de sectas y denominaciones religiosas se cubren con esta fe.
Ella es su fuerza,
y en ella se refugian contra todas las reprensiones internas o externas,
aunque viven abiertamente en las fornicaciones más grandes
contra el Espíritu de Santidad que puedan mencionarse.
Y aunque se mantienen lejos de la vida de Cristo, aun así,
creen que Cristo vino a salvar a los pecadores,
y dicen que "`entre los pecadores ellos son los primeros`",
y que "`los que están sanos no tienen necesidad de médico`", etc.,
como si mientras más grande fuera su iniquidad, más cerca estuvieran de Cristo.
Y por esta fe falsa,
Aquel que vino a salvar a las personas del pecado y a guiar fuera del pecado,
tanto mediante Su ejemplo como por Su Espíritu,
es convertido en una cubierta para toda clase de contaminación de carne y de espíritu,
que fortalece el corazón de los impíos contra la vida de santidad, algunos en un pecado,
y otros en otro.
Sí, con esta fe todas las denominaciones se fortalecen y endurecen sus corazones contra
la luz de Cristo y contra el Espíritu que redarguye y convence al mundo de pecado,
y que verdaderamente guía fuera del mismo.
Así, el santo Testigo de Dios en todos los hombres es pisoteado,
y casi nadie le presta atención,
ni cree que es el camino al Padre--a pesar de que
el mundo no tiene otra luz más que esta,
y solamente en ella hay promesa de vida.
Esta fe me parece que es la fe del diablo,
o la "`fe muerta`" de la cual habla el apóstol,
aunque ella quizás esté incluso más endurecida contra el temor del Señor;
porque cuando los demonios creen al menos tiemblan.
Así que ahora dejaré esta fe,
siendo ya juzgada por sus frutos por medio de la luz de
Cristo en cada corazón honesto que ama la santidad.

Ahora hablaré algo respecto a esa fe en la cual he encontrado
una medida de la vida de Cristo revelada en mí,
en cuya vida (y solo en ella) se experimenta la propiciación verdadera y eterna,
y la unión con el Dios santo, a la cual ninguna cosa inmunda tiene acceso.
Esta fe no es un concepto de lo que fue hecho en otro tiempo
(pasado o futuro--cientos o miles de años atrás),
sino aquello que lleva a la obra de la nueva creación en este día,
y del nuevo nacimiento que es engendrado espiritualmente,
y que nace y es llevado a la luz por el Espíritu,
sin el cual nadie puede ver el reino de Dios ni entrar en él. Y
esta fe no actúa por medio de la comprensión mental de nuestro cerebro,
como si,
por haber entendido o declarado algo acerca de Jesucristo en palabras o pensamientos,
yo por lo tanto hubiera aprendido a Cristo, o realmente lo conociera,
o hubiera crecido en Él a la medida de un varón perfecto.
Los que poseen esta fe conceptual engañan a sus propias almas, y también engañan a otros,
porque hablan y se jactan de lo que Dios no ha hecho en ellos,
y alejan a los hombres de la medida de la obra presente de Dios en ellos.
Pero la fe viva, cuyo misterio es "`guardado con limpia conciencia,`"^
footnote:[1 Timoteo 3:9]
obra poderosamente en el Espíritu (por amor a Él^
footnote:[Gálatas 5:6]), sacando la vieja levadura,
purificando el corazón y haciendo nuevas todas las cosas.
De hecho, esta fe juzga,
mata y crucifica con Cristo en el Espíritu las obras de la carne,
echando fuera de mí todo lo que no es de Dios,
y renovando en mi interior las cosas de Dios, en su orden,
por Su gran poder en mí. Por esto el alma es levantada de la tumba,
y el que está muerto es restaurado a la vida--verdaderamente, y no conceptualmente.

=== El Fundamento y La Obra de la Fe Viva

Ahora bien,
el fundamento o principio de esta fe es creer verdaderamente
en eso que Cristo hizo y sufrió en Jerusalén,
y que allí, en ese cuerpo, llevó los pecados del mundo,
aplacó la ira de Dios con respecto a los pecados pasados, venció la muerte,
el infierno y la tumba,
y abrió un camino para que la Semilla pudiera levantarse por todo el mundo,
en todos aquellos que estén dispuestos a creer en Su Luz,
la cual entonces resplandeció por medio de Él a todos los hombres,
por la cual Él puede ser visto como "`el camino, la verdad y la vida,`"^
footnote:[Juan 14:6]
al triunfar públicamente sobre todo lo que se ha levantado por encima de la Semilla.
Mucho más podría decirse respecto a lo que Él logró en ese entonces,
todo lo cual creí conforme a las Escrituras, lo cual fue como una puerta,
a través de la cual podía recibir a Cristo desde el cielo en el mismo Espíritu y poder.
Sin haber creído no hubiera podido recibir el don de ese Espíritu Santo.
Porque Dios desde el principio determinó que el pacto de vida y
poder eterno sólo puede recibirse por medio de la fe en Él,
quien, en el cumplimiento del tiempo,
fue manifestado en carne para quitar los pecados pasados,
y abrir un camino para que la resurrección de la vida viniera sobre todos,
y así salvar de los pecados de ahí en adelante.

El primer efecto de esta fe fue sacar mi mente de todos mis pecados pasados,
y volverla a Dios y a la vida de santidad que entonces creía posible alcanzar.
Y en esta fe, vi la necesidad de recibir poder para crecer en Él,
hasta la medida de Su plenitud y estatura,
y entendí que un tipo de fe inferior no podría salvarme,
sino sólo la perfecta "`fe del Hijo de Dios,`"^
footnote:[Gálatas 2:20]
la cual no había recibido en el pasado.
Pero ahora, en la luz,
recibí esta fe con tal alegría de corazón que me quitó el deleite que tenía en el pecado,
y volvió mi rostro hacia la perfección en Cristo,
que en verdad era el gozo puesto delante de mí. Sin embargo, en este punto,
la obra no estaba hecha o terminada en mí,
a pesar de que había recibido la fe y esperanza del Hijo de Dios,
y había sido vuelto de todo mi pecado pasado y de mi justicia propia--de modo que,
si en ese momento hubiera dejado este cuerpo,
no habría muerto en un tipo de fe inferior a la santa fe de Jesucristo; y, por lo tanto,
estando vuelto a Su Espíritu, fuera de las obras de la carne,
estaba apartado del camino de mi pecado, y por lo tanto de la condenación.

Sin embargo, todavía había una gran obra que hacerse en mí,
antes de que pudiera experimentar la libertad del cuerpo de muerte,
y ver la raíz y fundamento del mal removido, y la Semilla levantada para reinar,
y el alma llevada a la ciudad santa,
donde se encuentra la comunión en el Padre y en el Hijo,
la gloriosa libertad de la nueva criatura, y donde "`todas las cosas son de Dios,`"^
footnote:[2 Corintios 5:18]
como lo testifican las Escrituras.
Esta fe no formó en mí un concepto elevado de mí mismo,
como para que me gloriara en mi conocimiento,
y me convirtiera en un maestro de otros respecto a lo que había entendido sin la vida;
más bien, me humilló y me llevó a la obediencia del Espíritu de Luz,
a esperar ahí por la resurrección de vida.
Y llegué a ver en esa luz que las inclinaciones pecaminosas
todavía obraban desde el antiguo terreno y raíz,
y que esto debía ser removido por el poder de Cristo obrando en el Espíritu.
Vi que era necesaria la obediencia y la vigilancia en la luz,
y que sin la obediencia a esta fe no podía llegar a tener victoria sobre la enemistad,
ni a "`la libertad gloriosa de los hijos de Dios.`"^
footnote:[Romanos 8:21]
Porque,
aunque esta fe había vuelto mi corazón hacia Cristo
y me había dado la esperanza de llegar a Él,
aun así, todavía no lo había aprendido,
y Él aún no estaba formado en mí. Entonces fui llevado en la luz de Cristo
a ver lo que realmente poseía de este Tesoro en mi vaso de barro,
y me di cuenta de que era muy poquito,
y vi que Su Semilla era la más pequeña de todas las semillas en mi huerto.
De este modo me volví pequeño ante ese ojo que me dijo la verdad,
aunque antes me consideraba grande en mi propia opinión.

Y así, fui llevado al principio de la obra de la Palabra de Cristo,
o a los primeros principios de la doctrina de Cristo,
para que con esa luz que enseña a Cristo pudiera aprender a Cristo en cada medida de Él,
conforme creciera en Él. Fui llevado a conocer a Aquel que "`nació bajo la ley,`"^
footnote:[Gálatas 4:4]
y a ver el fundamento del "`arrepentimiento de obras muertas,
de la doctrina de bautismos y del juicio eterno.`"^
footnote:[Hebreos 6:1-2]
Entonces llegué a entender en la verdad y en la vida lo que hacían aquellos a quienes
el apóstol exhortó a "`obrar su propia salvación con temor y temblor,`"^
footnote:[Filipenses 2:12 RV 1602 Purificada]
incluso después de que habían creído plenamente en
lo que Cristo había hecho por ellos en Jerusalén,
en Su cuerpo preparado.
Él me reveló muchas otras escrituras conforme lo aprendía a Él,
que antes eran un misterio, cuando trataba de entenderlas como conceptos sin Su vida.
Pero estas eran abiertas por la revelación de Jesucristo, a medida que se cumplían en mí,
siendo llevado en la obra de fe por el Espíritu que las escribió.

Entonces llegué a ver que, por la ley, debía ser redimido de la ley,^
footnote:[Gálatas 2:19]
y que no iba a ser redimido de ella al invalidarla, sino al cumplirla.
Hasta entonces la ley se enseñoreaba de mí,^
footnote:[Romanos 7:1]
y el pecado tomaba ocasión por ella para fortalecerse en mí.^
footnote:[Romanos 7:5, 8.]
Pero a medida que crecía en el Espíritu y poder de Cristo,
era llevado en Él a través de la ley (hallándola cumplida en Él),
y así llegué a estar "`muerto a la ley`"^
footnote:[Romanos 7:4]
conforme se cumplía en mí. Entonces me di cuenta
qué tan verdaderas eran las palabras de Cristo:
"`No he venido para abrogar la ley, sino para cumplirla,`"^
footnote:[Mateo 5:17]
y, "`Más fácil es que pasen el cielo y la tierra que una jota de la ley pase,
hasta que todo se haya cumplido.`"^
footnote:[Lucas 16:17; Mateo 5:18]
En verdad, yo no necesitaba una interpretación para esta escritura,
sino su cumplimiento en Cristo Jesús. Y así vi que la ley
es ese ayo que nos lleva a Cristo (a Cristo formado),
y vi como somos "`herederos bajo tutores y curadores`"^
footnote:[Gálatas 4:2]
antes de experimentar la libertad de los Hijos de Dios, o la perfecta libertad.
Y vi que la Escritura no podía quebrantarse ni torcerse,
sino que debía aprenderse en la vida de ella para salvación,
aunque "`los indoctos la tuercen para su propia perdición,`"^
footnote:[2 Pedro 3:16]
con significados sin vida.
Sí, "`la Escritura no es de interpretación privada,`"^
footnote:[2 Pedro 1:20]
sino que sólo el Espíritu debe abrirlas todas en el cumplimiento de ellas;
y es así como ellas "`nos pueden hacer sabios para la salvación`"^
footnote:[2 Timoteo 3:15]
por la verdadera fe que es en Cristo Jesús.

Y entonces llegué a ver claramente a Jesucristo puesto delante
de mí en todas las cosas por las que tenía que pasar,
(en esa fe que había recibido al principio) y vi
que llegar a Él era la verdadera esperanza de gloria,
y que no había otra esperanza fuera de Él. Esta esperanza era como un ancla en todas
las tribulaciones y tentaciones por las que tuve que pasar (que no fueron pocas),
pero todo era estimado como nada cuando permanecía en esta fe,
por la esperanza que estaba en mí de ganar a Cristo.
Y a pesar de que había creído en lo que Cristo hizo en Jerusalén,
vi claramente que si no continuaba en la fe,
siguiendo al mismo Espíritu por medio de la obediencia a todas sus directrices,
manteniendo la esperanza de llegar a Cristo Jesús (el fin de esa
fe) y creciendo diariamente a la medida de Su estatura y plenitud,
sino que en lugar de esto me hubiera apartado, o detenido por el camino,
quedando corto de la guía de ese Espíritu,
habría dejado sin efecto la esperanza de gloria y la obra de mi redención. Entonces,
lo que Cristo logró en Jerusalén también hubiera
sido dejado sin efecto (con respecto a mí),
porque habiendo negado mi primera fe, no podría ser salvo de la ira por venir.
Por lo tanto, vi que debía seguirlo en el Espíritu fielmente y sin dudar,
a través de todas las pruebas y tentaciones,
y de este camino Él fue un ejemplo perfecto cuando anduvo en la carne.
Y a través de las Escrituras yo obtenía esperanza, puesto que Él, antes de mí,
pasó por el mismo camino en el que ahora me llevaba.
Y vi que Él era el mismo en todas las generaciones--porque,
así como Él fue en ese entonces, así ha sido en todos Sus santos que Lo han seguido.
Y así como ellos se exhortaban unos a otros a poner los ojos en
Él durante su viaje (quien es el Autor y Consumador de su fe),
y a considerarlo como un ejemplo (quien sufrió tal contradicción
de pecadores) para que no se cansaran de sufrir,
ni su ánimo desmayara, asimismo yo tenía mis ojos puestos en la misma vida en Él,
(que también estaba en aquellos que iban tras Él)
de modo que mi fe y paciencia fueron duplicadas,
y mi obediencia fue sin dudas,
y mi esperanza de llegar al fin fue afirmada--cuyo fin era ganar a Cristo en mí,
la esperanza de gloria.

¡Oh el gran misterio de la fe,
que está escondido de todos hasta la revelación de Cristo Jesús! Pero
cuando los santos y apóstoles tenían a Cristo revelado en ellos,
entonces fueron hechos ministros competentes de Él, y tenían el misterio abierto,
y predicaban sin dudar el misterio de la piedad.
Sí, "`indiscutiblemente, grande es este misterio de la piedad,`"^
footnote:[1 Timoteo 3:16]
que todavía está escondido del mundo--Dios manifestado en carne.
Este misterio de la fe debe guardarse en una conciencia limpia.

Entonces, cuando llegué a experimentar estas cosas,
me di cuenta de que mi fe era la misma "`fe una vez dada a los santos.`"^
footnote:[Judas 1:3]
Y llegué a conocer "`la buena batalla de la fe,`"^
footnote:[1 Timoteo 6:12]
y a experimentar esa "`fe que vence al mundo,`"^
footnote:[1 Juan 5:4]
la cual tiene la promesa y herencia de la vida eterna.
Y así, en mi aprendizaje de Cristo,
llegué a entender la diferencia entre la fe de Cristo que incrementa "`de fe a fe,`"^
footnote:[Romanos 1:17]
y la fe de los demonios; entre la fe que vive y obra, y la fe muerta que no tiene obras;
entre la fe de Cristo, y esa fe que es establecida sin Cristo.
Y me di cuenta de que _no_ es de la fe de Cristo creer
que los hombres nunca podrán ser perfectos,
ni vencer al pecado y al diablo;
y que no es de la fe de Cristo invalidar la ley del Padre sin que primero sea cumplida.
Y que nunca fue de la fe de Cristo vengarse del mal,
sino al contrario vencer el mal con el bien.
Nunca fue Su fe hacer acepción de personas,
o creer que alguien podía cometer pecado y no ser esclavo del pecado.
Nunca fue Su fe demandar, contender, pelear o perseguir a nadie, ni predicar por precio,
ni servir de ninguna manera a las riquezas de este mundo.
No fue Su fe guardar Su propia voluntad, Sus propios tiempos, o las costumbres del mundo,
sino solo la voluntad y los tiempos de Su Padre en todas las cosas,
y solo lo que recibía del Padre, eso hacía, y no podía hacer nada por Sí mismo;
y nunca creyó que los que dicen y no hacen son hijos de Dios.

Pero la fe del mundo, para poder mantener sus pecados y sus deseos,
cree que aquellos que "`dicen, y no hacen,`"^
footnote:[Mateo 23:3]
son hijos de Dios, cuando en realidad son enemigos de la fe de Cristo,
la cual presenta a los hombres perfectos a Dios al expulsar estos males.
Todo lo cual llegué a ver, no por hombre, sino por revelación de Cristo.
Y en Su fe lo aprendí a Él, y así crecí más en Su fe, y en Él,
y de este modo "`Su vida se manifestó en mi cuerpo.`"^
footnote:[2 Corintios 4:10]
Y así llegué a ver qué es de Cristo en verdad (según
la verdad que está en Jesús) y qué es del mundo,
aunque sea considerado como si fuera de Cristo (a fin de oponerse
a Él). Y vi que eso que ama las cosas de este mundo no es Su amor,
que eso que toma placer en las cosas visibles no es Su gozo,
que Su libertad no está en las obras de la carne,
que la paz que permanece en pecado no es Su paz,
que la paciencia que busca su propia venganza no es Su paciencia,
que la gloria que está mezclada con orgullo no es Su gloria,
que la adoración que consiste en cosas carnales no es Su adoración,
que el honor que los hombres buscan no es Su honor,
y que el temor que es enseñado por los mandamientos de los hombres no es Su temor.
Todas los que practican estas cosas están en el mundo
y no en Él. Ellos dicen que son de Él,
pero son enemigos de Su vida, y nunca han nacido de Su Padre, ni aprendido en el Hijo.
De hecho,
fue por esa verdad y simplicidad que encontré en Cristo (de manera contraria
a la voluntad del hombre) que llegué a ver el engaño en todas estas cosas.

Y así, en la vida de Cristo aprendí cómo crece la fe de Cristo,
y cuáles son sus riquezas, y cuál es su fin,
el cual es Cristo Jesús en todas Sus operaciones.
Y también comprendí la fe del mundo, y su inmundicia,
cuyo fin no es alcanzar la santidad de Cristo en esta vida,
sino más bien vivir en los placeres del mundo y tener a Cristo como un disfraz y ser
salvos por la justicia de Otro--una justicia en la que ellos no buscan caminar.
Y, por lo tanto, la fe terrenal no obra por amor, porque no ama la vida de Cristo,
sino que hace que los hombres que ponen su mente
en cosas terrenales sean enemigos de Su cruz.
Pero la fe viva obra por amor y lleva a la vida de santidad,
y por lo tanto purifica el corazón,
y "`el misterio de ella se guarda en una limpia conciencia`"^
footnote:[1 Timoteo 3:9]
dentro de aquellos que la tienen, y no al comprender y hablar de algo que estaba en otro.
Porque hasta los demonios creen en la santidad que estaba en Cristo,
y pueden predicar al respecto, pero no pueden heredarla,
porque no aman vivir en la vida de esa santidad.

Aquí vi claramente la diferencia entre estos dos tipos de fe:
El fin de una es la vida de Cristo en la que Él caminó,
manifestada en la misma obediencia del mismo Espíritu al mismo Padre por el mismo poder,
conforme la medida de fe recibida de Dios, cuya fe es de arriba,
y por lo tanto echa mano de las cosas celestiales para obtener su fuerza,
y produce frutos celestiales.
La otra fe profesa y promete grandes cosas, pero termina en el mundo,
pone la mira en cosas terrenales y no purifica el corazón,
ni cree que en algún momento alcanzará la vida de Cristo, Su estatura o plenitud,
sino que considera que los que buscan estos logros están equivocados.
Así que el fin de una es manifestar a Jesucristo en vida y poder, el mismo ayer, y hoy,
y por los siglos.
El fin de la otra es una libertad para pecar aquí
(mientras pueden tomar algún placer en ello),
y después recibir santificación y salvación cuando mueran.
Y cada fe obra conforme a su fin;
porque es imposible que aquel que no cree en la santidad produzca santidad.
Pero según la fe de cada hombre,
así será su herencia en este mundo y en el que está por venir.

Y en las operaciones y proezas de esta fe viva y poderosa,
encontré diversas medidas según mi crecimiento en ella--desde el
principio de la Palabra de Cristo (o el primer principio de Cristo),
hasta la plenitud y estatura de Cristo.
Y hay mucha labor en Espíritu entre un bebé en Cristo
y un hombre que ha crecido en fuerza,
y entre haber recibido la fe de Cristo, y tener a Cristo formado en mí. Porque,
aunque recibí fe para creer en Su plenitud, y en lo que Él era e hizo en la carne,
todavía no lo había aprendido a Él en el Espíritu y Vida en mi propia vasija mortal,
ni me revestí de Él inmediatamente,
sino que en la luz de la fe vi que tenía que correr de tal manera que pudiera ganarlo,
antes de que pudiera revestirme de Él. Y en esto llegué a ver y a sentir
que había sido engendrado nuevamente en Aquel que es el Camino a Dios,
y, en una medida, el Unigénito del Padre fue manifestado en mí,
en la imagen pura del niño santo, separado de la semilla carnal y pecaminosa.

Sin embargo,
aún después de haber visto Su imagen pura y Su mente
y naturaleza puras (tan contrarias a la mía),
vi que Él todavía no estaba gobernando en Su reino,
ni todas las cosas estaban puestas bajo Sus pies,
tampoco podía decir en ese entonces que Jesús era Señor en mí.
Pero por la obra del Espíritu (a través de la fe que había recibido,
y en la esperanza de esto) fui capacitado para soportar la pérdida de todo,
y para negar todas las cosas contra las cuales Su Espíritu Santo hacía guerra en mí,
que de cualquier manera podían oprimir esta planta santa u obstaculizar su crecimiento.
Sí, fui llevado a reconocer Su juicio en la luz,
sobre cualquier cosa que estuviera en mi corazón o afectos fuera de Él,
a pesar de cualquier pérdida que pudiera sufrir en el mundo.
Y a medida que reconocía y aceptaba este juicio en contra
de mí mismo y en contra de todos los amantes del yo,
entonces era separado de ellos en juicio,
y ellos eran sometidos por las poderosas operaciones
de Su Espíritu y puestos bajo Sus pies,
y yo era librado de ellos, a fin de levantarme con Él por encima de ellos,
habiendo sido sacado de debajo de ellos.
Esto no fue hecho todo de una sola vez,
sino según Él aparecía en la Luz para manifestar cada mal particular.
Y conforme la fe que había recibido obraba por amor a Él una aprobación
en mi espíritu a Sus justos juicios sobre todas estas cosas,
me sentía dispuesto a entregarlas al fuego, y a salir de ellas,
y unirme al Señor en la ejecución--no sea que me
consumiera con ellas (como habría sido el caso,
si hubiera permanecido en ellas).
Aquí encontré el beneficio de la luz que va delante de Su faz para preparar Su camino,
y de la salvación por la fe que me salvaba a través de la esperanza en Él,
para que no fuera destruido en mis pecados.
En verdad, esta fe y esperanza me dieron una entrada hasta dentro del velo,
o un refugio en Él hasta que pasó la indignación,
la cual tenía que pasar sobre el hombre de pecado.

Y así escuché la voz en el desierto que me llamaba a salir del pecado,
y a entrar en un camino que no conocía,
salvo en la medida que la luz de Su pacto me guiaba (que, como el espíritu de Elías,
hacía volver mi corazón hacia Él,
para que en Su venida no hiriera mi tierra con maldición;
Malaquías 4:6). Y conforme continuaba en este camino (antes
de llegar a experimentar un descanso puro en el reino de
Cristo) me topaba con muchas dificultades y grandes luchas,
y muchas tentaciones y pruebas internas y externas--pero
en verdad los enemigos más grandes estaban dentro de mí,
los cuales me tentaban con incredulidad en cada dificultad para destruir mi fe y esperanza.
Pero esta fe y esperanza estaban puestas delante de mí,
y me alentaban a soportar estas dificultades,
a seguir la luz por un camino que antes no había conocido,
a caminar en las nubes para recibir al Señor, a dejar mi antiguo conocimiento, sabiduría,
gloria y riquezas para andar en un camino por el que no había caminado,
y a resistir grandes asaltos por todos lados.
Y el mundo (fuera del cual había sido llamado) estaba listo para rodearme y abrumarme,
para hacerme volver atrás a eso que antes había visto y disfrutado,
siempre tratando de persuadirme de que jamás alcanzaría eso que
había sido puesto delante de mí por la fe y la esperanza.

Entonces llegué a ver claramente que,
aunque había recibido la fe de Cristo como un escudo en esta guerra
(por cuyo escudo la ira de Dios no me consumió en estas tentaciones,
murmuraciones, razonamientos y dudas que se levantaban en la parte carnal), aun así,
no fui llevado inmediatamente a disfrutar la posesión adquirida.
Porque aunque había escuchado y creído en el evangelio de salvación,
y había sido sellado con el Espíritu Santo de la promesa,
no podía disfrutar de la posesión adquirida hasta que llegara a
ser "`edificado en Cristo para morada de Dios en el Espíritu.`"^
footnote:[Efesios 2:22]
Y encontré por experiencia diaria que mi salvación no estaba completa
mientras mi alma estuviera sujeta a cualquier deseo o pasión terrenal;
ni la guerra había terminado hasta que estas cosas (por la poderosa obra de Dios
en mí mediante Su Espíritu) llegaran a ser sometidas bajo los pies de Cristo,
y mi alma fuera establecida por encima de ellas con el Señor,
para reinar en los lugares celestiales.
Así que, aunque "`mi salvación estaba más cerca que cuando había creído,`"^
footnote:[Romanos 13:11]
aun así, mientras el pecado vivía o la carne deseaba, mi alma no estaba a salvo,
porque esto batalla contra ella,
y cada pecado la hiere (como lo saben todos los que no han "`perdido toda su sensibilidad`").^
footnote:[Efesios 4:19]
En tanto el pecado contamine el alma, ella no está a salvo,
ni el corazón honesto tiene paz o descanso;
porque la paz y el descanso se encuentran en la ciudad santa,
a la cual nada impuro puede entrar.
Y el alma no experimenta ningún descanso ni paz duraderos
hasta que toda justicia sea cumplida en la tierra,
y el alma sea extraída de toda corrupción, habiéndose vestido de inmortalidad.
Aquí la muerte es sorbida en victoria, y su aguijón es quitado, el cual es el pecado;
y el poder del pecado (que es la ley) solo es quitado donde la
ley es cumplida--solo allí "`la gracia reina por la justicia.`"^
footnote:[Romanos 5:21]
Esto encontré como la verdad que está en Jesús,
a medida que lo aprendía a Él y me revestía de Él por la fe.
Y así,
vi la locura de aquellos que pretenden anular la ley hablando de la fe y de la gracia,
cuando el pecado todavía está en pie y el alma sigue estando cautiva por él. Porque,
aunque yo a menudo buscaba paz de esta manera también,
llegué a ver que mi alma no podía heredar libertad de otra manera más
que a medida que era "`purificada en la obediencia mediante el Espíritu.`"^
footnote:[1 Pedro 1:22]

Ahora bien,
esta obra no era llevada a cabo en mí por el conocimiento de Cristo según la carne,
sino sólo en la medida que lo aprendía a Él en el Espíritu; porque,
fue la iniquidad espiritual lo que había cautivado mi alma, y, por lo tanto,
debía ser santificada y puesta en libertad por el Espíritu.
Y llegué a ver que, si hubiera estado junto a Él,
tanto tiempo como Sus discípulos lo estuvieron en la carne,
y hubiera visto tanto como ellos, y escuchado palabras de Su propia boca, aun así,
hubiera quedado corto de esta obra--así como ellos, en quienes el niño^
footnote:[Él se refiere a que la vida de Cristo todavía
no había sido engendrada ni formada en ellos.]
no había nacido cuando Él se fue según la carne.
Porque ellos "`no sabían de qué espíritu eran,`"^
footnote:[Lucas 9:55]
hasta que Él vino otra vez a ellos en el Espíritu, y fue revelado en ellos.
Entonces podían predicar la resurrección de los muertos y la redención de las almas, y,
habiéndolo recibido en el Espíritu, ya no querían conocerlo según la carne.
Entonces predicaban a Cristo en el corazón, la esperanza de gloria,
aunque antes esperaban un reino y gloria externos.
Porque ellos recibieron Su Promesa: "`Aquel que mora con vosotros estará en vosotros,`"^
footnote:[Juan 14:17]
y "`No os dejaré huérfanos, vendré a vosotros;`"^
footnote:[Juan 14:18]
y "`el mundo no me verá más; pero vosotros me veréis; porque yo vivo,
vosotros también viviréis. En aquel día vosotros conoceréis que yo estoy en mi Padre,
y vosotros en mí, y yo en vosotros.`"^
footnote:[Juan 14:19-20]
Sí, ellos recibieron a Aquel quien era la promesa, a quien el mundo no puede ver,
porque sus expectativas son carnales,
porque sólo aquellos que nacen de este Espíritu y son herederos
de Su vida pueden ver el reino de los cielos.
Y el que tiene al Hijo, tiene la vida; el que no tiene al Hijo no tiene la vida,
sino que la ira de Dios está sobre él, independientemente de lo que diga creer;
porque sólo los que reciben este Espíritu, y son guiados por Él y han nacido de Él,
tienen al Hijo.

Y también entendí esto,
que el Hijo de Dios sólo aparece en nosotros en la
medida que Él nos conforma a Su propia imagen,
cuya imagen Él siempre ha llevado en este mundo, como dice la Escritura:
"`Cuando Él apareciere, seremos semejantes a Él,`"^
footnote:[1 Juan 3:2 RV 1602 Purificada]
y "`Él cambiará nuestro vil cuerpo, para que sea hecho semejante a Su cuerpo glorioso,`"^
footnote:[Filipenses 3:21 RV 1602 Purificada]
y "`transformados de gloria en gloria en la misma imagen por el mismo Espíritu,`"^
footnote:[2 Corintios 3:18]
y "`en esto tenemos confianza en el día del juicio; que como Él es,
así somos nosotros en este mundo.`"^
footnote:[1 Juan 4:17]
Esto no se obtiene por pensamientos que proceden de una creencia externa,
sino por la operación viva de Su poder interno,
que desgasta la imagen y naturaleza terrenal y nos conforma a Su imagen
celestial mediante ese nacimiento espiritual que no es de carne y sangre.
La carne y la sangre nunca podrán discernir esta obra en el hombre,
más bien siempre (en todas las edades) la ha aborrecido en cualquiera que haya aparecido.
Porque dondequiera que esta obra sea engendrada por el Padre,
es de una naturaleza que resplandece, y no puede esconderse donde es formada,
sino que por sus frutos ilumina al mundo oponiéndose a sus caminos y mostrando
la venida de Cristo en juicio contra todas las obras de las tinieblas.
Y los que tienen este nacimiento celestial del Padre deben mantenerlo en su imagen pura,
sin mezcla, según sus diversas medidas,
para que todos puedan ver que Él no es de este mundo,
y que los saca a ellos de este mundo conforme Él crece en ellos,
o ellos crecen en Él. Y estos deben ir al mundo y llevar Su vituperio,
para que la Escritura sea cumplida: "`Ellos no son del mundo,
como tampoco Yo soy del mundo;`"^
footnote:[Juan 17:16]
y esta es la luz del mundo y su condenación, a saber, Su venida.

Y así encontré que la fe que se une al mundo, y que no vence al mundo,
no es la fe de Cristo, no es la que echa mano del poder de Cristo,
aunque crea en la historia que las Escrituras relatan acerca de Cristo.
Esta fe no establece el reino de Dios en el corazón, ni echa fuera al mundo de él,
ni salva el alma de la corrupción que hay en el mundo a causa de la concupiscencia,
y por lo tanto solo es un concepto de salvación,
pero no el poder de salvación. Porque las Escrituras dicen:
"`Porque todo lo que es nacido de Dios vence al mundo;
y esta es la victoria que ha vencido al mundo, nuestra fe;`"^
footnote:[1 Juan 5:4]
y la fe que no obra de este modo es "`como el cuerpo que sin espíritu está muerto.`"^
footnote:[Santiago 2:26]
Pero la fe viva, que tiene su fundamento en Cristo Jesús,
purifica el corazón y la consciencia,
venciendo cualquier cosa que obstaculice la aparición de Cristo en Su templo,
o el surgimiento de Sus virtudes.
Y aquellos que creen con esta fe no creen en una mentira,
sino en la verdad y poder de Dios como es en Cristo Jesús,
y como ha sido declarado en las Escrituras, no simplemente para hablar,
sino para obtener la herencia de vida, de cuya plenitud tomamos todos según nuestra fe.

Por lo tanto,
encontramos que aquellos que eran de esta fe experimentaban a Cristo presente en ellos
(algo que la fe del mundo nunca ha podido recibir bajo ninguna forma o denominación,
al contrario, lo ha considerado blasfemia,
y a Su Espíritu lo ha llamado el espíritu del diablo).
Por medio de esta fe Isaías creyó en su tiempo, y experimentó al niño nacido para ellos,
el cual era el Dios Fuerte, Padre Eterno, etc., cuyo nombre ellos sabían que era Emanuel,
y esto fue antes de que Él apareciera en ese templo en Jerusalén.
Y también Ezequiel fue llamado hijo de hombre antes ese tiempo.
Y Pablo dijo que Cristo fue revelado en él, y que hablaba y obraba en su interior,
y que en su carne se estaba cumpliendo lo que faltaba
de las aflicciones de Cristo por Su cuerpo,
que es la iglesia.
Pudieran mencionarse muchos más hombres y mujeres que confesaron al mismo Cristo
presente en ellos (tanto antes como después de Su aparición en ese cuerpo) cuyo
testimonio nunca ha sido recibido por la sabiduría del mundo,
ni en aquel entonces ni en este día. Porque el dios de este mundo (siendo
rey en el corazón) ha cegado el ojo de ese entendimiento que puede ver
la gloria espiritual de Cristo mediante la luz del evangelio,
y él persuade al mundo diciendo que Cristo ya vino o está por venir, pero nunca presente.
Y por eso,
todos los que son llevados a confesar a Cristo delante de los hombres encuentran
en este día que son aborrecidos por todos ellos por causa de Su nombre,
para que la Escritura se cumpla, y Su testimonio sea consumado.

Pero la fe que confiesa a Cristo presente es la que el mundo no puede soportar ni recibir.
No, ellos predicarán a Cristo como si estuviera lejos--hablando de lo que Él era
y de lo que será--pero la fe de ellos no puede experimentar Su venida presente,
ni recibir ninguna medida de Su aparición ahora.
Esta fe jamás otorgará una entrada a Su Reino en la tierra, ni al reposo santo,
porque la fe que lo pone a Él lejos no es la fe de Cristo,
que llena a aquellos que creen con la plenitud de Dios.

Y por lo que he aprendido, esto siempre será claro y sin controversia para mí:
que la fe que permite el pecado no es la fe de Cristo,
ni tiene una participación o posesión en Él. Porque
la fe que no es santa no viene de Dios,
y, por lo tanto, no puede edificarnos en Dios.
De hecho, la fe que no salva de los pecados no es verdadera, al contrario,
es una fe falsa que engaña al alma y permite que los deseos la contaminen y la destruyan,
y por lo tanto hace que esté bajo condenación. Al creer en las mentiras de esta fe falsa,
al pecado se le deja pasar al alma con consentimiento,
la cual es persuadida a pensar que no puede ser de otra manera, y así el diablo,
el mundo,
la carne y el pecado tienen su victoria sobre el alma (que debería tener la victoria,
sobre todo).
¿Qué mayor engaño puede haber para el alma que este?

Y, por lo tanto, declaro abiertamente lo que he visto y aprendido:
esta es una fe engañosa, y, de hecho,
en lugar de ser la fe de Cristo es una forma de incredulidad,
porque abre paso al dios de este mundo para que reine y
actúe en la criatura en cosas contrarias a la vida de Cristo,
y a la vida del alma.
Nuevamente digo, esa fe que le da paso al pecado más pequeño no es la fe de Cristo,
porque el propósito de Su obra y venida es destruir
las obras del diablo y redimir al alma del pecado,
y la medida más pequeña de la verdadera fe (que está fundada
en Su vida) vence al pecado y al mundo en dicha medida.
Pero aquel que comete pecado sale de esa fe y actúa en contra de ella.

Es una fe mentirosa que persuade al alma y la hace creer que es libre de la condenación,
sin darle la libertad del pecado, que es la causa de la condenación,
y todos confesarán conmigo que esto es una realidad, ya sea ahora o en lo por venir.
Porque donde sea que el pecado tenga poder, allí la muerte tendrá poder, y el sepulcro,
el infierno y la condenación también tendrán poder,
porque estas cosas son la paga del pecado,
y aquellos que crean lo contrario pronto se darán cuenta que fueron engañados.
¿Y no se podría decir con verdad,
que los que cometen pecado y ya no sienten ninguna condenación,
realmente "`han perdido toda sensibilidad`"^
footnote:[Efesios 4:19]? Y este es el efecto de su fe falsa:
ellos endurecen su corazón contra el testigo fiel de Dios en sus propias consciencias,
hasta que la conciencia cauterizada "`naufrague en cuanto a la fe`"^
footnote:[1 Timoteo 1:19]
de Cristo.
Es la doctrina de demonios la que predica la fe de los demonios,
para abrir paso a las obras del diablo;
porque sabemos que todo pecado (desde el más pequeño
hasta el más grande) es una obra del diablo.
Y aquel que aboga por el pecado es padre de él, y aquel que comete pecado es esclavo, y,
si no se arrepiente, puede contar con su paga.

Hay muchos en este día que realmente sienten esta verdad (a pesar
de que tienen mucho tiempo creyendo por medio de esta fe falsa)
quienes día tras día engañan a sus propias almas,
creyendo que no serán condenados por Dios cuando
ya están condenados en sus propios corazones,
y sienten a diario el peso del pecado oprimiendo sus almas como una carga en sus conciencias.
¡Ay!
El temor de la muerte y del pecado mantiene a estas almas en esclavitud,
y yace sobre ellos durante toda su vida; y, no obstante,
se fuerzan a creer (de manera opuesta a la fe santa y a la buena
conciencia) que de alguna manera ellos ya son salvos y están redimidos.
Así ellos naufragan en cuanto a la fe verdadera y a la buena consciencia,
al creer una mentira que contradice lo que ellos mismos sienten a diario,
sin tener nada más que los apoye en esta creencia además de su propia opinión,
que es conveniente para aquellos que se complacen en la injusticia.
Pero esta persuasión no procede de Dios, más bien es condenada por Su testigo en todos.
Este es el estado de muchos en este día, aunque algunos,
cuyas consciencias están cauterizadas, ya no pueden sentir este testigo vivo en ellos.
La perdición de estos no se duerme, porque han perdido su llamado y elección.

Y esto he aprendido en Cristo: que hay una gran diferencia,
tanto en efecto como en naturaleza,
entre esa fe que es don de Dios y la fe que los hombres crean para sí mismos.
La fe que es don de Dios es de Su propia naturaleza--limpia, pura y perfecta,
como todos Sus dones, y, por lo tanto,
lleva a cabo naturalmente la obra y voluntad de Dios
en todos los que la reciben con ánimo voluntario,
y no la mezclan con nada que pueda oscurecerla o detener
Su operación. Por esta fe (que no es de nosotros,
pues es don de Dios), somos salvos tanto del pecado como de la condenación,
y engendrados en Cristo Jesús para el Padre de la fe,
a fin de ser santificados completamente.
Cualquier cosa que se haga en esta fe no es pecado,
pero lo que sea que esté en su contra, o que no provenga de ella,
es pecado y trae condenación, y ella no lo aprueba.
Pero si actúo sin dudar, y sin estar en contra de esta fe santa,
entonces soy justificado en mi propio corazón,
mi conciencia se mantiene limpia y estoy aprobado delante de Dios.
Sí, a través de la obediencia de la fe, tengo confianza en el día del juicio,
de que no es mi propia obra sino la justicia de la fe que es en Cristo Jesús. Este es
el efecto de la fe verdadera (que salva y obra) y esta es su naturaleza y gracia.

Pero he encontrado otra fe que no tiene la misma naturaleza ni efecto,
puesto que no es recibida por gracia desde arriba.
Esta es una fe fingida, que tiene su fundamento aquí abajo,
y su fin también. El hombre terrenal, utilizando esa sabiduría que se basa en la letra,
y de su razón y comprensión,
establece una opinión o imagen en su mente con respecto a Dios, a Cristo, a la religión,
la adoración, la doctrina o la conducta, o cualquier otra cosa, y entonces,
viendo esta semejanza con su parte racional,
reúne fuerza para creer que realmente debe ser como él lo piensa; de este modo,
forma una fe en sí mismo.
Y aunque esta fe es muy deficiente y hay muchas cosas en las Escrituras
y en las prácticas de los santos (y especialmente en el Testigo
de Dios en su consciencia) que no concuerdan con ella,
aun así, el hombre fuerte (teniendo el dominio en la comprensión del hombre terrenal),
lo obliga a tener una fe que contradice todas estas cosas,
y hace que todas las demás se inclinen ante ella.
Por tanto, esta fe no produce el nacimiento de Cristo,
ni Su imagen y vida pura en el hombre, ya sea en cuestiones de adoración o de conducta.
Pero cualquier cosa que un hombre, con este tipo de fe,
pueda imitar de Cristo y de los santos; que le permita aferrarse al mundo,
escapar de la cruz y salvar su vida,
su reputación y su gloria aquí a _eso_ él se conformará
y en _eso_ se gloriará. Y en cuanto a lo demás,
creerá que no le corresponde ahora, en este día,
obedecer en todas las cosas como lo hizo Cristo.
Porque cualquier mal al que él no es adicto, lo condena en todos los demás; sí,
él condena todo menos lo que está en su propio corazón y ojo,
y le produce ganancia y placer; esto él cubrirá,
e insistirá que es conforme a la verdadera fe de este día, aunque antes no lo era.
Esta es una fe creada según el hombre y no según Dios, que hace acepción de personas,
tiempos y cosas, pero que no entregará estas cosas como para adorar en Espíritu,
ni las traerá a los pies de Jesús. Y esta fe, siendo terrenal por naturaleza,
tiene efectos terrenales, y Dios no le concederá Su poder,
ni acompañará nada que los hombres hayan creado, sino solo Su propio don,
que es bueno y perfecto en todas sus medidas.

Y esto también he aprendido en Cristo Jesús,
y lo declaro a todos los que buscan fe en Él:
que nunca he recibido ninguna medida de esta fe de Cristo en vano,
sino que todo lo que he hecho o sufrido en ella (desde la
menor medida hasta la medida que conozco en este día),
en ella he prevalecido en cualquier cosa a la que la luz me ha guiado.
Y he encontrado que esta fe es un escudo, y, en cada una de sus operaciones,
he hallado un crecimiento en ella a la medida de Cristo Jesús.
Y he aprendido a permanecer inconmovible en ella hasta el fin,
sin importar cuán tentado o probado haya sido antes de que apareciera dicho fin;
porque el fin de esta fe es una conquista mediante el Espíritu,
como dan testimonio todos los que la han probado
hasta el final con fidelidad de corazón. En verdad,
una gran nube de testigos se ha ido delante de nosotros,
quienes por esta santa fe han prevalecido sobre los poderes del pecado,
y entrado al reposo santo,
los cuales no han buscado su propio reino sino el reino de Cristo.

Solo esta fe pura obra en nosotros para llevarnos a la manifestación
de Cristo en todas nuestras acciones y sufrimientos,
ordena todas las cosas en su lugar y tiempo,
y amolda todas nuestras relaciones para que Él se
manifieste en ellas para la gloria de Dios;
porque Dios no es glorificado en nada en la tierra,
salvo en aquello donde el Hijo aparece, quien es la imagen y gloria misma de Dios,
y en quien Dios se revela a Sí mismo y manifiesta la gloria de Sus juicios y de Su misericordia.
Sí,
la gracia y la verdad de Dios están en la faz de Cristo (en quien sea que Él aparezca),
y, por lo tanto,
cada medida de la fe celestial obra en nosotros para
llevarnos a la aparición o manifestación celestial,
y la fe terrenal obra en nosotros para llevarnos a la manifestación terrenal.
Así que la verdadera fe en Dios es eso que obra eficazmente
por el amor hacia la imagen y vida de Dios en este mundo,
la cual solo se realiza por el engendramiento espiritual.
Y cuando creemos en ella, y la ponemos por encima de todo lo demás,
resplandece en sus diversas medidas,
mostrando la virtud y la gloria del Espíritu de Dios.
Pero la fe fingida y terrenal permite que cosas terrenales
permanezcan en el corazón (para sus propósitos personales),
y por amor a estas cosas terrenales, hace que desobedezcamos al Espíritu, y,
por lo tanto, quedemos cortos de la gloria de Dios;
porque no podemos manifestar los frutos del Espíritu para
glorificar a Dios con un amante terrenal en el corazón,
tampoco es posible que una sola fe sirva tanto a Dios como a las riquezas.
De modo que el que ama las cosas de este mundo se constituye enemigo de Dios,
cuya fe no permite que Cristo se manifieste en sus acciones o tribulaciones, y,
por lo tanto,
resiste la gloria de Dios que debería manifestarse
a todos los hombres por medio de ellas.
Esta es esa fe que siempre ha mantenido lejos a Cristo, y, sin embargo,
usa la forma externa y las palabras para resistir la vida y la virtud.
Es con respecto a este tipo de personas que el apóstol habla,
advirtiéndonos que "`tienen apariencia de piedad, pero niegan el poder de ella.`"^
footnote:[2 Timoteo 3:5]
¡Ay! estos siempre han sido los más grandes enemigos de la venida de Cristo,
ya que no son de la fe de Cristo, ni del Espíritu de Cristo; más bien, siendo de abajo,
ellos resisten Su venida desde arriba,
que tiene como fin que Él sea manifestado en Su virtud y adorado en Su propio Espíritu.
Esto en verdad es el anticristo.

Es en este espíritu y en esta fe que los hombres tuercen
las Escrituras para seducir a otros a apartarse de Cristo,
y para destruir el camino de Su venida.
Y en lugar de mostrar Su vida y virtud con una manifestación real,
este espíritu se sirve a sí mismo con un significado o interpretación,
en vez de servir a Cristo con la verdadera obediencia.
Y así,
al "`nacimiento espiritual`" se le da un significado o interpretación
en lugar de considerarse como la verdadera vida de Cristo,
y este significado es establecido para oponerse a Su vida,
para que no se manifieste realmente en el mundo.
Por ejemplo, Cristo dijo en las Escrituras:
"`Cualquiera que te hiera en la mejilla derecha, vuélvele también la otra;
y al que quiera ponerte a pleito y quitarte la túnica, déjale también la capa,`"^
footnote:[Mateo 5:39-40]
y, "`al que tome lo que es tuyo, no pidas que te lo devuelva,`"^
footnote:[Lucas 6:30]
y "`Yo os digo: no resistáis al que es malo,`"^
footnote:[Mateo 5:39]
sino que "`vence con el bien el mal,`"^
footnote:[Romanos 12:21]
y "`amad a los que os aborrecen,`"^
footnote:[Mateo 5:44]
y muchos mandamientos similares.
Cristo realmente quiso decir estas cosas, y las mostró en Sí mismo como ejemplo.
Y cualquiera que reciba el mismo Espíritu,
encontrará que este lo mueve a estas mismas cosas a medida que se incrementa,
y al ser obedecido producirá los mismos frutos que
glorifican al Padre en todas las generaciones;
porque el Espíritu no envejece, ni sus frutos son estériles,
donde realmente es recibido y obedecido en la fe que viene de Él.

Pero la otra fe (en el espíritu terrenal) dice: "`Cristo no quiso decir lo que dijo;
no deben tomar Sus palabras literalmente,
¡esas cosas deben tener un significado espiritual!`"
Y de este modo, el significado espiritual de ellos devora la vida de obediencia,
tanto a las palabras de Cristo como al Espíritu de Cristo,
al establecer un significado sutil que no tiene la
vida de Cristo y que es contrario a Su ejemplo.
Y ellos desean que todos acepten este significado
que contradice las palabras claras de Cristo,
Su ejemplo cuando anduvo en la tierra y la obra de Su Espíritu en otros.
Y si de este modo no pueden destruir la verdadera fe y su fruto antes de que sea manifestado,
entonces se esfuerzan por hacer que cualquiera en quien
esta vida aparezca y sea dada a luz se tome por blasfemo;
porque ellos consideran que es una gran presunción afirmar que la vida
de Cristo puede ser engendrada en el hombre y manifestada al mundo.
Y aunque predican de Cristo en nosotros, y la vida de Cristo en nosotros,
y el Espíritu de Cristo en nosotros, y nuestros cuerpos como el templo de Dios, etc.,
(porque encuentran estas palabras en la Escritura) aun así,
no permitirán que nadie crea y obedezca ninguna manifestación de Su Vida.
No, esto no lo reconocerán, sino que pondrán su significado en su lugar,
y establecerán una forma externa para negar el poder,
y hacer que las palabras de Cristo nieguen Su venida.

Oh por cuánto tiempo esta fe falsa ha profesado que Él está por venir,
y ha hablado de la vida y la gloria en Su venida, según su propio entendimiento carnal;
y, sin embargo, no está dispuesta a recibirlo en la misma vida,
Espíritu y poder en el que Él siempre ha aparecido.
Y, por lo tanto, para esta generación Él siempre esta por venir,
pero nunca presente--salvo para crear una capa para sus pecados pasados y presentes,
y una licencia para los pecados futuros.
Así el devorador convierte (en todos los que le creen) las mejores cosas en una mentira,
para evitar que Cristo y el alma experimenten una unión presente,
lo cual él no podría seguir haciendo a menos que tuviera el consentimiento de la criatura.
Porque hay un don de Dios en todos, que diariamente inclina hacia Él,
en donde sea que no es apagado por creer mentiras;
pero aquellos que "`no reciben el amor de la verdad`"^
footnote:[2 Tesalonicenses 2:10]
perecerán, así como sucedió en los días de la antigüedad.
Oh, he visto que es angosto el camino que nos lleva por la senda de la verdad y la vida,
y que evade todas las pretensiones sutiles del enemigo.
Y me he dado cuenta de que son verdaderas las palabras que Él dijo:
"`pocos son los que la hallan;`" porque el enemigo siempre
está listo para ofrecer a los que buscan a Dios una sombra,
un significado o algún otro engaño (para que crean en ello en lugar
de la sustancia)--siempre adulterando las palabras de Dios,
usando los dones de Dios para resistir la vida del Dador,
y convirtiendo Su gracia en libertinaje.

Y esto he aprendido en Aquel quien es la Luz del mundo: que, al volverme a Él,
a Su reprensión (cuando no Lo conocía), y al creer en la Luz de Aquel que no había visto,
vi que me fue dada la fe que declaraba la justicia de Dios en Él--la justicia
en la que Cristo caminó perfectamente cuando estuvo sobre la tierra,
la cual se manifestaba tanto en Sus acciones como en Sus sufrimientos.
Y siendo vuelto hacia Él, experimenté la propiciación que Dios había propuesto,
"`por medio de la fe en Su sangre,
para manifestar Su justicia por la remisión de los pecados pasados,`"^
footnote:[Romanos 3:25 RVG]
a fin de que Dios sea el justo--quien no hubiera pasado por alto mis pecados pasados,
si Él no hubiese aceptado los sufrimientos de Cristo,
ni yo tampoco hubiera experimentado la libertad del pecado
pasado para poder seguirlo (ni hubiera sido acepto al hacerlo),
salvo en la fe y esperanza de la misma justicia.
Así Dios era el justo y el que justifica,
y Su paciencia fue magnificada para conmigo en ello;
y por volverme a esta justicia Suya (manifestada en la luz de la fe y la esperanza),
mi mirada fue puesta en la justicia de Dios en Cristo Jesús,
a fin de alcanzarla y caminar en ella, para vida y salvación,
durante el tiempo que me restaba sobre la tierra.

Y así, habiéndome vuelto hacia Dios, todos mis pecados pasados estaban detrás de mí,
y la justicia de Dios frente a mí,
y de ahí en adelante tenía que ser hallado en la justicia de Dios,
caminando en una medida de ella,
y en la fe y esperanza de alcanzar la medida de la estatura de Cristo como mi herencia.
Y en ese tiempo,
la gran redención que experimenté en Cristo fue en relación con las siguientes cosas:
Encontré que Él me llamaba mediante Su luz, y me mostraba Su vida y Sus sufrimientos,
que fueron tan santos que no podía evitar confesarlos.
Encontré que Él me guiaba a experimentar la misma vida y sufrimientos en fe y esperanza,
y engendraba un sentir en mí que me inclinaba hacia esa misma Vida,
y también que Él incrementaba Su Luz para dirigirme.
Y encontré que Él me libraba de la ira de Dios a causa de todos mis pecados de ignorancia,
que de otra manera habrían sido puestos sobre mí como un peso o cadena,
y me habrían atado de tal manera que no hubiera podido caminar en la senda de Su luz, etc.

Pero yo no estoy diciendo que, si volvía a cometer pecado,
que ese pecado también era echado tras mi espalda;
porque me di cuenta de que era de otra manera.
De hecho,
encontré que el pecado que estaba puesto delante de mí era más grande que los demás,
interponiéndose en mi camino hacia Dios,
e impidiéndome seguir Su luz o crecer en Su vida.
Y vi que la única manera de escapar de este pecado era arrepentirme de él,
recibir la sentencia justa de condenación en mí mismo, y soportar Su indignación,
hasta que Aquel que me había herido por el pecado,
me sanara otra vez--lo cual solo sucedía cuando me apartaba del mal con todo mi corazón,
y aceptaba el castigo, hasta que el abogado se levantaba para interceder,
cuya sangre había hollado, cuya vida preciosa había traspasado,
y cuyo Espíritu Santo había apagado, por haberme apartado de Su guía.

Tampoco estoy diciendo que todos los pecados que había cometido en el
pasado--de los cuales había sido convencido por la Luz del mundo,
cuando estaba en el mundo--fueron completamente borrados como mis pecados de ignorancia.
Porque, con respecto a estos pecados, encontré que Dios era misericordioso y justo:
misericordioso porque Él no los puso todos a la vez delante de mí,
no fuera que me oprimieran de tal modo que no hubiera
podido seguir la luz o encontrar fuerza,
sino que sintiera que ciertamente debía perecer por ellos.
Y justo, porque,
así como estos pecados no fueron cometidos todos
a la vez en contra de la Luz de Su Espíritu,
Él, por tanto, me ha visitado por ellos poco a poco, de un tiempo a otro,
y no los puso delante de mí todos a la vez,
ni de una manera tan fuerte como lo hacía con los pecados que cometí
después de haber creído en la luz y de haberme entregado a seguirla.
Sin embargo, Él en verdad me llevó a dar cuenta por ellos;
y llegando a sentir el terror de Dios, he aprendido a tener temor, y a amar.

Y así descubrí el fundamento,
surgimiento y engaño de esa fe que cree que Cristo ha quitado los pecados pasados,
presentes y futuros de los creyentes.
Muchos en este día, al creer esto, se regocijan sobre el testigo de Dios,^
footnote:[Apocalipsis 11:10]
y han matado al Justo en sí mismos.^
footnote:[Véase Santiago 5:6, y Hebreos 6:6]
También he aprendido el significado de esta Escritura:
"`Si pecáremos voluntariamente después de haber recibido el conocimiento de la verdad,
ya no queda más sacrificio por los pecados, sino una horrenda expectación de juicio,
y de hervor de fuego que ha de devorar a los adversarios.`"^
footnote:[Hebreos 10:26-27]
Nadie conoce estás cosas sino aquel que las encuentra cumplidas,
y entonces entenderá que "`aquel que es nacido de Dios, no peca,`"^
footnote:[1 Juan 3:9 RVG]
y que "`todo aquel que cree, es nacido de Dios.`"^
footnote:[1 Juan 5:1]
Pero el que peca le da la espalda tanto a la fe como al nacimiento que es de Cristo,
y se vuelve un adversario de Él en Su obra, independientemente de lo que diga creer.
Y esto he encontrado como una verdad eterna (sin
importar lo que los hombres crean o imaginen):
que los pecados de un hombre son echados tras Su espalda
solo cuando mantiene su mirada puesta en la Luz de Dios;
pero si se aparta de la justicia de Dios,
sus propias iniquidades (tanto las nuevas como las viejas) se levantarán
y vendrán sobre él. En vano un hombre como este cree que sus pecados
han sido borrados ante la vista de Dios,
porque es el ojo de Dios el que le muestra el error de su camino,
y lo condena por ello en su propio corazón.

Tampoco la semilla y raíz del pecado fue removida tan pronto como mi mente
había sido vuelta del pecado hacia Dios por medio de la luz.
Al contrario,
encontré que sus inclinaciones y deseos todavía estaban
buscando salir a sus diversos objetos,
con el fin de concebir el pecado nuevamente.
Esta raíz de pecado solo era removida en la medida que crecía en Cristo, y Él en mí,
y a medida que aprendía a Aquel que era en el principio, antes de que el pecado fuese.
Y al seguir y servir fielmente a Su Espíritu, aprendí a Cristo, en desvelos, en ayuno,
en oración y en toda batalla espiritual, según era movido a estas cosas por la luz.
Y en esta guerra llegué a ver las aflicciones de
aquellos que quieren ser soldados de Cristo Jesús,
y a experimentar los bautismos en Su muerte.
Y vi al siervo negligente y al siervo fiel, cada uno con su recompensa.
También las parábolas y figuras del reino de Dios me eran
reveladas en la medida que el Espíritu crecía en mí,
el cual interpreta las Escrituras en la vida, y abre sus misterios sellados en Su tiempo,
conforme llegan a ser cumplidas.
Y así experimenté el don de las Escrituras por inspiración,
que es la única manera de que puedan ser útiles para perfeccionar al hombre de Dios.
Pero el hombre de este mundo, no habiendo aprendido de esta manera,
tuerce las Escrituras para su propia perdición,
tomando sus palabras en la parte terrenal,
antes de que sean cumplidas en el corazón mediante el Espíritu.
Estos hombres no reciben las Escrituras por inspiración,
ni conocen el don del Espíritu Santo.

Y en este viaje he visto al siervo negligente sorprendido
en una falta que pensó que había dejado atrás,
sin haber tenido la intención de caer de nuevo en ella,
mientras el siervo diligente fue mantenido en libertad.
Y he visto que el salario de cada siervo fue asignado según su
diligencia en eso que Dios les había confiado en su interior,
pero no al luchar por sí mismo en sus propios pensamientos,
valor o sabiduría. Y he encontrado que la verdadera fidelidad a
Dios consiste en escuchar y obedecer diligentemente al Espíritu,
aunque vi que la mera adquisición de conocimiento es lo que los hombres tienen por sublime.
Y encontré que,
aunque tenía "`una manifestación del Espíritu dentro de mí para provecho,`"^
footnote:[1 Corintios 12:7]
aun así, los tiempos de llevar fruto estaban solo en Sus manos,
y que esperar en Él cuando no se movía era mi servicio racional,
lo cual era tan provechoso para mí como si se hubiera movido, aunque no lo pudiera ver.
Y a pesar de que encontré esto como una gran cruz para mi voluntad apresurada,
es en verdad la verdadera adoración en Espíritu,
porque vi que cuando no conocía este Espíritu--como para escucharlo,
obedecerlo y seguirlo conforme guía Su voluntad--"`adoraba lo que no conocía.`"^
footnote:[Juan 4:22 LBLA]
En ese tiempo mi temor a Dios era un mandamiento de hombres que me había sido enseñado,
porque no había sido enseñado por el Señor, ni había nacido de Su Espíritu.
Y todos los hijos del Señor son enseñados por el Señor,
y los que son guiados por el Espíritu, estos son los hijos de Dios.
Así llegué a leer y a entender estas Escrituras sin interpretaciones
ni significados que me enseñara mi propia sabiduría,
sino por eso que el Espíritu Santo me enseñó. Y encontré que las Escrituras que
son aprendidas y recibidas de esta manera ya no son conceptos que pueden perderse,
sino posesiones en nuestra herencia entre los santificados de todas las eras.
Ningún hombre jamás, por más sutil que fuera,
podía robarme o cambiarme la verdad de las Escrituras,
o de alguna manera engañarme con respecto a ella al torcerlas,
tampoco podía quitarme el consuelo que tenía en ellas,
porque mi consuelo y comunión estaban en el mismo Espíritu y Vida que las inspiró.

De modo que eso que declara la justicia de Dios por la remisión de los pecados pasados,
y también como la herencia en el tiempo que queda sobre
la tierra--he encontrado que esto es una fe sin falsedad.
Y aunque es una justicia inefable, aun así,
es heredada conforme las virtudes que están en Cristo Jesús son recibidas en la Vida.
Y cualquier fe que no tenga esta justicia como su fundamento y fin,
ni las virtudes y diversas medidas del crecimiento de Cristo como su vida e incremento,
la he encontrado (bajo prueba) como una fantasía fingida de la mente del hombre.
Y el que diga que tiene fe en Dios sin tener la esperanza
de obtener esta justicia como su herencia,
o que piense que tiene a Cristo en una medida mayor de lo que posee
Sus virtudes para su vida y crecimiento hacia esta herencia,
cuando sea pesado con la verdad,
será hallado demasiado liviano para estar de pie en el juicio, o morar en el fuego,
o habitar con las llamas eternas.

[.asterism]
'''

[.old-style]
=== Quienes Son Los que Están Bajo la Ley, / Quienes Son Los que Han Invalidado la Ley con Respecto a Sí Mismos, / Y Quienes Son Los que Están Bajo la Gracia

La gracia reina por la justicia, y la ley por medio de la transgresión; por lo tanto,
el que diga que no está bajo la ley cuando la naturaleza trasgresora aún vive en él,
aunque pretenda que la ley ha sido invalidada con respecto a él, aun así,
permanece bajo ella ante los ojos de Dios.

Porque debido a la caída de la semilla o imagen de Dios,
la naturaleza transgresora se ha levantado y ha tomado el dominio dentro del hombre,
y a esta naturaleza (que sólo obedece por razones
egoístas) no se le promete ni gracia ni vida.
La ley es añadida sobre esta naturaleza hasta que se levante la Semilla de la promesa.
Y la ley es un ayo para llevarnos a Cristo,
el cual ha nacido de mujer y nacido bajo la ley,
quien toma sobre Sí mismo la semilla según la carne,
para redimir al alma del dominio del transgresor,
a fin de que la planta de Dios pueda crecer.
De modo que el hombre debe experimentar las enseñanzas y correcciones de la ley,
para que ellas lo humillen y reduzcan hasta que llegue a estar por debajo de la Semilla.
Entonces la Semilla será establecida sobre la cabeza de la naturaleza transgresora,
y habiéndola herido, el poder del pecado será quitado, junto con el poder de la ley.
Y conforme el alma se va levantando mediante la ley (al
ella ser cumplida por la Semilla mediante el Espíritu),
se eleva por encima de ella al reino de la gracia,
que reina por la justicia (y no por invalidar la ley).
Porque la gracia es para la Semilla, y la ley para el transgresor;
y dependiendo de cuál de ellos reine en la criatura,
entonces está bajo la ley o bajo la gracia.
La ley se enseñorea del hombre de pecado entre tanto éste vive,
y durante este tiempo la Semilla de la promesa está en cautiverio.
Pero conforme eso (que mantiene la Semilla en cautiverio) sea puesto a muerte,
entonces la Semilla se levantará bajo la gracia;
e irá cumpliendo la ley a medida que se levanta a través de ella.
Y la ley, al ser cumplida, perderá su poder,
cuando el pecado muera y deje de tener poder--porque "`la ley es el poder del pecado`"^
footnote:[1 Corintios 15:56]
hasta que es cumplida por la Semilla mediante el Espíritu.
De modo que el que ha muerto al pecado es libre del pecado, y está bajo la gracia.
Pero el que desecha la ley mientras el pecado aun vive,
invalida la ley contra su propia alma.

Por lo tanto, el que está bajo la gracia está muerto al pecado y a la ley,
que es el poder del pecado.
En este hombre, el pecado ya no tiene más dominio sobre el alma,
porque su poder es sometido, el cual era la ley no cumplida.
Pero si un hombre trata de invalidar la ley cuando
el poder del pecado todavía permanece en él,
la ley lo sorprenderá al final.

Y el que aprenda estás cosas en la muerte y en la resurrección y en la vida eterna,
aprenderá en esta obra qué es la transgresión, y cómo la ley es añadida sobre ella,
y cómo ella es el poder del pecado en él (pero no en la Semilla),
y qué es eso que obtiene una entrada a través de la ley,
y cómo la gracia llega a sobreabundar donde el pecado había abundado,
y a reinar por la justicia para vida eterna.

Por lo tanto, donde la naturaleza transgresora es asesinada,
la ley llega a su fin y es cumplida, y la planta de Dios lleva su fruto,
contra el cual no hay ley.
Pero en verdad la ley estará en contra del hombre de pecado,
y el hombre de pecado en contra de la ley en tanto él viva.
Y sin duda la ley tendrá poder sobre él,
y ni una jota de ella pasará hasta que sea cumplida.
Así que el que quiera desechar la ley e invalidarla mientras todavía permanece pecado,
está lejos de la gracia.
Pero en Aquel que cumple la ley, la gracia y la verdad abundan.

[.asterism]
'''

[.old-style]
=== Con Respecto al Camino de Vida, / Y el Conocimiento que Devora la Vida

¿Desean entender la diferencia entre el camino de
vida y el conocimiento que devora la vida?
Entonces dejen de ser como un pollino de ansa montés, y tomen el yugo del Hijo,
en quien ustedes dicen creer, para que sientan y conozcan la vida de la fe;
porque solo en la obediencia está la vida de lo que ustedes creen que ya tienen asegurado,
y en ella también se perfecciona la fe y el conocimiento.
Pero hasta que no obtengan poder para experimentar "`la obediencia de la fe,`"^
footnote:[Romanos 1:5, 16:26 RVG]
todavía están muertos y solo conocen palabras.
Y por lo tanto su fe consiste en palabras sin vida que no logran nada,
sino que se levantarán para condenarlos cuando su tiempo se haya acabado.

Por lo tanto, durante toda su búsqueda,
que su corazón esté puesto en eso que obra en la humildad,
y que los llama a la obediencia de aquello que se manifiesta en lo que engendra el Padre,
y no en lo que concibe el cerebro.
Porque en el conocimiento mental reina la naturaleza jactanciosa,
que se gloría en la sabiduría de palabras, pero no en las palabras de vida.
Pero los que caminan en el Espíritu, y en la obediencia del Hijo,
conocen y glorifican verdaderamente al Padre, y su alabanza es de Él,
y sus vidas están escondidas con Él de todo conocimiento
que no sea aquel que es revelado en la obediencia del Hijo.
Ustedes pueden aprender de un hombre el conocimiento de palabras,
pero el conocimiento de vida sólo es engendrado por Dios.
Y el que tiene al Hijo tiene esta vida, que no es la vida de la naturaleza desobediente;
porque el que es engendrado por Dios es conformado
(en todas las cosas) mediante la obediencia,
a Aquel que lo ha engendrado.

Por lo tanto, sientan la medida de lo que Dios engendra en ustedes,
y en ella sean obedientes.
No intenten levantarse por encima de ella en nada,
para que el enemigo no obtenga poder para envanecer sus mentes con un
conocimiento que esté por encima de la vida de Cristo en ustedes,
porque este conocimiento devorará esa vida.
Y cuando sientan que la fe, el amor, la mansedumbre, gentileza,
paciencia o cualquier inclinación piadosa se mueve en ustedes,
en esto sean obedientes con toda diligencia,
y entonces experimentarán su poder contra todas las inclinaciones contrarias en su carne.
De este modo, aprenderán la salvación de la gracia para vida eterna,
la cual nunca podrán alcanzar con palabras,
o por cualquier otro método aparte de la obediencia de ella.
Y así no recibirán la gracia de Dios en vano,
ni las palabras externas sin la eficacia de la vida,
sino que recibirán el conocimiento del misterio de la piedad,
y lo sentirán creciendo diariamente.

Porque mediante la obediencia al Espíritu el alma es purificada de su oscuridad e impureza,
y preparada para una mayor manifestación del misterio escondido,
y para recibirlo en plenitud, con la capacidad de caminar en él. Y así,
por el Espíritu Santo,
serán capaces de confesar verdaderamente que Jesús es Señor
sobre toda potestad en el cielo y en la tierra,
que Él es quien abre todos los secretos y el único que revela al Padre.
Y por Él se harán sabios en su conocimiento para la salvación,
no para vana palabrería--porque todas estas palabras vanas se levantarán
y condenarán a aquellos que se glorían en ellas.

Pero si en el Espíritu escuchan diligentemente y obedecen,
conocerán que Aquel que antes hablaba por los profetas ahora habla por Su Hijo,
quien es el eterno poder de la piedad y el Unigénito del Padre.
Y ustedes, en quien Él ha sido manifestado,
serán hechos semejantes a Él en todas las cosas.
Los profetas profetizaron de la gloria por venir,
pero el Hijo declara al Padre en esta vida presente,
de acuerdo con la medida en que Él esté formado en el corazón;
y conforme Él se levante en plenitud, abrirá los cielos y dará la herencia.
