== Capítulo II. La Guerra del Cordero / Contra el Hombre de Pecado

[.heading-continuation-blurb]
El objetivo de ella, Su manera de llevarla a cabo, y contra qué Él pelea; Sus armas,
Su bandera, y Su reino, y cómo todos pueden saber si están en esta guerra o no;
y si el mismo Cristo que "`es, era, y ha de venir,`" está en ellos,
y si le son fieles o no.

El Señor Dios Todopoderoso,
a quien le pertenecen todos los reinos en el cielo y en la tierra,
no hace nada en ellos salvo por Su Hijo, el Cordero.
Es por medio de Él que Dios crea y gobierna, salva y condena, juzga y justifica,
hace paz y hace guerra.
En cualquier cosa que Él haga, ahí estará el Hijo a la diestra del Padre en todas partes,
en quien Dios
ha soportado la carga de iniquidad y la opresión de la maldad
que ha abundado por muchas generaciones.

Y ahora Su aparición en el Cordero es para hacer guerra contra el dios de este mundo,
y entrar en juicio con Sus súbditos respecto a su rebelión contra Él--Su
Creador--el cual ha ordenado su principio y les ha dado aliento.
Porque habiendo quebrado el orden que había en el principio,
y rendido su obediencia al espíritu del mundo y sus invenciones,
ahora han llegado a estar tan unidos a ese espíritu
que han contaminado sus almas y sus cuerpos,
cegado sus ojos, tapado sus oídos,
y se han convertido en criaturas completamente inútiles para Dios,
que no están en condiciones de ser un templo en el cual Él pueda ser adorado.
Ellos ya no pueden oír la voz o entender la mente
del Espíritu eterno (por el cual fueron creados),
sino que se han convertido en enemigos declarados de cada reprensión y
reprobación del Espíritu que les ha sido dada para guiarlos a Dios.
Este buen Espíritu testifica contra sus malas obras,
pero ellos no tienen miedo de hablar contra Él como
algo que no vale la pena tener en cuenta,
ni es capaz de guiarlos en el camino de la verdad.
Así la criatura ha caído del llamado y servicio de Dios,
y se ha hecho una con el dios de este mundo,
para servirlo y obedecerlo de muchas maneras que hacen afrenta al Espíritu de gracia,
usando la creación contra el Creador.
Por lo tanto, es contra la semilla del mal,
y contra toda su obra (que ha sido engendrada en esa naturaleza)
que el Cordero hace guerra para vengarse de Sus adversarios.

[.small-break]
'''

[.no-indent]
_El objetivo de Su guerra es:_ Juzgar a este engañador abiertamente,
delante de toda la creación, mostrando que sus caminos,
modas y costumbres son contrarios al orden de vida
que Dios estableció para el hombre en el principio.
Así que Él busca atar a este engañador y redimir
de su cautiverio a todos los que creen en el Cordero,
y están cansados de servir a Su enemigo, y de ser sus esclavos,
y que están dispuestos a presentarse y entregar su nombre y su corazón para unirse a Él,
y llevar Su imagen y testimonio abiertamente delante de todos los hombres.
Estos hombres,
que Lo siguen voluntariamente por el camino en el que el
Padre ha dado victoria sobre el poder del enemigo,
son hechos nuevos y redimidos para Dios,
para que así solo Dios sea quien reine en Su propia obra.
Pero el resto, los que no están dispuestos a creer en Él y seguirlo,
ni a llevar Su imagen, serán condenados junto con el destruidor a la destrucción eterna.

[.small-break]
'''

[.no-indent]
_Su manera de llevar a cabo esta guerra es:_ Primero,
a fin de que Él sea justo (quien juzgará a todos los hombres y espíritus),
pone Su luz en los corazones de todos, tanto hombres como mujeres,
por la cual les permite a todos ver (si le prestan atención) qué es lo que le desagrada,
qué es lo que es de Él, y qué es contrario a Él,
qué es lo que Él aprueba y qué es lo que desaprueba.
Por esta luz todos pueden saber qué es lo que está destinado a destrucción, y,
por lo tanto, salir de eso, para no ser destruidos con ello;
porque es Su deseo salvar y recibir a todos los que no son voluntariamente desobedientes
a Él ni están endurecidos contra Él en los placeres de este mundo.
Sí,
Él está dispuesto a recibir a todos los que están
engañados pero que quieren salir del engaño,
a todos los que están cautivos pero que quieren ser libres,
a todos los que están en tinieblas pero que quieren venir a luz; en pocas palabras,
a todos los que aman la justicia más que los placeres del pecado.
Él no tiene ningún deseo de destruirlos,
ni de verlos pelear ciegamente contra Él. En lugar de esto,
Su deseo es tomarlos a Sí Mismo,
para que sean uno con Él contra ese poder que los ha desviado y engañado.
Y Él en verdad recibirá a todos los que se vuelvan a Su reprensión,
y les dará poder en espíritu y vida para ser como Él es, según la medida de cada uno.
Pero todos deben permanecer en vigilancia y guerra contra eso que los mantuvo sujetos,
y que mantiene a todo el resto de la creación en esclavitud,
para que Él pueda restaurar todas las cosas a su antigua libertad.

[.small-break]
'''

[.no-indent]
_Contra qué deben hacer guerra:_
Deben hacer guerra contra cualquier cosa que no sea de Dios,
cualquier cosa que el ojo (que ama al mundo) desee,
cualquier cosa en la que la carne tome placer,
cualquier cosa que haga acepción de personas (como
dicen las Escrituras)--los deseos de los ojos,
los deseos de la carne, la vanagloria de la vida.
Estas cosas no provienen de Dios,
y cualquier cosa que el dios de este mundo haya engendrado en los
corazones de los hombres para que practiquen o defiendan--sí,
cualquier cosa que Dios no haya puesto ahí--contra todo
esto el Cordero y Sus seguidores deben hacer guerra,
y ellos deben permanecer en enemistad contra estas cosas
tanto en sí mismos como en cualquier lugar que las vean.
Porque el reino solo es conocido en la obra de Dios,
y todas las demás obras Él las destruirá.

Por lo tanto, la guerra de ellos no es contra la criatura,
porque ellos no tienen lucha contra la carne y sangre que Dios ha creado,
sino contra la maldad espiritual que está exaltada donde sólo Dios debe ser exaltado,
a saber, en los corazones de los hombres y mujeres.
Porque por abrazar las obras del diablo, y contender por ellas,
se han convertido en enemigos de Dios, y sus almas están destruidas.
Así que la guerra del Cordero es contra toda obra
y designio del dios de este mundo--sus leyes,
sus costumbres, sus modas, sus invenciones,
y todo lo que busque añadir o quitar algo de la obra de Dios,
y la haga diferente a como era en el principio.
Todo esto está en enemistad con el Cordero y Sus seguidores
(los que han entrado en el pacto que era desde el principio),
y, por lo tanto,
no es algo extraño que sean aborrecidos por el dios de este mundo y por sus súbditos.
Porque el Cordero viene a saquear todo lo que tiene,
y a destruir todo el cuerpo de pecado (que es el fundamento y fuerza de su reino),
y a tomar el principado sobre Sí Mismo,
para que Dios reine completamente en los corazones de los hombres,
y los hombres vivan completamente en la obra de Dios.

[.small-break]
'''

[.no-indent]
_Cuáles son sus armas:_
Puesto que su guerra no es contra los cuerpos de los hombres,
sus armas no son carnales, ni le hacen daño a la creación;
porque el Cordero no viene a "`destruir las vidas de los hombres,`"^
footnote:[Lucas 9:56 RV 1602 Purificada]
ni la obra de Dios.
Pero cuando Él aparece dentro de Sus súbditos,
pone armas espirituales en sus corazones y en sus manos.
De modo que su armadura es la luz, su espada es el Espíritu del Padre y del Hijo,
su escudo es la fe y la paciencia,
y sus caminos están preparados con el evangelio de la paz
y de la buena voluntad para con toda la creación de Dios.
Su coraza es la justicia y la santidad a Dios, sus mentes están ceñidas con piedad,
y ellos están cubiertos de salvación, y son enseñados por la verdad.
Y así el Cordero en ellos, y ellos en Él,
salen en juicio y justicia a hacer guerra contra Sus enemigos, venciendo y para vencer.
Ellos no pelean como pelea el príncipe de este mundo a través de sus súbditos,
con azotes y prisiones, torturando y atormentando los cuerpos de las criaturas,
matando y destruyendo las vidas de los hombres;
sino que los seguidores del Cordero salen en el poder
del Espíritu con la Palabra de verdad,
para hacer juicio sobre la cabeza de la serpiente que engaña y seduce al mundo.
Y a través de estos fieles, el Cordero cubre a los que son Suyos con amor,
y enciende ascuas de fuego sobre la cabeza de Sus enemigos.

Porque "`con espíritu de juicio y con espíritu de fuego`"^
footnote:[Isaías 4:4 RVG]
el Señor contenderá con Sus enemigos;
y habiendo encendido el fuego y despertado a la criatura,
y quebrado su paz y reposo en el pecado,
Él espera con paciencia a fin de recuperar a la criatura y matar la enemistad.
Y aunque el espíritu maligno que reina en la criatura arroje toda clase de ira y envidia,
el Cordero continúa siendo compasivo, ofreciendo amor a cambio del odio,
y luchando con Dios contra la enemistad--con muchas intercesiones, con toda paciencia,
longanimidad y fidelidad, en verdad y en amor no fingido,
y con todos los frutos del Espíritu, para que, por cualquier medio,
Él venza con el bien el mal.
Y por Su Luz, Él busca abrir ese ojo en la criatura que el dios de este mundo ha cegado,
con el fin de que los hombres aprendan a aborrecer lo que Dios aborrece,
y vean los frutos de muerte que han producido.
De esta forma todos verán y serán convencidos de que la luz no engaña, sino que,
en donde sea que gobierne, ella tiene la vida y poder de la inocencia y santidad.

En verdad,
la predicación interna del Cordero tiene poder para abrir los ojos de todos los
que no son ciegos voluntariamente a causa de su amor a las obras de las tinieblas;
y estos (por la luz) son dejados sin excusa para siempre.
Pero muchas veces el Cordero, a través de Sus súbditos,
contiende y predica a los espíritus encarcelados,
teniendo gran paciencia para con el mundo,
para con las naciones y para con cada individuo,
antes de entregarlos y contarlos para la destrucción. Sí,
algunas veces Él los persigue hasta que su rabia contra Él,
y la crueldad que ejercen contra Sus miembros,
se vuelven tan grandes que ya no hay remedio, como sucedió en los días de la antigüedad:

[quote.scripture]
____
Y Jehová el Dios de sus padres envió constantemente
palabra a ellos por medio de sus mensajeros,
porque Él tenía misericordia de su pueblo y de su habitación.
Mas ellos hacían escarnio de los mensajeros de Dios,
y menospreciaban sus palabras, burlándose de sus profetas,
hasta que subió la ira de Jehová contra su pueblo, y no hubo ya remedio.^
footnote:[2 Crónicas 36:15-16]
____

Ahora bien,
estos son los frutos que son la bandera que el Cordero manifiesta
a todo el mundo por medio de aquellos en quienes Él reina:
En la medida que ellos lo obedecen, Él los cubre con amor, gentileza, fe, paciencia,
pureza, gracia, virtud, sobriedad, abnegación, mansedumbre e inocencia,
vistiendo a todos de ropas blancas.
Los que tienen estas virtudes son los que verdaderamente
siguen a Aquel que está en ellos,
quienes "`andan como Él anduvo,`"^
footnote:[1 Juan 2:6]
en conformidad a Dios en todas las cosas, con denuedo y celo,
sabiendo que el Cordero es su líder,
y testificando juntamente con Él en contra del mundo que sus obras son malas.
Y estos son cubiertos con Su justicia contra todas las tormentas
y tempestades con las que seguramente se encontrarán,
participando de las mismas oposiciones que han experimentado
todos los que han llevado Su testimonio;
porque el Cordero solo ha tenido un testimonio desde
el principio para convencer al mundo.
Por lo tanto, todos los que estén dispuestos a creer en la santidad, y a amarla,
verán donde puede hallarse, y saldrán a Él y serán salvos,
para que el mundo entero no sea como Sodoma en el día de ira.
Porque después de que Cristo se haya manifestado de esta manera y haya sido rechazado,
el día de ira vendrá sobre todo pueblo y nación.

=== En Qué Consiste Su Reino

El poder, la gloria y el dominio del reino de Dios no pueden
comprenderse con el entendimiento mortal,
porque Su reino ya era desde antes del principio, y permanecerá para siempre.
Y este reino ordena y limita a todos los espíritus en el cielo y en la tierra,
y tiene dominio en los reyes de la tierra, y en todos los lugares celestiales,
aunque muchas veces los hombres no lo reconocen hasta que sienten
Su reprensión por haberse rebelado contra él. En verdad,
Él tiene dominio entre los paganos,
y Su mano está en los consejos de los reyes de la tierra,
y no hay lugar en el que Él no esté,
ya que Él ha descendido a las partes más bajas de la tierra,
y subido por encima de todo los cielos para llenarlo todo.

Pero Su reino en este mundo,
en el cual Él principalmente le place andar y darse a conocer,
está en los corazones de aquellos que han creído en Él,
y han respondido a Su llamado fuera del mundo; cuyos corazones Él ha purificado,
y cuyos cuerpos Él ha lavado en su obediencia,
haciéndolos templos dignos en los cuales el Padre es adorado.
En estos Él se regocija y deleita, y Su reino en ellos es justicia y paz.
Él los guía en amor, poder y pureza, mediante los dulces movimientos de Su Espíritu,
fuera de todos sus caminos propios y de la voluntad propia (en los cuales ellos se contaminarían),
y los lleva a la voluntad del Padre, por la cual ellos llegan a ser más limpios y santos.
Él les permite conocer los límites de Su pacto, y hasta donde pueden ir y estar a salvo.
Él les da Sus leyes y estatutos,
que en todos los aspectos son contrarios al dios de este mundo,
para que (delante de todos Sus enemigos) se pueda ver que ellos son Suyos.
Si ellos guardan Su consejo están a salvo; pero si lo rechazan,
Él les hace sentir la corrección del Padre.
Su presencia es gran gozo para con todos los de ánimo voluntario;
pero Él se mostrará rígido para con el perverso.
Los besos de Su boca son vida eterna, pero ¿quién podrá soportar Su ira?
Las cosas secretas del Padre están con Él, y Él hace sabios a todos sus súbditos.
Él los hace a todos de un corazón--que es uno con Él, y de un mismo sentir.
Su gobierno es completamente puro, y ninguna cosa inmunda puede soportar Sus juicios.
Cualquiera que verdaderamente llegue a entrar a Su reino,
no podrá evitar ser reconocido como un hijo del reino,
y su cambio será visto por todos los hombres.
Él los mantiene humildes, y engendra un espíritu manso en ellos.
Y con Su poder los lleva a enfrentarse contra la enemistad del maligno,
enseñándole a aquel que permanece en Su reino a estar
contento en todas las circunstancias.

Ya es el tiempo en el que muchos falsos cristos deben
aparecer y ser descubiertos por el verdadero Cristo,
junto con todos sus falsos profetas, caminos, adoraciones y adoradores, que,
aunque estén en guerra unos contra otros, no conocen la guerra del Cordero.
Entonces, puesto que Él ha aparecido (quien es desde la eternidad y no cambia),
aquí todos tienen una prueba eterna para que vean si lo
profesan a Él a partir de la letra o a partir de la luz.
¡Vengan ahora y vean si Cristo está o no en ustedes!
Midan su vida, y pesen su profesión con esa luz que no puede engañarlos,
que ha permanecido y que permanecerá para siempre.

En toda verdad, ante Dios y ante sus propias almas,
prueben sus obras mientras haya tiempo,
no sea que ustedes y sus obras perezcan juntamente.
Primero, vean si el Cristo que ustedes proclaman es el mismo
que ha sido desde la eternidad hasta la eternidad,
o si Él ha cambiado según los tiempos: en tiempos de vida y muerte, de paz y guerra,
de triunfo y sufrimiento, etc.
Y si en verdad ustedes han hallado al verdadero Cristo,
entonces prueben su fidelidad a Él en todas las cosas.
Aquel que ustedes obedecen como su líder ¿los guía a salir de este mundo,
y a hacer guerra contra él, y contra todo orgullo, gloria, modas, costumbres,
ídolos y placeres del mundo, y contra cualquier otra cosa que no sea de Dios?
¿Los lleva a entregar sus vidas hasta la muerte,
en lugar de conscientemente rendir su obediencia al pecado?
¿Justifica Él alguna cosa en ustedes aparte de la vida que justificó en los profetas,
apóstoles y santos de la antigüedad?
¿Acaso Él ahora le da libertad a Sus súbditos para que se sometan al dios de este mundo
y a sus caminos en cosas que Él ha prohibido en los santos antiguos (cosas que,
por negarlas, muchos han sufrido, tanto en ese entonces como ahora)?
¿Está Él en paz con ustedes mientras viven en los placeres de la carne
o tienen comunión con los espíritus inmundos que están en el mundo?
¿Acaso Él no guía a salir del mundo, y a contender contra él con vigilias, ayunos,
oraciones y fuertes clamores al Padre,
para que tanto ustedes como otros puedan ser guardados y librados de su esclavitud
y contaminación? ¿Es este el reino que han encontrado dentro de ustedes?
¿Y revela Él en ustedes las mismas leyes espirituales en
contra de todos los caminos y costumbres del hombre de pecado,
que ha revelado en Sus súbditos en todas las eras?
¿Engendra Él en sus corazones una nueva naturaleza que es contraria a la naturaleza,
deseos y placeres del mundo en todas las cosas,
por la cual echa fuera la vieja naturaleza que inclina al mundo
y que puede estar en paz con él? ¿Se encuentra su paz ahora enteramente
en Él? ¿Y eso que crucifica al mundo a ustedes,
y a ustedes a él, es su verdadero gozo y deleite?
¿Los ha llamado a salir de este mundo para que den testimonio
de Su nombre ante los poderes de dicho mundo,
poniendo este testimonio en sus corazones,
y las mismas armas en sus manos que usaron los santos
antiguos para combatir los poderes de las tinieblas,
mediante las cuales ustedes encuentran poder para vencer con el bien al mal?
En verdad, hay muchos otros frutos que Él siempre ha manifestado en Sus escogidos,
por los cuales se sabía que estaban en Él, y Él en ellos,
y por los que el mundo los ha aborrecido.
Y por todo esto, ustedes pueden saber claramente si Él es el mismo
hoy en ustedes como lo fue ayer en Su pueblo, y como lo será por siempre.
Porque el Cordero no cambia, ni se conforma al mundo,
ni a la voluntad de ninguna criatura,
sino más bien cambia a todos Sus seguidores hasta
que sean semejantes a Él en todas las cosas;
porque ellos deben llevar Su nombre e imagen delante de todos los hombres y espíritus.

¿Acaso no les concierne grandemente examinar su condición,
viendo cuán pronto todos deberán dar cuenta por sus vidas y por su servicio?
¿O han abandonado su estado original para vivir como las bestias del campo,
considerando solo sus propios vientres y placeres?
¿Invierten su tiempo y fuerza en vigilias y oraciones al Padre
de los espíritus por ustedes mismos y por el pueblo de Dios,
para que sean guardados en el tiempo de la tentación y de los ataques
del maligno (que busca aprovecharse de los hermanos más débiles)?
¿Oran ustedes por sus enemigos, para que sean librados de debajo del poder del diablo,
en el que están cautivos a voluntad de él, cumpliendo sus deseos y su envidia,
y ejecutando su ira sobre los inocentes?
¿Y se niegan realmente a ustedes mismos, cohibiéndose de placeres, ganancias,
comodidades y libertad,
a fin de que puedan mantener una conducta casta en el poder y vida de la ternura,
mansedumbre, fidelidad y verdad?
¿Está su conciencia libre de ofensas ante Dios y ante todos los hombres,
de modo que puedan resplandecer en justicia,
y convencer a esos enemigos por quienes ustedes oran,
siguiendo así a Aquel que ha dado Su vida por Sus enemigos?
¿Es esta su guerra, y son estas sus armas?
¿Es este su llamado, y son ustedes fieles a Aquel que los ha llamado,
de modo que no puedan, de ninguna manera, inclinarse ante el dios de este mundo,
ni ante sus caminos, ni siquiera para salvar sus vidas,
reputación o posesiones en el mundo?
¿Y, sin embargo, pueden servir a la criatura más pequeña en su camino hacia Dios,
aunque esto signifique la pérdida de todo?

Les ruego que sean fieles a sus propias almas y consideren:
¿Encuentran algo en ustedes que los llama o mueve a actuar de esta manera,
o que los reprende si hacen lo contrario?
Y si lo encuentran ¿son ustedes uno de esos que apagan este Espíritu,
cierran sus ojos y niegan el llamado del Cordero, a riesgo de sus propias vidas?
Y si no encuentran esto, ¿no es su profesión de Cristo una mentira?
¿No son ustedes miembros muertos, que han sido cortados de Él,
y están sin Dios en el mundo?
¡Oh que ustedes se probaran a sí mismos!
Porque hay muchos obreros fraudulentos en este día de Su aparición,
quienes hacen la obra del Señor con negligencia e indolencia,
ocupándose en su propia obra en lugar de la Suya.
Y hay muchos que son llamados, y que permanecen por un tiempo,
pero a la hora de la dificultad demuestran ser fraudulentos,
y vuelven a servir y encontrar placer en el mundo.
Otros son llamados y convencidos, pero solo salen a medias del mundo,
tan lejos como puedan sin experimentar ninguna pérdida o vergüenza,
y sin dejar su pacto con él en lo que sea que les provea mayor ganancia,
crédito o beneficios terrenales.
Todavía hay otros que han respondido a su llamado,
y sido fieles en el pacto del Cordero (hasta donde
habían entendido) contra el príncipe de este mundo,
pero al no permanecer vigilantes contra el enemigo,
ni mantenerse humildes en el temor y fervientes en la luz,
permitieron que su sencillez se desviara,
y fueron llevados de regreso a los viejos y pobres rudimentos del mundo otra vez,
considerando ahora como su perfección y crecimiento lo que una vez habían vomitado.
Estos esperan grandes cosas por su esfuerzo, pero son más ciegos que los demás,
y su condición es más lamentable, porque su sinceridad se ha desviado y perdido.
Y hay muchos otros tipos de tierra que no llevan fruto que conduce a la perfección,
corazones que no han sido hallados fieles a Aquel que los ha llamado,
y por lo tanto ahora es una realidad que "`muchos son llamados, más pocos escogidos`"^
footnote:[Mateos 20:16; 22:14]
y fieles.
Muchos se avergüenzan de la apariencia del Cordero, porque es muy humilde, débil,
pobre y menospreciable,
y otros se asustan cuando ven tan grande poder contra Él. Y muchos están
poniendo a trabajar sus imaginaciones para tratar de entender al reino,
y obtener poder sobre el pecado, y encontrar paz para su conciencia,
pero pocos están dispuestos a dejar todo para ser
guiados por el Cordero por un camino que no conocen,
para llevar Su testimonio y Su sello contra el mundo,
y para sufrir con Él por este testimonio.

Ahora bien, la mentira les ha enseñado a decir lo siguiente
(y quizás ustedes piensen que es verdad):
"`¡De ninguna manera, sino que yo sufriré con Cristo hasta la muerte!`"
¡Pero vengan a la prueba de hecho y en verdad!
¿No sufre Él en el corazón del
hombre bajo todo el orgullo y los placeres de la carne,
y por toda clase de excesos, costumbres y modas que no son de Dios sino del mundo?
¿No están en contra de Él todas las cosas que no son de Él ni del Padre?
¿No son los deseos de los ojos, los deseos de la carne,
y la vanagloria de la vida sus opresores en el corazón del hombre?
Y ustedes que viven en estas cosas,
y en las modas del mundo (e incluso abogan por ellas),
¿están verdaderamente sufriendo con Él por causa de estas cosas,
y peleando junto a Él contra ellas?
Porque si fuera así, estarían cansados de ellas,
y dejarían de practicarlas y de abogar por ellas contra
Él. Pero al final hallarán que esto es la verdad:
que no es posible sufrir con Él y al mismo tiempo servir a Sus enemigos.

Oh, todos ustedes de todas las denominaciones, que constantemente escuchan sermones,
¿cuánto tiempo más pasará antes de que escuchen lo que el Señor
(que no hace acepción de personas) dice en sus propias almas?
Porque Él rechaza a todos los que no llevan la imagen de Su Hijo haciendo el bien,
aunque hagan sacrificios como Caín,
u oren con lágrimas como Esaú. Oh que ustedes vieran con la luz de Cristo en sus propios
corazones cómo los deseos del mundo les han robado a sus almas la imagen celestial,
cómo el espíritu del mundo ha llevado cautivas a sus mentes a sí mismo y a su semejanza,
y cómo ustedes yacen muertos en pecado, tapados con tierra,
y recubiertos con palabras de hombres.
Ojalá ustedes despierten antes de que la ira los despierte,
y se pongan la armadura de Dios,
y ya no dependan más de hombres que golpean el aire para pelear
sus batallas contra un enemigo que ya ha entrado a sus corazones.
Sino que, como soldados de Cristo,
todos ustedes aprendan a usar armas espirituales para combatir
la iniquidad espiritual que se ha exaltado en el templo de Dios;
porque esto es lo que llena el corazón de cargas de iniquidad y de tropiezos mundanos,
y hace que ustedes no puedan ver ni servir al Señor.

Con estas armas espirituales,
todo pensamiento debe ser llevado cautivo a la obediencia de Cristo.
Esta es la verdadera guerra,
y estas armas "`son poderosas en Dios para la destrucción de cada fortaleza`" que el
hombre de pecado tiene en ustedes--"`estando prontos para castigar toda desobediencia,
cuando vuestra obediencia sea perfecta;`"^
footnote:[2 Corintios 10:4-6]
porque cualquier cosa que no quiera sujetarse al Espíritu de Dios debe ser condenada.
Solo estas armas son eficaces para limpiar el corazón de todo lo
que se levanta contra la vida y contra el conocimiento de Dios,
porque ellas abren paso a Su aparición por el poder de Cristo--Su
luz y vida--algo que ninguna palabra de hombre es capaz de hacer.
Y bienaventurados aquellos que sienten y encuentran
este tesoro obrando en sus vasos de barro,
porque estos verán que Dios aprueba sus obras, y tendrán la alabanza que viene de Él,
y no de los hombres.
De este modo llegarán a ver lo que otros han dicho en las Escrituras
acerca del "`Cordero de Dios que quita el pecado del mundo,`"^
footnote:[Juan 1:29]
porque ustedes sentirán el poder salvador de Su Cruz, de Su muerte y resurrección,
y la eterna pureza de Su vida, a la cual fluye libremente el amor eterno del Padre.

Llamados, elegidos y fieles son los siervos y súbditos del Reino de Cristo,
en quienes Él (en este día) hace guerra contra el príncipe de este mundo,
la bestia y el falso profeta, y contra todos los que sirven bajo el dominio de Satanás,
y obedecen las leyes que él ha establecido.

Ahora bien, ustedes que dicen que
"`los reinos del mundo han venido a ser del Señor y de Su Cristo;`"^
footnote:[Apocalipsis 11:15]
asegúrense de que esto sea verdad en ustedes, y que no estén engañándose a sí mismos.
Ustedes deben conocer la guerra del Cordero antes de que puedan experimentar Su reino,
y "`los que están con Él son llamados, elegidos y fieles.`"^
footnote:[Apocalipsis 17:14]
Aquel que predica el reino de Cristo en palabras, sin haber experimentado la victoria,
es el ladrón que viene antes de Cristo.
Así que miren que sus propias palabras no los condenen;
y consideren su llamado y cómo han respondido a él,
y si han sido fieles en la guerra a la cual han sido llamados.
Porque Cristo está en guerra contra Sus enemigos,
y Él llama a Sus súbditos para que lo sirvan en esta batalla
contra todos los poderes de las tinieblas de este mundo.
Él trastornará todas las cosas de este mundo antiguo--todos sus caminos y modas--y
Él hará nuevas todas las cosas que el dios de este mundo ha corrompido.
Porque en estas cosas los hijos del diablo (por seguir sus propios
deseos) se han corrompido a sí mismos y han servido al devorador.
Y es contra estas cosas que el Cordero hace guerra dentro de quien sea que Él aparezca.
Sí, Él invita a todos los hombres a unirse a Él con todo su corazón, con toda su mente,
y con todas sus fuerzas.
Y es por esto que Él ha encendido Su lámpara en sus corazones,
para que puedan descubrir cada secreto perverso que
el hombre de pecado ha atesorado allí,
y discernir los pensamientos y las intenciones del corazón. Porque es
de allí que Él echará fuera al hombre fuerte con todas sus posesiones,
y es ahí donde someterá a la criatura totalmente a Sí mismo,
para entonces poder formar un nuevo hombre, un nuevo corazón,
nuevos pensamientos y una nueva obediencia por un nuevo camino,
y Él hace todo esto para así reinar en todas las cosas--y este es el reino de Dios.

Ahora bien, muchos son llamados a esta guerra, pero pocos son elegidos y fieles.
Los que son fieles a su llamado, son los que Él elige, y en ellos Él reina,
y con ellos Él hace guerra por todos lados contra Sus enemigos,
sin importar la bandera con la que aparezcan.
Él ha puesto la espada de Su Espíritu en sus manos, y Su Palabra en sus bocas,
y con esto ellos hacen guerra contra todo el mundo, es decir,
contra todos los que no están dispuestos a someterse a Él; y en verdad,
el mundo está en guerra contra ellos.
Y aquel que es fiel no hará ninguna paz o acuerdo con este mundo,
ni se inclinará a él o someterá hasta que todas las cosas estén sujetas a Cristo.
Estos son fieles a Aquel que los ha llamado.

¡Así que ustedes que son grandes en palabras, pruébense a sí mismos,
si realmente están o no en Su reino y entre Sus súbditos!
Porque si lo estuvieran, ustedes estarían trabajando con Él en este Su día,
en el cual Él está viniendo
"`__en__ decenas de millares de sus santos, para tomar la venganza`"^
footnote:[Judas 1:14-15, Traducción Literal]
en Sus manos, y derramarla sobre Sus enemigos.
Pero ustedes que están dormidos y en reposo en la carne,
que están en paz en los caminos y modas del mundo,
los cuales han sido inventados y mantenidos por el
hombre de pecado--ustedes no son de Su reino.

Pero ustedes dirán:
"`Dios es amor, y se nos ha mandado que amemos a todos, y que busquemos la paz con todos, etc.`"
Pero yo les pregunto:
¿Es el amor de Dios en ustedes diferente de lo que
siempre ha sido en Cristo y en todos Sus santos,
a quienes el mundo siempre ha aborrecido, pero a quienes Dios ha amado,
y en quienes Él ha testificado contra el mundo,
incluso hasta el punto de sufrir prisiones, persecuciones y muerte?
¿No estaban estos en el amor de Dios?
¿No guardaban ellos Sus mandamientos?
¿Y tomarán ustedes las palabras de ellos en sus labios
y condenarán sus vidas con sus hechos?

La guerra del Cordero no es contra la creación, porque si fuera así,
Sus armas serían carnales, como las armas de los espíritus mundanos.
Pero nosotros "`no tenemos lucha contra sangre y carne,`"^
footnote:[Efesios 6:12]
ni contra la creación de Dios.
No, nosotros amamos la creación;
pero peleamos contra los poderes espirituales de maldad que luchan contra Dios
_en la creación_ y la llevan cautiva a deseos que batallan contra el alma,
y esto lo hacemos para que la criatura sea redimida y llevada
a la libertad preparada para los hijos de Dios.
Y esta guerra no es contraria al amor, ni a la paz eterna,
porque sin ella no podría haber amor verdadero o paz duradera.
En verdad,
es nuestro amor a Dios y a los hombres lo que nos constriñe a ser fieles en esta guerra.

Pero el amor de Dios no es para esa semilla de esclavitud,
ni Él jamás nos mandó a buscar la paz de esa semilla,
porque "`la amistad del mundo es enemistad con Dios,`"^
footnote:[Santiago 4:4]
como dice la Escritura.
Y si ustedes no hubiesen caído en el amor propio (que es
completamente ciego en cuanto al amor de Dios),
verían la gran diferencia que hay entre la criatura y la semilla
que mantiene a la criatura en esclavitud y fuera del amor de Dios.
¿Acaso ustedes pueden amar a esa semilla del mal, sin odiar la criatura,
y a Dios también? Todos los que conocen las batallas del Cordero,
quienes están en el amor verdadero de Dios, entienden bien estas cosas.

¿No es cierto que el espíritu de orgullo, glotonería, embriaguez, placeres,
envidia y contienda mantiene a la criatura
(la cual, según el mandamiento de Dios, ustedes deberían amar) en esclavitud?
¿No gime la criatura esperando ser redimida de la vanidad,
costumbres y modas de esta generación? ¿No está todo el tiempo
del hombre dedicado al servicio de los deseos e inventos que el
hombre de pecado ha concebido--inventos en comidas y bebidas,
en apariencia, en adoración, en deportes y placeres, etc?
¿No está esclavizada toda la creación bajo este espíritu de fornicación,
de modo que la vida entera a menudo es consumida en vano?
¡Ay! Hombres y mujeres vienen al mundo y salen otra vez de él como si
hubieran sido creados para ningún otro fin más que la vanidad,
y para complacerse a sí mismos;
apenas uno de diez mil experimenta algún llamado de Dios a Su servicio,
o tiene un oído para escuchar esa voz.
Y si alguno la escucha y obedece,
entonces el mundo concluye que este ha sido engañado,
y está listo para devorarlo porque testifica contra
los males que destruyen las almas de los hombres,
hacen nulo el servicio del hombre a Su creador y devoran la creación.

¿Y pueden ustedes amar este espíritu, inclinarse y conformarse a él,
o dejar que reine en ustedes o en sus hermanos,
y aun así pretender buscar el amor y la paz, y obedecer los mandamientos de Dios,
jactándose de palabras sublimes acerca del reino de Cristo?
¿Y consideran ustedes como algo bajo y necio que hombres, con fidelidad y celo,
den su testimonio de Dios en contra de estos males?
¿No los descubrirá Dios eventualmente a todos ustedes,
y expondrá su engaño e infidelidad en su generación? ¿No quebrará Él su paz,
y anulará el pacto que ustedes han hecho con el mundo
para establecerse en comodidad y placer?
¿No los sacará Él con verdadero juicio,
a un lugar en el cual se verá de qué naturaleza es su amor,
de quien es el reino en el que están, y qué es lo que ustedes aman y sirven?

El Día ha amanecido, y el Sol ha salido para muchos, y no se pondrá,
ni detendrá su curso,
hasta que Él haya hecho una separación perfecta entre la semilla preciosa
y los hijos de fornicación y engaño. Y ahora la semilla santa es llamada
a manifestarse con su bandera contra el hombre de pecado,
y Él "`pelea con la espada de Su boca,`"^
footnote:[Apocalipsis 2:16]
y consume todo lo que es impuro e inmundo
"`con espíritu de juicio y espíritu de fuego.`"^
footnote:[Isaías 4:4 RVG]
Y todos los que son fieles tienen su armadura puesta,
listos día y noche para seguir al Cordero conforme Él se mueva,
no considerando nada como demasiado difícil si es necesario para predicar la reconciliación
entre Dios y la criatura a aquellos que han caído bajo el dominio del príncipe del mundo,
y han sido llevados cautivos a voluntad de él. Y este es el verdadero amor,
entregar todo por aquellos que todavía son enemigos.

¡Oh, tiempos peligrosos han llegado!
Ahora la tierra y el aire se encuentran corrompidos y llenos de violencia y engaño,
y la iniquidad abunda en todas partes.
Satanás está suelto y ha salido a engañar;
multitudes de espíritus han sido enviados por todas partes y se
les ha dado poder para entrar en todos los que moran en la tierra,
quienes habitan en lugares oscuros, porque no aman la luz.
¡Ay del mundo! ¡ay de todos los que han atesorado iniquidad en sí mismos!
Porque Satanás buscará lo suyo en ellos, y sus vasijas van a ser llenadas--sí,
serán llenadas de ira, de orgullo, de concupiscencia,
de codicia y de toda clase de injusticia.
Cada vasija debe ser llenada, para que el Alfarero las quebrante una contra otra.
Ay de las naciones que están embriagadas, cuya inmundicia está en sus calles; sí,
cuyas calles están llenas de orgullo, llenas de opresión y engaño, mentira,
juramentos y palabras maldicientes.
Ellos vomitan su inmundicia abiertamente y aun así no les da vergüenza.
La vanidad y la locura se han convertido en su gloria,
la iniquidad se manifiesta descaradamente, no en un rincón,
sino en los espacios más amplios de las calles.

¡Ay, no hay seguridad para ninguno que mire hacia afuera,
porque el pecado está a la puerta, listo para entrar!
Y ahora los atalayas son ciegos (habiéndose convertido en enemigos de la luz),
de modo que es fácil que la casa se llene de espíritus malos.
Legiones de demonios pueden entrar y habitar en la oscuridad--espíritus de orgullo,
espíritus de mentira, espíritus de adulación, toda clase de espíritus engañosos, que,
al dejar entrar, obran en el vaso según sus diversas naturalezas.
Sí, ellos hacen las obra de su padre el diablo,
manifestando su imagen a todos los que miran hacia afuera,
tentando a todos con el fin de expandir su reino.
Porque cuando el deseo del hombre mira hacia afuera,
entonces el orgullo llama y presenta un objeto al ojo, que al dejarse entrar,
concibe y crece hasta el punto de poder producir sus propios frutos,
y convertir a esta persona en una tentación para otras.
¡La voz de la vanidad llama desde el tesoro del diablo a todos los que pasan!
La fornicación espiritual clama en alta voz en las calles
para engañar a los simples y contaminar a las vírgenes,
tratando de profanar el espíritu puro y corromper la mente para alejarla de Dios.

Es solo al velar en la luz con diligencia, fidelidad y paciencia,
que el enemigo es mantenido afuera, y su semilla es asesinada adentro.
Pero mientras la raíz del orgullo y concupiscencia permanezca adentro,
buscará alimentarse tomando de afuera más de su propia naturaleza.
Pero la vigilancia fiel no le cederá el paso--ni hacia adentro
ni hacia afuera--y así será cortada su provisión,
y la semilla del maligno se mantendrá en esclavitud,
y el diablo no podrá venir para socorrer lo suyo.
Porque, a pesar de que "`los enemigos del hombre son los de su propia casa`"^
footnote:[Mateos 10:36]
(lo cual es el caso de todos hasta que llegan a estar verdaderamente muertos y sepultados),
aun así, una vigilancia fiel en la luz evitará que el alma sea engañada.
Y aunque el tentador, con toda sus asechanzas y sutilezas,
trate de volver la mente a lo externo, para poder llegar a lo suyo, aun así,
él no podrá entrar en la luz.
Así que aquel que mora en la luz, mora en Dios y tiene la inmortalidad como su defensa.
Estos se mantienen aferrados firmemente a la Cabeza, y sienten Su poder de mansedumbre,
verdad, paz, amor y paciencia;
y mientras aprenden a mantener su corazón y mente puesto en Él,
ellos no son tentados a apartarse.
Porque Cristo es dado por el Padre como la cabeza a la "`iglesia que es en Dios,`"^
footnote:[1 Tesalonicenses 1:1; 2 Tesalonicenses 2:1]
y que mora en la luz, y Él está sobre todo principado y potestad,
y sobre toda maldad espiritual.
Este es el Salvador,
y Él es ese nombre y naturaleza ante el cual "`se doblará toda rodilla,
y que toda lengua confesará,`"^
footnote:[Romanos 14:11]
y todos los que se revisten de Él en verdad y en justicia,
se han revestido de inmortalidad, de vida eterna y de libertad.
