[short="Cómo el Pecado se Fortalece"]
== Capítulo III. Cómo el Pecado se Fortalece / y Cómo es Vencido

Todos en general creen y confiesan que el pecado está en el mundo,
y que por su causa todos se han convertido en hijos de ira;
pero muy pocos entienden correctamente o tienen el deseo de saber cómo
el pecado se fortalece dentro de hombres y mujeres en contra de Dios,
y en contra de sus propias almas, ni cómo es vencido.
Sin embargo, por el bien de aquellos que sí quieren entender esto,
voy a declarar aquí algo de lo que he recibido de Aquel
que es fiel y verdadero en todo Su testimonio.

=== Cómo el Pecado se Fortalece

He descubierto esto: que,
así como el pecado obtuvo su origen al principio mediante la concupiscencia,
asimismo (hasta este día) obtiene su fuerza a través de los deseos
que salen a codiciar algo--ya sea espiritual o carnal,
o cualquier cosa que esté por encima,
antes o aparte de lo que el Espíritu eterno comunica al hombre,
o engendra en Él. Porque el dios de este mundo ha cegado el ojo interno de la humanidad,
el cual debería mirar a Dios para todas las cosas;
y hay otro ojo abierto (el ojo de la incredulidad), que mira las cosas visibles,
y da lugar para que la concupiscencia dé a luz afectos y
deseos en pos de algo a lo que el Espíritu de Dios no conduce.
Entonces el hombre pone a trabajar todo el poder y la sabiduría
que están dentro de él para obtener lo que desea,
y esto se vuelve pecado tanto en los deseos como en las acciones;
y mientras más es seguido, más fuerte se vuelve.

Ahora bien, cualquier cosa que sea obtenida de este modo,
se convierte en un tesoro de iniquidad, guardado en el interior,
en la morada del maligno, por el cual se incrementa la concupiscencia,
y la Semilla de Dios^
footnote:[La Semilla del reino sembrada en el corazón del hombre.]
es oprimida y enterrada.
Es así como el hombre se vuelve cada día menos sensible a la voluntad de Dios,
y a los movimientos de ese Espíritu puro que deberían
mantener viva al alma para el Creador,
y hacer que la mente esté completamente puesta arriba, en el Padre,
esperando únicamente en Él, el suministro de todas las cosas,
tanto para el alma como para el cuerpo.
Pero cada deseo que brote de esta raíz de iniquidad
(cuando se permite que salga) contamina al hombre,
y trae adentro eso que oprime al Justo, hasta que el hombre,
por seguir dándole lugar a esto, crece en la naturaleza de la enemistad,
y el designio de los pensamientos de su corazón se vuelve solamente el mal,
y ese Testigo en él (que debería darle el conocimiento
de Dios y el conocimiento del pecado) es enterrado.
De este modo el hombre llega a endurecerse y "`a perder toda sensibilidad,`"^
footnote:[Efesios 4:19]
estando totalmente muerto en pecados y transgresiones,
que se vuelven por costumbre tan naturales de cometer
como lo es para el buey beber agua.

Sí, es con avidez que el hombre, en esta condición, caza su propia destrucción,
habiendo detenido el camino de vida en sí mismo por haberlo transgredido con tanta frecuencia.
En verdad, él se ha degenerado de la naturaleza de Dios,
y ha recibido en su alma la naturaleza de la serpiente,
a la cual se ha unido voluntariamente; la cual, como levadura,
obra en todos aquellos que la reciben y se entregan a ella,
conformándolos a su propia naturaleza.
Y a medida que los hombres crezcan en ella,
los frutos de esta misma raíz y naturaleza surgirán,
los cuales el hombre manifestará con deleite,
estando siempre equipado con formas sutiles de disfrazar y justificar sus malas obras.
Sí, estando en pacto y en acuerdo con el pecado
(algunos en una cosa y otros en otra)
cada uno aboga por ese pecado que más le conviene a sus deseos,
orgullo, ganancia, placer o reputación en el mundo, o a algún otro propósito egoísta.
Toman consejo del mundo (y no del Espíritu del Señor) para saber qué es pecado,
y qué no es pecado,
pero ninguno está dispuesto a creer que puede ser
libre de todo pecado por medio de Aquel que,
mediante Su propio Espíritu, testifica contra todo pecado.
Así es como "`el hombre de pecado`" obtiene su reino
a través del consentimiento del hombre;
porque el hombre, estando dispuesto a mantenerse en pacto con él en un solo mal,
se vuelve culpable de todos.

=== Cómo el Pecado es Vencido

Ahora bien, la manera de vencer estas cosas,
y de derrotar a aquel que tiene su poder en ellas, es por la fe en Cristo Jesús--la Luz,
la Vida y el Camino al Padre.
Porque no puede haber ninguna victoria sin creer; pero, al seguir fielmente al Señor,
cargar pacientemente Su cruz y soportar Sus sufrimientos,
la enemistad llega a ser matada,
la cautividad a ser llevada cautiva y el hombre a ser puesto en libertad en la
Semilla santa para servir al Padre en Espíritu y vida otra vez.

En primer lugar, se debe creer en Cristo (quien es la Luz del mundo),
porque Él viene a manifestar y a reprobar las obras de las tinieblas,
a revelar el verdadero juicio y a dar discernimiento.
Su luz hace una separación entre las obras de Dios y las
obras del diablo en la mente y espíritu de la criatura,
permitiéndole al hombre ver cuál es el espíritu que domina su mente y afectos,
junto con los movimientos, operaciones y frutos de cada uno.
Sin esta luz, nadie puede saber correctamente qué es lo que debe ser destruido,
y qué es lo que debe ser salvado; con qué debemos unirnos,
y contra qué debemos hacer guerra;
porque es únicamente por medio de esta luz que el
hombre llega al conocimiento de pecado en sí mismo,
y a entender su origen, su raíz y todas sus operaciones.
Aunque la letra escrita, o algún otro medio externo nos pueda mostrar qué es pecado,
al señalar sus evidentes frutos cuando son manifestados, aun así,
sólo el Espíritu en nuestro interior puede descubrir la
iniquidad espiritual en sus primeros movimientos y brotes,
lo cual es el único momento en que se puede matar
antes de convertirse en pecado en la criatura.
Es necesario creer en esta luz y prestarle atención diligentemente todo el tiempo,
porque la sutileza del enemigo es tan grande,
habiendo obtenido poder sobre la voluntad y los sentidos del hombre,
que él los pondrá a pelear contra sí mismo a fin de destruir la obra de Dios en su alma.
Esto no puede evitarse de ninguna otra manera más
que al prestarle atención a la luz de Cristo,
para que ella haga una separación entre eso que debe ser limpiado,
y eso que debe ser destruido.
Por mucho que un hombre busque esto, no puede hacerse sin el Espíritu,
porque es una obra espiritual.

Y esta es la razón por la que muchos son mantenidos en dura labor durante todo su tiempo,
y nunca llegan a salir completamente del pecado y de la impureza--porque
no creen en eso que tiene poder para separar y sacar del mal,
sino que en lugar de esto se ponen a trabajar en la oscuridad,
sin ese ojo que ve una clara separación. Así es como muchos se
destruyen a sí mismos en su intento por destruir el pecado,
y, al no prestarle atención a la luz del Salvador,
son llevados por el destructor a pelear contra esa parte que Cristo viene a salvar
(incluso mientras aquel que viene a destruir se encuentra escondido en la oscuridad).
Pero el que crea en la Luz que manifiesta todas las cosas,
reprueba todas las cosas y juzga todas las cosas,
verá (con el ojo verdadero) contra qué tiene que hacer guerra,
y con qué tiene que unirse en todo momento en la obra.
Porque sólo Cristo es el pacto de luz, y Él ha sido dado por jefe.^
footnote:[Isaías 55:4]
Y cualquiera que crea en la Luz y la siga no errará en juicio ni en práctica;
pero no creer en esta luz es la razón por la que existen tantos guías ciegos,
y por la que tantas personas mueren en sus pecados.

Por lo tanto, Cristo es el camino de Dios,
y debe creerse en Él como Aquel que manifiesta las obras del diablo y las distingue
de las obras de Dios--condenando las obras del diablo en la carne,
y justificando las obras de Dios en el Espíritu.
Y a medida que Él manifieste cada espíritu junto con su operación, movimiento y fin,
con su origen e incremento, mostrando de dónde viene y a dónde volverá,
así la criatura podrá saber qué es eso que controla su mente y sus miembros,
y a qué espíritu se somete con su obediencia y servicio.
De este modo el hombre puede llegar a entender la
utilidad y propósito de todas sus obras,
y saber qué escoger, qué negar, qué justificar y qué condenar en su primer movimiento,
antes de que sea manifestado o formado.
De esta manera el juicio puede mantenerse continuamente sobre la cabeza de la transgresión,
y la libertad será proclamada al Justo en el interior, para que reine sin obstrucción.

Es por falta de fe, y por no sentir a Cristo obrando de esta forma,
que muchos perecen en el pecado,
incluso mientras parece que están luchando contra él--debido a que ellos
no creen que la luz sea suficiente para salvarlos del pecado.
Porque la luz manifiesta el pecado mientras todavía está en la tierra,
antes de que haya brotado,
y lo condena en su primera aparición. Y si el hombre
tan solo estuviera dispuesto a unirse a Cristo,
con fe y diligencia, para condenar el pecado en su origen,
en su primera tentación y movimiento, este se marchitaría y moriría,
y ya no sería capaz de vivir o prevalecer.
Y si por un tiempo el pecado continuara viviendo en los miembros, aun así,
esto no sería para condenación;
porque he visto una gran diferencia entre el pecado condenado en la criatura (aunque
todavía no completamente muerto) y el pecado en el que vive y por el que aboga.
Porque si tu vida y tu juicio están en esa luz que condena el pecado,
entonces estás muerto al pecado y vivo para Cristo,
y "`ya no eres tú el que peca sino el pecado que mora en ti,`"^
footnote:[Romanos 7:17, 20]
para el cual estás muerto, y al cual no le das tu consentimiento, ni tu aprobación,
ni tu fuerza de ninguna manera, y en el cual no te alegras.
Al contrario, tu fe, tu amor, tu deleite y tu fuerza están en Aquel que condena al pecado.
El que verdaderamente esté en esta fe y amor,
verá a sus enemigos perecer por el poder de su operación. Y por esta fe y amor,
el Justo vivirá en la criatura,
y estará condenando y matando el pecado hasta que todo sea destruido,
y la nueva creación de Dios se hallará viviendo únicamente en Él,
y será presentada al Padre sin mancha, ni arruga.

Porque esto he encontrado: La Luz que manifiesta el pecado en su primer movimiento,
y lo juzga y condena ahí,
es lo único que tiene poder para matarlo antes de que sea cometido, y, por lo tanto,
tiene también poder para salvar de la condenación. Y esto es lo que descubrirás: que,
así como Cristo no vive para justificación en el corazón del hombre que no cree en Él,
ni lo ama, sigue y confiesa;
asimismo el pecado no vive para condenación en el corazón del hombre que lo aborrece,
condena y niega.
Porque en cualquier corazón en el que este espíritu de iniquidad
sea visto en la Luz y en el cual haya una separación de dicho espíritu,
siendo juzgado como algo aparte de la criatura (estando
ella unida en juicio con el Justo),
ahí el pecado se marchitará y Satanás huirá,
porque en este corazón no tiene ningún reino, ni escondrijo.
Y donde sea que se preste atención a la Luz,
y que el juicio tenga paso libre y aprobación en el corazón,
ahí ella escudriñará los tesoros escondidos de Satanás,
y el juicio se ejecutará sobre todo su engaño--su semilla, su raíz y sus frutos.
Así,
por la fe en Cristo (y no por la fuerza de la criatura) el hombre fuerte es saqueado,
junto con todos sus bienes.

Porque cada hombre recibirá de Dios conforme a su fe.
Ahora bien, el que cree en la salvación y, aun así,
se aferra a algún pecado y vive en él, y lo defiende, y cree que es necesario hacerlo,
tiene una fe que está fundada en algo impuro,
y por ende cosas impuras continuarán viviendo en este tipo de fe,
y serán justificadas por este hombre.
Y donde sea que el hombre esté aprobando o justificando cualquier cosa que sea impura,
allí está condenando al Justo, el cual le daría dominio sobre todo lo que es impuro.
Y así la planta silvestre tiene su libertad para crecer hasta ahogar la planta de Dios,
y cubrir al hombre, cerrar completamente su oído,
cegar su ojo y endurecer su corazón contra cada inclinación al bien,
o contra cada reprensión por el mal.
Este hombre no debería esperar ningún buen fruto,
o pensar que esa fe será contada por justicia.

Pero, al contrario: El que siente una lucha en sí mismo entre lo puro y lo impuro,
y ve lo primero reprendiendo por el pecado, y lo otro defendiendo el pecado,
y aun así cree en eso que es puro,
limpio y justo (que condena todo lo que es injusto e impuro)--la
fe de éste está fundada en eso que es puro,
y "`el misterio de ella es guardado en una conciencia pura.`"^
footnote:[1 Timoteo 3:9 (Traducción literal del Inglés)]
Y si esta fe pura es seguida,
purificará el corazón y limpiará las manos de acciones injustas.
Es por esta fe que el justo vivirá, crecerá, brotará y se manifestará,
y la planta pura se esparcirá y cubrirá la tierra interna con el conocimiento de Dios,
con Su santidad, poder, pureza y gracia en el corazón,
que opera como la levadura hasta que haya sacado la naturaleza impura,
y conformado a todo el hombre a Sí mismo.
Esta es la obra de la fe santa, que solo puede recibir aquel que cree en la santidad;
porque nadie puede producir frutos puros a partir de una fe impura.

Y tengo algo más que decir,
para el aliento de aquellos que honestamente desean deshacerse de su pecado,
y ser libres para servirle a Dios en santidad y sin engaño:
Cuando sientan en ustedes mismos el movimiento de esa Semilla que es santa,
dando testimonio en contra de todo lo que es contrario a la santidad,
y condenándolo (y condenándolos a ustedes por unirse a ello), entonces, les digo,
_crean en eso,_ porque eso es Cristo en ustedes.
Porque al creer en esto y seguirlo,
ustedes lo sentirán haciendo una separación en su
hombre interior entre eso que Cristo viene a salvar,
y eso que Él viene a destruir.
Sí, éste es Aquel que viene desde arriba para poner delante
de ustedes la vida y la muerte por separado,
para que uniéndose a la vida y creyendo en ella, sean salvos de la muerte.
Y a medida que sean fieles a este Espíritu que condena el pecado en la carne,
ustedes sentirán a diario una guerra en contra del pecado,
y una libertad progresiva de él. Y conforme se unan completamente a esto,
negando cualquier cosa que esto condene, serán un espíritu con Él en Su obra,
y ya no estarán más en la carne, ni serán condenados con el pecado que mora en la carne,
sino que serán uno con Aquel que condena el pecado (y que condena al yo en el pecado),
hasta que "`el pecado llegue a ser sobremanera pecaminoso`"^
footnote:[Romanos 7:13]
ante sus ojos, como lo es ante los ojos de Dios.
Y a medida que crezcan en el amor a ese Espíritu puro en todas Sus leyes y directrices,
ustedes llegarán a estar muertos a la ley del pecado, la cual, al no ser atendida,
amada y servida, perderá su poder en sus corazones; porque su mente,
amor y temor estarán gobernados por eso que la condena.

Aquí la "`fe que obra por amor`"^
footnote:[Gálatas 5:6]
toma la victoria, y no los esfuerzos del hombre en su propio poder,
tratando de vencer con solo una perspectiva del pecado recibida por la ley externa.
Porque por las obras de la ley ustedes no pueden ser justificados,
sino por la obra de la fe en Cristo Jesús,
a medida que sientan Su Espíritu obrando en ustedes, y sean uno con Él en esta obra.
Y contemplándolo a Él por medio de esta fe,
ustedes serán transformados progresivamente a Su semejanza por Su gran poder, sí,
por ese Espíritu al cual se han vuelto.
Y a medida que Él crezca en ustedes, y ustedes en Él,
sentirán el levantamiento de ese poder que los hace capaces de
dar la "`respuesta de una buena conciencia para con Dios`"^
footnote:[1 Pedro 3:21 Versión Moderna--H.B. Pratt (1929)]
con una paz eterna, y así, por medio de Su resurrección, serán salvos de la condenación,
de la cual sus propias obras no pueden salvarlos.

Esta obra continuará con gozo si sus corazones son honestos;
porque verán al Santo yendo delante de ustedes, condenando el pecado.
Y la belleza y santidad de todos Sus movimientos deleitarán al corazón honesto,
y harán que el camino para seguirlo sea fácil por el gozo puesto delante de ustedes;
porque en todas sus tribulaciones, pruebas y tentaciones,
esta fe Lo presentará a Él ante sus ojos.
En verdad,
esto hizo que los santos antiguos soportaran la cruz y menospreciaran el oprobio,
y llevaran el vituperio, siguiendo al Cordero gozosamente en todas Sus directrices.

Así que, ustedes que aman la santidad, ella está cerca;
el poder para vencer al pecado y a Satanás está cerca; la salvación está a la mano.
No salgan a buscar afuera lo que han perdido en su propia casa.
Aquel que condena el pecado en su seno es su Salvación.
Aquel que reprueba la iniquidad está con ustedes;
Aquel que es puro es su paz; Aquel que nunca ha aprobado ningún pecado,
sino que permanece como un testigo en su contra--si
ustedes tienen este Espíritu en sus corazones,
tienen el Espíritu de Cristo, el Salvador.
Así que préstenle atención a Él, crean en Él, pongan su mente en Su guía, y síganlo.
Si ustedes no se apartan de Él,
Él será su paz eterna y el poder dominante que someta sus pecados.
Por medio de Él hollarán la fuerza del enemigo con facilidad y deleite,
y serán capaces de decir junto a aquellos que han llegado al mismo Espíritu:
"`Mayor es el que está en nosotros, que el que está en el mundo.`"^
footnote:[1 Juan 4:4]
Sólo la fe que Lo ve a Él tiene poder para vencer al mundo,
porque aquel que contempla Su gloria pisa bajo sus pies la gloria de este mundo.
Y cualquier cosa que veamos en Él, supera tanto todas las otras cosas,
que saca la mente fuera de todos los otros deleites y los deja vacíos;
de modo que ni las cosas que hay en el cielo, ni las que hay en la tierra,
ni principados ni potestades, nos pueden separar del amor de Cristo.
¡Y cuánto más estarán dispuestos a dejar su deleite
en el pecado cuando lleguen a deleitarse en Él! Sí,
el amor los constreñirá.

Y esto es gozo en verdad, y amor inefable,
cuando el alma encuentra ese tesoro en su propia casa dado por gracia,
el cual por mucho tiempo había estado buscando afuera,
y que nunca pudo comprar ni con su vida ni con todas sus posesiones.
Y mientras más ustedes lo miren a Él,
más Su gloria y amor aparecerán. En Su Luz verán los movimientos puros del Santo,
y llegarán a ver lo que son sin Él, y cuáles son sus verdaderas necesidades,
sin las cuales no pueden ser felices.
Y verán que no pueden tener paz eterna hasta que Su virtud los haya llenado,
y Su gloria los haya cubierto,
y Su poder los haya armado contra toda tentación. Y Él hará
que ustedes hereden todo esto juntamente con Él,
conforme se mantengan fieles,
y presten atención a Sus movimientos para obedecerlos en todas las cosas.
De esta forma Él los guiará en Su camino,
que es el mismo camino a través del cual Él obtuvo toda la gloria y la potestad,
y la herencia del Padre.
Y al mantenerse en este camino,
ustedes encontrarán una cruz para todos sus propios caminos,
y para el espíritu del mundo en todas las cosas,
la cual será fácil de llevar si mantienen su ojo puesto únicamente
en Aquel que ha sido puesto delante de ustedes.

Pero si miran atrás al mundo, están mirando la tentación sin Él,
y ahí el espíritu del mundo les presentará todo lo que perderán y no ganarán,
poniendo ante ustedes eso que deben dejar,
con todas las dificultades e imposibilidades que pudiera haber,
y no verán la manera de soportarlo.
Pero al mantener sus ojos puestos en Cristo,
siempre tendrán poder y paz delante de ustedes en su camino,
y la esperanza de ganar a Cristo será como un ancla, y la fe como un escudo,
y el amor les dará vida para soportar todas las pruebas
por Él. Y llevar Su cruz cada día los separará de sus pecados,
y crucificará al espíritu del mundo con sus deseos,
y matará todo lo que todavía batalla contra sus almas y evita que ustedes tomen
su herencia--por esto la cruz es llamada el gran "`poder de Dios para salvación.`"^
footnote:[1 Corintios 1:18; Romanos 1:16]

Y a medida que sean fieles a esta cruz,
sentirán el fruto del Santo brotando en su interior,
moviéndose y manifestándose en ustedes hacia Dios y hacia los hombres.
Su fe crecerá, y sus oraciones serán fuertes clamores al Padre,
según las necesidades que vea el Espíritu.
Su amor brotará y se moverá en ustedes,
y fluirá hacia Dios y hacia los hombres en todas las ocasiones.
Y si resueltamente sirven a este amor en sus más pequeños movimientos, crecerá;
pero si lo apagan en sus movimientos, y se niegan a manifestarlo,
se marchitará y se secará dentro de ustedes, por falta de uso.

Lo mismo ocurre con la gentileza, mansedumbre,
paciencia y todas las otras virtudes que son de una naturaleza que brota y se esparce,
siempre que no sean apagadas, sino al contrario,
se les permita incrementarse para la alabanza de Aquel que es el autor de ellas,
en Su voluntad y tiempo, y para el consuelo de Su propia Semilla.
Y si ustedes son fieles cada día a su deber de presentar sus cuerpos como un sacrificio,
a fin de dar a luz Su imagen, nombre y poder ante la vista de Sus enemigos,
entonces lo que Él engendra en ustedes será su herencia,
y crecerá diariamente con el uso.
Pero si no se entregan por amor a Él, sino que esconden el tesoro y evaden el oprobio,
entonces este tesoro les será quitado y se le dará a aquel que le pague
Su fruto a tiempo al Señor de la viña. Porque el Padre desea que lo que
es engendrado por gracia produzca libremente un incremento,
a fin de que sea alabado por Su resplandor en este mundo oscuro.
Qué glorioso es ver la paz resplandecer en medio de la guerra, el amor en medio del odio,
la mansedumbre en medio de la contienda, el juicio justo en medio de la iniquidad,
la inocencia en medio de la violencia y la opresión. Sí,
eso que es de Dios resplandece entre los hombres del mundo como un lirio entre los espinos.
Y de este modo Su naturaleza y hermosura aparecen en Su templo,
la cual todos deben confesar y alabar.

Este es el Día de justicia del que muchos han hablado,
pero los verdaderos hijos del Día son los que experimentan
Su luz resplandeciendo en sus corazones.
Así que, lo que Dios engendra en ustedes es Su Hijo,
y deben confesarlo en medio de Sus enemigos,
y así el Padre será glorificado y Su Hijo coronado.
Pero si le niegan a Él sus cuerpos para testificar contra el mundo,
Él les negará Su vida para redimirlos del mal de éste.
Pero el levantamiento del Hijo es el principio del buen día,
cuando eso que por tanto tiempo ha estado condenándolos por el pecado,
empieza a resplandecer libremente mediante acciones de justicia.
Entonces sus tinieblas se convierten en luz, su condenación en paz,
su tristeza a causa del pecado en un gozo en la santidad.
Esto será un buen día para ustedes, sí,
será el Día de justicia y redención del Señor para con sus almas,
y un testimonio a todos los hombres de la manifestación del Justo.
Y cualquiera que se niegue a llevar este testimonio, toda su religión resultará en vano,
y consistirá en palabras sin poder.

Hay un camino para que el estéril se vuelva fructífero,
y ahí un poco es más útil para Dios que aquel que tiene muchas riquezas para sí mismo.
Ustedes que ven su necesidad están cerca de este camino,
y el humilde de corazón estará más dispuesto a seguirlo.
Porque este camino está preparado para los honestos de corazón,
los que no buscan servirse a sí mismos sino a Dios, y velan sobre sus propios caminos,
teniendo cuidado de no formar algo en la mente para ofrecérselo a Dios;
porque Dios será servido por lo que Él mismo engendra en ustedes.
Por lo tanto, tengan cuidado de formar algo por ustedes mismos,
y de asesinar eso que Él engendra por gracia en ustedes.
Pero dejen que sus mentes siempre estén puestas en lo celestial,
esperando con paciencia en esa luz que les permite ver su pobreza,
para que sus corazones siempre estén abiertos, vueltos hacia arriba,
a Dios el Padre de toda buena dádiva.
Así ustedes estarán escondidos en la mente celestial de
esa naturaleza que cubre la tierra con sus oscuras comprensiones,
y desea cubrir el cielo también. Esperen en eso que crucifica esa mente natural,
y a medida que lleguen a la paciente quietud,
sentirán lo que el Padre engendra moviéndose dentro de ustedes, buscando ser dado a luz.
Ustedes tienen que volverse siervos de esto, dejando de lado toda sutileza,
y todo lo apresurado, y cualquier cosa que venga de ustedes mismos,
o cuyo fin sea para ustedes mismos.
Y al experimentar una medida de la mente pura,
miren cómo se mueve en todas sus manifestaciones contra el espíritu del mundo,
a fin de que ustedes, con todo su corazón y con todas sus fuerzas,
puedan manifestarla en su propia imagen,
sin razonar, ni consultar con nada que sea de ustedes mismos, o de este mundo.
Porque todo lo que es engendrado por el Padre se levanta en una
naturaleza que es contraria a aquella que es una con el mundo.
Tiene otra imagen y fruto, y otra gloria en su aparición,
en la cual solo el Padre es glorificado, sí,
glorificado en el Hijo que Él mismo engendra y forma por gracia.
Aquí el Padre es glorificado en cuanto que Cristo
es manifestado con Sus frutos en el mundo,
por los cuales se puede saber cuán superior y contrario es Él al espíritu del mundo,
tanto en Su origen, como en Su raíz y linaje.

Y cualquiera que se entregue a servirle a Cristo en su interior,
se volverá (por el incremento del Hijo) rico para con Dios,
y cada día tendrá más fuerza contra el mundo.
Y al dar a luz esta nueva creación, y por Su hermosura en la santidad,
ustedes llegarán a ser gloriosos y amados ante los ojos del Padre,
llevando Su imagen y manifestando lo que Él engendra en ustedes,
en lo cual serán herederos de la gloria eterna.

Pero si miran atrás a la mente terrenal,
allí el espíritu del mundo se les aparecerá con su consejo;
y consultando y razonando con esta mente,
tomarán consejo en la noche cuando no pueden encontrar el consejo de Dios,
ni ver Su obra, ni Su propósito, ni Su gloria.
En lugar de esto,
el enemigo se les presentará con los placeres y las glorias de este mundo,
que consisten en cosas visibles,
y que son agradables al ojo externo y a los sentidos naturales,
cuya gloria busca el dios de este mundo, y a la que él quiere conducirlos,
y en la que se encuentra su sabiduría y conocimiento.
Y en este espíritu que no conoce a Dios, ni Sus obras, ni busca Su gloria,
ustedes se encontrarán con el ladrón y el homicida, los hijos de las tinieblas,
los cuales los persuadirán fuertemente a asesinar los movimientos puros de la Vida,
y a no manifestarlos.
O si no, los persuadirán a manifestar una imagen distorsionada,
que no sea un testimonio claro y perfecto contra el reino, poder y gloria del mundo.
Ustedes no podrán evitar esto si miran atrás al consejo del mundo,
y consultan con sus propios razonamientos, de los cuales se levantan los pensamientos,
afanes y placeres del mundo que contaminan la mente, ahogan la Semilla,
y cubren la Perla con pasiones y deseos terrenales.
Esto endurece progresivamente el corazón,
y fortalece la voluntad contra la vida inocente,
"`crucificando de nuevo al Hijo de Dios,`"^
footnote:[Hebreos 6:6]
negándose a manifestarlo en Su tiempo, y de acuerdo con Sus movimientos.
Y habiendo rechazado esto, no podrán engendrar Vida otra vez por ustedes mismos,
ni en sus propias voluntades,
aunque puedan crear una semejanza de ella a partir de otro espíritu,
y en esa naturaleza que resiste la verdad y corrompe la mente,
y manifiesta su propia voluntad.
En verdad, muchos se han ido por este camino,
a quienes Dios (luego de que ellos desobedecieran el suave movimiento del Espíritu manso,
y buscado cosas más sublimes) ha entregado a un espíritu altivo,
y a las fuertes operaciones de una naturaleza contraria.
Estos ahora tienen un poder con el cual resisten eso que los llama a salir del mundo,
y tienen un espíritu que los arrastra hacia el mundo otra vez.
Y este espíritu, habiendo entrado al templo de Dios, es adorado ahí como Dios.
A este le entregan su obediencia, y así vuelven a ser los mismos que eran antes,
o hasta siete veces peor, sin esperanza de ser restaurados.

Por lo tanto, deben velar en el temor de Dios con toda diligencia.
Obedezcan en la simplicidad de sus corazones,
y miren que no se deslicen y dejen de escuchar, o que formen alguna idea falsa.
Mas bien "`sean diligentes para que hagan firme su llamado y elección,`"^
footnote:[2 Pedro 1:10 LBLA]
no solo al tener el conocimiento de ello, sino también dejando que se forme en ustedes,
para que sea de ustedes para siempre.
Porque eso que la Semilla engendra en ustedes será su herencia,
y nadie podrá arrebatársela;
y en ella tendrán poder contra todos los espíritus contrarios.
Mientras la Semilla todavía esté en la tierra, estos espíritus los tentarán fuertemente,
y buscarán su Vida para sofocarla.
Pero cuando la Vida es dada a luz, permanece con ustedes,
y ella los viste como una coraza,
y se vuelve una defensa que los pone sobre la cabeza del maligno.
Pero si no es dada a luz, se marchita y se vuelve huesos secos en el vientre.

Por lo tanto, así como ustedes dan toda su mente para escuchar,
asimismo deben dar todas sus fuerzas para obedecer.
Y cuando sientan Su pureza moviéndose en ustedes, sírvanla con todas sus fuerzas,
y dejen que se manifieste.
Presenten sus cuerpos como un sacrificio para Él (a quién ustedes no han visto),
para que Su vida se manifieste en sus cuerpos mortales,
y también al mundo a través de ustedes,
para que Él sea visto en Su resplandor por todos los que lo aman,
y también por Sus enemigos.
Entonces encontrarán que "`el cuerpo no es para la fornicación, sino para el Señor.`"^
footnote:[1 Corintios 6:13]
Pero si reposan en el conocimiento de este misterio, y no dan a luz la Vida,
ustedes cometen fornicación con este conocimiento,
y enseñan a otros a cometer fornicación también. Este tipo de conocimiento en una mente
desobediente se vuelve la madre de las rameras y de las fornicaciones en la tierra,
con el cual los reyes de la tierra se han engañado,
y por el cual ninguno ha llegado a ser uno con Dios.

Porque no es escuchar la verdad lo que purifica el alma, sino obedecer la verdad;
eso es lo que hace que la vasija sea apta para el uso del maestro.
Y
así la vasija por el uso del maestro, y por su obediencia a Él,
se vuelve una vasija de honor que glorifica al Hijo,
y hace la voluntad del Padre en el mundo.
De este modo, el Padre es glorificado en el Hijo, en quién Él resplandece, sí,
a medida que el Padre engendra a Cristo de nuevo en ustedes, y a ustedes en Él,
quien estaba con el Padre antes de que el mundo fuese.
Y a medida que Su vida sea engendrada por la fe y la obediencia,
ustedes serán transformados a la misma imagen y naturaleza, y se deleitarán sólo en ella,
habiendo nacido del mismo Espíritu,
así como aquel que ha nacido sólo de la carne se deleita en las cosas de la carne.
