== Capítulo IV. Una Puerta Abierta / Para la Semilla Encarcelada en el Mundo

[.heading-continuation-blurb]
Y el camino de la libertad enviado al mundo por el Espíritu de la Verdad,
en amor a las ovejas que han estado perdidas por mucho tiempo;
para ayudar a todos los simples, los que buscan la vida de lo que profesan,
y para mostrar a los de corazones orgullosos y falsos la
causa por la que están excluidos del poder de la Verdad.

[quote.section-epigraph, , Juan 8:32]
____
"`Y conoceréis la verdad, y la verdad os hará libres.`"
____

Todo hombre que ha nacido de la naturaleza corrupta tiene
en su interior un espíritu cuyo deseo es contra Dios,
y una semilla (creciendo con él) que busca diariamente engañar
su alma para hundirla más en la iniquidad y en la vanidad,
y para aumentar su separación de Dios,
arrastrándola a la iniquidad y llenando el templo (donde Dios debería morar y
ser conocido) con cosas anatemas que Dios aborrece y no puede mirar.
Esta semilla maligna, siendo sutil y ambiciosa,
a menudo prevalece más que la Vida pura en el corazón,
y saca la mente del hombre de esta Vida y la lleva a muchas tentaciones,
presentándolas con deleites para la parte carnal y para los sentidos externos,
por lo que la Semilla de Dios se vuelve cada vez más velada y escondida de la criatura.

Es por causa de esto, que el hombre no conoce esa Palabra de vida por la cual fue creado,
y no podrá ser guiado por ella internamente,
hasta que la cabeza de esta semilla maligna sea herida
mediante el en esa luz que viene de la vida,
por la cual el mundo fue hecho.
Esta Luz es esa Roca que sigue al hombre^
footnote:[1 Corintios 10:4]
con su testimonio inmutable, testificando fielmente a favor de aquello que es de Dios,
y en contra de todos los caminos de la semilla maligna.
Ella llama y redarguye al mundo por la maldad,
y todos los que reciban y obedezcan Su llamado,
por medio de la fe llegarán a oír la Palabra de Vida,
en la cual se recibe el poder para ser hechos hijos de Dios.

Ahora bien, a medida que el poder de la vida se levante en la Semilla de la promesa,
la cabeza de la semilla maligna será herida,
y aquel que ha tomado cautiva al alma a su voluntad para cometer toda obra vana y maligna,
llegará a ser sometido.
Y conforme el alma creada sea redimida de debajo del poder de las tinieblas,
llegará a ser guiada en la luz de esa vida por la cual fue creada.
Y ahora, cuando el hombre está vuelto a Dios en fe y obediencia,
esa luz que antes lo redargüía por las obras de las
tinieblas (siguiéndolo de una obra a otra,
y condenándolo), se convierte en su líder,
el cual lo saca del mundo y lo lleva al Hijo de Dios,
en quien se revela la justicia de Dios para justificación. Y
a medida que esta justicia sea recibida y se permanezca en ella,
el pecado no será recordado más,
y el hombre será cambiado a la imagen de esa naturaleza
divina que transforma al hombre interior.
Entonces él llegará a amar esa luz que antes no podía amar;
porque ningún hombre puede amar eso que es de Dios sin primero recibir el amor de Dios.

Ahora bien, la Luz del mundo es el amor de Dios para con el mundo;
porque de tal manera amó Dios al mundo que (incluso cuando estaba bajo
el poder de las tinieblas) dio a Su Hijo al mundo como un pacto de luz,
para que todo aquel que Lo siga no permanezca en tinieblas,
sino que tenga la luz de la vida.
Ahora, el amor de Dios se encuentra en Cristo--la Luz del mundo;
Cristo es Su pacto con el mundo.^
footnote:[Véase Isaías 42:6; 49:8]
Y el que rechaza a Cristo, la Luz, y no Lo reciba, está fuera del amor de Dios,
fuera del pacto de Dios, y permanece en la enemistad.
Y esta es la causa por la que los hombres que aman sus malas obras hablan mal de la luz,
y no la pueden recibir como el amor de Dios, ni como el camino a la vida;
porque para ellos ella es su condenación. No es que
la luz haya sido enviada con este propósito,
sino que, para los hombres que aman más las tinieblas que la luz,
ella se vuelve su condenación. Pero esta luz es preciosa para aquel que cree y es obediente;
porque el que siga la luz fuera del mal del mundo, recibirá la naturaleza de hijo,
el amor del Padre (que el mundo no puede recibir),
el poder de la piedad y el tesoro de la vida eterna.
Estas cosas no serán dadas a ninguno hasta que salga del mundo,
incluso así como Él no es del mundo,
porque es allí donde permanece perpetuamente el pacto de Dios con la semilla de Abraham.

Así que mientras los hombres permanezcan en esa naturaleza corrupta,
la obra del amor de Dios para con el mundo, y del testigo del Espíritu de la Verdad,
será convencer al mundo de pecado,
y testificar que sus obras están bajo condenación. Pero aquellos que han recibido Su luz,
la misma se convierte en su jefe, en su consolador y en su salvador.
Y esta es la causa por la que uno ama y el otro aborrece,
porque cada naturaleza manifiesta la condición en la que se encuentra para con Dios,
de acuerdo con lo que ha recibido de Él,
ya sea amor o condenación. Y cualquiera que no quiera recibir
el amor de Dios (que lo llama a salir del mundo),
tendrá que permanecer bajo el poder de esa semilla que Dios aborrece,
en cuya condición buscará matar a aquellos que permanecen en el amor de Dios;
porque el maligno (habiendo cegado la mente que rechaza la luz) le hace
pensar al hombre que con ello está rindiendo servicio a Dios.
¡Ay!,
este es el triste final de todos esos profesantes
de la Cristiandad que rechazan la Luz del mundo;
porque el que camina en tinieblas no sabe a donde va.
Dios es luz, y no hay ningunas tinieblas en Él,
y ellas no tienen ninguna comunión con Él. Y en esto se manifiestan los hijos de Dios
y los hijos de las tinieblas--el que ama la luz lleva sus obras a la luz.
Este tiene comunión con Dios en sus obras, y hace la obra de Dios.
Pero el que rechaza la luz obra en las tinieblas,
y no puede creer en el poder que se encuentra en la luz,
estando él mismo bajo el poder de las tinieblas.

Y, por lo tanto,
el que ha nacido según la carne no conoce a aquel que ha nacido según el Espíritu de luz,
ni puede él juzgar sus caminos, los cuales son extraños y raros a su perspectiva carnal.
Tampoco él sabe por medio de qué poder y amor los hijos de luz vencen al mundo,
y se deleitan en negar sus placeres,
y en sacar todas sus vanidades fuera de su corazón y mente.
En verdad, estos ya no pueden tener gozo en el mundo,
ni contentarse con sus entretenimientos, sino mas bien regocijarse en la verdad,
y alegrarse en eso que salva de esa necedad.
Los impíos no conocen la vida de los justos, ni la Fuente de la que surgen sus virtudes,
ni el poder de su transformación,
ni el fin de todos sus sufrimientos y pruebas (que ellos soportan pacientemente),
sino que se quedan maravillados de todo esto como si fuera una locura y una necedad.
Porque el ojo que les daría una perspectiva de estas
cosas está cegado por el dios de este mundo,
y el alma estando en cautiverio bajo el dominio del príncipe de las tinieblas,
no puede heredar el tesoro inmortal.
Y esto será así,
hasta que ella niegue al mundo y salga de él a recibir
la herencia de luz y entendimiento divinos,
la cual nadie podrá recibir ni volverse uno con ella,
salvo en la medida que salga del mundo y de debajo de esa semilla
de enemistad que busca pervertir todos los caminos rectos de Dios,
y torcer todos Sus dones para la destrucción del hombre tanto como pueda prevalecer.

Ahora bien,
a este destructor (o semilla de enemistad contra la vida del hombre y su salvación)
no se le permite lograr repentinamente su objetivo sobre la criatura en la que él reina,
por nada menos que, la paciencia y longanimidad de Dios,
que no quiere que ninguna de Sus criaturas perezca, sino que todas escuchen la verdad,
y entonces sean restauradas y salvas de las trampas de este sutil engañador.
Esta es la razón por la que Dios a menudo soporta al hombre y detiene su destrucción. Él,
con mucha paciencia, y contendiendo mediante el Espíritu de la Verdad, reprende,
reprueba y le advierte al hombre,
incluso en el mismo instante en el que el pecado se está cometiendo.
Y si el maligno ha ganado tal poder en la criatura como para no permitir
que le preste atención a la reprensión antes o durante el acto de pecado,
entonces luego, cuando el calor de la tentación ha disminuido,
Dios le muestra la maldad y el peligro de tal iniquidad,
para así poder mantenerla en un temor de caer en la próxima tentación.
Y así (en muchos) el Señor detiene la destrucción durante mucho tiempo,
de modo que algunos continúan viviendo por un largo tiempo antes
de que el maligno los posea y llene sus medidas de iniquidad.
Pero hay algunos que, durante el tiempo de paciencia y longanimidad de Dios,
llegan a arrepentirse y a volverse a eso que los reprende, y entonces alcanzan salvación;
pero otros siguen avanzando hacia la destrucción,
la cual atraen rápidamente sobre sí mismos después de que
el Espíritu ha dejado de contender con ellos y de reprenderlos,
porque entonces el temor se pierde completamente,
y el maligno tiene su libertad según su propia voluntad.
Sí, cuando la criatura ha sido entregada por el Señor,
y el Espíritu de la verdad se ha apartado,
no queda nada más que la mentira para guiar al alma
que ha tratado con engaño al Espíritu de la Verdad.
Una persona así, en el mejor de los casos, tiene una apariencia de piedad sin el poder,
porque el poder de Dios está en ese Espíritu y vida
que se experimenta al resistir al maligno.
Solo aquellos que han nacido del Espíritu tienen vida y poder,
y experimentan su fuerza y virtud para la salvación eterna.
Pero este Espíritu está escondido en aquellos en quienes la muerte reina,
y ellos son entregados a sus propios pensamientos e imaginaciones.

Y esta es la razón por la que siempre ha existido una fuerte contienda
entre los hijos de luz (que son los que han nacido del Espíritu
de la verdad y tienen su luz y fuerza en el hombre interior),
y los profesantes de religión de este mundo,
cuyas expectativas están en algo fuera de ellos,
acerca de lo cual solo han oído a otros hablar,
otros que lo han tenido dentro de sí mismos.
Los últimos,
no conociendo el poder y misterio de la fe viva (que se sostiene en una conciencia pura,
y que es la única que tiene el poder para sacar de la oscuridad del mundo),
se mantienen cautivos en el mundo, contendiendo contra la luz espiritual.
Y, por lo tanto, mientras estos continúan en el mundo,
andan buscando comprender y medir al Espíritu de
la Verdad (que el mundo no puede recibir ni conocer),
asumiendo que ese Espíritu de Luz y vida no tiene otra operación
aparte de la que encuentran en sí mismos.
Así ellos tropiezan con la luz y son desobedientes e incrédulos de corazón. Ahora bien,
para nosotros, los que creemos, ella es la Piedra angular, elegida y preciosa,
y venimos a ella para recibir la provisión de todas nuestras necesidades.
Pero para la sabiduría y religión del mundo ella
es una roca de ofensa y una piedra de tropiezo,
a pesar de que testifica en el secreto de sus corazones, y los deja sin excusas.

Los que rechazan esta luz y Espíritu no tienen nada más que sea
capaz de mostrarles ni siquiera uno de sus pensamientos,
o de separar en su entendimiento lo malo de lo bueno, ya sea en pensamiento,
palabra o acción. Estos no pueden discernir entre lo que realmente es de Dios
y lo que es de aquel que se hace pasar por Dios (pero no es) a fin de engañar;
tampoco pueden ellos percibir los diferentes movimientos
de cada uno de los espíritus que están en ellos,
para entonces recibir el bueno y negar el malo;
ni pueden ellos diferenciar entre la raíz de la vida y la de la muerte,
ni saber cuál planta arrancar y de cuál alimentarse.
¿Y cómo podrían estos trabajar en la viña de Dios?
En verdad, cuando no se obedece a esta luz,
el cuerpo se convierte en una casa de oscuridad y
en una habitación de todo espíritu engañoso,
donde el corazón se mantiene perverso,
y ningún hombre lo conoce salvo aquel en quien resplandece la luz de la verdad.
Pero Él que le declara al hombre sus pensamientos, el Señor, Dios de los ejércitos,
es Su nombre.
Él es la verdadera Piedra angular y los que tropiezan
con ella no pueden comprenderla con su ingenio,
y por lo tanto Lo rechazan;
pero sin Él no es posible edificar ni hacer la obra de Dios verdaderamente.

Por lo tanto,
ustedes hijos de las tinieblas de este mundo ¡tengan cuidado
y miren contra qué se están oponiendo! ¿No están oponiéndose
a esa luz que limitaría y encadenaría al maligno en ustedes,
la cual además los condena por cada obra mala (tanto secreta como pública),
y no los deja ser orgullosos, ligeros y carnales?
¿No es la luz en sus propios corazones lo que testifica contra ustedes
por su engaño y falsedad para con Dios y para con los hombres,
por el engaño en la religión, por la hipocresía y la mentira,
y por hacer una forma de lo que ustedes no han experimentado personalmente?
¿Y no expone esta luz todo engaño en sus tratos con los hombres, cuando comercian,
hablan, y actúan, ya sea como gobernantes, sacerdotes o pueblo, sin acepción de personas,
o en cualquier otra cosa?
Sí, lo único que ella toma en cuenta es ese don de Dios en ustedes,
que es de Su naturaleza, y que les ha sido dado para guiarlos en la luz de Dios,
fuera de todos los caminos del espíritu engañoso.

Y ahora, si alguno viene a ustedes predicando esta doctrina,
la verdad que él declara será manifestada en el Espíritu
por ese don de Dios en sus propios corazones,
y este don les compungirá el corazón. Pero luego el maligno se
levantará y comenzará a pelear contra la medida de la verdad en
ustedes (la cual reconoce la verdad que otro les ha dicho).
Y si ustedes rechazan esta medida, se unirán con el maligno,
el cual se levantará con ira contra el testigo de la verdad en ustedes,
y así negarán la cosa misma que lo encadenaría y ataría. Sí,
así negarán al Señor de vida,
y le darán fuerza a su enemigo para crucificar al Justo en ustedes,
y para apagar al Espíritu de la Verdad,
y para hacer que el Señor se fatigue de contender,
hasta que finalmente sean entregados por completo al poder de las tinieblas,
el cual entonces los mantendrá buscando salvación externamente,
mientras que amontona maldad internamente.

Porque eso que busca devorar sus almas está dentro de ustedes,
incluso mientras el enemigo los sigue llevando hacia afuera para buscar
la salvación. Nada puede condenarlos salvo lo que está en su interior.
El pecado está adentro antes de que sea cometido,
y por ende la salvación debe estar adentro antes de que sean limpiados.
El antiguo engañador les ha enseñado a las personas a creer que
son salvos simplemente por tener una creencia en Dios a distancia,
pero estos no Lo conocen a Él, ni Lo adoran en Espíritu y verdad,
ni tampoco sus cuerpos son Sus templos,
ni puede el Santo morar o andar en ellos a causa de la inmundicia.
En verdad, sus vasos están llenos del poder de las tinieblas,
y los lugares celestiales son moradas de la maldad espiritual,
de modo que Dios se aparta de los hijos de los hombres a causa de su inmundicia.
Aun así,
el engañador continúa hablando paz y predicando salvación a las personas en esta condición,
y la criatura, estando llena de oscuridad, cree en esto.
Pero los hijos de la luz no reciben esta doctrina, porque ellos pueden ver y sentir,
y por lo tanto no se contentan con palabras sino con poder.
Hablar de Dios no satisfará al alma del hombre bueno,
hasta que sienta Su presencia y poder.
Tener a Dios afuera del alma y al diablo adentro no es la fe o salvación de los santos;
más bien tener a Dios adentro y al diablo echado fuera es su verdadera gloria y fortaleza,
y es por el poder de Su Espíritu en su interior que ellos tienen
denuedo para pelear a diario contra el príncipe de este mundo,
sabiendo que "`mayor es el que está en ellos, que el que está en el mundo.`"^
footnote:[1 Juan 4:4]
Esta es la fe que vence al mundo,
y el que ha nacido del Espíritu tiene al Padre y al Hijo.
Pero el que tiene al diablo es enemigo de Dios y no Lo conoce, ni sabe donde está,
sino que Lo juzga según la carne y según la apariencia externa.

Ahora consideren,
si los hombres no estuvieran completamente ciegos en sus
mentes y no hubieran "`perdido toda sensibilidad,`"^
footnote:[Efesios 4:19]
nunca podrían descansar en una creencia de que son salvos
incluso mientras permanecen siendo esclavos del pecado,
y a menudo son llevados a hacer eso que saben que no deberían. De hecho,
eso que los lleva a pecar, lo hace por medio del poder de la concupiscencia,
engañando al alma e inclinándola a toda tentación,
y haciendo que ella caiga en muchos males dañosos,
que echan raíces profundas y reúnen fuerza diariamente en ellos,
amontonando ira y venganza al añadir pecado a pecado.
Y en verdad, de todo esto se deberá dar cuenta al final,
cuando cada uno haya llenado su vaso por completo.

Y consideren lo siguiente:
¿Pueden ustedes decir que han sido redimidos de debajo del diablo mientras
él todavía tiene este poder en ustedes y que no son capaces de resistir,
sino que son llevados cautivos a su voluntad,
actuando en contra de todo temor de Dios o del poder de la justicia?
¿Están sus cuerpos redimidos para Dios,
o son ustedes miembros de Cristo aún cuando al mismo tiempo
presentan sus miembros como instrumentos de injusticia?
¿Son ustedes salvos incluso cuando son siervos del pecado?
¿En qué consiste su redención, su fe y su salvación,
ya que nada puede permanecer delante Dios salvo eso que engendra Su naturaleza?
¿No está aquel que da a luz iniquidad, todavía en cadenas de iniquidad?
¿No es esclavo del pecado aquel en quien el pecado reina?
¿No es hijo de esclavitud aquel que es forzado a
dar a luz lo que el maligno engendra en él,
y a servirlo en lo que sea que él lo mueva?
¡Consideren esto! ustedes que han nacido según ese espíritu carnal que obra en su carne,
a fin de hacer su voluntad y de producir fruto para muerte.
¿Acaso su religión los hará salvos, aún cuando no se aparten de las obras muertas?
El fundamento del arrepentimiento todavía no está puesto en ustedes,
y por lo tanto la muerte reina sobre ustedes,
actuando de forma contraria a la vida que debería llevar fruto para Dios.
En verdad, este es el estado del esclavo de pecado,
bajo el dominio del espíritu de servidumbre, y no el estado del heredero.
Uno hereda la justicia de Dios y manifiesta los frutos
de ese Espíritu que agradan a Dios;
el otro manifiesta el fruto de la carne que agrada al mundo.
Estas dos semillas están dentro del hombre, en enemistad y desacuerdo,
y no puede haber ninguna concordia entre ellas,
así como no hay concordia entre la luz y las tinieblas.
Sus diferentes frutos son puestos en evidencia por la luz,
la cual condena los frutos de una y muestra que los frutos
de la otra son de Dios y que son hechos en Dios.

Ahora bien,
todos los que son vivificados por el Espíritu de Vida tienen un
sentir de estas cosas antes de dar a luz sus frutos en el mundo,
porque ellos, al gustar y palpar la Palabra de Vida,
y conocer la elección que era antes que el mundo fuese,
han alcanzado un discernimiento que les permite ver
las cosas que difieren en naturaleza y efecto.
Es por esto por lo que son capacitados para juzgar
el origen y fin de cada inclinación en ellos;
y al permanecer en esto, no tienen necesidad de que ningún hombre les enseñe,
ni pueden ellos ser engañados.
Y esto hace que ellos manifiesten valiente y abiertamente esas palabras
y obras que son engendradas en ellos por la Palabra de vida,
las cuales muestran como el mundo entero yace en maldad,
y pone en evidencia su iniquidad mediante la luz de la vida.
Y en esta luz el príncipe de este mundo es juzgado y condenado,
y los secretos de los corazones son manifestados según la naturaleza de cada espíritu,
porque todo es descubierto en el Día de la aparición del Señor. Sí,
toda carne debe dar cuenta a este Espíritu de Verdad--a Aquel que vive de generación
en generación como un testigo inmutable contra esa semilla del mal,
sin importar cómo se disfrace con palabras y religiones.
Porque no hay ningún acuerdo entre estas dos naturalezas, ya sea en una persona,
familia o nación, ni ninguna persona, familia o nación puede servir a ambas;
sino que cualquiera que sirva a una, aborrece y condena a la otra.
Así que, aquel que sirve al engaño condena al Justo, y, por lo tanto,
condena eso que podría salvarlos y que los juzgará al final.
Esta es la causa de esa libertad carnal que algunos sienten actualmente, a saber,
que el Testigo de Dios está crucificado en sus corazones.
Pero estos tendrán terror en su conciencia cuando el Justo aparezca para juicio,
manifestando el estado inestable de todos los que no son fieles,
pero revelando la paz y poder eternos de aquellos en quienes Cristo tiene dominio.
Entonces será visto el fruto de aquellos que están en aflicción,
que han sido diligentes esperando y luchando (por medio de la fe y la paciencia),
desde el principio de la obra de Cristo Jesús hasta el final.
Todas estas cosas son comprendidas por aquel que ha aprendido a Cristo,
por medio de la fidelidad al Espíritu de la Verdad que ha sido enviado en Su nombre,
para testificar a favor de lo que es de Él y contra lo que es del espíritu
cuyo deseo es contra Él y mantiene a la creación en esclavitud.

Este es el único camino a la vida y salvación que el Espíritu de la Verdad ofrece gratuitamente,
y que el Padre envía en el nombre de Cristo Jesús. Porque el Espíritu tiene diferentes
operaciones en cada vasija según la condición en las que Él las encuentra para con Dios.
En algunos Él es uno que condena, en otros un jefe y maestro en las cosas de Dios,
en otros uno que justifica perfectamente ante los ojos de Dios,
y en otros un dador de dones y poder para aquellos que reciben este testimonio de Jesucristo.
Sin embargo, Él es uno en todos, inalterablemente justo, inmutable y santo,
quien por el poder de Su Palabra cambia todas las cosas cambiables,
y regresa todas las cosas al principio--antes que los pueblos,
naciones y lenguas fueran divididos--donde el hombre
vive por el Espíritu de una vida pura.

Ahora bien, todos los que desean ser libres de la esclavitud antes mencionada,
y de la ley del pecado y de la muerte (la cual tiene
su poder en la parte carnal) atiendan diligentemente,
y busquen sentir en ustedes lo siguiente:

El Espíritu de vida que está en Cristo Jesús,
por quién el mundo fue hecho en el principio, tiene una ley que es espiritual,
la cual procede de Sí Mismo, cuya ley arroja luz (en espíritu) sobre el bien y el mal,
y testifica contra el poder del pecado y de la muerte.
Todos los que reciben esta luz con fe y obediencia
son llevados por ella a estar bajo la ley de la vida,
y aquellos que son fieles a ella son conducidos por un camino en el cual
la parte carnal en el hombre (donde el pecado tiene su poder),
es crucificada y asesinada.
De este modo, la Semilla del pacto obtiene Su debido dominio y libertad en el alma,
la cual antes era mantenida en cautiverio por el hombre de pecado.
Porque mientras el hombre fuerte guarda la casa,
su fuerza se encuentra en esas cosas en las que la mente carnal se deleita.
Pero la ley del Espíritu llama a los hombres a salir de estas cosas,
y todos los que atienden Su luz son llevados a poner sus mentes
en cosas espirituales y a alimentarse de la Palabra de vida.
De este modo el hombre interior es fortalecido y
llevado a crecer a la estatura de un hombre espiritual,
llenándose así de poder, vida y virtud espiritual, para llevar fruto para Dios,
y para vivir para Él, incluso,
así como el otro hombre vivía para la carne y llevaba fruto para muerte.

Así el Espíritu de Vida, por medio de la luz, atrae a los hombres y dice "`¡Ven!`"
Y Él transforma y alimenta con vida nueva a todos los que le prestan
atención a Su voz y a todos los que la escuchan y obedecen,
por medio de lo cual se vuelven nuevas criaturas, nacidas del Espíritu.
Pero el espíritu carnal también atrae,
y dice "`¡Ven!`" presentando ídolos visibles para ganar los afectos carnales,
y para cautivar la mente y quitarla del Espíritu de vida, llevándola a objetos carnales.
Estos prometen mucho al ojo de la sabiduría terrenal,
y tienen una semejanza de la sustancia en ellos, pero su fin es de muerte,
y los que obedecen a este llamado pasan su vida como
esclavos a la vanidad y separados de Dios.
De modo que,
aquí los hijos de libertad (que es en Cristo Jesús)
se manifiestan al mundo mediante su salida de él;
y los hijos de esclavitud también son manifestados,
porque no pueden dejar de servir al mundo.
Y no hay acuerdo entre ellos;
porque el que es esclavo del pecado es libre de la justicia,
y el siervo de la justicia es libre del pecado.^
footnote:[Romanos 6:20 RV Gómez y RV 1602 Purificada]
Y así como aquel que está en la carne no puede agradar a Dios,
tampoco aquel que está en el Espíritu puede agradar al mundo--porque
estos son hijos de reinos opuestos y de naturalezas contrarias.
Y el que ha nacido según la carne tiene ese espíritu que desea con envidia la creación,
y que busca devorarla;
y el que ha nacido nuevamente según el Espíritu de vida
es restaurado a ese estado que era en el principio,
y le lleva a Dios los frutos de vida y salvación eternas.

Ahora bien, cuando la criatura cede y se entrega al sutil enemigo,
la vida se pierde y la semilla maligna obtiene fuerza en el hombre
para regir y engendrar fruto conforme al poder de las tinieblas.
Y del mismo modo, cuando la criatura cree en la luz,
y se entrega a los movimientos de la vida y la ley de la santidad,
la semilla maligna pierde su fuerza y su capacidad de alimentarse de las cosas carnales.
De modo que, por medio de la fe, la vida vuelve a ser renovada en el vaso,
y se levanta mediante el Espíritu y reina sobre la muerte.
Es evidente que la justicia y virtud de esta vida
no son de la naturaleza de la carne y la sangre,
sino mas bien de la naturaleza de Dios,
y estas cosas son manifestadas en el vaso de barro por el poder
del Espíritu actuando en contra de la voluntad y deseos de la carne.
Así el hombre regresa a la restauración y redención del cuerpo,
y vuelve a servir con libertad a ese Espíritu y vida que lo creó,
y por quien y mediante el cual vino al mundo.
Aquí no hay condenación, sino una verdadera reconciliación y paz con Dios,
y una unidad en Espíritu y vida, así como el Padre y el Hijo son uno.
Porque aquí los deseos son asesinados, el engañador es negado,
y el acusador es echado fuera; aquí todas las cosas son hechas nuevas,
y todo esto proviene de Dios.
Aquí el hombre ya no está en una casa de servidumbre al pecado,
sino en la gloriosa libertad de los hijos de Dios,
donde la naturaleza espiritual que es vivificada en él,
no se alimenta de placeres carnales, sino del Dios vivo.
De esta manera el hombre interior se vuelve un renuevo natural de la Raíz santa,
y una planta del Dios vivo, produciendo libremente cualquier cosa que brote de la Raíz,
por medio de lo cual Dios se glorifica, el hombre se convierte en una vasija de honor,
y su alma se llena de paz y abundancia, no teniendo más dolor ni muerte que la opriman.

Ahora bien,
conocer la luz y vida que están en Cristo Jesús y
que son manifestadas por el Espíritu de la verdad,
es tanto el principio como el fin de esta gran obra.
Y por esta luz, se puede ver cuán antinatural se ha vuelto el hombre,
habiendo sido echado de la presencia de Dios,
lejos de esa vida pura que le da aliento y ser,
y que lo preservaría de la destrucción. Sí, el hombre ha caído tan lejos de esto,
y se ha vuelto tan contrario a ello en naturaleza y juicio, que,
de todas las cosas en el mundo,
su cruz más grande es ser guiado por esa luz que
se levanta en su interior desde esa vida santa,
y que diariamente lo llama en espíritu.
Y habiéndose degenerado en una naturaleza contraria que es sutil y egoísta,
se encuentra dispuesto a unirse al enemigo (de cualquier manera) en contra
del testigo de la luz pura en su interior--ya sea para injuriar,
vituperar o crucificar su aparición,
convirtiendo la luz en tinieblas al cubrirla con engaño.

Pero aparte de esta luz, no hay nada más dentro del hombre que sea santo y justo,
o que lo llame a salir de las veredas del destructor y entrar en el camino de la vida,
o que produzca a través de él algún fruto de obediencia
o adoración espiritual que Dios acepte.
No hay otra cosa que siempre esté presente con el hombre,
para mostrarle cuando está siendo engañado con deseos y tentado a pecar,
o la forma de escapar de la tentación. Sin embargo,
el hombre está tan exaltado en la naturaleza contraria, que ha olvidado a su Creador,
y ha alzado su calcañar contra la reprensión de Su Espíritu,
pisoteando los pequeños movimientos del Santo y de la ley que sale de Su boca,
considerando la luz y virtud de Su vida como algo insignificante y menospreciable,
que no es capaz de salvar.
Así el hombre perdido menosprecia diariamente al Espíritu de gracia y verdad en su interior,
y rechaza al Espíritu Santo, perjudicando así su propia alma,
y negando ese ojo puro y bueno por el que los hombres santos de Dios veían,
discernían y hablaban en todas las edades, como lo testifican las Escrituras.
Todo esto está perdido para ese hombre que se exalta sobre la luz pura y Espíritu manso
en el que Dios aparece al hombre para enseñarle el conocimiento de la verdad.

Por lo tanto, ustedes maestros y pueblo de todas las denominaciones y sectas,
quienes tan violentamente se han puesto en contra de la luz del Espíritu,
tanto dentro de ustedes como en otros:
¿Cuánto tiempo más tirarán coces contra eso que aguijonea
sus corazones por sus caminos impíos y su religión falsa?
¿Por qué no quieren quedarse quietos, y meditar en sus corazones sobre esto,
para que puedan tener un verdadero sentido de ello, y discernir de qué naturaleza es,
de dónde viene, cómo obra y contra qué obra?
También podrán ver cuál es esa naturaleza en sus corazones que la luz condena principalmente,
y contra la que ella obra, y de dónde viene.
Así,
por medio de la luz de la verdad podrán juzgar entre
las cosas que difieren en su origen y fin,
y entonces caminar en la luz,
en juicio y en verdad de corazón para con Dios y para con los hombres.

Ahora, dejen que la experiencia de la verdad de Dios en ustedes (sin ninguna mezcla),
conteste las siguientes cosas:

[.numbered-group]
====

[.numbered]
1+++.+++ ¿Cuál es la razón por la que ustedes,
al mismo tiempo que profesan buscar a Dios y servirlo,
están tan indispuestos a servirlo en eso que es de Su propia naturaleza,
y a adorarlo a Él en Espíritu y verdad, en sus propios vasos,
cuyos cuerpos deberían ser los templos de Dios,
quien no es adorado en templos hechos de mano ni en una naturaleza contraria a Él?

[.numbered]
2+++.+++ ¿Hablar simplemente de lo que Dios es,
o de lo que era en otros (quienes lo sentían caminando y hablado en ellos),
librará sus almas del poder del príncipe de las tinieblas y del engaño que está en ustedes,
sin que lo reciban a Él así como ellos lo recibieron,
y sin que sientan Su poder venciendo y echando fuera a aquel
que los ha tomado cautivos y los obliga hacer su voluntad,
la cual es contraria a su fe y consciencia?

[.numbered]
3+++.+++ ¿Hallarán ustedes a Dios,
o aceptará Él su adoración mientras Su templo esté poseído por Su enemigo,
y una naturaleza contraria se mueva en él? ¿Pueden encontrarse
con Dios en algo que no sea eso que es santo,
sabiendo que Él no escucha la oración del que mira a la iniquidad?

====

Por lo tanto, su primera obra debería ser,
conocer en ustedes a Aquel a quien Dios acepta,
porque solo Él (que aparece sin pecado) debe presentarlos al Padre;
de lo contrario serán reprobados ante los ojos de Dios.
Porque no hay ninguna esperanza sin sentir a Cristo en ustedes (y a ustedes en Él),
el Sacerdote eterno,
haciendo la ofrenda sobre el altar de la expiación.
Y aunque debido a la altivez de sus mentes,
Aquel que no tiene pecado parezca algo insignificante y pequeño en ustedes,
aun así "`separados de Mí nada podéis hacer,`" dijo
Cristo Jesús. Tengan en cuenta lo que Él dice:
"`nada podéis hacer.`"
Entonces ¿qué están haciendo aquellos que no están en Su Espíritu Santo?
¿Pueden adorar por tradición, o ser salvos por la letra?
¿Harán de Cristo un mentiroso, que dijo:
"`Separados de Mí nada podéis hacer`" y "`Yo soy la luz del mundo,`"^
footnote:[Juan 8:12; 9:5]
y "`todo pámpano que en Mí no permanece será echado fuera, y se secará, y los recogen,
y los echan en el fuego y arden`"?^
footnote:[Juan 15:6]

Consideren esto, ustedes que rechazan la santidad en espíritu,
y la luz que resplandece desde el Espíritu Santo en su interior.
Si ustedes no permanecen en eso que es santo ¿no están cortados ya?
¿No están secos y preparados para el fuego?
Ustedes que no moran en eso que es santo ¿no han sido echados fuera,
teniendo poder y conocimiento para hacer el mal, pero no para hacer el bien?
¿No están cortados de la verdadera vid y plantados en una
vid silvestre que tiene una naturaleza contraria?^
footnote:[Jeremías 2:21]
La luz de ustedes está seca, su semilla está corrompida,
y su árbol se conoce por sus frutos, el cual ahora lleva fruto, pero no para Dios,
ni de Dios.
¿Dirán ustedes que tienen la esperanza de haber nacido de nuevo del Espíritu,
y que son bautizados en el Espíritu, y que caminan en el Espíritu,
y que adoran en Espíritu, aún cuando miran hacia afuera para obtener salvación y luz,
y hablan mal de eso que es capaz de vencer al mundo?
Por esta razón su esperanza no es un ancla, ni su fe eso que obtiene la victoria.

La Escritura declara: "`Toda aquel que ha nacido de Dios, se guarda a sí mismo,
y el maligno no le toca.`"^
footnote:[1 Juan 5:18 RV 1602 Purificada]
Ahora bien, consideren en ustedes mismos:
¿donde está Aquel que les permite ver cuando el maligno los toca y los tienta?
¿Cuál es la naturaleza de Aquel que hace esto por ustedes,
y dónde está? ¿No es Él luz y entendimiento, y no está dentro de ustedes?
¿Y no es Él de una naturaleza contraria al maligno que tienta?
¿Y no les muestra Él la tentación antes de que caigan en ella (si le prestan
atención)? Entonces ¿cuál es la razón por la cual el mal es cometido,
viendo que la luz aparece contra él? ¿No es porque ustedes se unen al maligno,
y prefieren sus deseos más que a Aquel que les muestra que son malos?
Así ustedes niegan al Santo y Justo, y se vuelven uno con el maligno.
Y después ustedes dicen que "`la Luz no es suficiente,`" cuando la han negado,
y no han sido fieles uniéndose a ella en consejo y fuerza,
sino que le han dado su fuerza al espíritu contrario.
Pero aquellos que han nacido del Espíritu y luz de Dios no hacen esto,
sino que cuando se les muestra el maligno y su tentación (cualquiera que sea,
o bajo la pretensión que sea), si la luz testifica contra ello, entonces son diligentes,
vigilantes y sobrios, en el temor de Dios,
no sea que sean alejados de la luz y engañados.
Ellos en cada prueba se unen en obediencia con todas sus fuerzas al camino de la luz,
de modo que experimentan una guerra y contienda antes de que la prueba termine.
Pero el enemigo, siendo resistido firmemente en la fe, huye,
y la gloria regresa a Dios que mora en la luz.
Y si en algún momento el enemigo prevalece,
entonces la criatura ve que fue por causa de sí misma y no de Dios,
y entonces es humillada y advertida.
Esto logra verlo cuando la tentación ha terminado y el enemigo ha huido,
y cuando regresa a su cabal juicio con Dios en la luz;
porque mientras las tinieblas estaban levantadas y el enemigo estaba dentro de la casa,
ella no podía verlo.

Así se obtiene experiencia a través de las tribulaciones y las pruebas,
pero aquellos que no soportan la tentación nunca aprenden de Dios,
sino que caen por su infidelidad a la luz.
Estos son mantenidos en cautiverio a la voluntad del enemigo de toda justicia,
el cual siempre tienta al mal y reina sobre los miembros--llevando los ojos, oídos,
manos y corazón a la iniquidad y vanidad,
y la lengua a abogar por ello en contra de toda reprensión. Y habiendo
negado la reprensión del Espíritu de la verdad dentro de sí mismos,
son incapaces de recibirla de otros,
porque el espíritu contrario reina exclusivamente en esa casa,
apartando el oído del conocimiento, y el corazón del entendimiento espiritual.

Esta es la causa por la que muchos no sienten el
poder de Dios ni tienen el conocimiento de Su Palabra,
porque los misterios de Su poderoso consejo son revelados a los fieles,
quienes han vencido por medio de la fe y la paciencia,
y en quienes Satanás ha sido sometido y pisoteado.
Pero donde sea que este devorador se haya levantado en la criatura,
allí él pervierte todo lo que Dios da o revela, y lo lleva a un fin contrario,
a algo que Dios nunca quiso,
de modo que una naturaleza incorrecta y un espíritu
contrario (que Dios aborrece) son alzados y exaltados.
Esto es evidente en la luz de la verdad a lo largo de todo el mundo.
Porque ¿de cuál don de Dios el espíritu del mundo no abusa?
Si Dios da riqueza, dondequiera que ese espíritu se haya levantado,
ahí la criatura se envanece, creyéndose superior al resto de sus hermanos,
como si ya no fuera de la misma carne y sangre.
Si Dios da belleza, es convertida en lujuria, orgullo y desenfreno,
tanto engendrando como engañando los ojos adúlteros.
La sabiduría es convertida en insensatez e iniquidad,
escarneciendo al inocente y burlándose del simple de corazón;
y aquellos que tienen más de ella, son más capaces de lograr sus fines corruptos.
Cuando Dios da gracia, es convertida en libertinaje carnal,
y Su inmensa paciencia en una cubierta para el pecado y la hipocresía.

No hay ni una sola cosa que Dios pueda dar,
que el maligno no tuerza y vuelva en contra del Dador; de modo que,
aunque Dios es bueno y está lleno de misericordia por naturaleza, aun así,
Él no está dispuesto a revelarse a aquellos en quien el hombre fuerte guarda la casa.
Esto hace que la criatura tenga aún menos vergüenza de tirar coces contra su Creador,
y de envanecerse y olvidar a su Hacedor y Sustentador.
Así el campo fructífero se vuelve estéril a causa
de la iniquidad de aquel que mora en el interior,
aunque no era así desde el principio.

Pero esto no sucede con los hijos de luz,
quienes tienen al Dador en sus corazones exaltado por encima del don.
Aquí el consejo puro ordena los dones,
y toda buena dádiva y todo don perfecto es manifestado en su propia naturaleza,
forma y manera, sin impurezas y sin ser desfigurado por el espíritu del mundo.
Sí, aquí los manantiales corren desde la Fuente pura,
y tanto la planta como los frutos son santos como la Raíz;
porque el espíritu es puro y la carne sin contaminación,
y todo permanece en la condición en la que salió de Dios.
En estos vasos el viejo hombre es despojado, y todas las cosas son de Dios,
y cada don de Dios es conocido por sus frutos, naturaleza y fin,
como lo era en el principio.
Aquí los dones de Dios regresan a Dios al ser glorificado por ellos en la tierra.
Las riquezas producen obras buenas y misericordiosas, y no orgullo y vanagloria;
la sabiduría se mantiene firme contra la opresión y no engaña;
y la justicia reina por la gracia para vida eterna.

La religión de estos es pura y sin mezcla con el mundo,
por lo que los hijos y las hijas de Dios son conocidos en las calles
por el manto de virtud y decencia con que están cubiertos--a saber,
los frutos del Espíritu Santo,
y la fe y verdad que están en Cristo Jesús. Estos son los "`vasos de honra,`"^
footnote:[2 Timoteo 2:20]
preparados por el Señor para resplandecer a través de ellos contra Su adversario
(el espíritu del mundo) por medio de los frutos que no pueden ser condenados;
porque aquí el don no es contaminado por el vaso, sino que,
alcanzando el testigo de Dios en cada corazón, manifiesta que viene de arriba.
Sí, estos son hijos de Dios sin mancha en medio de una generación maligna,
en la cual resplandecen como luminares,
honrando a Dios y cumpliendo el propósito por el cual el hombre fue creado.
Dios no se aparta de estos, sino que es rico para con ellos,
hasta que lleguen a ser llenos de la plenitud de Dios.
Pero Dios retiene Sus riquezas y Su plenitud de los impuros y negligentes,
que contaminan la carne con sus deseos, de modo que ellos no conocen a los hijos de Dios,
ni saben de dónde vienen, ni a dónde van, los cuales siguen a Cristo fuera del mundo,
y nunca más regresan al mundo excepto para testificar en su contra.
Los vasos de estos ya no son llenos de deseos, o del espíritu de este mundo,
sino que son llenos del Espíritu Santo que los ha hecho nuevas criaturas para Sí Mismo,
para caminar en ellas, y para resplandecer por medio de los frutos del Espíritu.

Ahora bien, todos ustedes cristianos profesantes que son estériles y de mente terrenal,
quienes han llenado sus vasos de descuido, engaño y de una mente carnal,
en vano salen a cazar con sus odres viejos pensando retener el tesoro celestial.
¡Ay!, ustedes andan viajando en búsqueda de nociones,
pero esto no sirve de nada ante los ojos y la estima de Dios,
porque mientras permanezcan en la naturaleza del mundo y en la vieja creación,
estarán en la obra incorrecta.
Sus palabras y ordenanzas carecen de la vida de Dios,
y ustedes no podrán recibir ni producir Sus frutos hasta que sean renovados;
porque nada que ustedes puedan hacer vale nada sino una nueva creación.
Sus viejos odres están llenos del vino viejo de las uvas silvestres,
y eso que contamina la conciencia está alzado en ustedes.
Por esto Dios mantiene Sus dones lejos de ustedes,
los cuales abundan en Su nueva creación,
y ustedes no experimentan nada de ellos salvo eso que sienten que los condena.
Entonces ustedes pelean contra Él y dicen que ya no hay nada perfecto,
y así condenan lo nuevo junto con lo viejo y los consideran iguales.
De esta manera erran, no conociendo el don de Dios ni las obras de Sus manos,
que son todas perfectas como Él es perfecto,
quien no camina en un templo contaminado ni se acuesta en el seno de las rameras,
porque estas cosas están fuera de Su poder y se han descarriado
del camino perfecto de la vida de santidad.

Por lo tanto, les sería de mucho provecho tomar la lámpara de la verdad y barrer su casa,
y echar fuera la vieja levadura junto con todo lo que sea de este mundo.
Sí, ustedes deben esperar en eso que obra en el Espíritu contra todo lo que es viejo,
hasta que todo sea hecho nuevo.
Hay un nuevo odre que no recibirá lo viejo, ni se mezclará con ello,
sino que retendrá únicamente lo que es nuevo.
Este odre Dios llenará de Sí Mismo, para que Su Semilla pueda brotar y no sea estorbada,
y Su lirio crezca sin ser ahogado.
Entonces el cordero podrá estar a salvo del lobo,
y lo puro será guardado de la contaminación;
porque la planta de Dios es demasiado pura y tierna como
para crecer mientras la contaminación de una mente codiciosa,
orgullosa, lujuriosa y terrenal siga viviendo en ustedes.

Así que deben venir primero al juicio,
para que acepten la condenación sobre todo lo que es viejo,
antes de que puedan recibir lo que es nuevo, o experimentar su crecimiento en ustedes.
¿Qué acuerdo hay entre el espíritu de mansedumbre y el espíritu de orgullo,
entre el contentamiento y la codicia, entre la santidad y la concupiscencia,
entre Cristo y Belial, entre la luz y las tinieblas?
Lean y entiendan,
porque aquí está la causa por la que han sembrado y trabajado por tantos años, y,
sin embargo, no han encontrado ninguna libertad,
ni han hallado ese descanso que el ladrón y el impuro no pueden devorar.
Consideren estas cosas mientras están cerca de ustedes,
no sea que sus corazones se endurezcan por incredulidad y por el engaño de la concupiscencia.
No desechen a Aquel que los llama y les da luz en la oscuridad,
sino que manténganse fieles en la vigilancia,
luchando con todas sus fuerzas hasta que todo aquello contra lo
que Él testifica en sus corazones sea puesto debajo de Sus pies.
Y cuando la Verdad los llame, no contesten con engaño y excusas,
no sea que Él se aparte de ustedes y llame a otros más dignos.

Si ustedes dicen que el mundo los detiene,
entonces es hora de romper esas cadenas que ya se han vuelto tan fuertes.
No se demoren, porque cada día se hacen más fuertes, ¿y en qué terminará todo esto?
Consideren y entiendan, y no digan que les falta fuerza,
sino que vuélvanse con esa fuerza con la cual han servido al mundo por tanto tiempo,
y experimentarán a Dios (quien fue el que se la dio) como un mejor maestro;
porque ustedes sirven con más vigor al espíritu de esclavitud que a su Redentor.
Cualquiera que sea la fuerza que hayan recibido de Dios,
no hagan otra cosa más con ella que entregarla fielmente al servicio de Dios en la luz;
porque Él no requiere más de lo que da.
Es el engaño el que crea estas excusas en ustedes, y no una mente dispuesta;
y si estuvieran en el temor de Dios, no dirían palabras como esas,
las cuales no hacen más que testificar contra ustedes.

Por lo tanto, ustedes que hablan de esta manera,
consideren con honestidad de corazón en qué condición se encuentran,
quién es su padre y quién tiene poder en ustedes.
¿Pueden ustedes hacer el mal con ambas manos, vivir para sus deseos, servir al mundo,
viajar por la tierra para obtener ganancias y placeres, con poder, sabiduría y deleite,
y sin embargo no tener poder para hacer el bien?
Oh, si ustedes realmente amaran a Dios y Su verdadera adoración,
sus corazones serían golpeados con dolor, y encontrarían poder para refrenar su lengua,
para apartar sus ojos de la vanidad, sus oídos del placer y sus corazones del engaño,
para que así obedecieran únicamente a la luz.
Sí,
entonces podrán oír la voz de Aquel que ha sido enviado al mundo para
llamarlos a salir de debajo de la potestad de Satanás al Dios vivo,
al predicarles luz a todos los que están sentados en tinieblas,
quienes están muertos mientras viven.
Porque ustedes no serán vivificados hasta que escuchen la voz del Hijo de Dios,
pero el engañador evita que ustedes la escuchen mientras
viven en sus placeres mundanos y en sus religiones falsas,
usando las palabras de los santos para esconderse del verdadero juicio.
Porque, aunque usan sus palabras, no tienen su Espíritu, ni poder para vivir sus vidas,
ni son plantas de esa raíz y naturaleza que produce fruto para Dios.

Por lo tanto,
la voluntad de esa naturaleza en ustedes que es completamente inútil debe ser negada,
y su camino debe ser detenido.
Sí, ustedes deben morir a esa semilla que ahora gobierna y tiene fuerza,
y que corre de un lado a otro en busca de comida para sí misma, pero no busca a Dios.
Y deben volverse a eso que es puro,
y esperar allí la unción y el levantamiento de la Semilla santa;
porque separados de Cristo nada pueden hacer.
Esa semilla que ni está dispuesta ni puede hacer nada no es Suya, sino la del maligno,
y esto es evidente por sus frutos, sus pensamientos, sus palabras, su religión,
sus oraciones, sus deseos, su pecado y su justicia.
Todo esto es de una misma naturaleza,
y se levanta en ustedes para resistir la venida de la Semilla del pacto--Cristo Jesús,
la vida de Dios y la luz de los hombres--quien tiene el poder y justicia de Dios,
que eran en el principio.

La luz de Cristo les mostrará Su ley, y el Espíritu de profecía testificará de Su venida,
para que Su camino sea preparado delante de Su faz.
Todos sus caminos torcidos, perversos y vergonzosos deben ser enderezados,
sus caminos escondidos y sutiles deben ser allanados,
y el fuego purificador debe pasar por sus casas y apoderarse de todo lo que arderá,
hasta que sea consumido.
Porque Dios no morará en Su templo, ni traerá la justicia perdurable como herencia,
hasta que la impureza sea eliminada y se haya puesto fin al pecado.

Aquí aprenderán los primeros principios de la religión pura,
y la doctrina de los comienzos de Cristo.
Porque aquí el fundamento del arrepentimiento de obras muertas será puesto en su corazón,
y verán qué tipo de tesoro ha atesorado su mente descuidada en sus vasos
de barro por medio de todas sus palabras y obras engañosas e inútiles.
Sí, ustedes llegarán a ver por esa luz que no miente,
y encontrarán que todo les fallará salvo la verdad.
Cualquier cosa que hayan reunido con artimaña y engaño,
ahora solo les servirá para engañarlos;
porque la verdad en lo íntimo debe ser su único apoyo.
Y cuando todo lo demás sea pesado y hallado muy liviano para soportar la prueba,
ustedes deberán huir a la Roca en busca de refugio (aunque Él ahora sea menospreciado),
es decir,
a Su luz en sus corazones la cual les revela el conocimiento de Dios en la faz de Jesucristo.
Nada fuera de ustedes hará que alcancen la paz,
sino solo eso que obra dentro ustedes y limpia sus casas de su adversario.

Es por medio de esto que los hombres santos de Dios (que han ido delante de ustedes
en la regeneración) han mantenido una casa limpia y una conciencia pura,
caminando por encima de todo lo que el mundo puede ofrecer o prometer,
habiendo aprendido (en el día de la prueba) que todo termina
siendo una mentira excepto la verdad en lo íntimo.
Estos aprendieron de Él que los verdaderos adoradores son
únicamente aquellos que adoran al Padre en Espíritu y verdad,
y encontraron que todo el misterio de la fe y de la piedad se aprende internamente,
y se guarda en eso que es puro; porque solo los puros de corazón han visto,
oído y aprendido de Dios.
Estos son hijos en verdad, nacidos del Espíritu, guiados por el Espíritu,
y están llenos del Espíritu, teniendo poder, luz y entendimiento para hacer el bien.
Sí, estos son templos del Dios vivo, quien es santo,
y son vasos de ese Espíritu que el diablo no puede resistir.
Y todo verdadero hijo de Dios tiene esto en medida,
por medio de lo cual resiste al mundo y lo vence,
porque "`todo lo que es nacido de Dios vence al mundo.`"^
footnote:[1 Juan 5:4]
Dios es fiel, y no se olvidará de lo que es Suyo.
Bienaventurados aquellos que tienen una medida de eso que Dios no puede olvidar,
ni permitir que sea tentado mas allá de lo que puede soportar.
Porque únicamente en esto se encuentra la elección por la que el alma es salva,
y es aquí donde la criatura halla gracia delante de Dios.

Por lo tanto, consideren esto,
todos ustedes que se burlan de la idea de tener una conciencia pura,
y rechazan el don de Dios en su interior, hablando de esto con ligereza y afrenta.
Si ustedes supieran quien es Aquel a quien afretan y escarnecen,
preferirían morderse sus lenguas antes de decir una palabra en Su contra.
Cambiarían de parecer y lo buscarían,
junto con aquellos que han vendido todo lo que tienen para hallar la perla.
Y aunque esto ahora parezca pequeño en ustedes,
de modo que no se atreven a confiar en ello, aun así, todos los que lo han probado,
lo estiman como el gran poder de Dios para salvación,
y se dan cuenta que no tienen otra elección más que la que se encuentra en esto.
Fue en esto que Noé halló gracia ante los ojos de Dios cuando la tierra estaba corrompida;
y en esto él caminó con Dios y fue salvo,
siendo justo y perfecto en su generación. Y fue en esta Semilla
de justicia en la que Lot se afligía por la inmundicia de Sodoma,
y por ella fue salvo.
De modo que la elección de Dios se encuentra en eso que era antes del pecado,
que es contristado por el pecado y que testifica en el hombre contra toda inmundicia;
esta era la Semilla escogida antes de la fundación del mundo.
Esto es lo que tienen que hacer firme para ustedes,^
footnote:[2 Pedro 1:10]
pero aquellos que dicen que no tienen ningún poder para hacer el bien,
niegan Su llamado y por lo tanto no lo pueden hacer.

Él los llama a salir del pecado,
y esa parte de ustedes que se aflige por causa del pecado,
todavía es pequeña y débil en ustedes; pero el dios de este mundo es grande,
fuerte y poderoso en ustedes,
y ha enaltecido sus corazones para que busquen cosas más atractivas que la Semilla pura
de luz y entendimiento verdaderos que Dios ha escogido y elegido para Sí Mismo,
y en la cual Él se comunica con el hombre, le enseña Su temor y conocimiento,
le da poder espiritual y lo salva del pecado.
Así que sus miradas altivas están demasiado elevadas para esta puerta,
y ustedes desprecian el día de la pequeñez y simpleza de Cristo,
no estando dispuestos a esperar grandes cosas donde ahora se ve muy poco,
porque no tienen fe.
Así corren por delante del verdadero descanso,
y el pobre en espíritu toma el reino antes que ustedes,
a quien le pertenecen la elección y la bendición.

Ahora consideren el llamado de Dios y Su elección. ¿Ha escogido
Él al rico en conceptos y altivo en su religión,
al orgulloso y al extravagante?
¿No ha escogido Él al débil y pobre, al necio y despreciable para avergonzar todo esto?
Sí, Aquel que es puro, manso y santo llama, y el alma que es mansa,
humilde y ama la santidad, responde,
obteniendo gracia para ser santa en toda su manera de vivir.
Aquí se hace firme el llamado de Dios,
y se conoce la elección por la respuesta a este llamado y por mantenerse en esta elección,
que era en Dios antes de que hubiera transgresión. Pero cualquiera que niegue
a Aquel que llama a salir de las tinieblas a la luz (por el poder de Su santidad,
humildad, mansedumbre y verdad,
que se manifiesta a través del don de Su Espíritu dentro de ustedes),
este niega tanto el llamado como la elección,
para agarrarse de algo externo y aferrarse a una cosa cambiable
en la que no se encuentra la elección. Porque la elección,
siendo la luz y poder de la santidad y la verdad, es preservada en Dios,
aunque todo el mundo sea engañado, contaminado, destruido y cambiado.

Por lo tanto, bajen de las montañas, ustedes que se han levantado en alto sin Dios,
que tienen una apariencia de piedad sin el poder de Dios.
Busquen sentir ese don que es puro, humilde y justo en ustedes; porque Dios es Espíritu,
y Él es conocido y servido en el Espíritu y en la verdad,
y es aquí donde Su consejo es recibido.
En la medida de la verdad en su interior, sientan dentro de ustedes eso que nunca pecó;
entonces acérquense a Dios en Espíritu, y manténganse ahí,
y esperen y obedezcan permaneciendo en esa Semilla que no puede pecar.
En esto esperen en el Espíritu Santo y atiendan Su movimiento continuamente,
siendo obedientes a Él, para que lleguen a servir lo vivo y no a eso que está muerto,
y para que así sean capaces de decir que su Redentor vive,
y que ustedes lo conocen y han escuchado Su voz.
Entonces podrán decir que han aprendido de Él, y que están unidos a Él,
a fin de ser conformados a Aquel que vive y no peca.
Y Su aparición será su salvación y su paz cada día,
así como también su crecimiento e incremento en Dios,
y por ella les será otorgada diariamente una entrada
al reino eterno que es en Cristo Jesús,
la luz, la verdad y el poder de Dios.

Pero si acuden a cualquier otra cosa en busca de
ayuda o consejo aparte de ese Espíritu que es puro,
justo, manso y humilde,
y que brota en ustedes para producir frutos para
Dios mediante esa Semilla que es pura y limpia,
entonces salen de la fuente de agua viva, y cavan para sí cisternas.
De esta manera salen a sus propias obras, y producen su propia justicia,
y no esa justicia que es revelada desde arriba a
todas las generaciones de los escogidos de Dios.
Entonces realizarán su obra con esfuerzo y fatiga,
y cuando la hayan acabado no satisfará esa parte en ustedes que tiene hambre de Dios,
sino que hinchará esa naturaleza que es egoísta,
y exaltará eso que ya está demasiado elevado como para recibir vida de Dios.
Dios no acepta esta justicia,
porque es producida por obras y no por la virtud de la naturaleza divina.
Pero la justicia que Dios acepta fluye libremente en el interior desde el Espíritu eterno,
y aquellos que entran en ella, entran en su descanso, y guardan el Santo Sábado,
y son alimentados y cubiertos gratuitamente por el Señor.

Por lo tanto, si su deseo es experimentar este nacimiento celestial,
entonces dejen de actuar por la carne y sangre,
y apártense de cualquier cosa que ella haga por ustedes
(tanto interna como externamente) que sea inmundo,
y esperen en eso que los llama y convence de pecado.
Sí, esperen y sean fieles,
hasta que experimenten el despertar de una vida y un deseo
que solo pueden deleitarse en eso que es puro,
justo y santo, y que abominan todo lo que sea contrario,
y no pueden unirse a ello en pensamiento, palabra,
o acción. Esta es la vida de la Semilla santa,
si en algún momento llegan a sentirla moviéndose y respirando en ustedes;
y a medida que su nacimiento espiritual crece en el vaso,
lo hace heredero del tesoro celestial, aunque al principio sea débil,
como un niño sin entendimiento o fuerza.
Sí,
al principio ustedes no saben cómo esto podría llegar
a tener toda potestad y dominio en ustedes,
debido a la abundancia de corrupción que se ha levantado por encima de ello en sus corazones,
y a las fuertes prisiones de maldad que gobiernan en su carne,
las cuales batallan contra la resurrección de este nacimiento inocente,
y por medio de los cuales el hombre fuerte guarda su casa,
usando de sutileza y maldad espiritual contra la vida pura y simple.
Sin embargo, si tan solo ustedes permanecen en eso que al principio les dio luz,
y son obedientes a ello,
sentirán como esto se levanta y los guía por un camino que no conocen.
Y aunque puede que pasen por grandes dificultades y tentaciones,
y muchas pruebas de fuego y tribulaciones, en las cuales son zarandeados y aventados,
aun así, ni un solo grano de esa semilla pura perecerá o caerá en el camino,
porque el Espíritu de luz y verdad los guiará. Esta
es la senda que ha sido probada en muchas generaciones;
porque esta senda es Jesucristo--la luz y salvación de los siglos,
quien ha vencido al diablo y al mundo,
y a todos los poderes de las tinieblas en todos los que han sido santificados.
Y ahora Él ha venido a hacer esto en ustedes,
para que ustedes también hereden la posesión adquirida
y se sienten con Él en los lugares celestiales.

Así que la labor de ustedes es la fe y la obediencia,
y la paciencia para con Aquel que es Espíritu y luz en su interior;
a Él deben entregarle su vida y todo lo que tienen.
Él confundirá la sabiduría corrupta de ustedes y dará luz
a todos los que todavía habitan en sombra de muerte.
Él edificará en ustedes el camino de la paz,
y ya no vivirán más por sus propias obras y dones naturales, sino que,
porque Él vive en sus corazones, ustedes también vivirán,
y su vida será eso que es engendrado por Dios y que nunca muere.
Esto Él lo hará por todos los que se entreguen enteramente
a la luz que conduce fuera del pecado.

Pero ustedes que oran y profesan,
y buscan y claman por ayuda en el exterior--no conociendo
a Aquel que tiene el socorro en Sus manos,
ni esperando en Él únicamente,
de modo que su expectativa está puesta en Él para todo--ustedes adoran lo que no conocen.
Aunque en palabras hablan del Dios vivo,
con sus hechos lo niegan y le dan su fuerza a eso que está muerto y no a lo vivo.
Pero díganme, ¿no debería cada hombre experimentar a su Dios viviendo en su interior,
e ir a ese Dios en su propio corazón para recibir vida,
según "`la manifestación de Su Espíritu que fue dada para el provecho de todos?`"^
footnote:[1 Corintios 12:7]
¿Y no deberían ustedes escuchar, conocer y aprender de Él--no en formas muertas,
sino en el poder del Espíritu de Vida?
Su Palabra dará vida a todos los que tengan el oído
abierto para escuchar al Espíritu vivo,
y puedan discernir lo vivo entre lo muerto.
Pero cualquier cosa que busquen para alcanzar vida y salvación,
que no sea de este Espíritu y poder, matará y devorará sus fuerzas,
porque nada puede darles vida salvo el Espíritu de Dios.
Solo este Espíritu puro puede alimentar con pan de vida al alma hambrienta,
y a este Espíritu ustedes deben entregarle todo lo que tienen y son.
Sí, deben gastar su tiempo y todas sus fuerzas en escuchar y obedecer,
para que crezcan en esa vida que es el verdadero pan.
Pero cuando ustedes le dan su fuerza a las costumbres, formas y rudimentos carnales,
a los placeres y deleites vanos, poniendo sus mentes en cosas visibles,
así gastan su fuerza en lo que no es pan,
y su trabajo en lo que no les aprovecha para vida eterna.
En lugar de esto, deberían esperar en eso que es puro,
para que Él les abra la puerta de vida.

Ahora mediten y consideren sus caminos,
ustedes que han mirado hacia afuera a las montañas para adorar y alimentarse.
Ustedes pueden leer acerca del pecado de Israel al separarse del templo,
en el cual el Señor había dicho que moraría y sería buscado.
Ellos edificaban altares fuera de Su templo, y allí lo invocaban, pero no lo encontraban,
razón por la cual Él rechazó la adoración de ellos y su
templo también. ¿Y dónde dijo Cristo que ahora sería adorado?
¿No es internamente?
Porque Cristo dijo:
"`Los verdaderos adoradores adoran al Padre en Espíritu y en verdad.`"^
footnote:[Juan 4:23]
Consideren esto, todos ustedes cristianos profesantes.
Él no será buscado en Jerusalén o en algún templo externo, sino en Espíritu y verdad;
y ahora el cuerpo es el templo, como Él ha dicho:
"`Habitaré en ellos y andaré entre ellos, y pondré mi ley dentro de ellos,
y todos me conocerán desde el más pequeño de ellos hasta el mas grande.`"^
footnote:[2 Corintios 6:16; Jeremías 31:33-34 LBLA; Hebreos 8:11]
La Deidad no habita en templos hechos de mano,
ni en sus lugares altos o sus casas de campanario,
sino en eso que brota de Él. ¿Pueden leer esto y entenderlo bien?
Es en eso que brota de Él que se conoce la Deidad y su poder.
Pero el altivo está demasiado lejos como para sentirlo.

Son los pobres y humildes de espíritu los que están cerca del poder,
y solo aquel que se ha hecho como un niño pequeño puede entenderlo,
quien no es demasiado grande en sus propios pensamientos como para
oír esa Semilla que es pequeña y pura en su corazón. Porque esta
Semilla brota por medio de un nacimiento en el corazón,
y es la naturaleza de Dios,
pero no es experimentada en la mente altiva que tiene conceptos espirituales,
pero no la naturaleza y la vida, ni el estado de hijo que es nacido de Dios.
Una vida y vaso santificado es descendencia de Dios; pero aquel que dice que quiere,
pero no hace, no ha nacido de la verdad, sino de la fornicación y la falsedad.
Así que lean su nacimiento, naturaleza y parentela con la luz de la verdad.
El incircunciso de corazón no es la descendencia de Dios ni un hijo del amor de Dios,
sino más bien el puro y limpio de corazón, de mente y de espíritu.
Y si su deseo es ser piadosos, deben experimentar esto en su interior;
pues de lo contrario ustedes están sin Dios en el mundo,
y no están ni viendo ni conociendo a Aquel que pretenden adorar.
En lugar de esto, están separados de Él en sus mentes, sus miembros, y en toda su fuerza,
de modo que no tienen ni poder ni entendimiento para hacer el bien,
habiendo sido tomados cautivos por un espíritu contrario
que controla todas sus habilidades de espíritu,
alma y cuerpo.
En verdad, su sabiduría está pervertida y su entendimiento oscurecido,
por haberse apartado de Dios en la raíz.

Y ahora, su manera de regresar debería ser la siguiente:
sumergirse en ese don que es santo y puro en la luz, y entregarle todo su corazón,
y todo lo que son y lo que tienen.
No consulten más con su sabiduría, ni sigan su propio entendimiento,
sino que dejen que esa pequeña Semilla en sus corazones los guíe,
la cual es pura y simple, porque solo ante ella deben inclinarse y doblar sus rodillas.
Esto será su restauración a Dios, entregarle todo lo que tienen al Santo en su interior,
quien, después de haber enloquecido su sabiduría carnal y derribado su gran altivez,
y atado al hombre fuerte, y amarrado al pollino a la vid,^
footnote:[Génesis 49:11]
entonces se levantará en poder Aquel (que es manso y santo) para gobernar en sus fuerzas,
dones y sabiduría, habiendo sacado al enemigo y renovado sus habilidades.
Así todo volverá a ser restaurado plenamente; todo será nuevo, limpio y eficaz,
por el poder del Santo que reinará y gobernará allí. Y ustedes
experimentarán al Señor (de cuya descendencia son) como la raíz,
la cabeza y el todo en ustedes, y nunca más dirán:
"`soy débil y nada puedo hacer,`" sino: "`todo lo puedo en Cristo que me fortalece.`"^
footnote:[Filipenses 4:13]
Entonces el devorador ya no pervertirá sus fuerzas,
sino que grande será en medio de ustedes el Santo.
Ustedes ya no sembrarán más para el devorador (como antes hacían),
ni llevarán fruto para el viento solano, sino que sus frutos se elevarán a Dios,
el cual los recibirá de buena voluntad,
y sus oraciones no volverán vacías cuando Él los haya inclinado
para Sí Mismo y haya quitado el anatema de en medio de ustedes.
Y entonces verán que todos los que menosprecian el
día de las pequeñeces rechazan su propia misericordia,
para seguir al maestro de las mentiras.
Estos no se vuelven a la reprensión del Santo, y por lo tanto adoran sin poder.

Y ustedes experimentarán la vida y poder de la redención, santificación y justificación,
y la renovación del Espíritu Santo en sus corazones,
cuando sus fuerzas sean redimidas para Dios, su sabiduría sea redimida, sus corazones,
lenguas, ojos y oídos, y todo lo que tienen sea redimido para Dios,
y llevado a eso que es santo, para que sean guiados y ejercitados en toda su conducta,
y posean sus vasos en santidad.
Aquí la renovación del Espíritu Santo es experimentada,
la cual santifica y justifica a través de la redención tanto del cuerpo como de la mente,
y de la reconciliación que es en Cristo Jesús. Porque Cristo
no es experimentado como Señor sino por el Espíritu Santo,
el cual lleva a toda verdad,
cuya verdad es un testimonio interno contra todos aquellos que
dicen haber sido redimidos para Dios por medio de Jesucristo,
cuando otro señor todavía gobierna en sus corazones y los mantiene cautivos al pecado.
De este modo, Jesucristo es negado por ellos, y sufre en ellos,
y ellos permanecen separados de Dios y en una naturaleza
que es contraria a Él. Por lo tanto,
ustedes deben venir a eso que cambia su naturaleza, y no solo sus palabras,
formas y maestros.
Deben venir a Aquel que engendra otra semilla,
y mata eso que es nacido de fornicación y concupiscencia
(que es según el príncipe de este mundo),
para que Dios sea servido en Su propio Espíritu, en Su propia verdad,
y en la naturaleza que Él mismo engendra,
siendo ustedes santos (en cada etapa de su crecimiento) como Él es santo.
Así, el más pequeño de Sus hijos es reconocido como de Él,
al salir y ser separado del mundo en alma y en cuerpo, y al llevar Su imagen y oprobio.

Y todos los que honestamente deseen ser herederos de este poder y reino santo,
esperen pacientemente hasta que sientan que algo
de esta naturaleza pura se mueve en ustedes;
y habiendo sentido como esto está vivo en sus corazones,
gócense en ello con esperanza y fe, y manténganse allí,
y no se desalienten debido a la pequeñez que tiene ante sus ojos en este momento,
ni busquen juzgarlo y medirlo con estos ojos,
porque ustedes no saben el poder que esto tiene de Dios,
y cuán precioso es ante Sus ojos,
y lo que hará por ustedes mediante Sus manos en el tiempo de necesidad.
Ustedes todavía no lo han probado, ni podrán probarlo,
mientras todavía queden cosas más grandes que esto en sus pensamientos,
a las cuales prefieran correr.
El poder de santidad y verdad en lo íntimo lo experimentarán únicamente en la profundidad,
cuando el fuego de la ira venga sobre toda esperanza vana y confianza hipócrita,
cuando todo lo que esté fuera del hombre sea echado lejos, cuando todas las relaciones,
amigos y familiares se sientan más lejanos que los extraños,
y cualquier cosa que la criatura busque para obtener consuelo se vuelva en su
contra y añada a su aflicción. Entonces el poder de la santidad será experimentado,
y la verdad de Dios en el corazón, y una conciencia limpia hablará paz;
y nadie podrá quitarles esto mientras permanezcan en este poder.
Uno que lo ha probado se los encomienda,
uno que ha sido despojado de todo para poder aprender
y conocer el tesoro de vida y santidad en Dios.
Por lo tanto, no juzguen eso que es más santo y mas pequeño que ustedes,
sino que dejen que esa Semilla que es justa y santa juzgue todo lo que se ha
levantado por encima de ella en sus corazones que no es de Su naturaleza.

La razón por la que ustedes menosprecian tanto esta Semilla es,
porque son demasiado grandes en la naturaleza contraria.
Así el orgulloso desprecia al pobre,
y el rico subestima al que es mejor que él. Ustedes encontrarán que esto es verdad,
si miden con eso por lo cual Dios considera y pesa toda carne, a saber, eso que es Suyo.
Por lo tanto, no juzguen al Santo, sino que crean y obedezcan,
porque su tiempo de juzgar todavía no ha llegado,
y no llegará hasta que el Santo y Justo se haya vuelto rey en ustedes,
y ustedes en Él. Por lo tanto, manténganse en eso que es santo y justo,
y crezcan en Él para que Él pueda reinar en ustedes,
y levantarse (a través de la muerte de Sus enemigos)
como la mayor de todas las hortalizas en el huerto,
y ser más grande que el mundo y su príncipe, que es el diablo,
de quien procede toda la incredulidad, los temores falsos y las dudas,
y todo lo que se exalta contra el Santo.
Y a medida que caigan estas torres que han sido levantadas contra el Señor,
Su camino se despejará, y la Verdad tomará Su lugar en ustedes como Rey y Señor,
y la incredulidad no tendrá lugar.
Y conforme la Vida se levante, ustedes experimentarán un cambio en sus mentes,
en su naturaleza, en su juicio y en su gobierno,
y sabrán que el reino y poder del Altísimo consiste en la unción del Santo,
y que el reino de Dios está dentro de ustedes, y que el pobre es el que lo hereda.

Así que no deben poner su fe en eso que se ve grande y fuerte en ustedes,
o en eso en que han puesto su esperanza, o que les ha prometido grandes cosas.
Mas bien, crean en eso que es santo, verdadero y justo en ustedes,
para que puedan experimentar la Unción en su propio corazón. Él es quien los llevará
a la congregación de los santificados en la cual el Santo reina sobre todos;
porque Él es quien ha sido enviado al mundo que yace en maldad,
para recoger a los hombres y llevarlos uno por uno a la santificación,
y así presentarle a Dios a todos los que Lo reciban.

Ahora, que todo el mundo preste atención a lo siguiente:
Este es Aquel a quien el Padre de las luces ha enviado
al corazón de ustedes que están en el mundo.
Este es el Santo, enviado por Dios para llamarlos y darles luz, el cual dijo de Sí Mismo:
"`Yo soy la luz del mundo.`"^
footnote:[Juan 8:12]
Escúchenlo y crean, para que sean hijos de luz y verdad;
porque esta son las buenas nuevas del evangelio de Cristo Jesús. Las religiones
y formas externas pretenden limitar al Santo a sí mismos,
y excluir a todos los demás, pero el don de Dios es dado libremente en Cristo Jesús,
y Su oferta es para todos los hombres,
porque Él quiere "`que todos los hombres sean salvos
y vengan al conocimiento de la verdad.`"^
footnote:[1 Timoteo 2:4]
Él no excluye a nadie sino a aquellos que no quieren recibir Su don, Su Hijo,
el Santo que los llama,
quien mediante la predicación del evangelio se ha acercado a ustedes.
Sí, Él está en ustedes con Su luz (sin dinero y sin precio),
permitiéndoles ver el camino para salir de las tinieblas,
lo cual nada ni nadie aparte de Él podría hacer por ustedes.
Y ahora, si ustedes lo reciben y guardan Sus palabras, y obedecen Sus movimientos,
Él habitará en ustedes y hará morada en ustedes,
y sabrán que el Padre lo ha enviado a llamarlos a
salir del mundo y a entrar en la luz de la vida.
Si ustedes lo niegan, Él los negará a ustedes; pero si lo reciben, el Padre los amará,
y les será dado poder de arriba para que sean hechos hijos de Dios.

Por lo tanto, atiendan a ese Espíritu que los llama a salir del pecado,
a salir del mundo,
y les da luz para que vean el pecado y el engaño en sus propios corazones.
Escuchen eso que es santo y que quiere apartarlos del mal, porque esto viene del Santo,
del Altísimo en su interior; crean en Él y síganlo.
No crean en aquellos que les dicen que Él no está dentro de ustedes,
los cuales "`han perdido toda sensibilidad`"^
footnote:[Efesios 4:19]
en sí mismos y ya lo han rechazado.
Pero ustedes que lo sienten, permanezcan en Aquel que es santo en su interior,
y que testifica contra toda impiedad.
Si ustedes no se cortan a sí mismos por medio de desobediencia e incredulidad,
Él de ninguna manera los echará fuera,
sino que incrementará Su luz por medio de la obediencia,
y purificará sus almas y limpiará sus vasos,
y actuará poderosamente en ustedes a través de Su verdad
para salvación. Entonces verán que Su obra es pura y buena,
y que es algo que nadie más puede hacer por ustedes.
Sí, este es el Señor, su justicia, aunque ustedes todavía no lo conozcan tal como Él es.

Y si quieren recibir al Santo,
este es su tiempo y el día de su visitación. Su luz está siendo
rechazada en este día por los edificadores de este mundo,
y la sabiduría de los sabios no quiere conocerlo.
No, ellos no quieren dejar que Él reine sobre sus rudimentos carnales,
ni que Él sea todo en sus corazones,
ni que ellos sean guiados por Su luz a la salvación. Así que Él es predicado a los extranjeros,
es decir, a los que están lejos y no lo buscaban.
A estos Él busca con Su luz, y si no lo rechazan, Él los hará ver la luz,
aunque estén asentados en región de sombra de muerte y cubiertos con densas tinieblas.
Por lo tanto, escuchen a Aquel que dice "`ven,`" y sientan al Espíritu que los atrae,
para que así correspondan a Su amor voluntariamente,
así como Él se los ha ofrecido libremente.
Experiméntenlo a Él mediante Su santidad,
y dejen que Su testigo inmutable en su interior (tanto de día como
de noche) persuada sus corazones que Él es el Señor que no cambia.
Sí, el que anuncia al hombre su pensamiento, el Señor Dios de los ejércitos es Su nombre.
Y ustedes que resisten Su aparición en Espíritu,
y les dicen a las personas que esto no es predicar a Cristo
(aunque ustedes profesan que Cristo está en ustedes),
díganme, si Cristo en los corazones de las personas no es ni luz, ni una vida santa,
ni un testigo fiel contra la naturaleza contraria
dentro de todos aquellos en quienes Él vive,
entonces ¿qué es?
¿De qué otra manera podría Él ser experimentado en Espíritu, vida y poder,
si esto es negado?
Así que dejen que la boca del anticristo sea tapada,
para que el simple siga en el camino correcto y vivo,
libre de todos aquellos que no quieren entrar en el reino ni dejar entrar a otros,
quienes siempre han resistido al Espíritu Santo.

[.asterism]
'''

[.blurb]
=== Las diferencias entre los Frutos de los Hijos de Libertad y Las Obras de la Ley, y los Hijos de Esclavitud Puestos al Descubierto por la Naturaleza de sus Obras.

Los hijos de este mundo--quienes tienen la apariencia, pero no el poder de la piedad,
y los conceptos de la vida,
pero no la naturaleza y Espíritu de ella--juzgan con sus pensamientos
oscuros y con su espíritu estéril a los hijos de luz;
y cuando nos ven actuando en la vida de Jesucristo,
entonces dicen que estamos bajo la ley,
y que pretendemos ser salvos por nuestras obras y por nuestro propio mérito, etc.
Pero ellos están muy equivocados y no están en ese Espíritu que puede vernos
o juzgar la naturaleza de nuestras obras o nuestra intención en estas cosas.
Por lo tanto, que todos callen y escuchen lo que ahora se les dirá,
si tienen un oído para oír. Porque, aunque ustedes estén muertos,
y sean como pámpanos secos, cortados de ese árbol que es bueno por naturaleza,
sin embargo,
este no es el estado de aquellos que han nacido de
nuevo y están injertados en el buen olivo;
porque aquel que realmente ha nacido de Dios conoce dos semillas y naturalezas diferentes,
que brotan y llevan fruto de raíces distintas, según sus diferentes géneros.

Ahora bien, el primero de estos árboles está en esclavitud, junto con todos sus pámpanos,
y lleva fruto para el yo, a partir de un precepto externo o un mandamiento escrito,
o cuando algo dentro que es carnal o natural se pone a obrar por sí mismo.
Y así ustedes,
por tratar de hacer cosas espirituales que son contrarias a su vida y naturaleza,
avanzan con mucha dificultad, y si logran realizar una obra externa,
entonces el jactancioso se levanta para gloriarse en lo que ustedes
pueden hacer--aunque ustedes hacen todo por motivos egoístas,
y buscan ser alabados por encima de aquellos que
no pueden hacer lo que ustedes han hecho.
Pero ustedes que no han tenido éxito en la práctica externa,
sino que se han fatigado a sí mismos en ella, y no han encontrado nada salvo esclavitud,
se vuelven atrás a la libertad carnal otra vez,
y juzgan a los demás según lo que han encontrado en ustedes mismos,
diciendo que todas las obras buenas proceden del espíritu de esclavitud,
de la jactancia y de la búsqueda de méritos para con Dios.

Pero ustedes no deberían juzgar a los hijos de luz según la carne,
porque la medida con la que miden no alcanzará ese nacimiento.
Porque el que es nacido de Dios es una rama de otra
raíz y semilla distinta a la que ustedes conocen,
la cual tiene otra naturaleza, que inclina a Dios de donde ella viene,
así como la primera rama inclina al mundo de donde viene.
Y así como el hombre natural hace lo malo naturalmente y con deleite,
porque su raíz y vida es de este género,
asimismo el hombre espiritual hace lo bueno naturalmente
(en su medida) según su raíz y vida.
Sí, es un placer y un gozo para él llevar fruto de la raíz que es buena por naturaleza,
incluso así como es el deleite de la otra rama producir
frutos de la raíz que es mala por naturaleza.
Porque como es el Celestial, así son también los que son celestiales,^
footnote:[1 Corintios 15:48 LBLA]
y no es esclavitud para la rama celestial llevar frutos celestiales;
pero para el hombre terrenal esto sí es esclavitud,
siendo un esfuerzo contra su naturaleza.
Por esta razón Cristo dice: "`Haced el árbol bueno, y su fruto bueno,
o haced el árbol malo, y su fruto malo.`"^
footnote:[Mateo 12:33]
De modo que es evidente que los árboles buenos,
los árboles malos y los árboles estériles son de diferentes naturalezas,
y producen diferentes frutos.

Así que no es más que su propia oscuridad la que piensa de esta manera,
y ustedes juzgan equivocadamente con sus malos pensamientos.
¿Dirán ustedes de los que están realmente injertados en la Vid viva,
que sus frutos (que brotan libremente de ella) son legales y son una forma de esclavitud,
y que nosotros pensamos ser salvos por nuestras obras, y por nuestra propia justicia,
etc.? No, estos son los frutos de aquellos que ya están salvos,
y que han cesado de sus propias obras y recibido la justicia de Dios.
En verdad, las obras de estos ya no son de la ley, sino espirituales;
ya no proceden de esclavitud sino de libertad,
y el que está en Cristo lleva fruto en toda buena obra,
y es libre en ello por nacimiento.
Y el que permanece en Cristo no peca, ni es su semilla la del maligno.

Si ustedes entendieran esto,
no condenarían los frutos de los vivos junto con
los frutos de aquellos que viviendo están muertos,
cuyos frutos se han secado.
Estos están separados del Único que es bueno por naturaleza
y plantados en eso que es silvestre por naturaleza.
Así que ustedes no pueden juzgar al hombre espiritual, ni sus frutos, su libertad,
su descendencia, o su fin; en cambio, él puede juzgar todos los árboles estériles,
aunque él mismo no es juzgado por nadie.
Yo sé que para ustedes que están habituados a hacer mal, es difícil hacer bien,
tan difícil como al leopardo mudar sus manchas;
pero es todo lo contrario para aquellos que ya han sido cambiados,
los cuales han nacido de la luz,
y son herederos por nacimiento y por naturaleza de la justicia y verdad eternas.
Para estos es difícil hacer mal, ya que es algo contrario a su naturaleza,
semilla y estado de hijos, que son de Dios.
Y aunque ustedes no puedan creer esto, aun así,
el que ha nacido de la fe sí puede y lo hace;
porque el hijo más pequeño de Dios puede leer esto en su medida,
puesto que conoce la diferencia entre el viejo Adán y el nuevo.
Y así como en la primera naturaleza todos están en pecado y esclavitud,
asimismo en la segunda todos son hechos justos y están libres para hacer la obra de Dios;
y en la segunda se experimenta la nueva creación donde mora la justicia,
como Dios ha dicho: "`Habitaré y andaré en ellos.`"^
footnote:[2 Corintios 6:16]

¿Considerarán ustedes esto como justicia propia,
cuando todas las cosas son hechas nuevas y todo esto proviene de Dios?
¿Son estás las obras de la ley y un yugo de esclavitud?
Si alguno está en Cristo, todas las cosas son de Dios,
y Él es el que produce en nosotros así el querer como el hacer por Su buena voluntad.
No, este no es el espíritu de esclavitud,
sino más bien la buena voluntad y placer que Dios obra en nosotros libremente.
Y cuando ustedes reprochan esto, reprochan lo que Dios obra por el oír de la fe,
que es la misma justicia que fue forjada en Abraham,
la cual también estaba en Dios antes de que Abraham fuese,
y es un don gratuito para todos aquellos que (por la fe
de Abraham) salen del mundo a Aquel que no es de este mundo.
Pero ustedes que permanecen en el mundo no heredan esta justicia,
porque siguen en el yo y están buscando sus propios intereses
en todo lo que hacen para Dios y para los hombres.
Cristo dice: "`¿Cómo pueden creer ustedes que buscan recompensa de hombres,`"^
footnote:[Juan 5:44]
y no están en ese Espíritu que obra por gracia?
Sí, ustedes (tanto los maestros como el pueblo) buscan alabanza, honor,
mérito y acepción de personas, en esa naturaleza que esta fuera de la fe de Jesucristo.
Porque Él andaba de un lugar a otro haciendo bienes libremente y predicando gratuitamente,
y así hacen todos los que han nacido de la verdadera libertad.
Ustedes hablan de Su vida, pero no la conocen por nacimiento y virtud,
la cual es naturalmente buena, así como el primer y caído hombre es naturalmente malo.

Ahora bien, la esclavitud se encuentra en eso que obra contra la naturaleza pura,
y no en eso que ha nacido en libertad;
y la ley es para el transgresor y para todos los que se
han degenerado a esa naturaleza que es carnal y animal.
Si este hombre carnal hace alguna cosa para Dios,
lo hace a partir de algo que se le impone desde afuera, y no en el Espíritu;
y esto es estar bajo la ley y la esclavitud,
porque no es hecho por el Espíritu de libertad,
el cual por naturaleza hace lo que es de la ley.

Y en verdad, es poco lo que el hombre natural haría o conocería,
si no hubiera una ley o letra externa, o un cielo e infierno que lo pusiera a actuar.
Aquí está la esclavitud y el temor que lleva en sí castigo.
Pero no es así con la semilla espiritual;
aquellos que han sido engendrados por Dios y han nacido de Él en Cristo Jesús,
de quien ellos reciben libremente como los pámpanos reciben de su raíz. Y lo
que fluye de la raíz a través de estos pámpanos son los frutos de Su Espíritu,
contra los cuales no hay ley.
Esto no se trata de legalismo, sino de algo espiritual y libre,
y estos pámpanos son ley para sí mismos; porque no hay ninguna ley contra la Semilla,
sino que la ley fue añadida para el transgresor (a causa
de las transgresiones) hasta que viniese la Semilla;
y donde sea que nazca y gobierne esta Semilla,
ahí la criatura no está bajo la ley o letra, o bajo tradiciones o esclavitud,
sino que es guiada por el Espíritu,
y nacida de esa naturaleza que era antes de la transgresión. Y por medio de esto,
los frutos de justicia son sacados a luz por la operación del Espíritu Santo,
que produce tanto el querer como el hacer por Su buena voluntad,
y estos frutos son dados a luz con la misma buena voluntad y placer,
sin esclavitud ni obligación.

Y en cualquiera que las prisiones de maldad sean quebradas,
ahí el mundo habrá llegado a su fin, ahí todas las cosas serán hechas nuevas,
y todo provendrá de Dios.
Ahí la justicia propia no morará, ni el espíritu de esclavitud,
sino que habrá una nueva creación en Cristo Jesús
(no en el yo) que será creada para buenas obras.
Ahí los cielos serán nuevos, y la tierra será nueva,
y la justicia morará en Cristo Jesús quien Dios revelará en Espíritu y poder,
de lo cual la ley y los profetas dan testimonio,
habiendo anunciado de antemano la gloria y libertad que serían reveladas
en los postreros días por la aparición de la Semilla.

Pero antes de que puedan juzgar sobre esta libertad,
o sobre la naturaleza de las obras que brotan de ella,
o heredar el poder que engendra esta justicia,
deben aceptar el juicio de Aquel que condena al hombre de pecado en ustedes,
y recibirlo a Él como su legislador.
Esto los arrancará del mundo, y los hará negar sus formas e imágenes,
y los sacará de debajo del poder de ellas.

Por lo tanto, tengan cuidado, ustedes que invocan el nombre del Señor y lo llaman maestro.
Apártense de iniquidad y obedezcan la justicia; esta es Su obra,
si ustedes son Sus siervos.
Él los ha llamado a ser santos, como Él es santo,
y por lo tanto deben apartarse del mundo,
y arrepentirse de las obras del príncipe del mundo,
negándolo a él y sus obras tanto abierta como secretamente.
Si ustedes quieren servir al Santo,
deben llevar Su marca y abrir sus corazones a Él y sus bocas para Él,
incluso con tanta audacia como los siervos del pecado lo hacen por el pecado.
De esta manera su luz resplandecerá contra las tinieblas de este mundo,
delante de una generación torcida y perversa,
y será evidente para todos los hombres que los caminos
del Señor y los del mundo no son los mismos,
ni sus siervos son los mismos, ni sus palabras las mismas, ni sus vestidos los mismos,
ni su mesa la misma.
Ustedes deben llevar Su imagen y gloria en todas las cosas por encima de Su adversario,
para que se manifieste a qué familia pertenecen,
y cuál es la obra del Señor en el mundo.

Y en esto todas las personas pueden verse a sí mismas, como en un espejo,
si están de lado de Dios en este Su día,
o contra Él. Cristo nos dice que solo hay dos señores,
y que ninguno puede servirlos a ambos, porque aborrecerá al uno y servirá al otro.
Ahora díganme, ¿quién los ha contratado?
¿A quién sirven, y a quién aborrecen?
¿Es al mundo al que ustedes le sirven?
Entonces, aborrecen a Cristo.
¿Es Cristo?
Entonces ustedes niegan al mundo.
Estas cosas son simples, y ustedes podrán ver claramente, cuando anden en sus asuntos,
de quién son los negocios en los que están, y de quién es la mano que ustedes fortalecen.
Si ustedes cometen pecado y contienden por él,
entonces pelean contra Aquel que ha aparecido para deshacer el pecado.
Y si dicen que el pecado debe vivir en ustedes mientras vivan sobre la tierra,
entonces ustedes creen que el diablo debe tener un lugar, un poder,
y un reino en sus corazones durante toda su vida.
Pero si ustedes creen que es posible vencer el pecado,
entonces esperan el reino de Dios (el cual consiste en justicia),
lo buscan diariamente de todo corazón y creen que lo verán.

Ahora bien, no son las palabras las que arrebatan el reino,
sino el poder de la fe actuando contra el maligno.
Tampoco es posible encontrar en las formas y profesiones religiosas,
o cualquier cosa externa, algo que pueda derrotar al diablo, porque él es un espíritu,
y debe ser resistido mediante un poder espiritual.
En verdad las armas que echan fuera su trono en el
hombre son espirituales y poderosas en Dios.
Pero ¡ay!, muchos son llevados de una forma a otra,
negando el poder de Dios en sus corazones, pero obedeciendo el poder del pecado; y así,
nunca experimentando el poder que pone el hacha a la raíz
del árbol malo desde la cual brota toda la maldad.
Pero el trabajo de ustedes en la viña del Señor comenzará
cuando se pongan a trabajar contra el pecado,
arrancando y cortando (con Su luz y poder espiritual)
cada cosa mala que sea tropiezo en el reino de Dios,
cuyo reino está dentro de ustedes.
Porque eso que los hace pecar está dentro de ustedes,
y eso contra lo que pecan también está dentro de ustedes,
y eso que está perdido está en el interior, y allí debe ser buscado.
Sí, la Perla, la Semilla, la Palabra, la ley del Espíritu de vida,
y el pacto están dentro del corazón,
pero estas cosas no serán vistas o creídas hasta que la casa de Dios sea barrida,
y los frutos de las tinieblas sean negados,
y el alma se vuelva a la luz de Cristo y obedezca al Justo.
Pero el injusto quedará manifiesto ante sus ojos,
y el poder que actúa contra él será visto,
cuando el fundamento de las tinieblas sea removido por la obra de la fe.

Ahora bien, todos los que son llamados a esta obra, y entran en ella en verdad y con fe,
no deben ser ociosos,
sino que deben obedecer al Espíritu de vida hasta que la casa sea limpiada,
lo inmundo sea echado fuera, y Aquel que es puro sea exaltado.
Entonces encontrarán su reposo santo en su interior, y su Dios cerca de ustedes,
y sus almas morando en descanso con Dios en su propia habitación,
siendo ustedes Sus templos.
Y estas no son obras propias, ni la voluntad propia,
sino fe y obediencia pura a la Semilla, o Palabra viva de Dios,
que lucha en ustedes contra el mundo y contra cada deseo y deleite egoísta y carnal.
Esta es la Semilla del santo pacto, cuya Semilla es Cristo, el Santo y Justo,
si ustedes la pueden recibir.
Este es Aquel que los hará limpios y los mantendrá así,
conforme lo obedezcan y caminen en Él. De Su Espíritu ustedes deben recibir su ley,
cuyo Espíritu les da Su vida para que la hereden aquí en la tierra.
Y si ustedes andan en el Espíritu no vivirán conforme a la carne.

Por lo tanto,
la objeción común (que el espíritu de este mundo hace contra
la vida y reino santo) es respondida fácilmente,
donde dicen, "`si fuera posible vivir sin pecado,
entonces no habría necesidad de un Salvador.`"
Porque aquellos que han aprendido verdaderamente esta vida y conocimiento,
encuentran que Aquel que limpia la casa debe mantenerla limpia también;
y que Aquel que es la muerte del pecado es también la vida de la justicia;
y que la misma luz y temor de Dios que lleva a despojarnos del viejo hombre
(con sus pasiones y hechos) también lleva a revestirnos del nuevo hombre,
el cual se va renovando conforme a la imagen del que lo creó, donde Cristo es todo,
tanto la vida como la guía, y donde el buen Hombre guarda la casa, no el hombre fuerte.
¿Cómo puede alguien decir que estos no necesitan salvador,
cuando ellos no pueden hacer nada sin Él,
cuya vida de justicia es tanto su comida como su vestido,
y la luz de Cristo es la armadura que usan diariamente contra el mal en cada pensamiento,
palabra y acción?

Por lo tanto,
todos ustedes que profesan a Jesucristo como su Señor y maestro en palabras,
que también sea así en verdad y justicia,
de modo que en cualquier lugar o actividad que se encuentren,
se ocupen principalmente de la obra del Señor y no a la suya.
Ahora bien, Su obra se manifestará dondequiera que Él aparezca;
porque Su obra siempre es contra el pecado,
para deshacer las obras del diablo en este mundo,
para que así los reinos de este mundo vengan a ser de Cristo Jesús,
y el Santo reine y produzca Sus frutos en ellos.
Ahora en esto se manifiestan Sus siervos,
en que ellos luchan por el reino de Cristo en este mundo,
y contra todas las obras del diablo.
Y los siervos del diablo se manifiestan, por lo contrario,
por encontrarse ocupados en su obra,
la cual es mantener el pecado en este mundo mientras las personas vivan,
porque el pecado es la fuerza de su reino.
Si quitan el pecado, entonces habrán quitado su reino aquí, y su poder aquí,
y su lugar aquí, porque él huirá de donde sea resistido.
Pero donde él sea recibido, ahí establecerá su trono y se deleitará en sus siervos,
y ellos se complacerán en su obra,
la cual es incrementar el engaño y la vanidad en ellos,
y llenar sus corazones de toda concupiscencia.
Así son llevados en pos de todos sus deseos,
hasta que ya no tengan complacencia en nada que sea contrario a ellos,
ni puedan creer que sea posible que alguien reciba
poder en el Espíritu de Cristo contra el diablo,
o experimente una redención que lleve a vencer al pecado en este mundo.
Y así se hace un acuerdo con la muerte, y se establece un pacto con la injusticia.

Todos los que son de esta mente y creencia, no son siervos de Cristo Jesús el Justo,
ni han recibido Su fe, que es pura como Él es puro,
y que cree que es posible alcanzar la justicia y la victoria, y ser libres del pecado.
Esta es la fe que vence al mundo y a su príncipe, y resiste al diablo,
con firmeza y esperanza de alcanzar victoria al final.
Los que tienen esta fe tienen sus corazones y sus rostros vueltos a la santidad,
y se encuentran en su viaje fuera del mundo.
Su mente está puesta en la luz santa y pura de Cristo en todas sus aflicciones,
tribulaciones y tentaciones, las cuales producen más esperanza, y más fuerza cada día,
y cada prueba que ellos encuentran en el camino les da experiencia,
y renueva sus fuerzas contra su adversario el diablo,
siempre y cuando se mantengan aferrados a Cristo en fe y amor.
Y aunque sientan que el diablo es fuerte y poderoso en la parte natural,
y que supera la fuerza que tienen actualmente, sin embargo, ellos no le ceden el reino,
sino que se hunden en la fe, en la esperanza y en la paciencia de Jesucristo,
esperando la resurrección de esa vida que nunca ha pecado, y la aparición de Cristo,
sin relación con el pecado,
para salvarlos del poder de la muerte que combate en sus
miembros para engendrar el pecado en este mundo.
Y este es su verdadero servicio y fidelidad: esperar el reino de Dios dentro de ellos,
y la justicia de este, y la venida de su Señor, con sus mentes ceñidas con la santidad,
y sus corazones firmes, no consintiendo ni la menor obra del diablo,
aun cuando hacerlo signifique ganar el mundo entero según la razón y sabiduría natural.

Y si estos son vencidos y cometen una falta, no es voluntariamente,
sino que como siervos de Cristo se oponen a su propio pecado hasta donde ellos lo vean.
Y sabiendo que el pecado es una obra del maestro equivocado,
lo aborrecen y se aborrecen a sí mismos por él, y lo niegan,
y nunca abogarán por él o buscarán esconderlo, sino más bien lo confesarán,
y no podrán tener paz hasta que sea limpiado.
Estos son los hijitos que tienen un abogado para con el Padre,
para quien el pecado es como la muerte,
y ellos no se atreven a decir ni una palabra a favor de él, sino solo en su contra,
tanto en sí mismos como en otros.
Y estos se muestran públicamente contra del pecado,
y le confiesan todo (con sus corazones y sus palabras) a Aquel que es santo.

Pero qué diferencia hay aquí entre uno de estos--que cuando ven o se les habla de su
ofensa contra al Señor se quebrantan con lágrimas o dolor ante la más pequeña reprensión,
condenándose a sí mismos abiertamente por su ofensa,
y condenando el pecado en sus corazones--y ustedes,
que cuando son reprendidos por el pecado (que es público y conocido)
se ponen con todas sus fuerzas y sabiduría a excusarlo,
y (como el diablo) utilizan las Escrituras para fortalecerse
contra la justa reprensión. Sí,
con corazones llenos de envidia y bocas llenas de oprobio,
ustedes se levantan y procuran armar lazo contra los que
los reprenden por amor al reino de Cristo y a sus almas.
Ustedes escarnecen a aquellos que buscan hacerlos volver en sí, a fin de que escapen^
footnote:[2 Timoteo 2:26]
de las obras de Satanás. Se burlan de aquellos que
desean que el reino de Satanás caiga en ustedes,
para así dejarlo con menos súbditos en su poder;
y que ustedes sean añadidos al reino de Cristo al ser sometidos a Sus mandamientos,
y al negar a su antiguo maestro, confesando y condenando sus malas obras.
Porque en verdad, tienen que negar al diablo y sus obras antes de que Cristo los reciba.

[.asterism]
'''

[.blurb]
=== Jesucristo Conocido como Rey en Sus templos, por medio del Poder del Espíritu Santo y de la Espada del Espíritu, Alzada en Verdadero Juicio contra el Hombre de Pecado.

Ustedes que buscan el reino de Jesucristo, sepan que no consiste en observaciones,
palabras ni formas, sino en el poder del Espíritu Santo, en juicio,
en verdad y en justicia.
Si ustedes desean experimentar Su aparición para salvación,
esperen por él en ese Espíritu y poder que es santo, y que juzga y condena el pecado.
Porque experimentar Su poder espiritual en el interior como un testigo contra
todo pecado (a través del espíritu de Su boca y la espada de Su Espíritu)--esto
es Su reino para con los hombres (si es que pueden recibir esto).
Aquí los hombres encuentran poder para juzgar a todos los
espíritus contrarios en el interior y en el exterior,
y todas las acciones contrarias;
pero todo lo que se oponga y niegue Su reino en Sus templos, es anticristo.

Porque el templo de Cristo es la nueva creación de santos hombres y mujeres
en quienes Él habla y mora y anda (como testifica la Escritura),
y en quienes Él juzga al príncipe de este mundo,
y todas sus obras en los hijos de las tinieblas.
Y Cristo manifiesta Su naturaleza y virtud en Sus propios
templos como un testigo contra el diablo y todas sus obras.
Cualquiera que quiera impedir esto es anticristo,
el cual se sienta en el templo de Cristo para resistir al Santo y rechazar
los justos juicios de Cristo contra el pecado en Su templo.
Estos dan voces diciendo: "`No juzguéis,`" siempre que la Verdad habla,
y "`No juzguen para que no sean juzgados,`" cuando el Espíritu
de Cristo testifica contra el pecado con verdadero juicio.
Y así, a través del engaño, estos tratan de volver las palabras de Cristo contra Su obra,
el cual dijo: "`Redimiré a Sion con juicio.`"^
footnote:[Isaías 1:27; Véase también Isaías 4:4]
Porque cuando Cristo dijo: "`No juzguen para que no sean juzgados,`"^
footnote:[Mateo 7:21]
no lo dijo para salvar el pecado del juicio,
ni para detener la boca de la verdad y la justicia,
porque Él entonces se habría contradicho a Sí Mismo al mandar a "`juzgar con justo juicio.`"^
footnote:[Juan 7:24]
En verdad, Cristo ha aparecido para deshacer el pecado y no para salvarlo.
Esto es lo que Él hace en cualquiera en quien aparezca,
y con este propósito Él vive en Su pueblo.

Por lo tanto, ustedes que profesan a Cristo en palabras y formas,
busquen Su reino en su interior,
y tengan cuidado de que sus formas no resistan Su poderosa aparición en Espíritu.
Su autoridad como rey consiste en Su naturaleza y virtud celestial y santa en Espíritu,
y no en rudimentos perecederos y sombras externas.
Lean en las Escrituras cuán a menudo el anticristo ha engañado a las personas
al hacer que las formas externas resistan el poder espiritual,
y así ha mantenido a las personas en palabras sin vida, oponiéndose a Cristo en Su reino.
Por lo tanto, en primer lugar, busquen conocer Su naturaleza y virtud espiritual,
la cual tiene poder contra el pecado,
tanto en palabra como en acción. Aquí está el reino de Cristo, aquí está Su gloria,
y aquí Él reina.
Su reino es espiritual y santo, y está en el interior, donde Sus testimonios,
leyes y juicios se conocen.

Y ustedes que están hablando de la aparición de Cristo ¿dónde piensan que Él reinará,
si no es en el corazón (el lugar más importante en el hombre), a fin de juzgar, gobernar,
hablar y dar Su ley allí? ¿Aceptarán que el maligno
pronuncie su voz abiertamente a través del hombre,
jurando, mintiendo, maldiciendo y haciendo toda obra perversa,
y que aun así Cristo deba permanecer en silencio y mudo en Sus vasos cuando Él vea esto?
¿No es este el privilegio de Cristo en Sus redimidos,
así como el príncipe de este mundo tiene poder en sus cautivos?
En verdad, este es el servicio racional de Sus vasos escogidos:
entregar sus cuerpos para que Él hable y actúe y muestre Su virtud,
vida y poder en ellos contra el espíritu del mundo en sus vasos.
Y si no fuera por las palabras que Dios habló por medio de ellos,
los hombres santos de Dios nunca habrían sufrido o sido aborrecidos; pero Cristo dijo:
"`No sois vosotros los que habláis,
sino el Espíritu de vuestro Padre que habla en vosotros.`"^
footnote:[Mateo 10:20]
Esta es la voz que el mundo no conoce, y por lo tanto procura callarla,
diciendo que no es el Señor;
pero estos no saben que la justicia y el juicio son la habitación
de Su trono en los corazones y bocas de Su pueblo.

¿Qué? ¿Debe el Espíritu de la verdad abstenerse de
juzgar el engaño y la falsedad donde Él mora?
¿No debe eso que es santo juzgar lo inmundo?
¿No debe eso que es humilde juzgar al orgulloso,
y eso que es casto juzgar toda concupiscencia?
¿No debe "`aquel que es espiritual juzgar todas las cosas?`"^
footnote:[1 Corintios 2:15]
¿No deben "`los santos juzgar al mundo?`"^
footnote:[1 Corintios 6:2]
¿Qué tipo de nación quisieran que fuera esta,
ustedes que quieren anular el juicio y sin embargo profesar a Cristo en su interior?
¿Está realmente Cristo en un pueblo en el que no hay juicio contra el pecado, el orgullo,
el exceso, la mentira, los juramentos, los falsos caminos y las falsas adoraciones?
¿Permitirán que todo pecado se cometa abiertamente sin ser reprendido?
¿Se ha vuelto toda nuestra tierra como Sodoma?
Consideren las palabras que los hombres de Sodoma le dijeron a Lot en este caso:
"`Este ha venido como extranjero, y ya está actuando como juez.`"^
footnote:[Génesis 19:9 LBLA]
Por esta razón el alma justa de Lot se "`afligía cada día,
viendo y oyendo los hechos inicuos de ellos.`"^
footnote:[2 Pedro 2:8]
¿Permitirán que el pecado ocurra abiertamente en las calles sin represión ni vergüenza?
Entonces ¿Donde está el Santo?
¿En quien mora Aquel que es "`de ojos muy limpios como para ver el mal?`"^
footnote:[Habacuc 1:13]
¿No es Cristo un rey?
¿No es un Juez?
¿No es puro y limpio de corazón? ¿No vive?
¿Puede ver el pecado y quedarse en silencio donde tiene boca por la cual hablar?
Consideren como Él andaba antiguamente en Sus siervos, y qué hizo y habló en ellos,
y contra qué. ¿Y no es todavía Él un Dios de juicio
que está cerca para hacer frente a Su adversario,
(aunque los que no conocen Su voz dicen que está lejos)?

Así que ustedes que dicen que están a favor de Cristo y de Su reino,
consideren de quién es el reino en el que se encuentra el pecado,
y de quién es la obra de defenderlo del juicio,
y de distorsionar las Escrituras para contender por él. Esto seguramente
es para "`justificar al impío y condenar al justo,
siendo ambas cosas igualmente abominación al Señor.`"^
footnote:[Proverbios 17:15]
Por lo tanto, si ustedes aman la aparición de Cristo Jesús, no deben amar el pecado,
sino que en esa Semilla que no puede pecar,
deben sentir a Aquel que sufre por causa del pecado,
y que sin embargo no tiene pecado y está en contra del pecado.
Y si ustedes vienen a Aquel cuya aparición es santa, justa y verdadera,
y en ella se unen a Él, amarán eso que condena el pecado.
Entonces ustedes estarán verdaderamente a favor de Cristo,
cuando puedan sentirlo y sufrir con Él,
y verán que nada ni nadie es ofendido cuando el pecado es juzgado,
salvo aquel que es culpable del mismo.

[.asterism]
'''

[.blurb]
=== Gracia Recibida, y Gracia Rechazada.

La gracia de Dios es eso que trae y acerca la salvación al hombre,
concediéndole una perspectiva de la verdad dentro de su corazón;
porque Dios quiere que todos los hombres vengan al
conocimiento de la verdad y sean salvos.
Todos los hombres son tinieblas naturalmente, estando "`sin Dios en el mundo;`"^
footnote:[Efesios 2:12]
por lo tanto la gracia de Dios es ofrecida a todos sin acepción de personas.
Ahora bien, esta gracia es la misma en todos los hombres,
y ni es indulgente con el mal ni niega el bien en ninguno,
sin acepción ya sea de personas, sabiduría, fuerza o riquezas de este mundo.
Solo considera al Espíritu de la verdad en todos, y la obediencia del hombre al mismo,
procurando enseñar y guiar a todos a la salvación,
y a la verdadera adoración de Dios en Espíritu,
a la vida eterna y al crecimiento de la Semilla santa en el hombre,
vivificando el alma que ha sufrido a causa del pecado.
Esto lo hace condenando el pecado en cada movimiento, y también ministrando consuelos,
promesas,
y poder en el Espíritu de tal modo que el alma pueda
levantarse sobre el poder de los hijos de iniquidad.
Sí,
es la gracia la que ministra luz y entendimiento
en lo íntimo al alma que aborrece el pecado,
abriendo diariamente (a través de la obediencia a
la verdad) ese ojo que el dios de este mundo ha cegado,
y purificando al alma al despojarla del cuerpo de corrupción. Y la gracia también es
la que ciega el ojo de aquel que dice que ve pero que no conoce el camino de pecado,
y además la que ministra la ley sobre él.

Esta es la ministración de la gracia que libremente es dada a cada alma que la recibe,
la cual, mediante el Espíritu de Cristo,
obra poderosamente en todos los que permanecen en ella.
Y, como dice la Escritura, esta "`gracia se ha manifestado a todos los hombres;`"^
footnote:[Tito 2:11]
sí,
y se manifiesta diariamente en todos aquellos que
verdaderamente esperan en el Espíritu Su aparición,
concediéndoles a estos una perspectiva de la verdad en sus corazones,
que testifica a favor o en contra de cada intención del corazón de acuerdo,
a como Dios la considere, ya sea buena o mala.
De esta manera "`su conciencia da testimonio, y sus razonamientos los acusan o defienden,
en el día en que Dios juzgará por Jesucristo los secretos de los hombres.`"^
footnote:[Romanos 2:14-15]
Así que la razón por la que algunos no son salvados
del pecado y la condenación por medio de la gracia,
no es culpa de la gracia; sino que la gracia, al ser rechazada,
se convierte en la condenación del hombre.
La misma gracia que salva a aquel que la recibe con fe y obediencia,
también condena a aquel que la rechaza con desobediencia.
Esta es la gracia de Dios que no cambia, y que se manifiesta a todos los hombres,
pero que solo "`reina por la justicia`"^
footnote:[Romanos 5:21]
para salvación en el corazón de aquel que cree que ella es suficiente y la obedece.

Así que, eso que es de Dios en el hombre es Su gracia,
la cual ministra luz espiritual al alma en medio de las tinieblas,
y vida a aquel que está muerto en pecado.
La gracia lleva al hombre a través del valle de la muerte hacia arriba, a Dios,
de donde ella vino y a quien ella pertenece.
Y la luz de esta gracia es juicio y discernimiento en todos
los que la reciben y son guiados por ella en juicio.
Pero esta misma luz es la condenación de aquellos que convierten
la gracia en una licencia para la inmoralidad,
negando la vida de ella y la verdad a la que ella lleva.
Estos no pueden ser salvos por ella.
Pero el que la reciba y se una a ella en Espíritu, se vuelve uno con ella,
y al sumergirse diariamente en su consejo, ella crece en él y él en ella,
hasta que ella se convierte en una morada y refugio contra todo mal.
Así se vuelve un hombre cuyas palabras y obras están llenas de gracia,
recibiendo diariamente de la plenitud de Cristo, sí, gracia por gracia.

Ahora bien, el que ha recibido de esta gracia y es fiel en ella,
no debe ministrar a partir de ella para fortalecer al transgresor
(el cual ama su pecado y por lo tanto está bajo la ley),
ni echar sus perlas delante de los cerdos.
Porque la gracia ministra juicio al impío,
para que así conozca su condenación por medio de la luz de la verdad,
y ya no le niegue a la gracia su reino.

Pero a aquellos que están cargados y cansados del pecado,
debe animarlos a seguir peleando contra el pecado y la tentación
(la cual todos los que se apartan del diablo tendrán que enfrentar).
Y el que recibe la enseñanza de la gracia llega a
través de ella a ser guiado por el Espíritu,
y por lo tanto a ser libre de pecado, y ya no está bajo la ley sino bajo la gracia.
Pero la ley tiene poder sobre todos los que andan conforme a la carne,
y cada aparición de la gracia es un testimonio en contra de ellos,
al declarar como ellos están bajo la ley del pecado y de la muerte,
y no en el pacto con el Único que aparece contra
el pecado en el poder de la gracia y la verdad,
el cual es Jesucristo el Señor.
