[short="Capítulo V -- Leche para Niños, Vianda para Maduros"]
== Capítulo V. Leche para los Niños / Y Vianda para los Maduros

[quote.section-epigraph]
____
"`Un banquete de vinos refinados,
de gruesos tuétanos y de vinos purificados.`"--Isaías 25:6
____

[.emphasized]
Oh vengan jóvenes y doncellas, ancianos y niños,
y beban abundantemente de las corrientes que fluyen de la fuente,
para que sientan un manantial de agua viva en su interior que salta para vida eterna;
de modo que, porque Él vive (a saber,
Cristo Jesús) de quien proceden todos los manantiales, ustedes también vivan,
y participen de la gloria de Aquel que se ha sentado a la diestra del Padre,
sobre todo principado y poder.

[.small-break]
'''

A ustedes que son tiernos de corazón, que han sentido el llamado del amor del Padre,
quienes ahora ven más bendición y hermosura en la inocencia y en la mansedumbre
que en toda la vanagloria y auto exaltación que se levanta del conocimiento
altivo--mi alma está con ustedes en esto.
Y ahora, esperen humildemente,
y atiendan diligentemente eso que les ha dado la perspectiva de esta excelencia,
hasta que brote la Vida que naturalmente posee las riquezas que vienen de arriba.
Porque, aunque esta Semilla yace muy por debajo de todos los afectos carnales,
pensamientos altivos y deseos apresurados (que la velan y esconden de ustedes,
de modo que no pueden venir a la vida y fuente de ella) aun así,
a medida que ustedes nieguen estas cosas y las aparten,
hundiéndose debajo de todas las cosas terrenales
y uniéndose a la Semilla que está debajo de ellas,
esta Semilla se levantará. Su
Amado sufre bajo todas estas cosas,
cuando ellas son levantadas por encima de Él en sus mentes;
y es por medio de la caída de todas estas cosas que Él se levantará y tomará Su reino,
antes de que ustedes lleguen a tener una morada de quietud en Él, y Él en ustedes.

Por lo tanto, ustedes deben ser plantados en la semejanza de Su muerte,
para que puedan sentir la comunión de Sus padecimientos y participar en
ellos de la mansedumbre y paciencia de Aquel que soporta todas las cosas.
Aquí su fidelidad a Él debe ser probada completamente,
en la fe y paciencia de las cuales aprenderán a Aquel que aman--tanto
Sus oprobios externamente como Sus tentaciones internamente.
Sí, incluso en esas pruebas que no pueden ser expresadas, ustedes aprenderán de Él amor,
obediencia, paciencia, mansedumbre y longanimidad,
y también cómo Él se levanta a través de todas estas cosas,
y cómo encadena a Sus enemigos y los lleva cautivos a través
de Su resurrección. Así participarán de Su resurrección,
en la cual llegarán a la resurrección de los muertos y a la herencia de la vida eterna.

Pero queridos hijos, no se extrañen cuando, por alcanzar esto, ustedes sean rechazados,
negados, condenados y contradichos por todos,
y tentados con toda clase de espíritus y maldades, asaltados interna y externamente,
sintiendo miedos y temores, en debilidad, desvelos y ayunos,
y con lágrimas de dolor día y noche.
Porque ustedes serán llevados al desierto y allí serán tentados
y probados en la noche con grandes tentaciones,
y no verán la manera de salir, y serán llevados por un camino que ustedes no conocen,
un camino de ira y terror,
pasando por las puertas del infierno sin nadie que
se compadezca de ustedes ni lleve su carga;
siendo castigados solos para que sean probados hasta lo extremo.
Así que cuando experimenten esto, no desmayen, ni miren atrás,
sino levanten su cabeza por encima de todo,
y sepan que Él ahora trata con ustedes como hijos e hijas de Su amor.

Tengan cuidado de no murmurar, ni lo juzguen a Él con su propia luz,
ni se quejen de Su vara.
Y no miren con malos ojos a los instrumentos que Él usa para afligirlos,
sean quienes sean o independientemente de lo que sean,
porque esto solo engendrará ira en sus mentes, y entonces perderán la vida que buscan,
y así sufrirán en vano.
Pero en las pruebas más grandes mantengan su ojo puesto en Su Amado,
y retengan la paciencia y la mansedumbre en longanimidad, con fe.
Que esto siempre esté en su corazón como el fin de todo,
y crean que todo lo que les acontece es únicamente para
desgastar eso que les impide unirse a Aquel que tanto estiman.
Así que en todas las cosas manténganse con Él;
dejen que Su gozo sea su fortaleza en todo,
y así la aparición de Su hermosura los refrescará en una nueva vida,
a medida que lo viejo se desvanezca.
Hagan guerra juntamente con Él en contra de la enemistad,
y dejen que Su amor apague toda la ira que se quiera levantar.
Dejen que Él sea su escudo de fe,
y mientras ustedes tengan su mente puesta únicamente en Él,
cualquier cosa a la que sean llevados a sufrir les
será provechosa para su objetivo deseado;
aunque sin Él nada pueden hacer.

Así que, si oran al Padre, que sea por medio de Él; y en todas sus luchas,
encontrarán que Su mansedumbre, paciencia y longanimidad en fe prevalecen mucho con Dios.
Si ustedes resisten al tentador, que sea con Él,
porque es únicamente Su bondad la que tiene poder para vencer el mal;
y Él será su fortaleza en todo momento si lo retienen firmemente en sus mentes.
En el fuego y en las aguas Él estará con ustedes y será su poder y paz,
y abrirá un camino a través de todo.
Aunque puede que a veces las nubes sean muy densas,
y los poderes de las tinieblas tan fuertes ante sus
ojos que ustedes no puedan verlo a Él,
aun así, si siguen amándolo y creyendo, lo tendrán a Él presente.
Sentirán Su paciencia llamándolos a bajar de la tormenta y poner sus ojos en Él,
y Su mansedumbre moviéndolos a seguir a Aquel que ha pasado
por el mismo camino antes en todos Sus santos.
Este es su Amado, el cual ahora va delante de ustedes.
Escúchenlo solo a Él, y entonces serán considerados fieles--es decir,
cuando no busquen a ningún otro para que esté con ustedes en todas las cosas,
ni para que los redima de todas las pruebas, sino solamente a Aquel que aman.
Y aunque el tentador les ofrezca alivio por algún otro camino (porque si él,
por medio de sufrimientos y amenazas, no puede sacarlos de Aquel que es manso y paciente,
entonces con halagos y promesas intentará alejarlos de Él), aun así,
esta es su fidelidad,
que permanezcan es su prueba hasta que la mansedumbre y la paciencia los saque de ella.

Porque lo que sea que busquen para redimirlos de la aflicción,
se volverá su señor y maestro, y ustedes serán sus siervos.
Por lo tanto,
tengan cuidado de no recibir nada como ayuda aparte de Aquel que desean heredar;
porque el que ponga carne por su fuerza heredará la maldición,
y la tierra vendrá sobre él, y tendrá que servirle.
Más bien mantengan sus mentes en la mansedumbre de Cristo, en Su paz y paciencia,
y recibirán las arras de su herencia en el día de la aflicción, y cuando salgan de ella,
nadie podrá arrebatárselas,
ni ninguna naturaleza contraria será señor en o sobre ustedes.
Pero Aquel en el cual han confiado reposará sobre ustedes,
y Su gloria los cubrirá y se volverá su vida y su líder para siempre.

Al ser fieles en estas pruebas, por un lado,
aprenderán a Cristo y por otro descubrirán las asechanzas de Satanás,
y llegarán a sentir perfectamente lo que cada uno
tiene en ustedes como su propio terreno para obrar,
según su obra presente en sus mentes.
Porque no deben confiarse en eso que piensa que los sufrimientos son fuertes,
y el tiempo largo.
Esto creará una desconfianza en la parte razonadora,
y los tentará a buscar libertad y alivio en alguna ayuda visible.
Y si no puede prevalecer con ustedes y lograr que salgan a cazar libertad, aun así,
si algún camino carnal es abierto,
formará una pretensión atractiva para hacerlo ver como si fuera de Dios,
y buscará seducirlos y sacarlos de Aquél que es justo y fiel.
Sí, esto busca ansiosamente mantenerlos fuera de su espera pura en Aquel que aman,
aprovechándose de su apresuramiento, fatiga y debilidad en el viaje.
Pero eso en ustedes que solo busca ser obediente a Dios en sufrimiento y en hechos,
con fe y diligencia, que escucha lo que Él dice con toda longanimidad,
mansedumbre y paciencia,
que considera que es mejor obtener consejo de Él que alivio de otro,
que estima todo como pérdida para poder ganar a Cristo,
que no piensa que el tiempo es demasiado largo,
ni considera nada como demasiado difícil de soportar por
el gozo y hermosura que es puesto delante de ustedes--esto,
digo,
nunca los engañará. Y siguiéndolo sentirán y verán a Su Redentor en medio de ustedes,
y con Él se levantarán y vivirán. Y Él los sacará de toda oscuridad,
y los pondrá sobre todos los miedos, y su libertad será perfecta y su herencia inmensa.
Pero todos los que no están dispuestos a mantener sus mentes puestas únicamente en Él,
serán consumidos en las pruebas de fuego, las cuales todo su apresuramiento,
búsqueda de tranquilidad falsa y desconfianza nunca podrán terminar.

Y habiendo aprendido este misterio de la piedad y encontrado su valor,
y habiendo hallado que Su camino es perfecto y puro,
y que Él es fiel con todos los que andan en este camino,
serán capaces de dirigir a los simples e indoctos en el camino hacia el descanso,
y sus palabras tendrán una manifestación de la vida en ellas,
y Su poder vivificador estará con ustedes.

Y esto sentirán durante todo el camino:
que mientras más diligentemente esperen en Él en todas las condiciones por las que pasen,
más de Él recibirán, al beber de la virtud celestial que está en Él,
y al cenar con Él continuamente.
Así llegarán a ser llenos de Él, y todo apuro,
impaciencia y desconfianza serán cubiertos y vencidos por Él,
y lo que es mortal será sorbido por la inmortalidad, hasta que Él se vuelva toda su vida,
y todos sus pensamientos, palabras,
y acciones tengan su origen y esencia en Él. De esta manera el yo nunca más será visto,
y ni la muerte, ni la condenación tendrán entrada o poder.
Y encontrarán esto como la casa de arriba,
donde todos los espíritus de los justos viven y caminan
y tienen comunión a medida que son perfeccionados.
Esta es esa ciudad celestial, de la cual el Cordero es la luz y la salvación,
y a la cual nadie puede entrar salvo aquel que a través
de Su mansedumbre y longanimidad es redimido.

Por lo tanto, con toda diligencia, húndanse en el sentir de la elección,
no mirando esa parte en ustedes que se jacta de palabras altivas antes de ser probada;
porque cuando entra al fuego no permanecerá pacientemente en la prueba.
Pero entregando esa parte a la muerte,
busquen eso que yace por debajo de ella en sufrimiento,
eso que los llama a descender de todo pensamiento altivo.
Bajen al valle de la humillación y únanse con Aquel
que soporta todas las cosas sin murmurar,
para que ustedes puedan sufrir con Él,
y aprender a obedecer con Él. Y cuando Él esté con ustedes en todas las cosas,
y ustedes con Él, entonces conocerán la elección, y la "`harán firme`"^
footnote:[2 Pedro 1:10]
para ustedes en la vida y en la muerte.
Y aunque sean derribados con Él en la carne, Él los levantará en el Espíritu;
aunque sean sembrados en debilidad, resucitarán en poder.
De esta manera serán transformados por Él,
si tienen cuidado de levantarse únicamente con Él, en la medida en la que Él los levante,
y si no echan de sí Su yugo, ni huyen de Su cruz,
ni sanan su propia herida.
Porque aunque su herida sea mortal,
aun así, la cura es inmortal; y aunque ustedes desciendan en vergüenza y oprobio,
sin embargo, resucitarán en gloria, cubiertos con honor inmortal y vida eterna,
con poder y fuerza para cumplir la voluntad de Dios,
y con "`un testimonio de una buena conciencia.`"^
footnote:[1 Pedro 3:21 RVG]
Es a través de este bautismo y resurrección que alcanzarán el premio,
y así se volverán un Espíritu con Aquel que mora en la luz--uno con Él en muerte,
en sufrimientos, en paciencia, en fe y en obediencia.

Porque la luz demanda que esa justicia sea cumplida,
pero el primer nacimiento no tiene el poder.
Por lo tanto, a través de la ley, el primer nacimiento debe perder su vida^
footnote:[Véase Gálatas 2:19]
(cuya ley tiene poder sobre el transgresor entre tanto que éste vive^
footnote:[Romanos 7:1]),
porque el alma no puede unirse a Cristo hasta que haya muerto a la ley.^
footnote:[Romanos 7:4]
Así que la ley debe matar al primer nacimiento (que
es terrenal) a causa del pecado y la desobediencia;
pero ese nacimiento que es del Espíritu vivirá a causa de la justicia y la obediencia.
De esta manera, la naturaleza jactanciosa es excluida, estando encerrada bajo pecado,
para que, mediante la misericordia de Dios,
la Semilla mansa se levante sobre todo y cumpla todas las cosas.

Porque la luz dice:
"`Ama a tú prójimo como a ti mismo;`" pero el primer nacimiento no puede hacer esto,
y por lo tanto es descubierto y excluido.
Por ende, la ley ejerce su dominio sobre la vida que carece de este amor,
y la criatura debe entregarla a la muerte para que pueda experimentar el Espíritu manso
que da el poder de otra vida--una vida que tiene la justicia y la obediencia en ella.
Y a medida que la criatura saque su mente,
sus afectos y su fe de este primer nacimiento (que tiene palabras sin poder),
y se los entregue al segundo nacimiento, el primer nacimiento comenzará a caer,
a secarse y a morir en esa vasija.
Y a medida que el corazón esté diligentemente puesto en el segundo nacimiento,
en esa medida se levantará en la fe,
y Cristo levantará el poder de la obediencia en esa vasija.
Así, conforme la nueva creación se levante a través de la ley (cumpliéndola),
también manifestará frutos superiores a la ley, contra los cuales no hay ley.
Es de esta manera que el que camina en el nuevo pacto
encuentra el poder de la obediencia para justicia,
y experimenta el fin de la ley.
Porque,
cuando esa vida que se levanta a través de la desobediencia (la naturaleza transgresora,
a causa de la cual la ley fue añadida), es negada, matada y enterrada,
entonces la ley también muere.
Y Aquel que cumple la ley en ustedes es el mismo que la dio,
el cual se convierte en el fin de ella en todos los que viven en Él por fe.
Estos heredan verdaderamente la justicia a medida que, por medio de la muerte,
se revisten de Su vida.

Así que siendo fieles en la luz aprenderán a Aquel que mata y da vida, derriba y levanta,
condena y justifica; y también conocerán el camino de la muerte y el camino de la vida,
y verán quién es el que es endurecido por la ley, y quién es el que la cumple,
y la vida y el fin de ambos.
Y ustedes entenderán la razón y el propósito de todas las tribulaciones, los terremotos,
los truenos, la oscuridad y las grandes tentaciones,
y la prueba de su fe en esto será como el refinamiento del oro,
y los llevará a heredar el conocimiento de Dios y la vida eterna.
Aquí encontrarán poder para juzgar al príncipe del aire,
para entender el misterio de la iniquidad y para negar al dios de este
mundo con todas sus artimañas y trampas en las que los profesantes indoctos
del cristianismo han sido tomados y son mantenidos cautivos a su voluntad.
Aunque algunos de estos tengan un conocimiento externo y una forma de la verdad,
siendo esto una imitación de lo que otros han aprendido, aun así,
ustedes podrán juzgar y comprender todo esto.
Porque el que sea fiel y diligente hasta el fin de esta gran tribulación
será emblanquecido y dotado con la capacidad de juzgar.
Sí, este recibirá la llave de la casa de David, para atar y desatar,
y se sentará en el trono del juicio y justicia del Cordero en los lugares celestiales.
Sobre estos ni el sepulcro, ni el infierno tendrán ningún dominio,
ni sus iniquidades pasadas tendrán ningún poder, porque el poder del pecado está muerto.

Por lo tanto, hermanos,
sean fieles en la luz cuando lleguen a esta condición. Tengan cuidado de la incredulidad,
y no se apresuren a salir de debajo de la mano refinadora,
no sea que tienten al Señor de su vida y contristen Su manso Espíritu.
Porque de este modo muchos han provocado que Él deje de disciplinarlos,
y por esto sus manchas permanecen.
Estos demuestran que son bastardos y no hijos nacidos de Su reino, poder y gloria,
y en el curso del tiempo sus antiguas iniquidades se apoderan de ellos otra vez.

Porque cualquier cosa del viejo hombre que salga del fuego sin ser consumida,
al no ser matada y sepultada en este bautismo,
será como una gangrena permanente que busca expandirse,
y como un enemigo que espera cada día su oportunidad (en todas
las ocasiones) para levantarse y ahogar la planta pura de inocencia,
y así separarlos de su Amado.
Esto hará nulo todos sus sufrimientos pasados,
y dejará entrar antiguas maldades como un diluvio sobre ustedes,
como le ha sucedido a muchos en este día. Por lo tanto,
sean fieles hasta el fin de toda iniquidad, tanto de la raíz como también de las ramas.
Entonces su justicia se levantará limpia y sin mancha,
y sus antiguos pecados serán enterrados,
y jamás se volverán a levantar--ni para acusar, ni para reinar.
Esta es su victoria sobre la muerte.

Y sepan esto con certeza (independientemente de lo que otros puedan imaginar): que,
aunque la mala semilla es sembrada cuando los hombres duermen,
y se arraiga a través de sus placeres, y brota por medio de su reposo falso y deleite,
aun así,
el fin de ella es amargura y gran tribulación. Pero
la preciosa Semilla es sembrada con lágrimas,
concebida en aflicción, y dada a luz con gemido, noches en vela,
días de luto y con mucha labor en espíritu y aflicción en el alma.
Porque, aunque el mundo ha concebido una fe en el aire,
que no produce nada más que distintos tipos de vientos
que pelean sobre la tierra (sin fundamento,
y sin edificar nada que tienda a la perfección); sin embargo,
esto no debe ser así con ustedes.
Porque la Luz verdadera les ha resplandecido, la cual conduce al fundamento de Dios,
y ustedes han recibido una fe que les da una perspectiva
de esa Piedra que los edificadores no pueden ver.
Y a ustedes se les ha concedido, no solo que crean en Él,
sino también que padezcan por Él,
y por lo tanto deben correr de tal manera que ganen a Cristo,
y luchar de tal manera que lo obtengan a Él--es decir, Su nombre,
Su poder y Su naturaleza.
Por esto sus almas gimen, anhelando poseer y heredar Su poder, Su amor, Su mansedumbre,
Su paciencia en todas las tribulaciones, Su fe en todos los temores,
y anhelando tener el poder de Su gracia y virtud viviendo en ustedes mediante
el cual ustedes estarán enteramente preparados para toda buena obra.

Por lo tanto,
su labor es pelear contra cualquier cosa que evite
que vengan a este fundamento y Piedra Angular.
No peleen sus batallas golpeando el aire,
sino haciendo guerra contra todo engaño y nociones altivas,
y contra todo espíritu que busque poseer sus mentes
con palabras y formas sin el poder de justicia.
La verdadera luz concede la capacidad de ver todo engaño y todo eso que yace
bajo el poder del pecado (que son las sendas sutiles del destructor) y de ver
cómo solo la victoria sobre el pecado y el engaño satisfará sus almas.
Sí, solo la _vida_ y el _poder_ pueden darles paz.
Por lo tanto, la labor de ustedes se encuentra en el interior, y no en palabras vanas,
y eso que golpea la raíz del pecado será su mejor arma.
La carne para nada les aprovecha,
es el Espíritu el que debe darle vida (a través de
las aflicciones) a eso que el reposo falso ha asesinado,
antes de que puedan disfrutar de completa paz.

Porque, aunque las Escrituras hablan de una Semilla que es heredera de todas las cosas,
la cual da Su herencia a todos aquellos en los que Ella es formada (cuyo nombre es Admirable,
Consejero y Dios Fuerte) aun así,
esta Semilla no es dada a luz sin duro trabajo y dolores de parto,
y sin pasar por las angustias de la muerte.
Porque cuando (como Rebeca) ustedes acudan al Señor a consultarle
y encuentren que hay dos tipos de semilla en el vientre,
entonces verán que es necesario que se lleve acabo
una gran obra antes de que puedan llegar al descanso.
Sí, antes de que la Semilla pueda reinar, el hombre fuerte debe ser atado,
y él está armado fuertemente con toda clase de asechanzas para salvarse a sí mismo.
No son las palabras ni los conceptos los que "`echarán fuera a la madre e hijo`"^
footnote:[Génesis 21:10; Gálatas 4:30]
que no heredan la promesa; sin embargo, es necesario que esto se haga,
o todo será en vano.
Porque el que ha nacido de la carne está en esclavitud a las cosas de abajo,
y este nacimiento no puede heredar la inmortalidad,
porque el pecado tiene poder en él. Así que este primer nacimiento debe morir,
para que el Hijo de Justicia se pueda levantar y vivir en ustedes,
y llevar sus vidas a la luz con Él conforme Él aparezca.

Por lo tanto, siendo fieles en la luz que viene del Hijo,
y que condena todos los caminos altivos del primer nacimiento,
serán guiados a los caminos de humildad los cuales
van en contra de su vida en el primer nacimiento.
El Espíritu los guiará a través de desvelos y ayunos,
y grandes tribulaciones en los que el primer nacimiento debe morir de hambre;
porque en la guía del Espíritu (a través del desierto)
no hay nada de lo que la concupiscencia pueda vivir,
tampoco hay maneras de que la sabiduría del hombre se exalte a sí misma,
o busque su tranquilidad y placer.
Por lo tanto, sean fieles a su Guía,
sin importar lo mucho que el primer nacimiento (que debe
ser destruido) se queje y se enfurezca en el camino.

Y con toda diligencia, prosigan a eso que llama a sus mentes errantes a regresar a casa,
y tengan cuidado de que con vigilancia y lucha permanezcan
allí. A medida que sean fieles en esto,
la casa se hará mas grande hasta el punto de convertirse en una
habitación para que sus mentes puras moren en ella y hallen descanso,
después de haber sido llevadas de aquí para allá como en un desierto.
Y al matar (a través de una cuidadosa vigilancia) todo lo que los saca a lo externo,
y al hundirse en una profunda y permanente humildad,
llegarán a sentir la planta de Dios que engendra esta mansedumbre y santidad,
y los manantiales de la virtud viva.
Allí se encontrarán al Señor en Su reino sobre la tierra,
donde a Él le place andar como en un huerto.
Porque en verdad, Su deleite se encuentra en aquellos que esperan sentir Su comunión,
y recibir Su consejo en pureza y tranquilidad.
Y aquí Él los dejará ver cualquier cosa que quebrante Su pacto con ustedes,
o los saque de la vida eterna, y con Su Espíritu los guiará a pelear contra ella.
Y al ser fieles en esta guerra espiritual no dejarán de experimentar una continua victoria,
hasta que todo estorbo en sus mentes sea echado fuera.
Entonces lo celestial se convertirá en su morada de quietud, y ustedes,
en el Espíritu de mansedumbre, se alimentarán de comida celestial,
la cual ningún espíritu rapaz y terrenal podrá devorar o hurtar de sus almas.

Y a medida que obtengan una entrada a esta habitación celestial,
manténganse velando diligentemente, y en la luz permanezcan armados contra el ladrón,
manteniendo fuera cualquier cosa que sea de él, que quiera entrar a sus afectos o deseos,
bajo cualquier pretensión. Porque si entra en sus afectos,
se robará la atención de sus mentes y la quitará de esta planta pura e inocente.
Esto es adulterio, traición y fornicación,
contra lo cual deben contender en el poder de Su amor.

Por lo tanto, con corazón dispuesto echen fuera todos los antiguos ídolos de sus afectos,
lo que sea que tenga algún lugar allí;
porque por haber permitido la entrada de estos ídolos a través de la concupiscencia,
el Hijo de Justicia ha sufrido, y el Inocente ha sido crucificado en el interior.
Y el Hijo de Justicia no se levantará a tomar Su reino,
ni le otorgará entrada a esta habitación santa,
hasta que todo eso en sus afectos que se ha levantado por encima del Justo,
haya sido condenado y echado fuera.
Porque Él debe cumplir toda justicia antes de que
se pueda disfrutar de la plenitud de gozo,
y esta obra es detenida donde sea que se aferren a la injusticia,
y su trono en el corazón no sea condenado, ni echado fuera.
Así es como muchos procuran entrar, pero no pueden,
porque el anatema (que no tiene lugar en el reino de Dios) no es echado fuera.
Porque la justicia no tiene comunión con la iniquidad,
ni el templo de Dios con los ídolos.

Y esto les digo (que es una verdad que he experimentado en este viaje):
si ustedes retienen sus antiguos amantes,
o permiten que algo entre a sus afectos y saque sus
mentes de esta planta pura de justicia y verdad,
de ninguna manera entrarán al reino de los cielos.
Porque este es el camino, y esta planta es la que les otorgará la entrada.
Por lo tanto, peleen contra cualquier cosa que quiera alejarlos de ella,
y así irrumpan con violencia y arrebaten el reino.
Porque solo el que ha sido fiel en el bautismo de Juan (a fin de cumplir toda justicia),
recibirá poder para proseguir hacia dentro del reino.
Y aunque ustedes encontrarán violentos poderes tratando de mantenerlos fuera,
estos deben ser vencidos violentamente con el Cordero a través de la guerra.
Porque el hombre fuerte, habiendo tomado una posesión en el interior,
no es atado y echado fuera con facilidad.
Su iniquidad es espiritual y está en los lugares celestiales, por lo tanto,
es con una virtud celestial que es contraria a él, y de un poder superior,
que ustedes deben pelear para poder alcanzar la victoria.

Así que esfuércense por participar del Espíritu celestial y Su poder,
para que puedan vencer al espíritu terrenal y su poder.
Luchen fervientemente en un espíritu manso por obtener
una medida de fe y paciencia que sea mayor que su tentación,
y ella permanecerá hasta el fin de la tentación,
en una mansedumbre y amor que cubre toda contienda e ira,
y con una longanimidad que matará de hambre todo apuro,
y cualquier cosa que busque su propio reposo falso.
Y, por lo tanto, en todas las cosas,
beban con anhelo de la virtud celestial que viene de arriba,
por la cual llegarán a estar fortalecidos con todo
poder para resistir los asaltos del enemigo,
tanto interna como externamente.
Y tomando la cruz,
aprendan a revestirse de Cristo Jesús--quien es el gran poder de Dios para salvación,
y el manantial de vida y gloria eterna--lo cual se hace
al sumergirse en la experiencia celestial de Su vida,
la cual es contraria a la voluntad del primer nacimiento.
Aquí serán cubiertos con Su sombra desde lo alto,
y podrán buscar al Salvador para que venza todas las cosas de abajo.

Y a medida que entren en la experiencia de estas virtudes,
sosténganlas firmemente hasta que venga Aquel quien es la plenitud;
y cualquiera que sea la medida de fe que tengan,
luchen contra todo eso que busca apartar sus mentes de esta experiencia.
Porque con la medida que ustedes tengan de Él,
deben luchar contra cualquier cosa que sea contraria.
Y conforme se mantengan fielmente en esta medida,
sentirán como cae cada cosa altiva delante de ustedes;
porque eso que limpia la vasija de toda corrupción es su arma,
y eso que brota de la naturaleza pura es su vida.
Así que, contemplando esto a medida que se levante,
y manteniendo sus ojos puestos constantemente en la fe y esperanza de alcanzar Su plenitud,
su obra será una obra de amor, su obediencia será un deleite,
todos sus sufrimientos se volverán fáciles de soportar,
y cualquier pérdida de la gloria anterior será vista
como una gran ganancia para este ojo.
Esta es esa fe que obra por amor y que puede lograr mucho para con Dios,
y cuando es seguida, vence al mundo y liberta de él en todas las cosas.

Por lo tanto, busquen en la luz hundirse en esa Semilla de vida que no es de este mundo.
Vengan a Aquel que no busca lo Suyo propio,
que no encuentra descanso en las cosas de la tierra, que es rechazado por los hombres,
negado por Su propia parentela y abandonado por todos.
Y a medida que vengan a Él también vendrán a ser probados en cuanto a
si están dispuestos a dejar todas estas cosas únicamente por Él,
para que así Él pueda seguir apareciendo en ustedes y cubriéndolos de
Sí Mismo--tanto del menosprecio que recibe de los hombres y de Su oprobio,
como de Su paciente poder para soportarlo todo.
Porque solo Él puede soportar todas las cosas y nunca ser movido, y, por lo tanto,
venciendo en Él,
experimentarán la piedrecita blanca y esa roca que quebranta las naciones,
pero edifica la casa de Dios.

Pero en todo su viaje tengan cuidado de la mente adúltera,
porque ella devora secretamente la preciosa vida.
Tengan cuidado de ese ojo que mira hacia lo externo, y no le den lugar ni por un momento;
porque si ustedes lo permiten bajo la pretensión que sea,
entran en pacto con él en contra de la Semilla santa, y destruyen la mente casta.
Así que ya sea que el anzuelo sea áspero o suave, considérenlo como un enemigo,
porque eso que entre por su consentimiento deberá salir con un sufrimiento doble
al deleite que trajo con él. Pero si ustedes lo rechazan como un enemigo,
resistiéndolo constante y pacientemente, huirá y se irá debilitando en cada asalto,
y ustedes estimarán más a Aquel que les ha dado la victoria, y se deleitarán más en Él.

Por lo tanto,
no consideren como algo extraño (mientras haya alguna levadura vieja en el interior,
que aún no haya sido limpiada) que mientras más se
acerquen a Dios en humilde y sufrida mansedumbre,
más profundamente se hunden en tribulación,
y sus sufrimientos se incrementan en la parte carnal,
porque este es el camino del Hijo hacia la perfección,
y son maravillosas las obras del Padre que se aprenden en lo profundo.
Porque por la mano de Dios sobre ustedes (siendo
fieles en los padecimientos hasta el fin del pecado),
llegarán a ver la raíz y renuevo de toda iniquidad, cómo llegó a establecerse,
cómo el Cordero llegó a ser inmolado,
y quién realmente es Él. Y ustedes verán y sentirán el fundamento de Dios
sobre el cual los santos fueron levantados y edificados en el Espíritu,
y cómo toda la paja, el heno, y la hojarasca llegan a ser limpiados.
Sí, Su aventador está en Su mano,
y las palabras de Su boca son un fuego que consume toda esa naturaleza de paja,
y es Él el que refina el oro y vivifica el alma, y separa lo puro de lo impuro.
Y mientras más se acerquen a Dios, más Él se acercará a ustedes en justicia,
juicio y verdad, para poner fin al pecado y traer la justicia perdurable.
Porque todos los que comparecen en Su templo y se convierten en Su herencia,
deben pasar por el fuego consumidor y sentir el jabón de lavadores (el fin de
todos los sufrimientos) y experimentar al Señor otorgándoles una entrada al gozo,
pureza y paz eternos, y al eterno peso de gloria,
hacia el cual no hay ningún otro camino más que a través de la aflicción.

Pero a medida que se hundan en el fundamento de Dios, velen con todo temor y diligencia,
para que nada los exalte, o eleve su mente, su opinión de sí mismos o su comprensión,
por encima de ese fundamento sobre el cual están siendo edificados.
Porque muchas tentaciones a apresurarse se presentarán con miedos y desconfianza,
para sacarlos del fundamento de vida.
Pero si ustedes se mantienen humildes, firmes y fieles a la medida de vida,
serán levantados y sacados juntamente con ella fuera del pozo,
y serán puestos sobre la tierra.
Porque el fundamento de vida ha sido puesto en ustedes con
el fin de que sean edificados en Espíritu sobre él,
y sean hechos conforme a la Piedra Angular--no de
la misma naturaleza de eso que está siendo derribado,
sino como un nuevo hombre que se está levantando.
Pero ninguno conoce la manera en la que se levanta,
salvo en la medida que permanece en el fundamento
y mantiene su mente puesta en la Piedra Angular;
pero si ustedes hacen esto diligentemente,
conocerán el cimiento estable de la ciudad santa,
no echando otra vez el fundamento del arrepentimiento, de la fe en Dios,
de la doctrina de bautismos, de la resurrección de los muertos y del juicio eterno.

Y a medida que sean edificados sobre el fundamento de vida y poder,
serán llevados fuera de los dominios de la muerte,
y aprenderán cuál es el lugar en el que la muerte tiene su poder,
y por medio de qué reina, y cómo lleva cautiva la Semilla,
y cómo sus cadenas son quebradas,
y cómo aquel que tiene el poder de la muerte es vencido y encadenado.
De modo que llegarán a ver lo que ata y lo que desata, lo que mata y da vida.
Y experimentarán la vida de la ley, la vida de los profetas, la vida de los apóstoles,
teniendo comunión con ellos en el mismo Espíritu,
y heredando la misma promesa a medida que acudan a la Palabra de Dios (que permanece
de generación en generación) para experimentar el cumplimiento de dicha promesa.

En verdad,
este es el fin de toda la aflicción del alma que
sienten los hombres y mujeres justos aquí abajo,
quienes regresan en paz a Aquel que los hizo, revestidos de su habitación celestial.
Por este premio ellos estiman todas las cosas de aquí abajo como pérdida,
desechando sus placeres terrenales y haciendo morir todo afecto hacia estas cosas,
caminando como extraños a ellas mientras están aquí,
sabiendo que el amor por las cosas terrenales es un enemigo de su crecimiento espiritual,
y que a diario el espíritu terrenal y adúltero busca devorar
la preciosa vida y mantener el alma en las cosas de abajo.
Sí, este espíritu presenta diariamente sus deleites carnales,
y muestra las sendas del destructor con placeres para el ojo carnal.
Cualquiera que se una a él no puede ascender a la herencia celestial,
sino más bien desciende diariamente junto con el mundo oscuro,
que se ha degenerado de la vida de Dios y se ha apartado de ella incluso desde la matriz.
Estos nunca son capaces de alcanzar el conocimiento de Dios,
ni llamar a Dios Padre en verdad y en justicia.
Porque ellos son voluntariamente ignorantes de lo siguiente: que,
así como ningún hombre ha subido al cielo sino Aquel que descendió del cielo,
así tampoco nadie subirá jamás, sino aquel que no haya nacido de la semilla corruptible,
sino de la Palabra de Dios que vive y permanece para siempre.

Pero no es así con ustedes,
que sienten la influencia celestial atrayendo sus
mentes fuera de todos los deleites terrenales,
y que experimentan cómo la vida celestial vence sus afectos terrenales,
de modo que ustedes mueren diariamente al mundo.
Y sienten que algo está cobrando vida en ustedes
que no puede alimentarse de placeres terrenales,
sino que tiene hambre de justicia,
ve una hermosura en la santidad y diariamente siente sed de la virtud celestial.
Ustedes que han probado estas cosas, húndanse ahora en la Fuente de ellas,
en la Semilla que todavía yace en sufrimiento; sientan hambre con Ella,
sufran con Ella y únanse a Ella en todo Su consejo,
para que ustedes puedan ser levantados con Ella.
Porque esto está sobre el fundamento de Dios, y al acercarse a Él como piedra viva,
ustedes serán edificados en el mismo fundamento, siendo el mismo Espíritu su cabeza,
por cuyo levantamiento todos los velos serán desechos--el velo de la muerte,
el velo de la ley y el velo de los profetas.
Así el Señor desatará los sellos de todo el misterio de la piedad,
y el Cordero inmolado abrirá el camino al cielo,
el cual les dará poder desde el medio del trono de Dios si ustedes
se unen a Él tanto en Sus sufrimientos como en Sus levantamientos.
Es Él el que crea un camino entre el cielo y la tierra,
y lo mantiene abierto en todos los que le prestan atención
y conservan sus vasijas en santidad y temor para con Dios,
de modo que nada impida que sus oraciones lleguen al trono de Dios,
ni que el rocío y bendición del cielo caiga sobre la Semilla.
Aquí experimentarán los cielos abiertos,
y un camino de gracia y salvación para que el viajero ande
en él. Y si ustedes ejercitan toda su mente en este camino,
no errarán,
y nada podrá impedir que reciban dones del Padre--siempre y cuando nada (de una
naturaleza contraria) evite que Su propia planta se levante a Él con alabanzas,
y que ustedes se levanten con ella.

Así que no permitan que nada los separe de su comunión
con Dios en la medida que ya han recibido;
sino que dejen que los suspiros de sus almas y de sus corazones se dirijan
continuamente a Él. De este modo no solo recibirán de Él,
sino que se convertirán en fieles aumentadores de eso que tienen por la bendición
que está en el pacto hecho con todos los que lo aman y moran en la luz.
Porque donde la ciudadanía en verdad está en el cielo, la tierra se vuelve fructífera.

Por lo tanto, con toda diligencia procuren que nada atrape sus afectos aquí abajo,
o evite que sus mentes celestiales se sigan levantando.
Porque el espíritu de esclavitud espera en ustedes continuamente
la oportunidad de oponerse a la vida celestial,
y levantarse sobre ella en sus mentes,
y él obtiene poder cuando dejan entrar alguna cosa carnal a sus corazones,
la cual los oprime y se convierte en un peso que los asedia en su camino,
y que detiene el camino de la vida.
Porque eso que viene desde el cielo debe encontrar un paso libre a través de
una vasija limpia para regar la semilla celestial--una vasija libre de afanes,
enredos y placeres terrenales, que tiene acceso a los cielos desde la tierra.
Porque eso que viene de arriba es lo que le muestra al hombre su camino y sus necesidades,
y lo que le enseña a orar de tal modo que reciba una respuesta,
y únicamente mediante esto Dios hace todas Sus obras en ustedes y por ustedes.
Pero si ustedes se unen a otro, y le dan la fuerza de su corazón y mente a Su enemigo,
entonces la obra de Dios cesa, porque el camino de la vida es detenido.
Porque en el caso del adulterio, la codicia, la idolatría, el descuido,
la pereza o cualquier cosa de esa naturaleza maligna a la que los hombres se pueden unir,
es su consentimiento lo que les da la fuerza para detener el camino de la vida,
y esto se convierte en su condenación, la cual se puede ver claramente en la luz,
porque así es como la muerte obtuvo poder al principio.

Porque la serpiente no puede ser cabeza en el hombre excepto donde se le escucha,
se le deja entrar o se le obedece.
Al ser resistida ella huye,
pero al ser dejada entrar se sienta en el lugar celestial con mucha astucia y poder,
y no es expulsada, ni reconocida con facilidad.
Así que cuando sientan que su camino se ha entenebrecido,
o que sus afectos por las cosas celestiales se empiezan a enfriar,
entonces con mucho cuidado y con toda diligencia
escudriñen sus corazones con la luz pura;
porque su enemigo ha conseguido alguna entrada.
Al esperar fiel y pacientemente en la luz, llegarán a ver su adversario,
y a través del poder de la cruz matarán esa vida carnal,
y echarán fuera el vientre en que fue concebida--porque el hijo de la carne no
habitará en la casa con Aquel que es el heredero de la herencia celestial,
sino que es un enemigo de Su venida.
Este es "`quien al presente lo detiene, hasta que él a su vez sea quitado de en medio,`"^
footnote:[2 Tesalonicenses 2:7]
el cual, mientras está en medio,
embota los afectos y nubla la mente celestial de tal modo que ella no puede ascender.

Por lo tanto,
retengan firmemente la unción que han recibido del Santo hasta que Él venga,
y con ella manténganse armados contra cualquier cosa que
quiera entrar con la intención de llevarlos hacia afuera,
a cualquier observación externa.
Guarden con toda diligencia eso que han recibido de Él en Espíritu,
de lo cual el adversario procura mucho alejarlos,
para evitar el incremento del talento que el Señor les ha dado.
En su medida mantengan su vigilancia diariamente,
y hagan guerra usando lo que tienen de vida y poder, y no lo que no tienen.
De este modo serán considerados fieles administradores,
y serán aceptados conforme lo que tienen, y no conforme lo que no tienen.
Porque los hombres del mundo yacen en tinieblas, y por lo tanto esperan lo que no conocen.
Ellos no tienen fundamento para su fe, ni poder para preparar el camino para Su venida,
sino solo palabras que han oído de otros,
o que son producto de sus propias ideas carnales.
Estos no están en el Verdadero; pero ustedes sí están en el Verdadero,
y han recibido Su luz,
y andan en ella de tal modo que pueden reconocer Su manifestación en todas las cosas.
Y ustedes conocen al mensajero de Su pacto, "`el cual prepara Su camino delante de Él,`"^
footnote:[Malaquías 3:1]
volviendo sus corazones de todo mal camino, y sacándolos de las sendas del destructor.
Así serán fructíferos en la tierra,
y Él los recibirá a Sí Mismo cuando "`venga a herir la tierra con maldición`"^
footnote:[Malaquías 4:6]--la tierra que produce espinos y abrojos,
cuya semilla no es de Él (de Su raíz y renuevo),
sino que es engendrada en la mente adúltera.

Porque la mente alimentándose externamente de cualquier conocimiento,
forma u observación religiosa (excepto de aquello a lo que la vida guía
en Espíritu y poder) es el fundamento del misterio de la iniquidad,
y el pecado de adivinación, que busca cazar la vida preciosa del Niño Santo,
tratando de apartar sus fuerzas y afectos de Él y ponerlos en la ramera,
para que así Él sea sepultado y crucificado diariamente en sus corazones y afectos.
Porque cada vez que sus deseos vayan en pos de otro
(aunque se cubran con un bonito pretexto),
el espíritu mundano ganará fuerza diariamente,
como lo sentirán todos los que son vigilantes y diligentes en esta guerra espiritual.
Entonces su amor se enfriará, y la maldad se multiplicará con un poder irresistible,
sin importar lo que piensen en contra,
o crean sin esa fe que obra por amor a la vida de la verdad.

Por lo tanto, que su lucha sea por el poder y vida de Dios, y aliméntense de esto,
para que sus vidas permanezcan para siempre,
y sus fuerzas y virtud sean renovadas diariamente.
Ustedes han leído de aquellos que tenían la "`forma
del conocimiento`" y la "`forma de la verdad,`"^
footnote:[Romanos 2:20 RV 1602 Purificada]
pero estando fuera de la vida de la verdad, detenían la verdad en injusticia.^
footnote:[Romanos 1:18 RV 1602 Purificada]
Aunque conocían a Dios, no lo glorificaron como a Dios en la vida,
y por lo tanto fueron entregados a sus vanas imaginaciones,
y no pudieron retener la vida por medio de su conocimiento,
sino que cambiaron la verdad de Dios por la mentira.
Así que vemos que su conocimiento no podía evitar que se llenaran de injusticia,
porque ellos no permanecieron en la vida y poder de la justicia,
ni recibieron la verdad en esa fe que ama vivir la vida de justicia.

Por lo tanto, que su comida sea _la vida_ de eso que conocen,
y gócense en _el poder_ de la obediencia, pero no se gocen en eso que conocen,
pero no pueden vivir.
Porque la vida es el pan de sus almas,
la cual crucifica la carne y confunde todo lo que corre delante de la cruz.
Por ende, que su labor y diligencia sea en eso que prosigue hacia la vida celestial,
y busca conformarse a Cristo en obediencia a eso que ustedes creen.
No escuchen esa mente que quiere salvar su vida, y alimentarlos, así como son;
más bien escuchen (en amor) eso que los separa de la vida del yo
y los transforma a la imagen celestial de Aquel a quien esperan.^
footnote:[Filipenses 3:20]
Sí, reciban Sus mandamientos en esa parte que ama ser como Él,
y entonces su fe obrará por amor,
y Sus mandamientos les serán un gozo a través de este amor.
Esta fe produce obediencia, vida y buena disposición;
echa fuera lo viejo e introduce lo nuevo.
Y a través de una esperanza puesta en Aquel que aman (y de la obediencia de la fe),
obtendrán una entrada con la vida al reino santo,
y llegarán a ser revestidos de la gloria inmortal, la cual es vista en la luz,
y obtenida en la vida.
Y es por medio de la Palabra de fe que se hace una separación,
y se experimenta el despojo del primer nacimiento,
cuya vida está fuera del velo y entregada a la muerte.
Pero la otra vida obtiene una entrada a través de Su sangre, y a través de Su carne.
Este es el camino vivo, o camino de vida,
que es nuevo para todos los que han estado buscando
la puerta en las antiguas ordenanzas y tradiciones,
y en observaciones externas,
alimentando sus mentes con pensamientos o palabras
sobre lo que otros han experimentado años atrás,
o sobre lo que podría suceder en los tiempos futuros.
Estos se fatigan a sí mismos tratando de encontrar la puerta
sin la Luz de la vida (que no es de este mundo),
pero están fuera de esa vida que tiene la promesa del Padre,
y el poder para acceder a Él,
y todavía permanecen en los deseos de la carne y en esa
naturaleza que se ama a sí misma y hace obras impías.

Pero a medida que ustedes tengan cuidado de alimentarse únicamente de la planta de vida,
conocerán la obra del Padre en Su viña, y verán quién es el obrero fiel,
y cuál debe ser su labor.
Y también verán al siervo negligente, y qué produce su labor,
y la razón por la que el campo del siervo perezoso está cubierto de malos frutos,
y por la que su viña no lleva fruto a perfección. Porque
encontrarán muchas plantas aparte del árbol de vida,
todas las cuales buscan ser alimentadas y fortalecidas en la mente y en los afectos.
Sí, encontrarán muchos árboles altos y fuertes, que tienen profundas raíces,
y que se esparcen y producen abundantemente según sus diferentes géneros.
Todos estos se presentan a sí mismos al ojo de la mente, para ser alimentados desde allí,
que es como ir a buscar comida de lejos, sin la cual ellos no pueden vivir mucho tiempo,
porque desfallecerían y caerían. Porque estos árboles morirán a medida que los
afectos y la mente sean quitados de esos objetos que los alimentan.

Por lo tanto,
la labor de aquel que es fiel es entregar todos estos árboles al hacha y al fuego,
y no permitir que tengan algún lugar en la mente,
sin importar cuán fuertemente tienten o esparzan sus raíces para mantenerse vivos.
Porque es a través de la muerte de ellos que la viña del Señor puede crecer sin disturbios,
en afectos limpios y en la mente santa, y en un corazón honesto y puro,
que es la buena tierra.
Aquí la planta pura producirá su incremento en todas las cosas,
donde no es estorbada por eso que es contrario a ella.
Pero el siervo perezoso condena el fruto, pero no es diligente en cavar y sacar la raíz,
y por eso se mantiene creciendo cada día hasta que la buena tierra es cubierta.
Estos son aquellos que saben qué hacer, pero nunca son capaces de permanecer en ello,
porque su vida ha sido perdida en medio de este desierto,
y ha sido ahogada con plantas silvestres.

Pero ustedes, siendo diligentes en su vigilancia,
verán que hay una causa de todos sus problemas y confusión;
porque hallarán muchas plantas de diversos tipos en el corazón
(porque el mundo esta en el corazón del hombre,
y el corazón del hombre está en el mundo,
habiendo sido echado fuera de la presencia de Dios).
Ahora cada planta tiene su vida particular, y cada vida tiene su alimento particular,
todo lo cual ustedes podrán sentir en la luz por sus diferentes
tentaciones a llevar sus mentes a lo externo.
Y aunque tengan diferentes
apetitos y vivan de distintos objetos,
ustedes encontrarán que,
si en algún momento la más pequeña de ellas es alimentada
por un consentimiento de su mente,
invadirá la viña, y en el proceso del tiempo, por su crecimiento en sus afectos,
la enterrará. Por lo tanto, todos deben humillarse,
para que solo la verdad pueda levantarse en sus afectos,
y la Palabra de vida tenga lugar en sus corazones,
la cual es demasiado pura como para morar en la mente adúltera.
Porque Su ojo no puede contemplar la iniquidad,
y no tiene ningún acuerdo con las tinieblas,
ni comunión donde algún ídolo permanezca en Su templo.

Así que esfuércense en esa fe que vence al mundo y que no
permite que nada del mundo tome lugar en sus mentes.
Y con el Espíritu de vida, velen y luchen contra cada deseo,
y maten cada afecto que quiere salir a buscar su alimento;
porque cuando los afectos salen, traicionan al Inocente,
y los placeres de la carne son como una gangrena que carcome la vida santa y justa.
Pero por fe, el Justo vivirá en ustedes,
y mediante la fidelidad Él juzgará y hará guerra contra todos Sus enemigos.

Y en esta obra, tengan cuidado con lo que siguen.
No sigan nada apresuradamente, sino que prueben todas las cosas con fuego.
Eso que no soportará la tentación ni llevará la cruz es la naturaleza de la adúltera,
la cual mirará hacia afuera en todas las direcciones en busca de un reposo falso;
y la serpiente le presentará muchos caminos atractivos bajo pretextos creíbles,
que serán escuchados rápidamente por esa naturaleza
que desea vivir en reposo sin la cruz.
Pero si ustedes escuchan estas cosas,
traicionarán la obra de la vida (que está siendo
dada a luz con fuertes dolores de parto y esfuerzo),
porque donde el reposo en la carne y la ociosidad son consentidos,
la vida es asesinada en el nacimiento,
y es al vivir en esta tranquilidad falsa y en placer,
que la vida ha sido asesinada y mantenida abajo desde el principio del mundo.
Sí, por la búsqueda de placeres la Semilla escogida se ha perdido en el hombre,
y ha sido ahogada por la semilla de iniquidad que Dios aborrece,
la cual lucha según la carne y desea conforme a la carne con el fin de fortalecerse
y levantarse por encima de la Semilla santa y espiritual.

Pero teniendo cuidado de hacer firme para ustedes eso que los llama,
y siendo obedientes a ello,
esto los llevará por el poder de la cruz por debajo de todo
lo que se ha levantado por encima de la vida pura,
hasta que sientan la elección,
y sea hecha una separación entre eso que Dios escoge y eso que Dios condena.
De este modo llegarán a saber con qué deben unirse, y de qué deben apartarse,
a fin de que obren juntamente con Él,
y no contra Él. Porque el sutil enemigo hará que los hombres
obren contra su propia salvación hasta que,
por la luz, se haga una separación, y entonces,
al unirse en fe y obediencia a las operaciones de Dios,
la Semilla escogida se levante y se experimente.

Y una vez que sientan que la vida inocente comienza a moverse en ustedes bajo su opresión,
entonces no descansen hasta que el hombre fuerte sea sometido.
Porque la Semilla de la promesa debe ser redimida de debajo del poder
del enemigo con grandes plagas sobre esa naturaleza y voluntad.
Y, como Faraón, si se le da algún descanso,
no dejará que Israel salga de debajo de su poder.
Pero si ustedes se mantienen aferrados al Espíritu con una profunda humildad,
Él les dejará ver qué plagas deben ser derramadas sobre el enemigo hasta que sea derribado,
de modo que un pequeño niño pueda dominarlo y reinar sobre él,
y aquel que estaba oprimido por la bestia pueda subyugarla.
Porque esa naturaleza obtuvo fuerza y se volvió la cabeza
en ustedes por medio del cumplimiento de sus deseos,
y por lo tanto debe ser sometida por medio de hacer morir de hambre estos deseos.
Pero aquellos que son infieles a la Semilla de Dios en esta obra venden su primogenitura,
traicionan su propia redención y son hallados como obreros
fraudulentos contra Dios y contra sus propias almas.

Por lo tanto, no corran con eso que es apresurado,
sino que descansen en eso que es manso, humilde y paciente,
y que está dispuesto a esperar el tiempo del Padre,
y procura obtener victoria únicamente por medio de la obediencia de la fe,
y no en la voluntad que quiere tener su propio camino.
Porque hay una naturaleza que corre en busca de ayuda,
y que anda vagando en lo externo buscando satisfacción;
pero Dios desea matarla de hambre.
Esta naturaleza tratará de dirigir la mente, y si es seguida,
buscará en lo exterior y murmurará cuando no reciba satisfacción.
Así que debe sufrir hambre y sentir la ira del Cordero y todas
las plagas sobre su cabeza sin importar la dirección que tome,
hasta que se humille y se ponga por debajo,
lo cual no hará hasta que sea debilitada con hambre y fatigada sobre los montes de caza.
Pero entonces el león se acostará con el cordero, y el pequeño niño llevará al descanso,
y ninguna fiera le quitará su comida.

Pero en esta obra,
tengan cuidado de no ser engañados por ese espíritu sutil
que corre hacia un lado o hacia el otro--es decir,
ya sea hacia la impaciencia y el apuro,
(que es la primera tentación después de ser convencidos de la verdad), o si no,
cuando ustedes no han logrado su objetivo de esta manera,
hacia la pereza y el descuido ocioso--porque ambas cosas mantienen
vivo y fuerte al espíritu equivocado por encima de la Semilla.
Pero hay un camino estrecho entre estos dos errores, en el que la Semilla se levanta,
y este camino es una mansedumbre diligente,
vigilante y paciente que espera sentir el movimiento de la Semilla piadosa de vida,
y la sigue con fe y obediencia en todas las cosas sin apuro ni metas,
y que no va más allá de lo que es abierto delante de ustedes en la vida de la obediencia.
Ustedes deben permanecer en diligencia,
no sea que algo se deslice de sus mentes que haya sido dado por gracia,
ya sea para que lo practiquen o lo aprendan;
porque solo la mente diligente retiene el tesoro verdadero y vivo,
pero el perezoso y desobediente es como un vaso roto.

Así que sean sabios en la luz, y prueben su libertad de esa naturaleza que es altiva,
furiosa y apresurada, y que se ha levantado por encima de la mansedumbre;
porque en esto consiste toda su redención:
en experimentar que ustedes ya no son siervos de esa naturaleza.
Porque esta es la naturaleza que busca con codicia las cosas de este mundo,
y siente miedo y desconfianza cuando no tiene en su vista y posesión la cosa que desea.
Y si es convencida de una herencia en el cielo,
buscará eso también con mucho apuro por medio de su vista, pero no por fe,
paciencia y obediencia.
Y cuando es incapaz de traer la herencia celestial ante su propia vista,
según su propia manera y tiempo, entonces está lista para desmayar y desconfiar,
porque nunca se permitirá llegar a una condición en la que esté despojada
de todas las cosas en esperanza de una herencia que no haya visto.
Así aquellos que están en esta naturaleza permanecen en esclavitud,
y no son herederos de la promesa.
Pero los justos viven por fe, y su nacimiento está libre de este mundo,
y ellos han sido redimidos de una naturaleza e introducidos en la guía de la otra,
la cual los llevará a heredar la posesión adquirida.

Así que prueben su libertad en todas las cosas, para que no se gloríen en vano,
sino en la libertad de los hijos.
No digan que "`todas las cosas son lícitas, todas las cosas son puras,`" etc.,
y así sentarse y decir que ya están redimidos y tienen derecho a todo.
En lugar de esto, primero pasen todas las cosas por el fuego, una tras otra,
tal como la luz los guíe,
y de acuerdo con sus medidas verdaderas vean si todavía están dominados por alguna.
Cuando hayan probado esto con todas las cosas, y en verdad se hayan encontrado libres,
entonces podrán decir: "`Todas las cosas me son lícitas,`"^
footnote:[1 Corintios 6:12; 1 Corintios 10:23]
y también sabrán cuáles son beneficiosas,
y cuáles realmente los edifican a ustedes y a otros,
y reinarán sobre el resto de ellas si ser esclavos a ellas.
Esta es la libertad de los hijos de la nueva creación,
los cuales han nacido de nuevo y no están en esclavitud,
y tienen una libertad gloriosa sobre todas las cosas.
Estos son los puros, para quienes todas las cosas son puras,
porque ellos han examinado todo con eso que es puro, y retienen únicamente lo bueno,
y están libres del resto.

Y siempre tengan cuidado (independientemente de cuál sea la medida de libertad
que ustedes obtengan a través de los sufrimientos y la paciencia de Cristo en
Espíritu) de no apartarse de esta libertad para complacer la carne,
sino que reténganla firmemente como la posesión eterna que ha sido adquirida para ustedes.
Sí, eso que fue comprado por un gran precio no lo dejen ir con ligereza;
más bien recuerden a Israel, quienes fueron redimidos de Egipto con muchas aflicciones,
muchas señales y sufrimientos, pero pronto se levantó algo en su impaciencia que dijo:
"`Volvámonos a Egipto,`"^
footnote:[Números 14:4]
que de todas las cosas fue lo que más entristeció a Dios.
Esto mismo ustedes encontrarán listo para levantarse en sus corazones
en cada tribulación y cada vez que sientan carencia,
como sucedió con ellos.
Por lo tanto, permanezcan firmes en eso que ustedes han probado como verdadera libertad,
y de ninguna manera miren atrás ni deseen nada de lo que está quedando atrás,
permitiendo que esto los venza nuevamente.
¡Acuérdense de la mujer de Lot!
La ira de Dios siempre estará sobre esa mente que mira atrás
hacia las cosas viejas que fueron juzgadas en la luz,
y de las que la vida los sacó. Así que manténganse determinados
en sus mentes a no seguir nada nuevo ni viejo,
sino únicamente eso a lo que el Espíritu Santo los guíe;
porque la obra es una obra que ustedes no conocen,
y el camino es un camino que ustedes no conocen,
salvo en la medida que estos son aprendidos en la obediencia.
Porque la obra de Dios no es vista en la primera naturaleza,
sino solo a medida que el alma es purificada y limpiada a través de la purificación
de la vieja levadura terrenal que ha oscurecido el templo de Dios.

Por lo tanto,
con toda diligencia presten atención al movimiento y a la guía del Espíritu,
contra qué los mueve y a qué los guía. Porque ahora Dios hará todas las cosas nuevas:
una nueva creación, unos nuevos cielos y una nueva tierra, un nuevo corazón y mente,
una nueva ley, y un nuevo hombre que camine alegremente en ella con Su Creador,
a medida que las antiguas cadenas sean quebradas por la guía del Espíritu,
a fin de que sirvan bajo el régimen nuevo del Espíritu.
Y conforme presten atención a la guía pura del Espíritu,
y la sigan y obedezcan con un corazón dispuesto,
llegarán a conocer a su Creador en los días de su juventud,
y a entender cómo Él constituyó el universo por la Palabra de Su santidad,
y cómo es su Padre, y cómo Él los engendra nuevamente en el gozo celestial,
aunque ustedes se hayan apartado de Él e ido a la tierra con sus corazones y afectos,
y seguirán alejándose más de Dios si siguen mirando a la tierra.
Porque el hombre nunca podrá regresar a Dios a menos
de que muera y sea transformado por el Espíritu,
para que así la nueva creación sea aceptada por Dios--el nuevo corazón, mente y espíritu,
que son renovados conforme a la imagen de Dios, por el Espíritu que los creó.

Pero esta obra será un misterio para sus entendimientos a menos que sus
mentes salgan completamente de lo viejo y entren en lo nuevo.
Porque la ira se levantará, y la confusión abundará en la mente doble,
donde el ojo no se mantiene bueno, mirando únicamente al Espíritu,
sino que mira atrás a eso que está perdido, que está muriendo y que ha sido condenado.
Ahí no encontrarán nada más que humo, oscuridad, tormento y tentaciones,
que los seducen a regresar a lo viejo.
Pero si su ojo se mantiene bueno, entonces todo el cuerpo estará lleno de luz,
y la verdadera fe se levantará para permanecer hasta el fin del mundo,
mirando al autor y al consumador de la obra de la regeneración. Y manteniéndose
con la mirada puesta únicamente en Dios en este camino,
aunque el mundo pase con truenos, terremotos y grande estruendo, aun así,
no temerán ni desmayarán, permaneciendo en el espíritu manso, paciente y sufrido,
y en la guía de ese Espíritu que soporta todas las cosas para ganar a Cristo.
Y saliendo así de Babilonia, no caerán junto con ella,
ni serán oscurecidos con el humo de sus tormentos y plagas,
como lo serán todos los que habitan en ella;
sino que la mente pura se regocijará sobre ella en medio de todo.
