== Capítulo VI. Amor a los Perdidos / Y una Mano extendida a los Desamparados Para Guiarlos a salir de la Oscuridad

[.heading-continuation-blurb]
Donde se tratan claramente varios asuntos particulares,
conforme han sido aprendidos de Cristo;
y que son los que más necesitan conocer todos los que profesan la piedad;
expuestos principalmente para dirigir a los simples al camino vivo de la Verdad,
como es en Jesucristo el Justo,
para que en él puedan llegar a la vida y poder de eso que el mundo solo tiene en palabras;
lo cual, al ser recibido, satisface al alma cansada,
y hace que la criatura sea agradable a su Hacedor.

[.heading-continuation-blurb]
Hemos hallado al que ama nuestra alma; y mayor es el que está en nosotros,
que el que está en el mundo.

=== El Que Lea Entienda

Amigos, las siguientes cosas que he declarado, no son de hombre,
ni las he recibido de hombre, sino por revelación de Jesucristo,
la cual es contraria a la sabiduría y a la voluntad del hombre.
Ni tampoco las he escrito para que sean recibidas
por la sabiduría y por la voluntad del hombre,
porque la sabiduría del hombre natural no recibe las cosas del Espíritu de Dios,
y devoraría con avidez lo que nace de este.
Así que yo no apelo a esa sabiduría, y en muy poco tengo el ser juzgado por ella.
Pero si alguno conoce el don de Dios,
y una medida de ese Espíritu que abre el seno del
Padre y revela Sus secretos a los niños,
la medida más pequeña de esto (si no es nublada con imaginaciones) saboreará estas cosas,
y para estos podrán ser de provecho.
Así que a la luz de Cristo en todos (que no cambia,
y que es una tanto en el hombre como en la mujer)
les presento esto para que sea juzgado y discernido.
Porque únicamente en la luz,
tanto estas cosas como todas las otras que proceden de la Raíz,
harán la obra de reunir a todos en ese único Nombre y Semilla
en la que son benditas todas las naciones de la tierra.
Sí,
es por la luz de Cristo que los hombres son reunidos
en la única Palabra de fe y poder de vida,
para creer y hablar las mismas cosas en una conducta piadosa,
lo cual lleva al fin de las disensiones, herejías y errores, sectas y divisiones,
y a ser bautizados en el único nombre,
donde la plenitud de Dios es bendita para siempre.

Así que quienquiera que seas tú que leas las siguientes cosas,
y encuentres algo en ellas que en este momento no puedas recibir;
no te apresures a juzgar lo que todavía no conoces,
ni tires coces contra eso que parece contrario a tu voluntad,
no sea que alejes de ti (en tu propia voluntad) eso
que quizás no puedas acercar a ti otra vez,
y no sea que el día de tu visitación se acabe sin que te des cuenta,
y en el día del juicio te veas obligado a decir: "`¡Cómo aborrecí el consejo,
y resistí el día de curación!`"

Y entiende esto: que ninguna profecía de la antigüedad fue traída por voluntad humana,
ni podía ser recibida por voluntad de hombre;
sino que siempre fue resistida por aquellos que caminaban en sus propias voluntades,
y lo mismo sucederá con estas cosas, a menos que las leas con el ojo que nunca cambia.
Y si tu sientes este ojo en ti,
y te mantienes viendo únicamente a través de él en el Espíritu manso,
sin levantarte por encima de tu medida,
sentirás como el don de Dios en ti corresponde a las cosas de Dios,
como en el espejo el rostro corresponde al rostro.
Y también encontrarás que concuerdan con la vida de las Escrituras,
aunque por el momento algunas cosas puedan parecer oscuras;
porque mi servicio está dedicado a esa Semilla que no es de este mundo,
la cual saborea las cosas espiritualmente y no juzga según la experiencia externa.

=== Con Respecto a la Caída del Hombre

En el principio Dios hizo todas las cosas buenas.
El hombre también fue creado bueno, a la imagen de Dios,
quien puso en él Su propia sabiduría y poder,
por los cuales estaba dotado complemente de dominio,
poder y autoridad sobre las obras de las manos de Dios,
entendiendo la naturaleza y uso de cada cosa creada debido a eso que Dios, de Sí mismo,
había puesto en él. En este estado, Adán era un hijo de Dios, cuya semilla estaba en él.

Dios puso también el árbol de vida en medio del huerto,
y el árbol del conocimiento del bien y del mal, y ambos eran buenos en su lugar,
pero el árbol del conocimiento no era bueno para comer.
Por lo tanto, Aquel que lo había hecho les advirtió que no comieran de él,
declarándolo como algo por lo cual experimentarían la muerte,
así como en el otro árbol estaba la vida.
Aquí estaba la bendición y la maldición, la vida y la muerte,
la obediencia y la desobediencia,
la elección y la reprobación. Todo esto era bueno en su lugar,
mientras el hombre permanecía en su lugar, guiado por Aquel que lo puso en lo bueno,
y le advirtió sobre el conocimiento, y le dio poder contra él. Sí,
él estaba a salvo mientras se mantenía en esa voluntad
que había puesto todas estas cosas en su lugar,
cuya voluntad era libre para servir a Dios, y estaba libre del pecado;
y aquí la voluntad de Dios y la voluntad del hombre eran una,
y así ellos estaban en unidad con toda la creación.

Pero cuando el hombre miró hacia afuera de su dominio (al
lugar donde gobernaba uno que no permaneció en la verdad),
entonces la desobediencia fue recibida en su interior,
y él se alimentó de eso que era contrario a la voluntad de Dios,
y de este modo se unió a eso que era contrario, donde se encuentra la debilidad,
la muerte,
la oscuridad y la ceguera con respecto a las cosas de Dios y con respecto a lo que él
había recibido de Él. Entonces el hombre comenzó a volverse sutil en su propio corazón,
y sabio para hacer el mal.
Él perdió la voluntad que era libre para esperar en Dios esa sabiduría
y consejo a través de los cuales era conducido por Él;
y así cayó de la rectitud e inocencia, y de la sabiduría pura y poder espiritual,
que Dios había puesto en su corazón,
a sus propias metas e invenciones que él había escogido en la voluntad contraria.
Así, entrando en la cosa prohibida, se hizo maldición,
perdió su medida de la gracia de Dios,
perdió el honor y la semejanza de Dios en la que había estado sobre toda la creación,
y se hizo necio en su entendimiento; y en cuanto a las cosas de Dios,
se volvió como las bestias que perecen.
Porque él en verdad perdió la Semilla en la que consiste la elección, la sabiduría,
la autoridad y toda felicidad (presente y eterna),
y entonces comenzó a ser
guiado por otra semilla que Dios había echado de Sí Mismo,
y que había permitido que se levantara para deshonra.

Fue en este momento que el hombre perdió su dominio sobre el diablo,
al dejarlo entrar a su corazón;
de otra manera solo habría tenido poder para ofrecer y tentar.
Pero ahora, habiendo entrado al templo de Dios,
la parte principal del hombre (haciéndose pasar por Dios y aparentando piedad),
el hombre se ha unido a él y se ha convertido en su prisionero,
en quien el diablo hace estragos,
separándolo con engaño de la vida de simplicidad y piedad,
y pervirtiendo los caminos y fines por los cuales el hombre fue creado.
Y ahora el pecado, habiéndose levantado y tomado el gobierno en el corazón,
hasta las misericordias de Dios dadas a la criatura son usadas para satisfacer
los deseos carnales y egoístas a los cuales el hombre se volvió un esclavo.
¡Ay!,
el hombre ha perdido tanto su dominio que se ha convertido en un
esclavo de la creación sobre la cual antes era gobernador.

Así es como los hombres se han vuelto esclavos y son tomados cautivos,
algunos por la codicia, otros por el orgullo,
otros por la concupiscencia y muchas otras cosas.
Sí, estas cosas se han vuelto señores en el corazón,
por las cuales él se apresura con toda avidez a abandonar
toda moderación y a cazar vanidad y locura.
¡Oh!,
qué vanos juegos y necias tonterías han desviado el corazón
del hombre de la sabiduría pura de su Dios,
al punto de que prácticamente no conoce ningún límite para su búsqueda de cosas cambiables,
para su glotonería y exceso en su dieta (aunque nunca queda satisfecho),
para su necedad en la apariencia (que no tiene freno ni restricción),
estando totalmente caído de eso que no cambia, y de la verdadera satisfacción y honor.
Y mientras más siga el hombre en este estado, más vacío y oscuridad entran a su corazón;
y habiendo caído bajo el poder de la naturaleza terrenal él es cubierto con densas tinieblas,
de modo que no conoce ni la mente de Dios ni su propio estado miserable,
porque el dios de este mundo ha cegado el ojo que le mostraría su miseria,
y ha tapado el oído que escucharía la voz del pastor de su alma,
mediante la cual él podría ser vivificado.
Sí, su ojo y su oído son llevados hacia lo externo,
hacia cosas carnales y ahí son tomados cautivos,
de modo que él no conoce la voz del Espíritu.

Así, habiéndose vuelto ciego de corazón,
el hombre no puede recibir el camino del Espíritu,
y cualquier cosa que se le diga al hombre en este
estado (en amor a su alma que yace en la muerte),
la serpiente (habiéndose levantado y teniendo dominio
en el hombre) procura meterse en sus imaginaciones,
por lo cual la criatura es llevada a consultar con ella en la carne.
De esta manera el hombre es engañado y desviado de la simplicidad, y mantenido en el yo,
de modo que ignora a la Semilla de Dios que se encuentra
oprimida bajo toda esta muerte y oscuridad.
Y mientras la criatura quiera escuchar a la serpiente y sus promesas mentirosas,
será llevada de una cosa externa a otra, pero nunca a ver eso de lo que ha caído.

Por esto Cristo y todos Sus ministros predican el
arrepentimiento a aquellos que están en este estado,
para que todos ellos vuelvan sus mentes de estas obras muertas al Dios vivo,
quien es Espíritu, y es conocido y adorado en Espíritu, cuyo reino está en el interior,
y cuya luz está en el medio de todas estas tinieblas,
aunque las tinieblas no la comprenden.
Y a todos los que se arrepientan de seguir el camino de su propia sabiduría y conocimiento,
y lleguen a un estado de quietud,
Él les mostrará Su salvación y Su reino que está cerca (aunque
la serpiente les dice a sus seguidores que está lejos).
Y cuando la mente permanece quieta en espera del reino de Dios en Espíritu,
entonces el dios de este mundo es negado y resistido;
y cuando la mente se mantiene en la luz, no escuchando más lo que es terrenal,
entonces el alma, que yace en la muerte, comienza a escuchar la voz del Hijo de Dios,
y a recibir vida y fuerza de la Palabra,
por la cual es levantada de la tumba y puesta sobre la parte terrenal,
para recibir del Padre el rocío del cielo, mediante el cual es nutrida y refrescada.
Y conforme el hombre experimente el crecimiento de la semilla,
comenzará a ver la nueva creación y a entender lo que él ha perdido en la caída,
y así será restaurado por el poder de la Palabra, es decir del Hijo de Dios,
a Su dominio, poder y pureza,
y será capacitado para resistir al diablo y escoger
eso que es bueno y deleitarse en ello,
así como antes se deleitaba en lo contrario.
Así el hombre es reconciliado con su Hacedor en la eterna
unidad que va más allá de lo que las palabras pueden expresar.
Porque la sabiduría y poder que se reciben de arriba libertan al corazón de la corrupción,
al capacitarlo para huir de las contaminaciones que hay en el mundo,
y para correr por la senda pura con deleite,
lo cual es la gloriosa libertad de los hijos de Dios,
la resurrección en Cristo de la muerte en Adán, y la entrada al reposo eterno.

Y ahora, todos ustedes que sienten que han caído de su dominio,
de esa medida del don de Dios que Él ha puesto en el hombre,
y que ahora se ven llevados cautivos por el maligno a los caminos de la muerte,
el pecado y la maldad,
de modo que la corrupción tiene dominio en ustedes y sobre ustedes;
no busquen ser restaurados por medio de eso que los llevó a lo externo,
porque ese poder que actúa en la carne es de continuo solamente al mal.
Esto los llevará de monte en collado, en el yo, en el vacío, sin vida ni poder,
haciendo que ustedes busquen sanarse a sí mismos en falsas persuasiones,
pero nada de esto permanecerá en el día del juicio,
porque todo esto se encuentra en el primer hombre con su justicia propia.
Más bien ustedes deben buscar eso de lo que han caído,
y regresar a eso de lo que han salido, para que,
por la luz que está en medio de todas estas tinieblas y muerte,
puedan ser llevados de regreso por la sangre de la cruz,
a través del fuego y de la espada, al huerto de Dios, donde Él planta y alimenta,
y donde el viejo hombre (con toda su voluntad y obras) no puede entrar,
ni tampoco aquel cuyo líder es algo visible.
Porque el hombre ha caído y salido del Espíritu, y, por lo tanto,
por el Espíritu debe ser guiado a su estado original otra vez;
y esa Semilla contra la que el hombre ha pecado debe hacer la paz, cuya Semilla es libre,
y ponen en libertad a todos los que nacen de ella.

=== Con Respecto a la Luz y la Vida

Dios es la vida de cada criatura, aunque hay pocos que lo saben;
porque las tinieblas no lo ven ni a Él ni a Su vida,
aunque los hijos de las tinieblas pueden hablar Sus palabras a partir de las Escrituras,
las cuales fueron dadas por la luz.
Aun así, estos no conocen a Dios presente,
porque la primera aparición de Dios en el mundo es a través de la Luz: Dios dijo,
"`Sea la luz,`" y fue así. Y Dios vio que esta luz era buena.
Esto es lo que era en el principio con Dios, y era la Palabra,
por la cual todas las cosas fueron hechas y vistas,
y sin la cual nada de lo que ha sido hecho fue hecho, ni existía nada que fuera bueno.
Ahora bien,
las tinieblas estaban sobre la faz de las aguas hasta
que la luz resplandeció desde la Palabra,
la cual es vida, cuya vida se dice que es "`la luz de los hombres.`"^
footnote:[Juan 1:4]
Así que nadie puede ver la vida salvo por la luz
que viene de la vida y que lleva de regreso a ella.
Esta era la luz en el principio,
dada para mantener en orden a toda la creación. Y aunque resplandece en las tinieblas,
las tinieblas no la comprenden;
y todos los que permanecen en tinieblas (no discerniendo la vida
o siendo ordenados y gobernados por la luz) son destruidos.

Porque todos los que salen de la luz van a las tinieblas,
donde la vida y la imagen de Dios se han perdido.
Aquí está la caída,
y todos los que permanecen aquí están reservados en prisiones de oscuridad,
sin conocer la vida que puede romper las coyundas y cadenas de iniquidad,
y abrir el sepulcro y la puerta de la cárcel.
Aquí el hombre permanece en muerte con las tinieblas levantadas en dominio en su corazón;
y en estas tinieblas la criatura es llevada a sectas, opiniones y errores,
persiguiendo imaginaciones y corriendo en la sabiduría
natural cada vez más rápido hacia la muerte y las tinieblas,
hasta que está tan cegada en su entendimiento que piensa que rinde
servicio a Dios cuando está actuando contra Su vida,
tanto en sí misma como en otros.
En este estado la criatura llega a perderse completamente,
y el evangelio que podría recuperarla está escondido de sus ojos.
Porque,
aunque Dios dotó al alma con una medida de vida por
medio de la cual puede hacer Su voluntad,
aun así, ahora el dios de este mundo ha cegado tanto su mente,
y la ha alejado tanto de la vida de Dios,
que ya no tiene ni poder ni vida para hacer la voluntad de Dios,
ni luz para saber dónde encontrarla.
Pero, aunque carezca de vida, la criatura continuará manteniendo su profesión religiosa,
o alguna otra noción elevada, a fin de mantener una vana esperanza de salvación.

Esta es la única razón y causa por la que hay tantos tipos de formas y opiniones religiosas,
y modos de adoración, pero nadie que haga el bien, o viva lo que predica,
porque todos han perdido la vida de Dios,
que es la única que es capaz de producir la justicia de Dios.
El yo se aferra a la forma externa de religión y
la retiene en su imaginación por encima de la vida;
y la vida (que yace oprimida por debajo) no puede unirse con la forma,
sino que más bien la condena.
Así que todo el mundo yace en tinieblas; sí,
densas tinieblas están sobre todos los mares;
y de aquí se han propagado las imaginaciones sobre todos,
de modo que nadie puede experimentar la obra de Dios,
ni conocer el principio o el fin de ella.
Esta es la causa de la condenación,
la cual permanece sobre todos los que han salido de la vida de Dios.

Ahora bien,
no hay otro camino señalado por el Padre para salir
de esta condición salvo por medio de Cristo Jesús,
la luz y vida de los hombres.
Él es la luz que está en el mundo, aunque el mundo no lo conoce;
cuya luz resplandece en las tinieblas, pero no puede ser comprendida por ellas.
Esta luz es la que revela las tinieblas, y manifiesta sus obras.
Su primera aparición en la criatura descubre las tinieblas
de su condición y el cautiverio que existe en dichas tinieblas;
y sin su iluminación,
la criatura nunca podrá ver la condición miserable en la
que se encuentra el hombre (sin la vida de Dios),
ni estará dispuesta a estar quieta y ver la salvación de Dios,
sino que en lugar de esto estará llena de vanas esperanzas, conceptos e imaginaciones,
estando el velo sobre su corazón, considerándose a sí misma sana,
y no en necesidad del Médico.
Y con este corazón ciego,
la criatura lee las Escrituras y hurta las promesas que son dadas a los hijos
de luz (quienes tienen la Semilla a la cual le fueron hechas las promesas),
aunque ellos no conocen ni la ley ni el Evangelio.
No, ellos ni siquiera han llegado tan lejos como a la experiencia del ministerio de Moisés,
aunque se jactan de Cristo.

Pero cuando la criatura le presta atención a la luz,
comienza a ver esa muerte que todavía sigue reinando, y que el yo aún vive sin la ley.
Y con esta luz, todo lo que se ha levantado por encima de la vida en la criatura,
y ha contaminado su alma, es visto y juzgado.
Y aquí, eso que ha llevado al alma a la esclavitud puede ser visto,
y la dureza de corazón puede ser sentida, y la causa de ella conocida--a saber,
la gran transgresión de la ley pura de Dios.
Entonces el temor de Dios comienza a apoderarse del hombre que
ha vivido fuera de la vida de Dios y se ha complacido en la injusticia,
y la criatura siente gran angustia en su interior,
incluso donde anteriormente el hombre fuerte había mantenido un tipo de paz en su casa.
Pero al permanecer en la luz, la causa y el fin de estas cosas llegan a verse;
y al morar en el temor, se recibe sabiduría de arriba para apartarse de la iniquidad;
y al separarse de la iniquidad, se experimenta un acercamiento a Dios,
de modo que Su luz crece y se esparce,
a medida que el alma se acerca a las sendas justas de la vida.
Y a medida que la luz se va levantando, el estado de la creación es discernido,
y se comienza a entender cómo la enemistad se ha esparcido,
cómo los deseos la han contaminado,
y cómo eso que fue plantado como una viña se ha vuelto un desierto debido a la esterilidad,
lleno de espinos y cardos, de fuertes encinas y altos cedros,
por la falta del Labrador de la viña. Sí, donde el lirio debería crecer,
el alma se encuentra llena de malas hierbas, abrojos y ortigas,
de modo que Dios no quiere caminar en medio de tan grande abominación.
Y esta es la causa de todas sus miserias--Su ausencia.

Y cuando ustedes puedan ver esto, entonces comenzará el luto en la casa de alegría, sí,
comenzará el lamento por Aquel de quien ustedes han
caído. Pero a medida que sigan la luz,
y se acerquen al Señor (de quien ella viene),
ustedes verán que han sido sus propias voluntades
y caminos los que los han separado del Santo.
Y con la luz se darán cuenta de cuán a menudo han sido reprendidos
por el Espíritu de luz en el curso de sus malos caminos;
y que la única razón por la que ustedes han permanecido tanto tiempo en
la caída es, por haber seguido la voluntad propia y los placeres mundanos,
por los cuales la vida de Cristo en su interior ha sufrido.
Ningún hombre, antes de experimentar esto, podrá ver a Aquel que ha traspasado,
ni lamentarse por Él, ni ver qué es eso que oprime al Justo;
ni podrá aborrecer lo que Dios aborrece y amar lo que Dios ama en ninguna medida.
En lugar de esto, se unirá a eso que destruye el alma y le roba la vida,
siendo soberbio y altivo, y teniendo una boca que habla grandes cosas,
palabras infladas y vanas, como metales sin vida,
que dan un sonido placentero al oído carnal,
pero sin ninguna evidencia de la vida de Dios o de su obra.

=== Con Respecto a la justicia

La justicia que Dios acepta es solo una, y es la Suya,
la cual ha sido cumplida y manifestada perfectamente en Cristo Jesús,
quien es la luz y el Salvador del mundo.
Esta justicia no es del mundo,
ni puede el mundo heredarla salvo en la medida que crea en la luz de Cristo,
la cual Dios ha dado para guiar al hombre fuera del mundo a Cristo,
donde se encuentra la justicia de Dios.
Aunque hay muchos que hablan de esta justicia, aun así,
ninguno puede heredarla más allá de su experiencia del Hijo de justicia por la fe,
y con Él Su justicia es imputada por gracia,
siendo puesta en la criatura como un don del Padre.
Y con esta justicia la criatura es verdaderamente _hecha_ justa, así como Él es justo,
conforme a la medida de luz que ha recibido,
y no más allá--luz que condena todo acto del yo sin importar lo que pretenda,
para que "`como Él es, así seamos nosotros en este mundo.`"^
footnote:[1 Juan 4:17]

Así que aquel que permanece en esta justicia,
permanece en eso que niega el yo y el mundo,
y vive en obediencia a eso que es contrario a la voluntad del hombre,
y por esto en todas partes se habla en su contra.
Porque la voluntad del hombre no obra la justicia de Dios;
sino que la justicia de Dios se forja en la criatura en
esa obediencia que es contraria a la voluntad de la carne.
Y en la fe que viene del Espíritu eterno se experimenta una nueva fuente,
tanto del querer como del hacer, de modo que lo que se produce es Espíritu y vida.
En la medida que alguien tenga esta justicia, él no estará en pecado,
ni le dará lugar al diablo,
sino que experimentará esta justicia como una coraza contra
todos los asaltos a la mano derecha y a la mano izquierda.

Pero ustedes dicen que su justicia es como trapo de inmundicia.
Estoy de acuerdo, pero ¿por qué permanecen en eso?
La justicia de Dios no es un trapo de inmundicia.
Por lo tanto, abandonen su propia justicia, y experimenten eso que es perfecto, a saber,
la justicia eterna en la que todos Sus Santos han sido reunidos en Él mismo.
Porque Dios no recibirá nada que no sea Suyo,
y debe ser lo que ustedes deben también poseer,
de otra manera no podrán ser recibidos a Él. En vano ustedes
piensan que arando iniquidad y sembrando maldad,
aun así, segarán justicia.

Con la luz ustedes podrán ver qué es lo que obra en ustedes,
y a qué se están sometiendo como esclavos.
Y a medida que obedezcan esta justicia,
sentirán al hombre espiritual resucitado y viviendo,
verán las cadenas de la muerte quebradas y experimentarán
esa vida que da poder sobre el infierno y sobre la muerte.
Entonces podrán decir: "`El Espíritu vive a causa de la justicia.`"^
footnote:[Romanos 8:10]

Pero muchos convierten la justicia de Cristo en una cubierta para sus abominaciones.
¿Qué iniquidad existe ahora entre las naciones para la cual
la justicia de Cristo no ha sido invocada como una cubierta?
Sí,
los hombres se bendicen a sí mismos con un concepto de la
justicia de Cristo mientras viven en la más grande iniquidad.
Pero sepan esto: es para cubrir su iniquidad,
orgullo y codicia que sus maestros inventan esta fe,
diciendo que es suficiente creer en una justicia acerca de la que
se lee en la letra (aunque no son obedientes a ella en espíritu).
Pero aquellos que no son siervos de la justicia, no son siervos de Cristo;
y la fe de ustedes, sin Sus obras,
no servirá para que alcancen su salvación. Y un día
sus conciencias darán testimonio de esto:
No pueden heredar justicia,
o ser hechos "`la justicia de Dios en Cristo`" más allá
de su experiencia del poder de Su justicia obrando en ustedes,
y de que la reciban con obediencia y sumisión,
y de que se unan a ella contra toda injusticia.

Y en aquel día cuando Él venga a separar lo precioso de lo vil,
entonces verán que sus conceptos de justicia no tienen ningún valor,
cuando el hacedor de iniquidad es encontrado y juzgado en ustedes,
el cual se ha jactado de la justicia de Cristo en palabras, pero no conoce su poder.
Porque por el poder y la pureza de la justicia todos
los hacedores de iniquidad serán juzgados y condenados.
Así que no se engañen: "`el que hace justicia es justo, como Él es justo;`"^
footnote:[1 Juan 3:7]
pero el que habla de la justicia y comete pecado es del diablo,^
footnote:[1 Juan 3:8]
y heredará la porción de aquel por quien él es movido y guiado.
Porque la justicia de Dios no se mezclará con el engaño, ni lo cubrirá,
ni jamás fue dada con ese propósito; pero conforme es obedecida,
revela y destruye tanto la justicia como la injusticia del hombre,
según es revelada de fe a fe.
Y todos los que tengan la justicia de Cristo experimentarán
su poder para matar y dar vida,
a medida que ella sea recibida por la fe.
Sí, esta es la justicia de Sion "`que sale como resplandor,
y su salvación es como una antorcha encendida.`"^
footnote:[Isaías 62:1]

Avergüéncense ustedes paganos, que se apoyan en el Señor, y dicen:
"`La justicia de Cristo,
la justicia de Cristo;`" porque ustedes han deshonrado Su
justicia más que todos los que han venido antes de ustedes;
y el nombre de Cristianos se ha convertido en un oprobio en todo
el mundo debido a su infidelidad a la justicia de Cristo.

=== Con Respecto a la Palabra

La Palabra es eso que estaba en el principio,
y fue el principio de todas las cosas visibles.
Por ella todas las cosas fueron hechas,
y aunque ella es la que sustenta todas las cosas visibles,
y revela su verdadero fundamento y uso, aun así, es invisible en sí misma,
y ninguna cosa visible la puede revelar.
Y así como sin ella "`nada de lo que ha sido hecho, fue hecho,`"^
footnote:[Juan 1:3]
asimismo, sin ella nada puede ser visto tal como fue hecho,
ni nada puede usarse en su lugar puro y apropiado;
sino que cualquier cosa con la que el hombre se entrometa,
sin tener la Palabra en Él para guiar, ordenar y santificar, él la contamina,
y se vuelve impura para él. Sin esta Palabra ninguna
Escritura Santa puede leerse con provecho,
porque ella es la que abre las Escrituras de la verdad.
Y aunque las Escrituras hablan de ella, aun así,
ni las Escrituras ni todos los escritos en el mundo son capaces
de comprenderla o de declarar la profundidad y alcance de ella,
que va más allá de toda descripción. Sin embargo, ella es, en todas las generaciones,
el maestro y guía de aquellos que son del Señor;
y los santos en todas las generaciones la han experimentado en diferentes medidas,
aunque ella no ha tenido lugar en las religiones del mundo.

Así los hombres al oír acerca de una Palabra, pero sin tener una experiencia de ella,
dicen que ella es la letra escrita.
Pero cualquiera que tenga esta Palabra tiene eso que comprende la muerte,
el infierno y el sepulcro, eso que ata y encadena a Satanás, y vence al mundo.
Tiene eso de lo cual mana la vida y luz, por la cual se experimenta la nueva creación,
y en la cual mora la justicia.
Estas cosas son experimentadas por aquellos que tienen la Palabra morando en su interior,
pero no por todos los que tienen la letra escrita.
La voluntad del hombre no puede cambiar la Palabra,
porque ella es contraria a dicha voluntad;
ni el ingenio del hombre puede abrirla o exponerla,
porque ella confunde la sabiduría de los sabios y desecha el entendimiento de los entendidos.
Sí, esta Palabra se esconde de los sabios y de los entendidos,
pero se revela a Sí Misma a los niños, y crece y se incrementa en ellos,
cosa que la letra no hace.
Y a medida que ella crece, santifica a todos los que la tienen,
y es como un fuego y un martillo para todos los que la conocen.
En verdad, ella es viva y poderosa, y penetra hasta partir las coyunturas y los tuétanos,
el alma y el espíritu, donde sea que se encuentre;
pero la letra no es así. Y esta Palabra es un oprobio para toda mente carnal,
incluso para muchos que profesan la letra.
El que tenga está palabra, será lavado, purificado,
trasladado fuera del mundo y conformado a Dios por medio de ella, tanto como la posea.
Pero muchos tienen la letra y no conocen a Dios, sino que siguen en las costumbres,
modas y caminos inmundos del mundo, y no son ni cambiados ni reconciliados con Él.

Nadie puede guardar esta Palabra y también mantener sus pecados,
pero sí puede hacerlo teniendo solamente la letra escrita;
porque dondequiera que la Palabra sea conocida, la nueva creación es experimentada,
la cual es creada para caminar en justicia.
Y aquel que tenga la Palabra, verá que todos los que dicen conocerla,
pero no andan en justicia, mienten y no practican la verdad.
Estos en verdad deshonran la Palabra,
y hablan como si ella pudiera morar con la inmundicia.
Pero la Palabra es un fuego que quema toda inmundicia donde sea que se encuentre;
así que la Palabra no está siendo experimentada donde sea que el pecado permanezca.

Los hombres carnales pueden leer acerca de la Palabra del Señor que vino a los santos,
quienes fueron lavados, purificados y engendrados nuevamente en su obediencia a ella.
Pero estos hombres, no conociendo esta Palabra en sí mismos,
dicen que la Palabra es la letra escrita, la cual solo habla acerca de ella.
Así la palabra que ellos conocen no tiene poder en ellos
para vencer al diablo y quebrar los yugos de iniquidad;
en cambio la Palabra de Dios no está presa sino libre,
y pone en libertad a todos los que la obedecen y la tienen morando en su interior.
Sí, ella destruye el trono del pecado, y levanta y vivifica la Semilla de Dios.
Por esta razón la vida vieja y la Palabra no pueden permanecer juntas en un cuerpo;
ni puede el viejo hombre conocer otra palabra más aparte de la letra.
Y en su imaginación,
él busca con su sabiduría caída eso que Dios (en Su sabiduría)
ha escondido de los sabios y de los entendidos,
y por lo tanto permanece en tinieblas.
Para este hombre las Escrituras son como una parábola y un misterio,
que su sabiduría desobediente no puede descubrir.
Así que él crea significados, interpretaciones, tergiversaciones y adiciones,
todo lo cual se levanta del hombre que no tiene acceso a este misterio,
y en quien la Palabra no puede morar.

Por lo tanto, habiéndose el hombre apartado de la Palabra e ido al mundo,
la luz del evangelio es predicada con el fin de volverlo a ella otra vez, para que,
por medio del conocimiento de esta Palabra en el corazón,
y de tener la mente puesta en ella en la luz,
pueda experimentar el poder de la Palabra destruyendo
la naturaleza inmunda y la voluntad rebelde,
y matando al hombre carnal con todos sus afectos por medio de la cruz,
y forjando en su corazón la naturaleza pura.
Y así, a través de la muerte de lo viejo, se levanta lo nuevo,
haciendo una nueva creación en Cristo Jesús que tiene poder para hacer buenas obras,
el cual viene de la Palabra eterna.
Dios acepta estas buenas obras, porque Él es quien las inspira y las obra,
y la criatura es solo el siervo en esto, que colabora con Él en el mismo poder.
Esto no es el hombre tomando prácticas de la letra escrita para realizarlas por sí mismo,
sino el eterno consejo y fuerza de Dios, ordenado,
movido y ejecutado en la voluntad y tiempo de Dios,
y de forma contraria a la voluntad de la carne,
mediante lo cual la voluntad de toda carne es sometida,
para que así Dios sea alabado por sus propias obras.

Por lo tanto, a través de la Palabra viva, se comienza a experimentar un alma viviente,
la vida de Cristo se manifiesta en el cuerpo mortal
y la criatura llega a tener comunión en la vida,
siendo transformada en ella y hecha una con ella.
Esta es la "`Palabra de reconciliación,`"^
footnote:[2 Corintios 5:18]
que une a Dios y a la criatura en Espíritu.
Cualquiera que conozca esto, no necesitará salir a buscar sabiduría,
consejo o fuerza para pelear contra todos los poderes de
las tinieblas o para resistir los asaltos del enemigo,
sino que al diligentemente prestarle atención a la Palabra que está cerca en el corazón,
encontrará manantiales de vida,
fuerza espiritual y poder contra toda iniquidad espiritual.

=== Con Respecto a la Adoración

La adoración del Dios verdadero y vivo está fuera del alcance de la voluntad,
conocimiento, sabiduría y entendimiento natural del hombre; porque Dios es Espíritu,
y es en Espíritu que Él es adorado.
Él no es adorado por manos de hombres o con prácticas externas
(excepto cuando el Espíritu es el autor y la fuente);
ni Su adoración consiste en comida y bebida,
ni de diversas abluciones u otras ordenanzas carnales
que son tomadas por tradición o imitación de otros,
sino solo cuando cada criatura es movida por el Espíritu del Dios vivo.
Dios quiere ser servido y adorado en Su propio Espíritu,
y no con ninguna de las cosas que el hombre ha ofrecido
desde la caída. Así que las imaginaciones,
pensamientos y concepciones de los hombres están excluidas; todos sus caminos,
sus tiempos y formas, sus costumbres, disciplina e ideas respecto a la decencia,
que ha creado y añadido,
todo esto está excluido y condenado por ese Espíritu en el que Dios únicamente es adorado.
Dios le enseña a Su pueblo Su adoración y la manera de realizarla;
y los tiempos están en las manos de Aquel a quien le pertenece la adoración.

Así, antes de que alguien pueda adorar correctamente a Dios,
debe esperar conocer Su Espíritu,
que es lo único que conduce al verdadero conocimiento
y adoración (tanto a lo que hay que ofrecer,
como a la forma de hacerlo.) Todos los que desean
adorarlo de manera aceptable deben conocer Su luz,
y en ella deben esperar conocer qué demanda Dios de sus manos.
Porque no es hacer lo que los hombres les digan que hagan o dejen de hacer
lo que los justificará delante del Señor. Porque sepan esto:
Dios hizo al hombre para Sí Mismo y para Su servicio, y el Dios vivo no es un ídolo mudo,
como para que las personas tengan que imaginar una manera de servirlo
que sea lo más acorde posible a la moda y costumbre de una nación o pueblo.
Al contrario, Él que hizo al hombre le ha dado una medida de vida de Sí Mismo,
para que sea incrementada en Su servicio;
y también le ha dado luz por la cual el hombre puede
ver el movimiento de este Espíritu de vida.
Esta vida o Espíritu siempre se mueve conforme a la voluntad de Dios, porque es de Él,
y por lo tanto todos los movimientos de este Espíritu en la criatura la atraen a Dios.
La mente, voluntad, afectos y amor de Dios están en este Espíritu,
y el que camina en la luz ve estas cosas.

Pero cuando la criatura corre delante de esto, o sin esto,
corre a toda clase de obras y adoraciones muertas;
y el fundamento de esto surge de las tinieblas y de la desobediencia.
Porque la criatura que ha estado afuera en el mundo y en sus caminos injustos,
haciendo lo que es malo,
es condenada por la luz en su corazón por el mal y por negar lo que es bueno;
pero luego la misma mente corrupta corre a realizar actos de adoración para obtener paz,
de modo que tanto sus malas obras como su adoración son ejecutadas en la misma naturaleza.
Así su oración se vuelve una abominación (como fue dicho de otros, Proverbios 28:9);
porque Dios no oirá las oraciones ni aceptará la adoración
de aquel que considera la iniquidad en su corazón. De hecho,
este es el sacrificio de Caín,
y estas son las oraciones de Esaú. Pero la adoración de
ustedes debe ser realizada en Aquel que nunca pecó,
para que sea aceptada por el Dios puro.

Así que la manera de complacer al Padre es esperar en la luz hasta que sientan
algo del Espíritu de Vida (que es en Cristo Jesús) moviéndose en ustedes,
y entonces, al unirse a eso, en su poder ustedes podrán adorar.
Porque este poder viene de Dios, y Él no puede olvidarse de Sí Mismo.
Lo que es hecho en Su luz, poder, sabiduría y fuerza es hecho en el nombre de Cristo;
y cualquier cosa que sea hecha en Su nombre no será negada por el Padre.
En la medida que alguien esté en Él, en esa misma medida será considerado hijo,
y será aceptado en Él, pero sin Él ustedes nada podrán hacer,
ni serán oídos por el Padre.
Ustedes que no experimentan este poder como su líder y guía en su adoración,
están "`adorando lo que no conocen,`"^
footnote:[Juan 4:22]
y tampoco saben con qué naturaleza adoran (aunque
digan que están realizando Su adoración y obra).
Ay, los falsos adoradores siempre fueron los enemigos
más grandes de Cristo y también de sus propias almas;
y ay de aquel que de este modo esconde su pecado.

Así que todos los que deseen adorar en verdad, deben primero conocer la verdad, a saber,
el Espíritu de Verdad que guía a toda verdad.
Este Espíritu de verdad toma de Cristo y testifica
de Su vida y poder en la criatura que está adorando.
Estos saben que están en Él y que Él está en ellos, y en Él adoran al Padre de verdad,
de modo que Dios es servido por eso que viene de Él. Solo hasta el punto en que
esto sea experimentado es que alguien podrá adorar a Dios en Espíritu.

Por lo tanto, ustedes que han recibido luz de Cristo, esperen en ella,
hasta que en ella experimenten la guía, obra y gobierno del Espíritu;
y aquí el más pequeño de los adoradores en la luz se encuentra en el servicio de Dios,
cuando esperan en Él en Espíritu.
Y a medida que estos permanezcan en esta luz, esperando en Dios en la luz,
serán guardados de servir al príncipe de las tinieblas;
porque sus lomos están ceñidos y sus lámparas encendidas,
y siempre están listos para reconocer Su voz y responder a ella con obediencia.
Porque aquellos,
cuyo temor y servicio a Dios son mandamientos de hombres que les han sido enseñados,
adoran en vano; porque "`todos los hijos del Señor son enseñados por Jehová,`"^
footnote:[Isaías 54:13]
y, "`los que son guiados por el Espíritu de Dios, éstos son los hijos de Dios.`"^
footnote:[Romanos 8:14]
Estos escuchan al Señor y conocen Su voz; y lo que ven y oyen, eso hacen,
y "`no ofrecen el sacrificio de los necios.`"^
footnote:[Eclesiastés 5:1]

Pero ¿no están ofreciendo el sacrificio de los necios,
ustedes que pelean y contienden por una forma de adoración que Cristo nunca ordenó,
ni Sus seguidores jamás practicaron,
lo cual podrían ver claramente si tan solo compararan
su adoración establecida con la práctica de los santos?
Porque todo ha sido cambiado por hombres y concilios,
bajo la pretensión de decencia y conformidad,
o alguna otra cosa que tiene su origen en la voluntad del hombre,
pero que Dios nunca ordenó. De hecho,
Nabucodonosor no era más celoso por su imagen que lo que ustedes son por la suya,
y si ustedes tuvieran su poder,
también forzarían a los que han encontrado el camino
eterno de Cristo a inclinarse a sus imaginaciones.
Pero ustedes nunca encontrarán a Dios en una adoración que no venga de Él,
que los hombres y concilios han alterado y a la que le han añadido,
y la cual han cambiado de tiempo en tiempo según
lo que mejor se adapte a sus costumbres y países,
de modo que cada nación tiene su manera diferente de adorar.
Y aunque todos los hombres mediante sus concilios
llegaran a un acuerdo en cuanto a la forma de adoración,
aun así, estarían fuera del consejo de Dios.

Así todos los que de alguna manera han salido de Cristo, el verdadero patrón y ejemplo,
se han ido a las imaginaciones de los hombres y al "`culto voluntario,`"^
footnote:[Colosenses 2:23]
y ahí se han convertido en siervos de hombres, y no de Dios.
Porque no es el nombre lo que lo hace la adoración de Dios, sino la naturaleza,
que debe ser en Espíritu y en la voluntad de Dios.
Esta naturaleza es contraria a la voluntad y sabiduría de los hombres,
en la que ellos han realizado su adoración idólatra en todas las edades,
y establecido sus semejanzas e imágenes en lugar de la verdadera adoración,
siendo ciegos de corazón,
y asumiendo que todos están fuera del camino correcto excepto ellos.

Y en verdad, esto es lo que ustedes han hecho,
todos ustedes que en este día establecen a partir de la letra escrita
una imitación de lo que otros hombres han hecho y experimentado,
pero que no han recibido del Señor el mandamiento y poder en Espíritu para hacerlo.
A ustedes se les preguntará: "`¿Quién demanda esto de vuestras manos?`"^
footnote:[Isaías 1:12]
Porque todos los santos tienen su mandamiento en Espíritu,
y saben cómo el Espíritu da vida para cumplir el mandamiento,
y por lo tanto su adoración es espiritual, y el corazón,
mente y alma están unidos en ella.
Aquí no hay ningún ídolo o semejanza,
sino que en un mismo Espíritu se experimenta el mandamiento, el poder, la vida,
la voluntad,
el camino y la adoración. Pero todos ustedes que han tratado
de realizar las prácticas de los santos sin ser llamados,
mandados y preparados en Espíritu, carecen de poder y vida, y, por lo tanto,
incluso durante su adoración, sus corazones corren en pos de cosas carnales.
Esto es idolatría espiritual, porque lo que sea en que ustedes tengan puestas sus mentes,
eso será el dios que adoran.
Pero el Dios puro busca la verdad en lo íntimo.

=== Con Respecto a la Fe

El que tiene la fe viva (que es en Cristo) _vive_ por ella;
y la vida que vive está por encima de todo el mundo y de los poderes de las tinieblas.
La medida más pequeña de esta fe es perfecta,
y es un poder presente que actúa contra todos los asaltos de Satanás,
si la criatura permanece fiel en él, y no corre a otras ayudas,
cayendo de este modo en la desconfianza.
Porque la verdadera fe es el don de Dios, y cualquiera que reciba una medida de ella,
ha recibido una medida del Hijo,
contra la cual el Padre no permitirá que ninguna tentación prevalezca.
Esta fe echa mano de la justicia de Dios,
cuya justicia es vista en la luz y forjada en el Espíritu,
a través de la cual la criatura se vuelve "`hechura de Dios,
creada en Cristo Jesús para buenas obras,`"^
footnote:[Efesios 2:10]
y así llega a quedar libre del mal, estar muerta al pecado,
pero viva para la justicia de Dios,
esperando en fe ver la justicia que se revela a través de la obediencia a ella,
de fe a fe, como está escrito, "`el justo por la fe vivirá.`"^
footnote:[Habacuc 2:4; Romanos 1:17; Gálatas 3:11; Hebreos 10:38]

Ahora bien, esta es la fe viva, que "`purifica el corazón`"^
footnote:[Hechos 15:9]
hasta llevarlo a una vida de piedad,
y por lo tanto revela la justicia de la fe como una herencia--la justicia eterna,
que siempre está creciendo y brotando--por la cual
la criatura crece en el conocimiento de Dios,
y camina con Él por fe, fuera del mundo y sus placeres y reinos,
al reino del Hijo de Dios.
Aquí el vituperio de Cristo es considerado como grandes riquezas,
y los hombres echan mano de cosas invisibles--cosas que la fe del mundo no puede alcanzar.
Porque la fe del hombre no lo lleva más allá de los razonamientos
visibles y de la consulta con la sabiduría natural y la ayuda carnal,
y por eso no lleva nada a la perfección, debido a que no ve a Aquel que es perfecto.
Pero la fe viva ve a Aquel que es invisible,
y echa mano de la medida de Dios hecha manifiesta en Espíritu,
la cual echa fuera lo viejo, y produce lo nuevo (tanto el querer como el hacer),
cuya obra es perfecta tanto para matar como para dar vida.

Pero la fe del mundo no es de esta naturaleza y poder,
porque los que tienen esta fe escuchan algo con el oído externo,
y entonces se ponen a creer, o a no creer, según su propia voluntad o imaginación,
o a partir de la persuasión externa.
Y conforme sus imaginaciones, pensamientos y concepciones cambian, su fe también cambia;
y por esto no puede ser firme,
porque no está fundada en la medida del Espíritu de Dios
que se experimenta en el corazón. Esta fe no sirve a Dios,
ni puede agradarlo, ni "`ve al Invisible.`"^
footnote:[Hebreos 11:27]
Y, por lo tanto,
al no estar fundada en ese poder que es contrario
a la voluntad del hombre y al poder del pecado,
la fe del mundo está sujeta a la voluntad de los hombres,
y al poder del príncipe de este mundo; y así como el mundo y los tiempos cambian,
también lo hace esta fe, pero ella nunca puede guiar a nadie fuera del mundo,
y del tiempo, al Redentor del alma.
Y para todos los que permanecen en esta naturaleza,
la fe viva (que viene de Dios y se mantiene en una conciencia limpia) es un misterio,
que no es conocido ni recibido.

Por lo tanto, la fe de Cristo y la fe del mundo son distintas,
y tienen sus diferentes efectos y frutos.
Con una los hombres profesan libertad y redención en la imaginación y compresión,
pero siguen siendo esclavos del pecado; la otra es la fe viva que da la vida de libertad.
Y así como el fundamento y raíz de ellas es diferente,
también su fruto y efecto es diferente, estando siempre uno en contra del otro.
Porque esa fe que está fundada en Cristo crucifica el pecado, y cree en la pureza,
en la perfección y en la santidad, y es únicamente por esta fe que el justo vivirá,
sacando el juicio y la justicia a luz mediante una conducta piadosa.
Pero la fe que está fundada en las imaginaciones y en la sabiduría del hombre,
que cree en una salvación sin una vida de santidad, esta fe crucifica al Justo,
y mantiene al injusto vivo.
En verdad,
esta es la fe de aquellos que creían en las Escrituras y en las palabras de los profetas,
y que Dios era su Padre, pero que, al no tener la Palabra de fe en sus corazones,
mataron al Hijo de Dios y pusieron al asesino en libertad.

Por lo tanto, así como la fe que está muerta produce muerte,
asimismo la fe viva produce vida.
Porque una profesión de fe sin justicia es como un cuerpo sin vida;
y así como un hombre vivo se conoce por sus acciones,
asimismo la fe viva se conoce por sus frutos.
Y tal como el hombre no puede vivir sin acción,
así la verdadera fe en Cristo no puede vivir sin justicia.
Estas dos cosas son inseparables, por eso se habla de "`la justicia de la fe;`"^
footnote:[Romanos 4:11,13; 9:30; 10:6]
donde "`el corazón cree para justicia, ahí la boca lo confiesa para salvación,`"^
footnote:[Romanos 10:8]
sin hipocresía o justicia propia.
Por lo tanto, la justicia de Dios se recibe en el corazón por fe,
y por la obediencia a esta justicia ella es manifestada
en el mundo como un testigo contra toda injusticia.
Pero la fe que no da a luz la vida de Cristo en el mundo es una fe muerta.

=== Con Respecto a la Esperanza

La esperanza es un don de Dios.
Es pura, y está fundada en eso que es puro,
mostrándole al alma la pureza de Dios y la justicia en Cristo Jesús. Al contemplar esto,
el alma es preservada de unirse al inicuo en todas sus tentaciones,
debido a que ve en la luz una mejor expectativa.
Porque cuando la vida de Cristo no se experimenta en todo su poder, aun así,
se contempla en la esperanza,
que es como un ancla que aquieta la mente y evita que siga al inmundo;
de modo que la esperanza mantiene fuera del pecado, y "`no avergüenza,`"^
footnote:[Romanos 5:5]
e incluso en la hora de angustia sostiene su "`esperanza contra esperanza.`"^
footnote:[Romanos 4:18]
Esta es la esperanza que penetra detrás del velo hasta el lugar santísimo,
donde la vida y la inmortalidad son sacadas a luz,
y al cual ningún ojo mortal o sentido carnal puede acercarse.
Sí, esta es la esperanza viva,
que espera hasta el fin que Cristo y Su justicia se revelen para quitar el pecado,
salvando y sacando de él. Y en la esperanza de esto,
los hijos de Dios esperan en la obediencia del Espíritu,
y no se conforman a los deseos engañosos;
sino que como Aquel que los ha llamado a tener esta esperanza es santo,
así "`el que tiene esta esperanza en él, se purifica a sí mismo como Él es puro.`"^
footnote:[1 Juan 3:3]

Pero el diablo ha engendrado otro tipo de esperanza en sus siervos,
quienes creen en él y son movidos por su espíritu.
Esta esperanza está fundada en otro terreno y produce otro fruto,
la cual le dice al hombre que, aunque él sea un esclavo del pecado, aun así,
hay esperanza de salvación. Y aunque el testigo de
Dios en la conciencia testifique lo contrario,
sin embargo,
la serpiente enseña que esta esperanza no debe ser juzgada como falsa o cuestionada.
Así que donde el diablo se ha vuelto el maestro en el hombre,
la conciencia tierna es resistida como si fuera el
error y la locura más grande del mundo.
Y por esta serpiente el hombre es enseñado a creer que esperar
un Cristo internamente es negar el Cristo que murió en Jerusalén;
o que buscar el misterio que ha estado oculto desde los siglos
y edades (que es Cristo en nosotros la esperanza de gloria),
es negar la persona de Cristo y Su sangre y sufrimientos.
Y Satanás ha engendrado muchas imaginaciones de este tipo en las mentes de las personas
para hacerlas tener miedo de prestar atención a la luz de Cristo en el interior,
para que así él pueda mantener el corazón en tinieblas,
y su trono allí sin ser descubierto.

Así que él pone al hombre a buscar un reino de Cristo externo,
y una manifestación externa del Espíritu, y una luz externa, una Palabra externa,
y una justicia externa,
y a tener una esperanza en estas cosas incluso mientras la serpiente mora en el corazón,
y allí (en tinieblas) sostiene su reino de pecado
y un trono de injusticia durante toda su vida,
alimentándolos con una esperanza de lo que ellos experimentarán después de que mueran,
por una religión de palabras sin el poder, la vida, el Espíritu y la verdad en ellos.
Esta es "`la esperanza del hipócrita que debe perecer`"^
footnote:[Job 8:13 Traducción literal de la KJV]
al final y que queda corta de la salvación.

Porque no es la esperanza de Cristo vivir en pecado y aun así esperar salvación. No,
la esperanza que es de Cristo anhela ser libre de
pecado tanto como desea ser libre del infierno.
Y el que conoce a Cristo y tiene su esperanza en Él, tiene la esperanza en la justicia,
y desea vivir en justicia en el presente mundo malo
tanto como estar en justicia en el día del juicio.
Pero ¿hay alguna razón por la que ustedes tengan esperanza de ser salvos por Cristo,
quienes en este momento quieren ser los siervos del diablo,
y presentan sus miembros a él como siervos, deleitándose en su iniquidad mientras viven,
y aun así deseando ser salvados por la justicia de Cristo cuando mueran?

=== Con Respecto al Amor

El amor de Dios es puro y perfecto, y no puede cohabitar con el yo,
ni con ninguna cosa cambiable.
Dios es amor, y nadie puede morar en amor a menos de que more en Dios.
Y a medida que la criatura viva en Dios, será transformada a Su imagen y semejanza,
y así el amor de Dios será visto en la luz pura y será derramado en el corazón,
por el cual el poder de la fe obrará hasta alcanzar la victoria
sobre todo lo que es contrario a Él. Aquí el amor de Dios abunda,
y aquellos que moran en él no hacen ningún mal,
sino que a través de la obra del amor cumplen la ley de Dios.
Pero el amor del mundo se levanta desde el espíritu del mundo,
que (por motivos egoístas) pone los afectos en cosas cambiables,
y de este modo cae en la enemistad contra Dios.
Es por esto que "`cualquiera que quiera ser amigo del mundo,
se constituye enemigo de Dios.`"^
footnote:[Santiago 4:4]
Pero el amor de Dios es un fruto del Espíritu de Dios,
que salta desde la fuente y corre hacia toda la creación de Dios.
Este amor solo lo tienen aquellos que tienen el Espíritu del cual brota,
el cual es eterno, inmutable y está sobre todas las cosas carnales,
y ni el tiempo ni las cosas carnales lo pueden apagar.

De tal manera amó Dios al mundo,
que ha dado a Su Hijo al mundo como una luz que condena al pecado en la carne,
para que la justicia de Dios se cumpla en la criatura que
anda conforme al Espíritu y niega las obras de la carne.
Y en verdad, este es el amor de Dios para con los pecadores:
condenar todo pecado y quitarlo por medio de la luz y vida de Jesucristo.
Todos los que aman con este amor saben que este es su objetivo y fin.
Pero con el amor de Dios todo el amor del hombre es condenado,
el cual consiste en cosas que han surgido a través de la caída,
y han contaminado tanto al cuerpo como al alma.

Por lo tanto, este amor de Dios consiste en represiones,
juicio y condenación contra todo lo que contamina la creación,
y contra la criatura que se entrega a la inmundicia.
Esto es amor puro para con el alma,
porque trata fielmente con ella al declararle su condición.
Y este fue el gran amor que Cristo le mostró a los Judíos,
cuando les dijo que eran hipócritas, guías ciegos, mentirosos, diciéndoles "`¡Serpientes,
generación de víboras! ¿Cómo escaparéis de la condenación del infierno?`"^
footnote:[Mateo 23:33]
Él habló muchas palabras claras y verdaderas como estas en amor a ellos.
De igual modo, fue el amor de Dios en Pablo lo que le dijo a Elimas "`¡Oh,
lleno de todo engaño y de toda maldad, hijo del diablo,
enemigo de toda justicia! ¿No cesarás de trastornar los caminos rectos del Señor?`"^
footnote:[Hechos 13:10]
Porque tratar fiel y verdaderamente con cualquier criatura según es vista en la luz,
es todo el amor que se le puede mostrar;
y los que no aman tanto a Dios como al hombre de esta manera (como
se verá en el día del juicio) están fuera del amor de Dios,
y han imaginado un amor que es de otra naturaleza.
Estos se halagan unos a otros en sus malos caminos y en sus opiniones cambiantes,
y su amor está fundado en cosas carnales y en sus propias voluntades.
Así que ellos aman cuando quieren, y aborrecen cuando quieren,
pero no conocen el amor como es en Dios, ni tampoco aborrecen lo que Dios aborrece.
Y tan grande es la ceguera de los que dicen "`Todos deben
ser ganados por amor,`" que no entienden lo que afirman.
Porque Dios dice:
"`Sion será rescatada con juicio,`" y "`con espíritu de
juicio y con espíritu de fuego lavará su inmundicia.`"^
footnote:[Isaías 4:4 Reina Valera de Gómez]
Pero aquellos que todavía están en su inmundicia quieren
que todos los demás sean halagados en ella.

Por lo tanto, el amor que es indulgente con la inmundicia es inmundo,
porque contamina el templo de Dios.
Pero el amor del Espíritu es puro,
porque condena lo inmundo y lava la inmundicia de todos los que lo aman.
Pero ¡ay de ese amor que gana amigos por ser indulgente con los enemigos de Dios!
Por eso Pablo dice: "`El amor sea sin fingimiento.
Aborreced lo malo, seguid lo bueno.`"^
footnote:[Romanos 12:9]
Este es el amor que descubre el pecado, que condena el pecado a la muerte,
y lo cubre con justicia.
Esto es lo que Santiago dice: "`el que haga volver al pecador del error de su camino,
salvará de muerte un alma, y cubrirá multitud de pecados.`"^
footnote:[Santiago 5:20]
Y Salomón dice: "`Mejor es reprensión manifiesta que amor oculto;`"^
footnote:[Proverbios 27:5]
porque estas heridas son preciosas para todos los que saben lo que es el amor.
Pero aquel que es indulgente con la iniquidad de un hombre, aborrece la justicia de Dios.
Y, por lo tanto, con la luz, el amor de Dios y el amor del diablo son vistos,
y como cada uno ama sus propias obras,
y lo mismo hacen sus hijos en quienes ellos reinan.
Y el que ama al uno, aborrece al otro; y el que sirve al uno, menosprecia al otro;
y así el siervo siempre contiende por el maestro a quien ama.

=== Con Respecto al Juicio

El verdadero juicio (según es dado a conocer a los
hombres) es un don del Espíritu de Dios,
puesto en el corazón de todos los que moran en la luz de Cristo,
cuyo juicio pasa sobre todo lo que es contrario a la vida de Dios en la criatura.
Y a medida que es recibido, brota con luz y salvación,
para redimir al corazón de toda inmundicia,
condenando todo lo que es contrario a la pureza,
para que Dios sea visto en Su morada con Su justicia.
Por eso se dice que Él "`redime a Sion con juicio, y sus convertidos con justicia;`"^
footnote:[Isaías 1:27]
y "`lava las inmundicias de las hijas de Sion con Espíritu de juicio y Espíritu de fuego.`"^
footnote:[Isaías 4:4 Reina Valera de Gómez]
Y si se permanece continuamente en la luz,
entonces este juicio no cesará hasta que el trono
de Cristo se establezca en paz en el corazón;
porque este es Su juicio, y está sobre todo lo que está contra Su reino.
Y aunque los enemigos de la justicia no lo amen, aun así,
los justos se deleitan en el juicio de Dios y lo aman,
porque por él fueron redimidos y salvados,
y saben que esta es la primera promesa de Dios que tiene que recibirse.
Porque el Señor dice: "`Pondré Mi juicio como luz de los pueblos;`"^
footnote:[Isaías 51:4]
y cuando es recibido: "`Cercana está Su justicia`"^
footnote:[Isaías 51:5]
para ser revelada.

Por lo tanto, Su juicio debe pasar primero sobre todo lo que es injusto,
y nadie puede tener la justicia de Cristo salvo aquellos que reciben Su juicio.
Por esta razón el Señor dice: "`Los corté por medio de los profetas,
con las palabras de mi boca los maté; y mis juicios son como luz que sale.`"^
footnote:[Oseas 6:5]
Y con este fin el "`juicio es dado a los santos del Altísimo.`"^
footnote:[Daniel 7:22]
A Ezequiel a menudo se le mandaba a juzgar a los
pueblos y hacer que ellos conocieran sus abominaciones.
Y Jeremías estaba lleno de la ira del Señor, y estaba cansado de contenerse.
Y Miqueas estaba lleno del poder del Espíritu del Señor, y de juicio,
para denunciar a Jacob su rebelión y a Israel su pecado.
Y así en todas las eras el Señor ha puesto Sus juicios en Sus siervos,
y por medio de estos juicios ellos han juzgado a
los paganos y a aquellos que no conocen a Dios.
Y todos los que han creído y recibido los juicios de Dios y se han arrepentido,
han encontrado misericordia, pero los demás fueron endurecidos.

Ahora bien, este juicio es eterno,
y permanece firme en el cielo cuando pasa sobre la tierra.
Y esto ha sido encomendado a los apóstoles como una
doctrina--que a quien sea que ellos ataran,
sería atado; y a quien sea que ellos desataran, sería desatado.
Por esto todos los santos amaban el juicio;
porque sabían que era la ministración de Cristo,
la cual era ministrada sobre todo lo que está en Su contra,
y lo que sea que esté en contra de Cristo está en contra del alma.
Así que este "`juicio debe empezar por la casa de Dios;`"^
footnote:[1 Pedro 4:7]
pero el diablo lo rechaza donde él es quien guarda la casa.
Porque Salomón dice: "`El perverso se burla del juicio,`"^
footnote:[Proverbios 19:28]
y los hombres malos no lo entienden.
Porque el que no está dispuesto a recibir juicio es ciego, y no ve que su enemigo reina,
y seguirá reinado hasta que el "`juicio sea sacado a victoria`"^
footnote:[Mateo 12:20]
y establecido en la tierra.
Porque es solo cuando el "`juicio es ajustado a cordel y a nivel la justicia`"^
footnote:[Isaías 28:17]
que el pacto con el infierno y la muerte es anulado.

Pero ustedes que aborrecen la reprensión,
cuando se les habla de su malvado corazón (donde mora el pecado),
y de su naturaleza torcida, dicen: "`¿Quien los puso por jueces?`"
Y así buscan detener el ministerio de Cristo.
Pero el que tiene al Espíritu de Cristo tiene el Espíritu de juicio,
y cualquiera que sirva a ese Espíritu debe permitir que hable y que juzgue en ellos.
Por eso David dice: "`La lengua del justo pronunciará juicio.
La ley de su Dios está en su corazón, no vacilarán sus pasos;
pero el impío acecha al justo, y procura matarlo.`"^
footnote:[Salmos 37:30-31 RV 1602 Purificada]

=== Con Respecto a la Perfección

Dios es perfecto, y así son todas Sus obras y todos Sus dones.
Cualquiera que reciba Sus dones, recibe lo que es perfecto,
y al recibirlo y unirse a eso que es perfecto,
la criatura es progresivamente hecha perfecta en sí misma.
Un alma no puede estar unida a Dios, ni presentarse delante de Él,
ni ser bendecida por Él, más allá de lo que permanece en esta perfección;
porque al salir de esta perfección ella entra en la caída
y en la maldición. El hombre no tiene más de Cristo,
que lo que tiene de perfección; porque la perfección es de Cristo,
y la imperfección y el pecado son del diablo.
Estas dos cosas son contrarias, y surgen de diferentes terrenos,
y producen frutos contrarios.
El que es de Dios es de la perfección y cree en la perfección;
pero el que es de la serpiente no puede reconocerla ni creer en ella,
porque ha sido cegado por el dios de este mundo.

Dios envió a Su Hijo al mundo para predicar la perfección, es decir,
el regreso a la imagen perfecta del Padre, lo cual Él hizo diciendo: "`Sed, pues,
vosotros perfectos, como vuestro Padre que está en los cielos es perfecto.`"^
footnote:[Mateo 5:48]
Y después de haber dejado un ejemplo de perfección en todas las cosas,
Él ascendió y dio dones a los hombres "`a fin de perfeccionar a los santos,`"^
footnote:[Efesios 4:12]
para que todos pudieran llegar a la unidad de la fe, "`a un varón perfecto,
a la medida de la estatura de la plenitud de Cristo.`"^
footnote:[Efesios 4:13]
Por lo tanto, Él es un Redentor eterno,
que perfecciona la obra de Dios en cada generación
de aquellos que creen en Su obra y lo siguen.
Y todos Sus verdaderos ministros han procurado el mismo fin,
y han predicado la perfección,
y orado para poder "`presentar perfecto en Cristo Jesús a todo hombre,`"^
footnote:[Colosenses 1:28]
de quién ellos han recibido el don.
Y todos los que creen en Sus ministros, creen en la perfección,
y se esfuerzan por alcanzarla como el fin de su fe;
sabiendo que nada menos que la perfección puede darles
un reposo pleno y una redención completa.

Ahora bien, desde que el misterio de la iniquidad entró,
otro tipo de ministerio salió al mundo,
el cual ha adoptado una imitación en lugar de un don,
y ha engendrado otro tipo de fe que se opone enteramente a la perfección,
predicando contra ella,
considerándola como blasfemia y llamándola doctrina de demonios y cosas por el estilo.
Estos desean ser llamados los ministros de Cristo,
aunque ellos engañan a todos los que reciben sus palabras.
Y cualquiera que mire el fin de su obra,
podrá ver fácilmente tanta diferencia como la hay entre Cristo y Belial.
Porque la obra de Cristo es (y siempre ha sido) renovar
al hombre y regresarlo al estado de perfección;
y la obra del anticristo es resistir esto;
y cada uno tiene sus ministros adecuados para sus fines previstos.
El propósito de Cristo es perfeccionar; el del diablo es mantener en pecado,
y cada clase de ministros tiene su correspondiente fe, esperanza y dones--los unos puros,
y los otros impuros.
Según cada tipo de fe, así son los que creen y lo siguen.
La fe de Cristo es un escudo, y da victoria sobre la inmundicia, el pecado y el mal.
Pero la fe del diablo deja entrar el pecado,
y cree que debe ser así. Y si el diablo no hubiera hecho primero
que el hombre creyera en él en lugar de creer en Dios,
él nunca habría contaminado lo que Dios había perfeccionado.
Pero la manera por la que él obró al principio en el hombre,
es la misma con la que él mantiene su obra.

Por lo tanto,
solo aquellos que creen en la perfección en Cristo llegan a experimentar
la nueva creación. Pero todos los que están en la justicia imperfecta
y contaminada están en su propia justicia;
porque la medida más pequeña de la justicia de Dios es perfecta,
y los que se vuelven siervos de ella son por ella librados del pecado.
Así que, es por su incredulidad que ustedes destruyen sus almas,
y permanecen en sus propias obras, que nada perfeccionan.
Y entonces, midiéndose a sí mismos por sí mismos, se separan a sí mismos de Cristo.
Y midiendo su fe por su propia habilidad, permanecen en ese pacto que nada perfecciona.
Pero fue por esta razón que se halló defecto en el primer pacto, y se anuló,
porque "`no hacía perfecto, en cuanto a la conciencia, al que hacía el servicio.`"^
footnote:[Hebreos 9:9 Reina Valera de Gómez]

=== Con Respecto a la Obediencia

La obediencia espiritual y viva no es esa obediencia
que es en la forma y voluntad del hombre,
en la que los hombres y mujeres (en el primer nacimiento y sabiduría) leen las Escrituras,
encuentran lo que los santos hicieron en el Espíritu y poder del Señor Jesús,
y entonces se ponen ellos mismos a hacer lo mismo.
Esto es hacer una imitación en lugar de obedecer,
establecer las obras del hombre en lugar de las obras de Cristo,
obedecer la justicia propia en lugar de obedecer la justicia de Dios,
y por lo tanto cubrirse a sí mismos con trapos de inmundicias
en lugar de cubrirse con la justicia eterna.
Todos los que quieren experimentar la verdadera obediencia deben primero
experimentar una medida del Espíritu de Dios en la luz de Jesucristo.
Aquí ellos encontrarán movimientos e inclinaciones hacia Cristo,
y una fe que echa mano de la justicia de Dios, y una obediencia que es en Cristo Jesús,
el segundo Adán. Y a medida que la criatura se una en la luz al Espíritu de Cristo,
y crea en la vida de Jesús que se le ha manifestado,
será vivificada para caminar en la única obediencia,
que es contraria a la voluntad del hombre.
Porque solo existe una obediencia verdadera que es en Cristo Jesús,
que Él aprendió del Padre por nosotros,
para que en esta obediencia muchos sean constituidos justos.^
footnote:[Romanos 5:19]
Y todos los que aprenden a Cristo, aprenden Su obediencia,
que no era lo que Él veía u oía de los hombres, sino lo que veía y oía del Padre;
no en Su propio tiempo o voluntad, sino en el del Padre;
tampoco Él hacía nada por Sí mismo, sino solo lo que veía hacer al Padre.
Cristo siempre se encontraba en esta obediencia;
no haciendo lo que los escribas y fariseos hacían
(aunque ellos se sentaban en la cátedra de Moisés),
ni lo que el mundo aprobaba, sino lo que era contrario al mundo,
y contrario a Su propia voluntad,
estando siempre y únicamente sujeto al movimiento
del Espíritu del Padre que moraba en Él,
que era lo único que lo guiaba y lo preparaba para toda buena obra.

Y ahora Él guiará a todos los que crean en Él y sigan Su luz,
y los llevará gradualmente al mismo conocimiento y obediencia,
fuera de todo conocimiento, poder y obediencia de la carne;
para que la criatura participe por fe de la obediencia
de Cristo y de su poder de fe a fe.
Y todos los que Lo han aprendido, encuentran que "`como Él es,
así son ellos en este mundo,`"^
footnote:[1 Juan 4:17]
tanto en amor como en vida, tanto en poder como en Espíritu,
según la medida que hayan aprendido a Cristo.
Y esta no es una obediencia externa, sino una obediencia a la verdad,
mediante el Espíritu, que es en la vida y no en imitación,
en la voluntad de Dios y no en la voluntad del yo.
No está fundada en cosas que hayan visto los hombres, o que ellos hayan hecho,
por las cuales los hombres pueden imitar o hacer algo similar.
Más bien, está fundada en Jesucristo y en Su propia obediencia al Padre,
vista en la luz por la medida de fe que se ha recibido,
mediante la cual el creyente es hecho uno con ella, y ella obra en él. Por lo tanto,
puesto que el mismo Padre todavía demanda la misma obediencia en Espíritu,
le corresponde al creyente ahora ofrecerse a sí mismo, con todo lo que tiene,
en el mismo Espíritu, poder y obediencia que están en Cristo Jesús. Y así,
a medida que el hombre participe por fe de esa única obediencia, en el segundo Adán,
en esa medida será constituido justo, y no más allá;
así como todos son constituidos pecadores en la medida
que participan de la desobediencia del primer Adán,
y no más allá.

Por lo tanto, el que sabe participar de esta obediencia,
también conoce al Espíritu eterno en el que todos los hijos de Dios han
sido enseñados y capacitados para obedecer (en sus diversas medidas),
desde el principio del mundo.
Y esta obediencia no son obras hechas por ellos,
sino la justicia eterna de Dios siendo obedecida en el Espíritu,
según sus propios movimientos y deseos, los cuales son vistos en la luz.
Pero los que son ciegos de corazón no pueden saber esto,
los cuales les prestan atención a los movimientos y deseos de la carne, y los obedecen;
porque su mente ha salido de lo interno a los placeres carnales,
y no escuchan el llamado a la obediencia de Cristo.
Sin embargo, el espíritu carnal que lleva a lo externo, al mundo,
enseña a los hombres a hacer una imitación de esta obediencia,
y así engaña a los simples, estableciendo una semejanza sin vida,
y haciendo que se gloríen en la apariencia y no en el corazón. Y entonces,
cuando el Testigo de Dios en el corazón o conciencia de estos hombres,
les testifica que su obediencia no es perfecta o aceptada,
ellos concluyen que no existe ninguna obediencia
perfecta que sea alcanzable en este mundo;
porque no conocen la poderosa operación del Espíritu de Dios que
obra perfectamente en aquellos que creen y caminan en la luz,
mediante la cual se vuelven hechura Suya en Cristo Jesús. Estos son llevados a Su obediencia,
y Su obediencia es forjada en ellos (en su medida),
hasta que ellos se vuelven de un corazón, una mente, un alma, un Espíritu, una carne,
hueso y sangre, una obediencia y una vida, de modo que ya no vivimos nosotros,
sino que Cristo vive en nosotros;
y la vida que ahora vivimos es por la fe del Hijo de Dios.
Y aunque la plenitud
de esta obediencia no se alcanza de una sola vez,
aun así, la medida más pequeña de ella es perfecta y aceptada;
porque es aceptada en Aquel en quien es forjada.
Y así como la obediencia de un niño es tan pura y
voluntaria como la obediencia de un adulto,
asimismo es con los bebés en Cristo Jesús, según lo que el Padre requiera,
quien solo requiere lo que Él da,
y que solo da lo que es perfecto y lo que Él acepta perfectamente.

=== Con Respecto a las Buenas Obras

Así como hay solo uno que es bueno,
asimismo hay solo uno en el cielo y en la tierra
que puede verdaderamente obrar lo que es bueno,
quien por la Palabra de Su poder hizo todas las cosas buenas en el principio.
Por esta buena obra y voluntad el hombre fue hecho a la imagen de Dios,
y así permanecía en Su bondad.
Pero al caer de esa estabilidad que es en Dios,
y mirarse a sí mismo con el deseo de hacerse sabio, se volvió sutil y orgulloso,
y buscando ser como Dios, fue echado de Su presencia, de Su poder, amor y bondad,
a la oscura imaginación de su propio corazón caído. Así,
hallándose a sí mismo bajo la maldición (de la cual
la luz de Cristo en la conciencia da testimonio),
inmediatamente se puso a hacer semejanzas de Dios y de Su adoración,
y también de las buenas obras, de la fe, de la esperanza, de la paciencia, del amor, etc.
Pero estando bajo los poderes de las tinieblas,
y no teniendo experiencia ni de Dios ni de Su obra,
él es engañado por el príncipe de las tinieblas y se complace
a sí mismo con una imitación de las obras de Dios (sin poder);
y así imagina que él hace lo bueno.
Pero el testigo de Dios en su corazón
testifica contra él que su obra no es perfecta o aceptada.
Él también imagina que ha sido redimido,
aunque todavía está bajo el poder dominante de Satanás
y se encuentra cautivo a voluntad de él. Y Satanás,
a fin de atar al hombre más fuertemente,
lo lleva a una apariencia de adoración para que el hombre no sospeche que está en cautiverio,
ni se preocupe mucho por sus otras prácticas injustas.
Así es que, incluso el peor de los hombres en este estado, tiene su adoración,
y cada denominación piensa que está en lo correcto, y que no es tan mala como las otras,
porque tiene su forma de religión y sus pretendidas buenas obras,
aunque se ha apartado demasiado de la única obra de Dios.

Y no es nada fácil sacar de este engaño incluso al más ignorante de estos hombres,
sin embargo,
los que tienen mayor erudición y estudio pueden fácilmente llevarlos de un engaño a otro.
Pero toda la sabiduría del mundo no es capaz de llevarlos a la única buena obra de Dios,
ni enseñarles la manera por la cual es hecha.
Solo los que le presten atención a la luz de Cristo en sus oscuros corazones
(la cual manifiesta las cosas malas y los reprende por ellas),
que tengan cuidado de seguirla fuera del mundo y de la mente carnal,
y esperen en ella hasta que la Palabra viva sea recibida en sus corazones--solo estos,
digo, llegarán a la verdadera buena obra y voluntad de Dios.
Porque sin la Palabra nada fue hecho, y sin ella nada puede ser redimido.
Porque es la Palabra del Señor, cuando es escuchada y recibida,
lo que resucita a los muertos y le da vida a eso que está muerto en delitos y pecados.
Y es el poder de esta misma Palabra lo que produce
la obra de la justicia de Dios en el hombre espiritual.
Así es como la criatura es renovada en el espíritu de su mente
y recibe sabiduría y poder para escapar del mal y resistirlo,
y para manifestar todo lo que Dios engendra en el corazón.

Y a medida que el creyente continúe esperando diligentemente en la luz,
y sea obediente a esta obra en el Espíritu,
aprenderá cada vez más el poder y la enseñanza de Dios,
y también la obediencia de Cristo.
Y entonces la sabiduría y cuidado de Dios estarán sobre él,
llevándolo a sufrimientos y tribulaciones, a pruebas y tentaciones,
y a la fe y participación de Cristo en todo esto.
Y si la criatura se mantiene firme, ni un solo cabello de su cabeza caerá a tierra,
sino que sin duda saldrá más pura que el oro.
Así crecerá en el conocimiento de Cristo y en Su estado de Hijo,
a la medida de la estatura de la plenitud de un varón perfecto, a la semejanza de Dios.
Es de este modo que todos los santos fueron hechos conforme a Dios,
a través de Su poderosa operación,
la cual actuaba poderosamente en ellos según Su buena voluntad,
y de forma contraria a sus placeres carnales.
Y lo que es hecho de este modo es bueno, porque viene de la fuente de todo lo bueno.

Ahora bien, esta no es una nueva obra, sino la eterna y buena obra de Dios,
manifestada en la criatura, y a través de la criatura al mundo.
Y por ella Dios es glorificado,
quien es Su Padre y autor y consumador en todos los que creen verdaderamente.
Esta no es una obra del yo,
ni puede realizarse excepto donde se niega el yo y se toma la cruz.
Así toda jactancia queda excluida,
porque la criatura no tiene nada sino lo que ha recibido,
y no por su propia voluntad u obra, sino al creer en la luz,
y a través de la obediencia de la fe.
Y aunque pueda que haya una diversidad de obras,
según la obediencia del alma y su medida de crecimiento, aun así,
todas contribuyen a la única obra de la redención de la criatura,
y de la alabanza de Dios en ella.

El mundo es ignorante de la verdadera obra de Dios, aunque están predicando,
imponiendo y realizando sus buenas obras (como ellos las llaman);
pero todas sus obras no manifiestan el poder que saca del pecado y del mundo,
y de la conformidad con sus caminos y adoración. Pero la buena obra de
Dios en Sus santos (a medida que son obedientes a Su operación y están
sujetos a Su voluntad) siempre acerca a los hombres a Dios,
y los hace a Su semejanza y naturaleza,
hasta que sufren toda clase de mal por causa del nombre del Dios que está en ellos,
y son aborrecidos por el mundo.
Sin embargo,
los vituperios del mundo se vuelven grandes riquezas para
todos los que aman a Dios y son obedientes a Su obra.

Por lo tanto, las obras del yo y las obras de Dios son manifiestas en la luz.
Las unas son aquellas que los hombres ven, oyen o imaginan,
y por lo tanto se ponen a imitarlas en sus propias voluntades y maneras,
según lo que han concebido en su sabiduría caída y en sus mentes terrenales,
no en el Espíritu,
sino bajo el viejo régimen de la letra o de las tradiciones de los hombres.
Pero todos aquellos que quieran llegar a la obra de Dios,
serán enseñados a negar el mundo y sus propias voluntades,
a fin de que todo lo que esté en ellos se incline y conforme
al movimiento y a las operaciones del Espíritu,
los cuales son vistos por todos los que moran en la luz.
Estos, en el modo y tiempo del Espíritu,
producen los frutos del Espíritu ante los ojos de Dios.

=== Con Respecto a la Elección y la Reprobación.

Esta es una doctrina que está sellada para el mundo;
y ninguno que todavía esté en el estado de reprobación
podrá entenderla o recibirla verdaderamente.
Y aunque muchos son los debates acerca de ella en la oscuridad,
nadie realmente la entiende excepto los hijos de luz.
Porque hay un espíritu que neciamente acusa a Dios de haber determinado
la condenación de muchas personas antes de que vinieran al mundo;
y que, aunque busquen a Dios, aun así, no pueden ser salvas,
porque Dios ha establecido lo contrario.
De la misma manera, estos dicen que ya está determinado que algunos sean salvos,
aunque vivan y mueran en sus pecados.
En verdad, esta doctrina es del espíritu del mundo,
el cual no conoce los secretos de Dios que son revelados en el Espíritu,
y por lo tanto juzga carnalmente a partir de la letra y de las figuras y sombras.
Y aquellos que son de este espíritu no conocen la
verdad que se encuentra oculta en un misterio;
y estando sin luz, solo pueden imaginar.
Porque nadie entiende el propósito de Dios salvo aquel que regresa al principio;
porque en el principio la elección y la reprobación fueron establecidas por un
decreto eterno e inalterable en __las dos semillas__--la semilla según la carne,
y la semilla según el Espíritu.
Y aquel que pueda juzgar respecto a estas dos semillas,
también podrá entender los dos vasos que han sido ordenados,
uno para honra y otro para deshonra;
y conforme cada hombre se encuentre en uno de estos dos,
será lo que Dios determine con respecto a él.

Ahora bien, en la caída, todos están en la deshora, y por lo tanto son hijos de ira,
están bajo maldición, sin Dios y sin la promesa; y al no tener a Dios morando en ellos,
no son vasos de honor,
sino que están reprobados en cuanto a Él. Pero en Cristo Jesús la elección es conocida,
porque Él es la Semilla elegida en la cual se obtiene y se establece
la elección. Y Su luz es ofrecida a los hombres en medio de todas
las tinieblas para guiarlos fuera de la deshora,
fuera de la maldición y fuera de la caída;
y el que crea en Su luz (sin acepción de personas), Él lo guiará fuera del mundo,
a la purificación y santificación del cuerpo, del alma y de la mente,
hasta que el vaso sea transformado, y pase de estar bajo el régimen viejo de la voluntad,
afectos y deseos de la carne, al régimen nuevo del Espíritu.
Así, la criatura, en su corazón y en su mente,
es sacada de la carne (que está preparada para la deshonra,
y donde la deshonra se aloja) y llevada a vivir en el Espíritu,
donde los deseos de la carne no son satisfechos,
y por lo tanto el vaso de honra es experimentado,
el cual es preparado para el uso del Maestro.
Pero mientras los hombres permanezcan en la carne,
están preparados para deshonra y destrucción,
no conociendo al Maestro ni el uso adecuado de Sus vasos.
Y aunque Dios soporte estos vasos con mucha paciencia, Él podrá, en Su voluntad,
desplegar Su ira sobre los que no quieran recibir
la misericordia que Él les mostró en Su Hijo.
Y con esta misma intención, Él soportó mucho tiempo a Faraón, y permitió su opresión,
hasta que vio adecuado mostrar Su poder sobre aquel que por mucho
tiempo se había estado levantado por encima de Su semilla.
De la misma manera Él soportó a los Amorreos, hasta que "`su maldad llegó a su colmo;`"^
footnote:[Génesis 15:16]
y así Él hace con muchos en este día,
los cuales proceden de una iniquidad a otra hasta que llenan su medida,
para que Él pueda mostrar Su ira sobre aquellos que no quieren recibir Su Semilla.

Así será con todos los que no reciban la luz de Cristo, cuyo día de visitación ha pasado.
Estos tienen una medida de pecado que llenar en la otra semilla,
la cual no podrán exceder.
Y para este fin esa semilla maligna fue levantada y preparada,
para que Dios pueda mostrar Su poder sobre todos los que
"`no les pareció bien tener a Dios en su conocimiento,`"^
footnote:[Romanos 1:28 RV1602 Purificada]
para que puedan ser condenados todos aquellos que se complacen en la injusticia,
y sirven más a la criatura que al Creador,
cuyos corazones están llenos de toda inmoralidad y deseos carnales.
Estos en verdad son los vasos de deshonra.
Sin embargo "`si alguno se limpia de estas cosas, será vaso para honra,
santificado y útil para los usos del Señor, y preparado para toda buena obra.`"^
footnote:[2 Timoteo 2:21 Reina Valera de Gómez]
Pero los que viven en estas cosas están verdaderamente
reprobados con respecto a Dios y Su obra.

Por lo tanto, aquí está la elección y la reprobación:
aquellos que han nacido según el Espíritu, y aquellos que han nacido según la carne.
Aquellos que han nacido según la carne no son la semilla;
pero aquellos que viven por el Espíritu son contados con la Semilla.
Estos han obtenido la promesa, pero el resto son endurecidos.
Y por lo tanto no hay injusticia en Dios,
sino en los hombres que rechazan el consejo del Señor perjudicándose a sí mismos,
y escogen permanecer en eso que Dios ha maldecido.
Y todos los que continúen aquí serán endurecidos para su propia destrucción,
independientemente de todos sus esfuerzos y labores,
oraciones y lágrimas que tengan en esta naturaleza; porque estas cosas no son aceptadas,
porque son de esa semilla que está en enemistad contra la Semilla de Dios.
Dios ha decretado Su ira contra la semilla maligna,
pero en la otra Él ha establecido Su misericordia para siempre.
Por lo tanto, "`no depende del que quiere, ni del que corre,
sino de Dios que tiene misericordia.`"^
footnote:[Romanos 9:16]
Y Él ha puesto esta misericordia sobre todas Sus obras,
de modo que el que permanece en el mundo no la puede obtener.
Pero la luz que guía fuera del mundo nos lleva hacia arriba a ella,
y cualquiera que venga a Él, Él de ninguna manera lo echará fuera.
Pero el que no venga a Él ya ha sido echado,
porque no ha querido venir a la luz de la vida.

Así que escuchen ahora, todos ustedes habladores de vanidad,
que malgastan su tiempo debatiendo sobre la elección con sus mentes reprobadas.
Cuando sientan que la luz de Cristo los condena por sus deseos y placeres terrenales,
y que el Espíritu de Dios se mueve en ustedes en contra de la maldad de sus obras,
y que sin embargo ustedes no quieren ser obedientes,
y todavía endurecen sus corazones contra la luz--sepan entonces,
que _este_ es el estado reprobado.
Y sepan también que es el Espíritu de Dios el que contiende en ustedes contra este estado,
el cual no desea que ustedes mueran en él. Y dejen que la medida de luz
en su conciencia juzgue si su destrucción no es por causa de ustedes mismos,
ustedes cuyo camino es reprobado por Dios.
Y dejen que ella también sea un testigo contra ustedes
de que Dios no quiere que ninguno perezca,
sino que procedan al arrepentimiento y sean salvos,
y con este fin Él ha enviado Su luz para reprobarlos y guiarlos al arrepentimiento,
demostrando que Él no ha determinado su condenación antes de que ustedes hayan nacido.
Y dejen que la misma luz que los reprende por su pecado,
y les permite ver en su corazón que el Dios justo ha establecido
un día en el cual el pagará a cada uno conforme a sus obras,
dejen, les digo,
que esto sea un testigo contra la vana idea de que Dios
ha determinado de antemano dejarlos en su iniquidad.

Por lo tanto, el Juez justo de toda la tierra seguirá haciendo justicia.
Y para lograr esto,
Él ha puesto Su luz pura en el corazón de todos los
que están dispuestos a prestarle atención,
la cual les mostrará claramente a todos si están
en la Semilla elegida o en la semilla del maligno;
porque es esta luz, cuando se cree en ella y se sigue,
lo que revela el misterio de la elección y la reprobación.
Y sin esta luz nadie puede saber quien es elegido o reprobado,
ni puede juzgar en este asunto.

=== Con Respecto al Nuevo Nacimiento

Hay un viejo hombre, y un nuevo hombre, que son conocidos en la luz, cuyos nacimientos,
naturalezas y parentelas difieren según aquello de lo que han nacido.
Eso que es de la tierra es terrenal, carnal y corrupto;
y este es el estado del viejo hombre.
Todos los que están en este estado han caído de Dios y de Su pacto,
y están en la maldición,
enteramente ciegos de corazón con respecto a los misterios de Dios.
Y aunque ellos tengan una profesión de Dios y de
Su evangelio en la sabiduría natural de la carne,
no lo conocen a Él ni Su poder,
sino que están separados de Su vida y son llevados cautivos en las tinieblas
a la voluntad de aquel quien es el príncipe de esas tinieblas.
Lo que sea que un hombre haga en este estado está
bajo maldición. En este estado Caín ofreció su sacrificio,
pero no pudo ser aceptado, porque estaba fuera de ese estado que hace o es bueno,
aunque deseaba ansiosamente ser aceptado.
En este estado Esaú procuró la bendición y lloró por ella, pero no pudo obtenerla.
Y en este estado Nicodemo vino a Cristo, y aunque lo amaba,
y creía que había sido enviado por Dios, no pudo entrar al reino en ese estado,
ni entender el nuevo nacimiento.
Y este es el estado del que David habló, cuando dijo:
"`Si en mi corazón hubiese yo mirado a la iniquidad, el Señor no me habría escuchado.`"^
footnote:[Salmo 66:18]
Y en este estado están todos los que ahora adoran en la carne,
y en sus mentes carnales y sabiduría natural.

Pero lo que es nacido del cielo es celestial, espiritual, eterno e incorruptible;
y este es el estado del nuevo hombre, que es engendrado por la naturaleza divina de Dios.
Y así como es su naturaleza, también son sus obras, y sus deleites son espirituales.
Porque en verdad, como es el árbol, también son sus frutos; y como es el hombre,
también son sus obras.
Así que aquel que es nacido de esta Semilla es nacido de Dios;
y "`todo aquel que es nacido de Dios no peca,
porque Su Semilla permanece en Él.`" Y todos los que permanecen en esta Semilla,
y ella en ellos,
tienen la promesa y el poder que crucifica al viejo hombre con sus hechos,
pasiones y deseos;
así el cuerpo de pecado es despojado mediante el poder del cuerpo de Cristo,
y la redención es experimentada.
Y a medida que la criatura pasa de lo viejo a lo nuevo, pasa de la muerte a la vida;
porque la vida está en lo nuevo, y allí se recibe la victoria sobre el pecado,
sobre la tumba y sobre el infierno.
Ahora bien, el primer nacimiento habla de estas cosas en la naturaleza caída,
pero no puede recibir el poder y la victoria por
medio de los cuales se entra en el reino,
ni ve su gloria, y por lo tanto reposa y se deleita en cosas visibles,
y así se engaña a sí mismo en cosas cuyo fin es la destrucción. Pero los
que han nacido del Espíritu huellan con sus pies estas cosas,
y no pueden poner su mente en ellas, ni inclinarse a ellas,
ni conformarse a estas vanidades.
Y por lo tanto los celestiales no tienen comunión con los terrenales,
porque sus mentes son contrarias la una de la otra en todas las cosas.
Porque lo que es sabiduría para la una es locura para la otra, y siempre ha sido así.

Ahora bien, la Semilla que es de Dios lleva al corazón arriba a Dios,
pero la semilla que es de la tierra lleva a las cosas terrenales.
Los hijos de Dios son los que son guiados por Su Espíritu (del cual nacieron),
pero los hijos de este mundo son guiados por el espíritu de este mundo,
y están cautivos en los caminos, en las modas y en el amor del mundo,
donde la serpiente tiene su trono y reino,
y donde su poder es visto en todos los que son desobedientes a la luz de Cristo.
Y así,
en aquellos que se han entregado a su poder (debido a la ceguera de sus corazones),
él manifiesta su enemistad contra los hijos de Dios, nacidos según el Espíritu,
hijos de la luz y de la Semilla inmortal, los cuales tienen la imagen del Dios invisible,
y adoran en el Espíritu, y son dirigidos y guiados por ese Espíritu del cual nacieron.

Ahora bien,
los que han nacido del Espíritu no pueden permanecer en ninguna
forma de adoración más tiempo del que Dios se manifiesta allí,
sino que por Su Espíritu son guiados a seguirlo a dondequiera que Él vaya,
y fuera de lo que sea que Él se aparte.
Pero los que han nacido según la carne, solo ven lo externo y la forma,^
footnote:[Con la palabra _forma,_ Nayler se refiere a cualquier práctica, formalidad,
tradición, manera o método externo de realizar la adoración o el servicio religioso.]
y por lo tanto permanecen en la forma por mucho tiempo
después de que Dios se haya apartado de ella.
Estos luego se convierten en el trono de Satanás,
donde él se sienta y persigue a aquellos que siguen al Espíritu.
De este modo la serpiente a menudo ha engañado a la criatura,
al tomar algo de la forma que una vez fue usado por
los santos (cuando Dios moraba en ella),
y agregarle a esto sus propias invenciones,
llamándolas decencia y orden y cosas por el estilo.
Con esto ha engañado a la criatura de tal modo que la hace cumplir sus objetivos,
a saber, derramar la sangre de sus hermanos bajo un pretexto de error y blasfemia,
y de negar las ordenanzas y formas de adoración,
llamándolos cabecillas de sectas y herejías peligrosas, etc.
Así los hijos de luz siempre han sido contados con los transgresores,
pero nunca lo han sido realmente,
excepto que han transgredido las voluntades de los
hombres para guardar la voluntad de Dios.
Sin embargo, todos estos sufren como malhechores ante los ojos del mundo,
como no dignos de vivir en el mundo,
porque nacieron de la Semilla que está por encima del mundo,
la cual el hombre natural no conoce.
Por lo tanto,
"`el que había nacido según la carne perseguía al que había nacido según el Espíritu,
así también ahora,`"^
footnote:[Gálatas 4:29]
y estos piensan que rinden servicio a Dios, porque no conocen ni al Padre ni al Hijo,
sino que viven en tinieblas,
y no reconocen esa Semilla de la cual han nacido los hijos de luz.

=== Con Respecto al Bautismo de Cristo

En el mundo hay muchos tipos y formas de bautismo, pero en Cristo hay solo uno,
el cual es el del Espíritu.
Este es el bautismo de Cristo,
y todos los que son bautizados con este bautismo son bautizados en Su muerte,
son sepultados juntamente con Él para el mundo, para sus caminos y adoraciones,
para su amor y amistad,
y para toda esa parte en el hombre que se conformaría e inclinaría a estas cosas.
Y es a través de este bautismo en Su muerte que la
Semilla de Dios es levantada del sepulcro,
siendo vivificada por el mismo Espíritu que levantó de los muertos a Jesús. Y todos
los que son bautizados con este Espíritu (en quienes el viejo hombre está muerto y enterrado),
son levantados como una semilla espiritual para Dios, santos y celosos de buenas obras,
siendo engendrados nuevamente de otra naturaleza que viene de arriba,
la cual es solo una.
Y a medida que son bautizados en esto, crecen en un solo Espíritu,
en Dios el Padre y en el Hijo, Jesucristo.
Y por lo tanto los santos fueron "`todos bautizados por un solo Espíritu en un cuerpo,`"^
footnote:[1 Corintios 12:13]
fuera de esa naturaleza en la que están todas las diferencias, sectas y opiniones,
y por lo tanto llegaron a estar revestidos de Cristo, el cual es solo uno.
"`Porque todos los que habéis sido bautizados en Cristo, de Cristo estáis revestidos,`"^
footnote:[Gálatas 3:27]
con Su amor, Su mente, afectos, etc.
Y estos conocen un premio mayor que contender sobre los rudimentos del mundo,
lavamientos externos y cosas que consisten en tiempos, ocasiones, costumbres y personas.
Porque vemos que algunos abogan por salpicar agua sobre los bebés, otros por hundirlos,
unos por esta moda y otros por aquella,
todos disputando y contendiendo a partir de la letra
escrita en imitación al ministerio de Juan,
llamándolo el bautismo de Cristo.

Y cuál es el efecto de todas estas imitaciones e imaginaciones,
sino una multitud de bautismos, religiones y sectas,
y que cada secta con su líder y sus seguidores se ponga contra todos los
que no estén de acuerdo con la manera que ellos consideran la correcta.
De modo que ahora todos deben someterse a sus interpretaciones (que son
todas diferentes entre sí) o de lo contrario se dice que están en el error.
Así la forma es establecida por encima del poder, y ni siquiera es la verdadera forma,
sino solo lo que los hombres han concebido a partir de la letra,
o por los consejos de su propio cerebro;
y así todos están esparcidos y divididos en sus diferentes
imaginaciones y diversos bautismos.

Y esto fue lo que Pablo vio entrando en medio de las iglesias de su tiempo,
como ellas establecieron sectas según la persona por la que fueron bautizados,
siendo envanecidos por ellos, y puestos en contra de los otros apóstoles, unos de Pablo,
otros de Pedro, otros de Apolos, etc.
Y Pablo, al ver esto,
dio gracias a Dios por no haber bautizado a ninguno excepto unos pocos,
diciendo claramente, "`Cristo no me envió a bautizar, sino a predicar el evangelio,`"^
footnote:[1 Corintios 1:17]
aunque él estaba dispuesto a hacer uso de esta práctica
hasta que los vio creando un ídolo de ella,
y haciendo divisiones y grupos por ella,
y envaneciéndose unos sobre otros a causa de esta ceremonia, como se usa hoy en día. No,
es mucho peor en este día,
porque ahora el bautismo en agua es considerado la llave
que abre y cierra lo que los hombres llaman iglesia,
y algunos dicen que nadie puede ser salvo sin él.

Pero si ustedes supieran el propósito correcto del ministerio de agua de Juan,
sabrían que fue precursor del bautismo y reino de Cristo,
y un testimonio para todos los hombres de que las ceremonias,
ordenanzas y adoración judaicas (en las cuales ellos se llenaron de divisiones),
iban a tener un fin,
y que el ministerio y bautismo espiritual iba a establecerse
en la caída de las ordenanzas y elementos carnales.
De hecho, de todo esto ellos tenían que arrepentirse,
porque el reino de Dios estaba cerca--es decir dentro
de todos los que estaban dispuestos a creer.
Y los que creyeron con el tiempo llegaron a negar toda la adoración de los judíos,
con su circuncisión y ordenanzas externas de la letra,
y en lugar de esto predicaron el misterio y el fin de estas cosas en Espíritu.

Pero nosotros estamos constreñidos a negar sus bautismos actuales,
porque no los llevan al fin de los diezmos y de las
ofrendas y de las otras ceremonias judaicas.
Y aunque sabemos que,
si tan solo nosotros nos sometiéramos a sus diferentes formas de bautismo y adoración,
y a las voluntades de los hombres en estas cosas, no sufriríamos por parte de ustedes.
Pero entonces habría cesado la ofensa de la cruz^
footnote:[Gálatas 5:11 RV 1602 Purificada]
(como ha cesado en todos los que predican bautismos, ordenanzas carnales,
acepción de personas, conformidad a las voluntades de los hombres,
costumbres y métodos del mundo,
y la doctrina de la imperfección y del pecado presente durante toda la vida).
Pero por esta misma razón los primeros Cristianos sufrían
toda la envidia que los judíos podían reunir contra ellos,
los cuales sostenían la forma en la letra, pero negaban el poder y el Espíritu.

Y por lo tanto les digo a todos los que pueden conformarse
a los caminos de los hombres y agradarlos:
La cruz de Cristo ha cesado en ustedes, y con ella el poder.
Por esta razón ustedes siempre están predicando contra
los caminos y la iniquidad del mundo,
pero nunca pueden guiar a nadie a salir de estas cosas.
Ustedes son como aquellos que solo piensan en lo terrenal,
los cuales son enemigos de la cruz de Cristo,
quienes siempre están aprendiendo y enseñando,
pero nunca pueden llegar al conocimiento de la verdad que hace libre.
Y todos aquellos en quienes la cruz (con sus sufrimientos) ha cesado, están,
junto con los poderes de la tierra,
unidos contra todos los que toman la cruz para seguir
a Cristo en el camino del Espíritu.

Por lo tanto,
a todos les digo con respecto al bautismo exactamente lo
mismo que el apóstol dijo con respecto a la circuncisión:
'`Nosotros somos el bautismo,
los que en Espíritu adoramos a Dios y nos gloriamos en Cristo Jesús,
no teniendo confianza en la carne.
Aunque pudiéramos tener confianza en el lavamiento externo,
tal como antes lo habíamos recibido de aquellos que lo aprendieron por tradición.`'^
footnote:[Véase Filipenses 3:3-4]
Pero esto hemos aprendido, '`que no es el bautismo el que es exteriormente en la carne,
sino el bautismo que es en el Espíritu, y no en la letra;
la alabanza del cual no viene de los hombres, sino de Dios.`'^
footnote:[Véase Romanos 2:28-29]
Por este bautismo somos "`bautizados por un solo Espíritu en un cuerpo;`"^
footnote:[1 Corintios 12:13]
y "`todos los que han sido bautizados en Cristo, han sido bautizados en Su muerte,`"^
footnote:[Romanos 6:3]
y se han revestido de Él, y convertido en nuevas criaturas.
Y este es el bautismo que sirve para salvarnos--"`no
quitando las inmundicias de la carne,
mas dando testimonio de una buena conciencia hacia Dios por la resurrección de Jesucristo.`"^
footnote:[1 Pedro 3:21 Reina Valera 1602 Purificada]

Y con respecto a este bautismo,
damos testimonio de la verdad de que "`el que creyere y fuere bautizado, será salvo.`"^
footnote:[Marcos 16:16]
Pero en cuanto a los otros bautismos,
sobre los cuales los hombres están contendiendo a partir de la letra,
vemos su fin y lo que producen.
Ahora bien, si alguno viniera en el poder y Espíritu del bautismo de Juan,
o tuviera un llamado de Dios para ello,
no lo juzgaríamos ni nos opondríamos a él. Pero decir que cualquiera tiene poder
a través de la letra para tomar el bautismo de Juan e imponerlo sobre otros,
esto lo niego.
O decir que dejar la sombra externa y avanzar hacia el bautismo espiritual,
es menospreciar una ordenanza de Dios, esto también lo niego;
porque Pablo pudiera haber sido acusado de esto también,
quien dejó de bautizar con agua en su tiempo,
y predicó el bautismo en Espíritu en su lugar.
Y es por esto mismo que nosotros somos perseguidos en este día,
quienes no hemos sido enviados para hundir o salpicar con agua,
sino a predicar el evangelio de luz y vida, y el bautismo espiritual de Cristo Jesús,
a fin de llevar a todos los que reciben nuestro testimonio a un solo cuerpo,
por un solo Espíritu, no haciendo divisiones respecto a cosas carnales.
En verdad, para nosotros el día ha llegado, y las sombras se han ido.

Y esto les digo a aquellos
que buscan conocer la verdad del asunto:
Nosotros no despreciamos ninguna ordenanza de Dios a la cual Él
ha llamado a cualquiera de Su pueblo en cualquier generación;
pero tampoco nos atrevemos a adoptar tradiciones
que Dios no ha demandado de nuestras manos,
no sea que mantengamos a las personas en algo de lo que Dios se ha apartado,
y se nos diga: "`¿Quién ha demandado esto de vuestras manos?`"^
footnote:[Isaías 1:12]
Y en verdad, Dios nos ha mostrado un camino más excelente: La luz ha llegado,
y en ella hemos encontrado a Cristo Jesús, el guía de Su pueblo,
y el jefe de todas las edades.
Sí, hemos encontrado al Espíritu de la verdad,
que guía a toda verdad y a todo lo que Dios requiere;
y obedecer a este Espíritu es mejor que los sacrificios.
Y nosotros hemos sido enviados a dirigir a las personas a este Espíritu,
para que Cristo sea el todo en todos,
el cual suministra poder en la criatura para hacer todo aquello a lo que Él conduce.
Aquí todos los que crean en la luz podrán aprenderlo a Él,
quien engendra tanto el querer como el hacer,
y quien es el autor y el consumador de la fe en aquellos que tienen sus ojos puestos
únicamente en Él. Y es por medio de una medida de Su Espíritu que hemos recibido,
que nosotros podemos verlos a ustedes también,
que leen lo que los santos hicieron por un llamado de Dios,
y entonces se ponen a hacer lo mismo en imitación,
en su propia justicia y en un culto voluntario,
tanto en el bautismo como en todas las otras cosas a las
cuales no han sido guiados por el Señor. Pero esto les digo,
que el Padre ha dado a Su hijo como un jefe y guía para todas las edades,
a veces usando formas y a veces conduciendo fuera de ellas según Su beneplácito,
y en Su manera y tiempo, en cada generación.

Y es por esta razón que todos los que conocen la voluntad de Dios en este asunto,
no pueden soportar ver ninguna cosa visible establecida por encima de Él,
porque esto limita Su obra de guiar en Espíritu, o a Su pueblo de seguirlo en Espíritu.
Por lo tanto, nosotros no negamos ninguna forma a la que Cristo conduce por Su Espíritu;
pero negamos todas las formas que han sido impuestas por los hombres,
las cuales evitan que las personas sigan al Espíritu.
Porque los que son guiados por el Espíritu de Dios, éstos son hijos de Dios;
pero los que son guiados únicamente por la letra siempre han sido sus enemigos.
Es la ministración espiritual (y no la escrita) la que da el conocimiento de Dios,
y Su gloria y poder.
El que ha nacido según la carne tiene su camino en cosas visibles,
pero el que ha nacido según el Espíritu tiene una comida que el mundo no conoce.
¿Y en qué estado están ustedes,
que establecen la sombra para oponerse a la sustancia (que es el fin de la sombra),
y se aferran a la letra para oponerse al Espíritu;
letra que fue dada para declarar la suficiencia del Espíritu?
Así ustedes pervierten las Escrituras,
sacándolas de su lugar y fin (las cuales fueron dadas para dar testimonio de Cristo,
quien es la vida y fin de ellas),
y poniéndolas en el lugar de Cristo y pensando que en ellas tienen vida.
Y en este estado,
tanto las Escrituras como las ordenanzas y todos los otros dones de Dios, son abusados,
torcidos y sacados de sus lugares, y hechos inútiles.

=== Con Respecto a la Cena del Señor

Sobre esto contienden los profesantes de religión en todo el mundo; y en verdad,
es un gran misterio para los que todavía no han visto al Señor.
Pero desde que el misterio de la iniquidad comenzó a obrar,
los maestros y profesantes del mundo (habiendo perdido su
morada en el cuerpo de Cristo) han corrido a imaginaciones,
y están tan lejos de la vida de esta cena que han perdido incluso la forma
y la primera institución de la sombra tal como fue realizada por Cristo.
Y en verdad,
ellos ahora están tan lejos de ser uno en la sangre
de Cristo a través de la cena del Señor (así llamada),
que están derramando la sangre uno del otro en sus contiendas respecto a la forma.

Ahora bien,
esto fue hecho por Cristo cuando ellos se sentaron a la mesa y comieron la Pascua,
y bebieron la copa que Él les dio, y todas las veces que ellos comieran este pan,
y bebieran esta copa tenían que hacerlo en memoria de Él,
"`anunciando la muerte del Señor hasta que Él viniera.`"^
footnote:[1 Corintios 11:26]
Y este misterio es lo que los apóstoles recibieron del Señor,
y así fue practicado en la pureza de la iglesia (antes de que corrieran a la confusión)
por aquellos que perseveraban en la doctrina y en la comunión de los apóstoles,
"`partiendo el pan en las casas, y comiendo juntos con alegría y sencillez de corazón,`"^
footnote:[Hechos 2:46]
en el temor y favor de Dios.
Y esto tenía que ser hecho en todas las ocasiones,
todas las veces que comieran y bebieran;
porque en su comer y beber debían hacerlo para el Señor,
y así tener comunión con Su cuerpo y Su sangre, y guardarse puros de toda contaminación,
no participando de la mesa de los gentiles, que comen para satisfacer sus deseos.

Y, por lo tanto,
a fin de guardarse de la indulgencia y de comer para satisfacer sus deseos,
ellos tenían que hacerlo en memoria de la muerte de Cristo hasta que Él viniera; quien,
cuando viene, toma el dominio y gobierno de la criatura sobre Sus hombros,
y de este modo siempre los mantiene fuera de la concupiscencia
y del exceso en todo lo que hacen.
Y así la creación es restaurada y reconciliada con
Dios en la venida o aparición de Jesucristo.
Por lo tanto, se les ordenó a los discípulos que esperaran Su venida en Jerusalén,
y ellos anunciaron Su muerte todas las veces que comieron el pan, hasta que Él vino.
Y luego de que Él llegara a los apóstoles, ellos,
en condescendencia con aquellos que eran débiles en la fe,
para quienes Cristo todavía no había aparecido, partían el pan en las casas,
y comían con sencillez de corazón.

Por esta razón Pablo los exhortaba que cuando comieran y bebieran,
debían hacerlo para la gloria de Dios, y les advertía respecto a hacer lo contrario.
Y Judas vio como algunos habían entrado a las iglesias,
y "`convertían en libertinaje la gracia de Dios`"^
footnote:[Judas 1:4]
andando según los deseos de su propio corazón,
mediante los cuales mancillaban la carne y vivían en ella.
Estos,
no teniendo al Espíritu para que los gobernara "`se
apacentaban a sí mismos sin temor alguno,`"^
footnote:[Judas 1:12 Rv 1602 Purificada]
y eran "`manchas en sus ágapes,`" quienes habiendo una vez sido
iluminados y luego dado lugar otra vez a los deseos y al exceso,
llegaron a estar "`dos veces muertos, y desarraigados,`"^
footnote:[Judas 1:12]
aunque "`sus bocas hablaban palabras infladas.`"^
footnote:[Judas 1:16]

Y de este tipo de personas existen muchos ejemplos en este día,
quienes han experimentado algo vivo en ellos que los ha
llevado a la esperanza de la aparición del Señor,
pero luego la plenitud y el exceso los han vencido por no
comer siempre en temor y en memoria de Su venida.
Y así estos vuelven a estar muertos a cualquier esperanza de Su aparición en el presente,
y entonces alejan Su venida a otro mundo;
y sin embargo continúan contendiendo respecto a las sombras o figuras de Su venida,
de acuerdo con sus imaginaciones.
Pero el Señor Jesús, para evitar esto, les ordenó a Sus discípulos que,
de manera figurativa,
cuando comieran y bebieran anunciaran Su muerte hasta que Él viniera.
Y estos les dieron un ejemplo y una advertencia a aquellos que fueron convencidos,
de que en todo temor y modestia esperaran Sus apariciones,
diciéndoles "`que su modestia fuese conocida a todos los hombres,
porque el Señor está cerca.`"^
footnote:[Filipenses 4:5]

Pero ahora los que viven en la libertad de la carne
y en las observaciones externas ponen su venida lejos,
aunque tienen determinado un día cada año para ir a su lugar de reunión
y comer pan y vino en una ceremonia solemne inventada por ellos mismos;
o quizás una vez al mes, o tres veces al año,
unos afirmando que el cuerpo y sangre de Cristo está en la criatura
después de que la cena es consagrada (como ellos dicen);
otros diciendo, "`¡no!,
sino que es espiritual después de la consagración;`" otros diciendo, "`¡no!,
es natural y no cambia con palabras,`" etc.
De modo que uno imagina que el cuerpo de Cristo está realmente en el pan y el vino,
y otro dice que solo es real por fe (como ellos la llaman), pero todos coinciden en esto:
que después de comer y beber regresan a sus placeres
en la carne y en las modas del mundo,
para ahí comer y beber para su deleite y gastarse a sí mismos en sus deseos.

Esto es lo que sucede con todos los que no disciernen Su cuerpo en sus comidas,
quienes se apegan a sus observaciones, y dicen que Él siempre está por venir,
o que Su venida ya ha acontecido.
Pero el ojo carnal, que no puede ver más allá de lo visible,
nunca puede ver a Aquel que está presente para guiar la creación fuera de la concupiscencia.
Y, por lo tanto, cuando comen, esto no es el comer la cena del Señor,
ni tampoco Él cena con ellos en el nuevo reino;
sino que en el viejo espíritu de concupiscencias
estos se convierten en una mesa del diablo,
donde la creación es sacrificada para su uso.
Así él los mantiene en la observación de un día o una forma,
lo cual ellos creen que es adoración,
pero él sigue teniendo el gobierno de todas sus vidas a través de su espíritu.
Y de aquí viene toda clase de lascivia y ligereza, contiendas, peleas,
pleitos y violencia, deportes y vanidades,
demasiadas como para ser mencionadas en este lugar,
en todo lo cual la creación es gastada, y por lo cual ellos darán cuenta.

Por lo tanto, por el bien de aquellos que están perdidos en esto,
y con sus mentes angustiadas respecto a ello, lo que he recibido lo declararé:
Si ustedes pretenden cenar con el Señor,
o anunciar la muerte del Señor hasta que Él venga,
procuren que todas las veces que ustedes coman y beban, sea en memoria de Él,
y en Su temor, para que puedan dar testimonio de haber muerto a todo deseo y exceso,
que en verdad es lo que ha inmolado al Cordero desde la fundación del mundo,
y es el gran enemigo de Su aparición,
por lo que Él es crucificado espiritualmente en la "`grande
ciudad que en sentido espiritual se llama Sodoma y Egipto.`"^
footnote:[Apocalipsis 11:8]
Porque todos ustedes que "`viven en deleites sobre la tierra, y son disolutos;
que han engordado sus corazones como en día de matanza;
han condenado y dado muerte al Justo, y Él no les hace resistencia.`"^
footnote:[Santiago 5:5-6]
Y por lo tanto ustedes deben experimentar una muerte
a todo eso antes de poder cenar con el Señor,
o Él con ustedes.
Pero si ustedes comen en memoria de Él, y llegan a morir a eso que lo crucificó,
entonces anuncian la muerte del Señor hasta que Él venga;
y cuando venga Él no los encontrará "`comiendo y bebiendo
con los borrachos ni golpeando a sus consiervos.`"^
footnote:[Mateo 24:49]

Y esto ha sido recibido del Señor en la luz eterna
como el propósito verdadero de la cena del Señor,
para que en Su venida todos sean hallados en una condición apta para recibirlo;
cuya aparición niegan aquellos que se alimentan sin temor,
y crucifican nuevamente en sí mismos.
Y por lo tanto en otro lugar, hablando de Su venida,
Él les advierte que "`miren por ellos mismos,
que sus corazones no se carguen de glotonería y embriaguez y de los afanes de esta vida,
y venga de repente sobre ellos aquel día, porque como un lazo vendrá sobre ellos.`"^
footnote:[Lucas 21:34-35]
Porque así será con todos los que estén en este estado cuando Él aparezca,
y por lo tanto no pueden recibir el día de Su visitación,
porque sus corazones se han vuelto a lo externo, a las cosas carnales.

=== Con Respecto a la Redención

Hay muchos que se jactan y se glorían de redención,
quienes no conocen más que palabras e imaginaciones.
En verdad,
pocos han llegado tan lejos como para saber qué es lo que necesita ser redimido,
y a quién fue hecha la promesa, y en qué Semilla^
footnote:[Nota de pie de página de George Whitehead:
"`La semilla se considera en dos sentidos: la semilla que es Cristo,
que es la que redime, y la semilla de Abraham, a saber, los creyentes,
que son los que Él redime.
Los hijos de la promesa son considerados como la semilla.`"]
es vista y recibida.
Porque hay una Semilla en la cual la promesa de redención fue hecha al alma,
pero todos los que se deleitan en el pecado y en
la libertad carnal son de una semilla contraria.
Estos no ven necesidad de redención, sino que están en reposo en su pecado;
no necesitan de médico porque dicen que no están enfermos,
pero todo lo que hablan de redención no cambia en nada su verdadero estado.

Pero si ustedes encuentran algo en su interior que en medio de todos sus deleites mundanos,
clama '`¡vanidad y vacío!`' y no puede encontrar satisfacción en estas cosas,
ni conformarse a este mundo o deleitarse en la iniquidad;
si hay algo que no se atreve a abogar por el pecado sino
más bien clama '`¡ay de ti!`' a causa de tu iniquidad,
y se aflige por las abominaciones de sus tiempos;
y si ustedes encuentran algo que se vuelve a Dios
implorando vida y fuerza contra toda vanidad y maldad,
y desea seguir a Cristo fuera del mundo; yo digo,
si ustedes encuentran una Semilla como esta en su interior,
aunque sea la más pequeña de todas las semillas, aun así, esta es la Semilla del reino,
a quien fue hecha la promesa.
Y ustedes no han sido redimidos por Cristo Jesús más allá de lo que esta Semilla
se haya levantado para reinar en ustedes sobre todo lo que sea contrario.
Porque esta es la planta de renombre de Dios, el lirio entre los espinos,
la cual es ahogada por los afanes de este mundo,
y por el engaño de las riquezas y de los placeres,
que no la dejan llevar fruto para Dios.
Pero Dios ha puesto esta Semilla en ustedes para Sí Mismo,
para que en ella Él pueda enseñarlos provechosamente,
y para que de ella ustedes puedan recibir sabiduría y fuerza, sí,
todo lo que sea necesario para ustedes en la medida a la que han sido llamados.

Y la razón por la que ustedes no conocen al Padre ni al Hijo es porque
esta Semilla yace oprimida y velada bajo sus deseos y placeres,
porque es al nacimiento espiritual que Él se revela.
Y aunque ustedes hablen de redención, aun así, no conocen a Dios,
ni experimentan Su poder, vida o presencia como un líder que los saca del mal,
y que les da victoria sobre el príncipe de este mundo,
más bien son llevados cautivos a voluntad de este príncipe, a hacer sus obras,
y por lo tanto están bajo la misma condenación en la que él se encuentra.
Y todas sus pláticas acerca de redención no los librará de sus trampas,
sino que ustedes no pueden evitar caer continuamente en su tentación,
cometiendo el pecado al cual él los lleva, y así permanecen siendo hijos del diablo.

Pero la Semilla que es de Dios yace bajo todo esto, y sufre debajo de ello,
en muerte y cautividad, cuando las prisiones de maldad están sobre ustedes.
Y por esta razón ustedes no pueden recibir Su poder, Su promesa o Su salvación,
lo cual está todo puesto en la Semilla;
porque mientras ustedes permanezcan en sus deleites,
la Semilla no es de ustedes ni está con ustedes, sino más bien en contra de ustedes.
En verdad, en este estado ustedes no son de la Semilla de la promesa,
sino enemigos de ella,
y están pecando contra ella con sus deseos y placeres y con su voluntad propia.
Así ustedes están en la naturaleza y estado de Faraón,
que mantiene la Semilla de Dios en la casa de servidumbre,
y no se compadece ni considera sus clamores.
Porque ella en verdad clama contra el orgullo y el exceso de ustedes,
y contra su envidia e ira,
y contra toda la iniquidad por la que ustedes la
oprimen en ese estado en que la muerte reina.
Y por esta razón la ira de Dios viene sobre el mundo de maldad,
el cual es enemigo de la Semilla del pacto, y no está unido a ella,
sino a la semilla de una naturaleza contraria.

Pero todos los que están unidos en la luz a la Semilla de Dios,
participan del amor y la vida que están en Cristo Jesús. Y todos los que sienten
esta Semilla viva y levantada en el corazón por el Espíritu de Jesús,
conocen "`la planta de renombre de Dios,`"^
footnote:[Ezequiel 34:29]
el renuevo de Su propio plantío, en el cual se encuentra el fruto del Espíritu.
Estos saben donde esperar el suministro de toda necesidad,
y el consejo en toda dificultad;
donde se recibe la ley que es espiritual y la justicia de la fe.
Sí, es en esta Semilla que los hombres son redimidos,
y en la que los santos tienen comunión en la luz con el Padre y con el Hijo,
y experimentan todos los dones y gracias por medio de los cuales la criatura
llega a ser librada de la ley del pecado para que pueda casarse con Cristo.
Y ellos, habiendo sido librados de la esclavitud al pecado y a Satanás,
están libres para servir al Dios vivo.
Y esta es su libertad, a saber, la justicia que es eterna,
la cual es experimentada a medida que el alma es redimida del hoyo
de corrupción. Porque donde esta Semilla se haya levantado,
ahí la criatura recibirá de Dios de Su plenitud;
pero donde la Semilla se encuentre en el sepulcro, ahí la maldición permanecerá,
y el pecado y la transgresión reinarán. Sí,
cuando la Semilla se haya levantado en el interior
y el nacimiento inmortal haya sido dado a luz,
entonces la criatura será bendecida por Dios a causa de la Semilla,
y es en esta Semilla que Dios es adorado verdaderamente.
Pero donde sea que la muerte siga reinando,
ahí el sacrificio del hombre será una abominación,
porque los que están muertos no pueden alabar a Dios.

Por lo tanto,
esto les digo a todos los que sienten esta cosa santa moviéndose
en ustedes contra sus deseos y placeres mundanos:
tengan cuidado,
y no se engañen con un simple hablar de redención mientras esta Semilla
yazca en prisión y no se haya levantado por encima de todos sus deseos.
Más bien esperen en la luz de Cristo, la cual les permite ver esto,
de modo que puedan experimentar Su poder levantando
Su Semilla en ustedes sobre todo lo que es contrario,
y así ustedes reinarán con Él sobre todo el mundo y sus caminos impíos.
Pero si ustedes han sentido estos anhelos en pos de Dios en sus almas,
y, aun así, no les han prestado atención,
tengan cuidado no sea que Él que les dio estos anhelos
para su salvación se los quite otra vez^
footnote:["`Quitadle, pues, el talento, y dadlo al que tiene diez talentos.
Porque al que tiene, le será dado, y tendrá más; y al que no tiene,
aun lo que tiene le será quitado.`"
Mateo 25:28-29]
y los entregue a sus deseos sin reprensión,
porque Su Espíritu no contenderá con ustedes para siempre.^
footnote:[Génesis 6:3]
Y entonces mejor les hubiera sido no haber nacido.
Ay, esta ha sido la porción de muchos,
quienes después de haber recibido muchas reprensiones e inclinaciones al bien,
ahora han sido entregados a una mente reprobada para
que llenen su medida de pecado con avidez.
Estos son los que ahora se glorían en su vergüenza y se jactan de su inmundicia.
Y oh,
Su día está llegando sobre muchos más, quienes ahora le prestan muy poca
atención a la medida de la gracia de Dios que se mueve en ellos,
más bien viven en sus deseos, pecando en contra de sus conciencias por motivos egoístas,
y aun así se complacen a sí mismos con un simple hablar de redención.
Porque la profesión común que ahora muchos han adoptado, convierte la redención
de Cristo en una cubierta para la inmoralidad y la libertad carnal;
pero todos los que han experimentado la redención de Cristo a través de
Su preciosa sangre han sido redimidos y sacados de toda conducta vana,
y llevados a la conducta santa de Aquel que los ha llamado a ser santos.
Porque la redención que es en Cristo Jesús es que "`nuestras conciencias
sean limpiadas de obras muertas para que sirvamos al Dios vivo.`"^
footnote:[Hebreos 9:14]
Por esto "`Él se dio a Sí Mismo por nosotros para redimirnos
de toda iniquidad y purificar para Sí un pueblo propio,
celoso de buenas obras.`"^
footnote:[Tito 2:11]
Y Él "`con Su sangre nos ha redimido para Dios, de todo linaje y lengua,`"^
footnote:[Apocalipsis 5:9]
y de toda nación pecaminosa, para que sigamos al Cordero,
y no sigamos los deseos mundanos.

Por lo tanto, con la luz de Cristo que les permite ver sus transgresiones,
escudriñen sus corazones, para que vean si la Semilla justa,
que se mueve en ustedes en pos de la justicia,
no se encuentra oprimida y cargada por la semilla del maligno,
y por esa naturaleza que ama los placeres carnales.
Porque si ustedes todavía son llevados cautivos a hacer las obras de Satanás,
¿que redención tienen aparte de solo hablar de ella?
Es como un hombre que imagina que come, pero todavía está hambriento,
así ustedes imaginan que son libres, pero siguen sirviendo al pecado.
Y mientras continúen siendo siervos de pecado, son libres de la justicia,
así como aquel que es siervo de la justicia es libre del pecado.
Es muy fácil imaginar justicia y redención, pero "`el que hace justicia es justo,
como Él es justo.`"^
footnote:[1 Juan 3:7]
Y esto no se experimenta cuando la Semilla de Dios
yace oprimida bajo sus deseos y no es atendida.

=== Con Respecto a la Justificación, Santificación y Mortificación^
footnote:[Con mortificación, Nayler se refiere a hacer morir las obras de la carne.
Véase Romanos 8:13.]

La sabiduría del hombre en la caída,
habiendo encontrado estas tres palabras en la Escritura,
las ha dividido y separado en su imaginación,
pero estas tres cosas son una sola realidad espiritual,
que no puede dividirse en la experiencia del hombre;
porque es un solo Espíritu el que obra todas estas cosas en donde sea que Él esté presente,
según la medida recibida.
Y Él es el Justo, quien vive en la criatura por la fe, y la criatura vive en Él,
y por lo tanto Él es el que justifica y santifica a todos los que creen,
y el que hace morir esa naturaleza que está fuera de la fe,
de modo que no se puede encontrar una de estas cosas sin las demás.
Porque el poder que santifica también es lo que hace morir,
y este mismo poder es el que justifica;
y todos los que saben lo que es experimentar estas cosas de manera viva,
entienden estas palabras.

Ahora bien, hay personas cuyo deseo por el cielo es mayor que su deseo por santidad,
las cuales, para no estropear sus placeres carnales,
han concebido (en la imaginación de sus cerebros)
una justificación sin santificación o mortificación,
torciendo esas escrituras que condenan las obras de la ley,
tratando con ellas de excluir también la justicia de la fe.
Y debido a que la Escritura dice que Dios justifica
o perdona a los impíos a través de la fe,
ellos por lo tanto se consideran a sí mismos justificados en su impiedad por
una creencia que ellos llaman fe (aunque están sin la verdadera fe en Cristo).
Porque esa fe que no echa mano de la justicia de Dios no es la fe de Cristo,
sino más bien una cosa muerta;
porque la verdadera fe de Cristo revela una justicia aparte de la ley, de fe a fe,
y también vive en ella.
Así que los hombres son justificados a medida que son santificados y mortificados,
y no más allá. Y donde no hay justicia, no hay verdadera fe en Cristo;
pero donde la justicia de Dios está obrando en la criatura,
ahí se experimenta una verdadera creencia y se muestra la fe por sus obras.
Pero la "`fe sin obras es muerta,`"^
footnote:[Santiago 2:20]
estando sola, porque "`como el cuerpo sin espíritu está muerto,
así también la fe sin obras es muerta,`"^
footnote:[Santiago 2:26]
y así también su justificación sin santidad y sin hacer morir el pecado es muerta.
Y al final verán que eso en ustedes que justifica
al impío es lo mismo que condena al justo,
y ambos son igualmente una abominación al Señor.^
footnote:[Proverbios 17:15]
Pero este es el estado de ustedes,
que defienden el pecado y viven en deleites y en desenfreno sobre la tierra; sí,
ustedes crucifican al Justo y Santo, y salvan al injusto de la muerte.
Así ustedes muestran que no conocen a Aquel que es justo,
quien también es el que justifica, mortifica, santifica y redime.

Y aunque las Escrituras mencionan estas tres cosas,
no es para que los hombres las dividan y les hagan
creer a las personas que pueden tener una y no todas,
sino para demostrar los diferentes efectos de la única obra de redención del hombre,
los cuales son todos llevados a cabo por un mismo poder en la criatura.
Porque es la sangre y Espíritu de Cristo la que purifica de la inmundicia,
y por lo tanto despoja al viejo hombre, y hace morir las obras de la carne,
y así santifica y justifica.
Sin embargo, ninguna de estas cosas ocurre sin la obediencia del hombre,
puesto que son obras de fe y no del yo.
Porque, por la ley de la fe queda excluida toda santificación,
mortificación y justificación que el hombre haga por sí mismo,
porque estas cosas son la obra de Dios llevada a cabo por Cristo en el creyente,
el cual también debe unirse a ella en fe y obediencia.
Porque Dios obrará en todos los que crean en la luz a fin de que reciban a Su Hijo,
en quien se encuentra la promesa y el poder para mortificar, santificar y justificar.
Pero los que quieren participar de Su justificación sin obediencia
ni participación (obedecer y participar) de Sus padecimientos,
son los que están justificados en un sueño, mientras el pecado todavía reina,
y el injusto vive y actúa en ellos.
En verdad, esto no es más que el yo buscando justificarse a sí mismo,
aunque el hombre sigue muerto en delitos y pecados, y no es justo ante Dios.

Pero los santos sufrieron la pérdida de todas las cosas,
teniéndolas por basura "`a fin de conocer a Cristo, y el poder de Su resurrección,
y la participación de Sus padecimientos,
llegando ellos a ser semejante a Él en Su muerte.`"^
footnote:[Filipenses 3:10]
A través de la muerte, estos llegaron al poder y participación de Su resurrección,
mediante lo cual fueron justificados,
siendo levantados juntamente con Él a una nueva vida;
y por fe recibieron el don de la justicia de Dios y se volvieron siervos de ella,
y así llegaron a ser libres del pecado.
Esta es la verdadera justificación, en la cual no hay condenación. Aquí,
las obras de la carne son mortificadas, y la criatura ya no anda conforme a la carne,
sino conforme al Espíritu.
Porque la condenación es para todos los que andan conforme a la carne;
pero el que anda en el Espíritu es justificado,
porque ya no satisface los deseos de la carne.
Y en estos se experimenta una mortificación de la naturaleza que quebranta la ley,
y se conoce al Justo que cumple la ley en todos los que no andan según la carne,
sino según el Espíritu.
Por lo tanto, "`no son los oidores de la ley los justos ante Dios,
sino los hacedores de la ley serán justificados.`"^
footnote:[Romanos 2:13]

Ahora bien, en el primer estado del hombre, en su estado terrenal, la ley es quebrantada,
y la mortificación y santificación son negadas.
Aquí los hombres desean ser justificados de la culpa del pecado,
pero no del amor y poder del pecado.
Sí,
ellos quisieran tener sus deleites carnales tanto en el mundo como en el cielo también;
pero esta esperanza vana perecerá. Pero en el estado del segundo hombre,
la ley es cumplida a través de la mortificación,
santificación y justificación del Espíritu.
Y ningún hombre podrá ser justificado donde el Justo no viva;
porque aquello que le da vida al justo es lo mismo que justifica a la criatura.

=== Con Respecto a Ley

Todos los que no conocen el ministerio del Espíritu
están confundidos con respecto a la ley.
Porque yendo a las Escrituras y encontrando que ahí se menciona
un ministerio de la letra y un ministerio del Espíritu,
y al no estar ellos mismos bajo ninguno de estos ministerios (salvo en sus imaginaciones,
o según conceptos que han recibido, pero no de la boca del Señor),
entonces algunos dicen que están bajo la ley y que ella todavía continúa;
otros dicen que solo la parte moral continúa; otros dicen, no,
sino que todo se ha acabado,
y ellos no están bajo ninguna ministración de la ley sino bajo la gracia; y de este modo,
por su supuesta fe, ellos invalidan la ley, sin entender lo que dicen al respecto.
Y en verdad,
esto es todo lo que saben (ya sea de la ley o del evangelio)
aquellos que leen la letra con su sabiduría carnal,
e imaginan qué es la ley y qué es la gracia,
sin conocer al Espíritu por el cual ellas fueron ministradas a los santos,
quienes tenían la ley escrita en sus corazones,
y la gracia también allí. Estos saben que la una no invalida la otra,
sino más bien la confirma;
porque la venida de Cristo no fue para abrogar la ley sino para cumplirla.
Sí, Él no vino a alejar la ley, sino a acercarla,
para que con Su luz todos la pudieran ver tal como
está escrita en el corazón por el Dios vivo.
Y tan lejos está Él de destruir o quitar la ley,
que Él la establece con más fuerza y pureza,
diciendo que "`ni una jota ni una tilde pasará de la ley,
hasta que todo se haya cumplido.`"^
footnote:[Mateo 5:18]

Y donde fue dicho en la letra,
"`No cometerás adulterio,`" Él dice "`No codiciarás.`" En la letra fue dicho,
"`No perjurarás;`" pero en el Espíritu, Él dice, "`No juréis en ninguna manera.`"
En la letra dice, "`No matarás;`" pero en el Espíritu,
"`No te enojarás;`" y cualquiera que haga alguna
de estas cosas será culpable delante de Dios.
Ahora bien, lejos de invalidar la ley, el Espíritu la declara en su pureza,
de modo que incluso aquellos que pudieran verse libres de culpa según la letra,
pueden ser hallados culpables según la ley del Espíritu.
Por lo tanto,
por medio de Cristo Jesús (el cual es fin de esa ley) todos pueden ver su propia condenación,
y, por la fe en Él, llegar a ser libres,
no por la sangre de los toros y de los machos cabríos,
ni por las cenizas de la becerra rociada, ni por sacrificios, templos, altares, tiempos,
o días de reposo externos según la letra, sino por todo esto en Espíritu,
lo cual en Cristo Jesús es ministrado al alma y a la conciencia,
para purificar de pecado y "`limpiar la conciencia
de obras muertas para servir al Dios vivo,`"^
footnote:[Hebreos 9:14]
lo cual el ministerio de la letra y de las ordenanzas carnales no pudo hacer.

Y esta es la razón por la que el ministerio de la letra tenía que perecer:
porque no podía hacer perfectos, en cuanto a la conciencia, a los que se acercaban.^
footnote:[Hebreos 9:9; Hebreos 10:1]
Por lo tanto el ministerio del Espíritu es predicado en su lugar,
el cual concede un conocimiento perfecto de pecado y una perfecta redención de este;
y de todas las cosas de las cuales la ley externa no pudo librar.
Porque, aunque la letra puede mostrarle a un hombre su condenación, aun así,
no puede dar vida; puede mostrar el deber, pero no concede poder para realizarlo,
porque "`la letra mata, pero el Espíritu da vida.`"^
footnote:[2 Corintios 3:6 LBLA]

Así es como muchos leen su deber en la letra pero
carecen de poder para realizar lo que leen,
y por lo tanto establecen imaginaciones en lugar de acciones;
algunos diciendo que la ley terminó, y que ahora ninguno es condenado por ella;
otros diciendo que Cristo la cumplió en Su propia persona,
y solo necesitamos creer lo que Él hizo hace mil seiscientos años; otros dicen, no,
sino que debemos hacer todo lo posible por cumplir lo que la Escritura ordena,
y Él hará lo demás;
y aun otros dicen que Cristo hace que cualquier cosa
que realicemos sea aceptada por el Padre,
porque Él ya hizo todo lo que se requiere.
Pero ninguno de estos conoce el mandamiento de Dios en Espíritu,
que concede tanto la vida como el poder para realizar todo lo que se requiere.
Y ustedes no podrán experimentar esto leyendo lo que otros hicieron,
mientras aún carezcan del Espíritu y poder por el cual ellos actuaron.
Porque cuando ustedes asumen el cumplimiento de la ley con sus propias fuerzas,
sin el Espíritu de vida, se forma una justicia propia a través de la letra.
En este sentido la "`ley era débil por la carne,`"^
footnote:[Romanos 8:3]
pero el poder de la ley es experimentado por todos los que la reciben en Espíritu y vida.
Porque la ley es cumplida en el Espíritu y no en la letra; en Cristo y no en el yo;
por fe y no por obras; en la justicia eterna de Dios,
la cual es dada libremente y recibida por fe, y revelada en la criatura de fe a fe.
La ley en la letra concede un conocimiento de pecado;
pero la ley en el Espíritu concede no solo el conocimiento de pecado,
sino el conocimiento de Dios y de Su justicia en
Cristo Jesús para el cumplimiento de la ley,
lo cual es vida eterna, según Su promesa: "`Daré mi ley en su mente,
y la escribiré en su corazón; y todos me conocerán,
desde el más pequeño de ellos hasta el más grande.`"^
footnote:[Jeremías 31:33-34]

Por lo tanto, todos ustedes que solo conocen mandamientos en la letra escrita,
de ahí ustedes pueden obtener su propia condenación,
pero de ahí nunca podrán obtener poder para obedecer y alcanzar la justificación de vida.
Porque del interior fluye la vida en el Espíritu, y no del exterior en la letra.
Y aquí está el "`cambio de la ley`"^
footnote:[Hebreos 7:12]
a eso que es espiritual--a un sacerdocio espiritual, a un templo espiritual, a un altar,
circuncisión, ofrenda, sangre, oráculo, unción, lavamientos, etc., espirituales.
Sí, todo el culto de ellos,
que era externo y que no podía hacer perfecto a ningún hombre,
ha cambiado y se ha vuelto espiritual e interno;
lo cual "`introduce una mejor esperanza,`"^
footnote:[Hebreos 7:19]
siendo más pura y perfecta que lo que cualquier cosa externa podría ser; sí,
así como Él es perfecto.
Ahora bien "`la ley fue añadida a causa de la transgresión,
hasta que viniese la Simiente a quien fue hecha la promesa,`"^
footnote:[Gálatas 3:19]
acerca de la cual se profetizó en tipos y figuras.
Esta Simiente es Cristo, el fin de la ley para todos los que creen,
sin acepción de personas.
De modo que ahora Dios ha escrito en el corazón una ley en Espíritu,
mediante la cual el transgresor es condenado en su propia conciencia.
Sí, esta ley está sobre y en contra del primer hombre, el cual es el transgresor,
y "`tiene dominio sobre ese hombre entre tanto que vive,`"^
footnote:[Romanos 7:1 Rv 1602 Purificada]
tanto juzgando, reprobando y condenando,
como también profetizando de Aquel que viene a cumplir
la ley en todos los que obedecen la luz.
Por lo tanto, la "`ley es un ayo para traer a Cristo;`"^
footnote:[Gálatas 3:24]
pero hasta que Él venga a cumplirla (quien es el fin de ella),
habrá condenación sobre la criatura,
debido a que la ley pura de Dios ha sido quebrantada.
Y todo esto es testificado por la luz en la conciencia,
la cual actúa como un testigo contra el viejo hombre y sus hechos,
que son contrarios a la ley perfecta de Dios.
Y así, a través de eso que es perfecto, será condenado aquel que es imperfecto,
donde sea que la imagen de Dios se haya perdido,
y la muerte reine a causa de los delitos y pecados.

Porque Dios no emite ninguna ley para condenar Su propia obra,
sino más bien para condenar la obra del diablo.
Y donde sea que se encuentre el transgresor, allí estará la obra del diablo.
Todas sus obras serán condenadas por la ley,
hasta que se experimente la resurrección de la Simiente y la imagen de Dios,
cuando todas las cosas estén puestas debajo de los pies de Aquel que es el fin de la ley,
por quien los frutos del Espíritu también son manifestados,
"`contra los cuales no hay ley.`"^
footnote:[Gálatas 5:23]
Y, por lo tanto, por la resurrección de la Semilla y de Su virtud,
el requerimiento de Dios en la conciencia es cumplido,
y la criatura es salvada de la condenación de la ley de Dios.
Pero la condenación permanecerá sobre todos aquellos
en quienes la Semilla yazca en la tumba,
y la muerte reine.

Por lo tanto, nosotros damos testimonio de que la ley,
que tiene dominio sobre todos los transgresores, continúa, y que es espiritual,
justa y buena, y que ha sido dada contra el primer hombre y sus obras,
sean buenas o malas (según los hombres las llaman).
Sí, aunque un hombre se ponga a hacer las obras de la ley con el mayor celo, aun así,
la ley pura de Dios dará testimonio de condenación contra él en su conciencia,
hasta que la Simiente de la promesa nazca y se levante
en él. Y esto no es de la voluntad del primer hombre,
ni según la carne, sino según el Espíritu, el cual es uno con la ley,
y conforme a la voluntad y a la gracia de Dios.

Ahora bien,
Israel según la carne recibió la ley en el ministerio literal de las ordenanzas carnales,
y Cristo tenía que venir de ellos, el cual "`nació de mujer y bajo la ley,
para redimir a los que estaban bajo la ley,`"^
footnote:[Gálatas 4:4-5]
si ellos creían. Así también ahora, Israel según el Espíritu,
quien recibe la ley espiritual que es escrita en el corazón,
experimentará al Hijo nacido de la Simiente real, es decir, al Heredero de la promesa,
cumpliendo la ley pura de Dios.
Y en verdad hay muchos testigos en este día,
quienes han esperado pacientemente en eso que Dios ha escrito en sus corazones,
lo cual es visto con la luz de Cristo.
Estos han recibido la fe del evangelio y el fin de esta fe, a saber,
la justicia de Dios que se revela de fe a fe,
mediante la cual la ley pura de Dios ha sido cumplida en muchos,
y está siendo cumplida en otros, que permanecen en la medida de fe que Dios les ha dado,
y caminan en la luz, no andando conforme a la carne, sino conforme al Espíritu.
Y así, por la ley del Espíritu de Vida que es en Cristo Jesús,
estos se hallan a sí mismos librados de la ley del pecado y de la muerte,
y por lo tanto experimentan el poder del evangelio.
Pero esto nunca lo harán, ustedes que echan la ley de Dios tras sus espaldas,
y en sus mentes vanas dicen que no están bajo ella.
En verdad, en el día del juicio serán hallados bajo su condenación.

=== Con Respecto a Cristo Jesús

Este es Aquel de quien el mundo habla mucho, pero pocos son los que lo conocen.
Por Él todas las cosas fueron hechas, y Él es la vida de todas las criaturas,
y era antes que todas las criaturas, quien no tiene principio de días, ni fin de vida,
un Sacerdote para siempre, y un rey cuyo dominio no tiene fin.
Por Él reina los reyes, y los tronos son abatidos,
aunque no lo conocen aquellos en quienes todavía permanece el yo.
Él está escondido de la sabiduría del mundo,
y la profundidad del entendimiento del hombre no puede alcanzarlo,
pero Él se revela a Sí mismo a aquellos que caminan en Su luz,
la cual es contraria a todos los caminos oscuros del mundo.
Sí, los que se nieguen a sí mismos podrán aprender el camino del Señor,
porque a estos Él les revelará libremente el camino de su regreso,
a fin de que Él pueda bajarlos del trono de exaltación y darles
a conocer el principio del cual fueron arrancados.

Él es la Palabra eterna,
la cual fue glorificada en los cielos con el Padre antes de todo tiempo,
y luego manifestada en el tiempo.
Porque "`la Palabra fue hecha carne y habitó entre nosotros,`"^
footnote:[Juan 1:14]
y Él "`tomó forma de siervo, y fue hecho semejante a los hombres;
y estando en la condición de hombre, se humilló a Sí Mismo,
haciéndose obediente hasta la muerte,`"^
footnote:[Filipenses 2:7-8]
para poder convertirse en un ejemplo vivo para todas las generaciones.
Y habiendo terminado la obra,
y habiéndose ofrecido a Sí Mismo por la redención del hombre (para lo cual fue engendrado),
subió por encima de todos los cielos,
para preparar un lugar para todos los que lo siguen a través de la fe en Su luz;
y desde ahí Él aparece como un Salvador a todos los que ansiosamente lo esperan.
Y en verdad, solo aquellos que lo experimentan a Él como su juez y legislador,
y lo aman y guardan Sus mandamientos, pueden experimentarlo como su redentor;
a estos Él viene, y el Padre también, a "`hacer morada con ellos.`"^
footnote:[Juan 14:23]

Y este es Aquel que es "`la luz del mundo,`"^
footnote:[Juan 8:12]
y que "`alumbra a todo hombre que viene a este mundo;`"^
footnote:[Juan 1:9 RVG]
quien "`está a la puerta y llama; y si alguno oye Su voz y le abre la puerta,
Él entrará y cenará con él.`"^
footnote:[Apocalipsis 3:20]
Estos lo conocen, y Él conoce a aquellos que oyen Su voz.
Y estos reciben vida para salir de sus delitos y pecados,
y la Semilla de Dios se levanta sobre la muerte en ellos.
Pero donde Cristo es rechazado, la muerte sigue reinado,
y la sabiduría por la cual Él es conocido es considerada locura.

Así que, si ustedes desean conocer a Aquel que no es de este mundo,
sino que era antes que el mundo fuese,
y es un testigo contra todos los caminos y maldades del mundo,
entonces presten atención a esa luz en ustedes que les muestra estas cosas.
Porque como es Cristo, así también es Su Luz la cual conduce a Él. Sí,
eso que testifica contra el mundo no es del mundo, así como Él no es del mundo,
y por lo tanto guía fuera del mundo a Él;
pero el mundo mediante su sabiduría no lo conoce.
Y cualquiera que siga la luz fuera del mundo,
llegará a discernir esa Semilla que es crucificada
por la sabiduría y la gloria del mundo,
a cuya Semilla fueron hechas todas las promesas,
y en la cual están escondidos todos los tesoros de la sabiduría y del conocimiento.
Y a medida que esta Semilla se levante en el interior por el mismo
Espíritu que levantó a Jesucristo de entre los muertos,
ustedes verán a Aquel a quien se le ha dado toda
potestad y juicio en el cielo y en la tierra,
cuya carne es la vida de los hombres, y Su luz es como una ley que sale,
por la cual el hombre es guiado a su comida espiritual,
y los hijos de los hombres ven el camino para salir de la oscuridad.

Y este es Aquel que no puede ser limitado ni restringido a un solo lugar,
sino que llena los cielos y la tierra con Su presencia,
y aparece según Su voluntad a los Suyos, y mora en Sus santos,
aunque los sabios del mundo no lo conocen,
e imaginan que Su morada se encuentra más arriba que las estrellas.
Estos no lo conocen, y por aborrecer la reprensión han alejado Su día,
a fin de gastar sus días en locura, alimentándose a sí mismos con el viento,
y llenando sus corazones de deleites carnales.
Y mientras los corazones de los hijos de luz siguen afirmándose en la gracia,
estos siguen debatiendo sobre el cuerpo de Cristo,
cuando el cuerpo de pecado mantiene su gobierno en ellos.
Por eso están entenebrecidos y ciegos de corazón,
habiendo perdido toda sensibilidad a la medida de la gracia de Dios,
teniendo sus corazones cargados de disipación y afanes del mundo,
y sus mentes corrompidas con cosas terrenales.

A estos les digo, dejen sus imaginaciones,
porque Cristo solo se revela en Espíritu a los que
esperan en la luz y aman lo que es puro.
Para estos Su aparición es como el sol,
cuyo levantamiento no es por la voluntad del hombre.
En verdad, todos deben esperar Su aparición,
si desean ser salvados y refrescados con los rayos de Su gloria.
Y a todos los que todavía están en la noche les digo lo siguiente: Él aparecerá,
si ustedes miran hacia el lugar de Su levantamiento,
el cual no es "`helo aquí,`" ni "`helo allí;`" sino en el interior, en sus corazones.
Y todos ustedes que han experimentado la "`palabra profética más segura,
como una antorcha que alumbra en un lugar seguro, a la cual hacen bien en estar atentos,
hasta que el día esclarezca y el lucero de la mañana salga en sus corazones,`"^
footnote:[2 Pedro 1:21]
ustedes en verdad verán este sol levantarse donde
el lucero de la mañana haya aparecido en sus corazones,
si siguen esperando en la luz que resplandece en las tinieblas.
Y ustedes sentirán Su virtud y vida, y recibirán de la misma.
Sí, lo verán a Él tal como Él es, y lo experimentarán como el "`Sol de Justicia,
cuyo nacimiento trae salvación en Sus alas,`"^
footnote:[Malaquías 4:2]
y cuyo irrumpimiento es sobre todos Sus enemigos, los cuales han reinado sobre la Semilla.
Y en verdad Sus "`armas espirituales son poderosas en Dios para la destrucción de fortalezas;
derribando argumentos y toda altivez que se levanta contra el conocimiento de Dios,
y llevando cautivo todo pensamiento a la obediencia a Sí Mismo,
y estando pronto para castigar toda desobediencia,
cuando vuestra obediencia sea perfecta.`"^
footnote:[2 Corintios 10:4-6]

Y así los santos experimentan al Hijo de Dios con Su luz,
poder y dominio sobre todas las cosas en los cielos y en la tierra,
porque Él reina en justicia en los corazones de Su pueblo,
y hoya a Satanás bajo Sus pies.
Y aunque los hipócritas lo llaman "`Señor, Señor,`" aun así sirven y obedecen al diablo,
teniendo las palabras de Cristo, pero no la experiencia de Su luz, de Su poder,
de Su reino y dominio.
Estos han convertido el nombre de Cristo en un oprobio entre las naciones,
los cuales lo llaman Redentor, pero todavía viven en sus pecados.
Pero ninguno conoce a Jesús más allá de su experiencia de Él como un salvador del pecado,
y no como una cubierta de pecado; porque la promesa del Padre es:
"`Él salvará a Su pueblo __de Sus pecados.__`"^
footnote:[Mateo 1:21]

=== Con Respecto al Ministerio de Cristo

Los verdaderos ministros de Cristo son llamados a
salir del mundo y son contrarios al mundo,
ya que están en contra de sus propias voluntades y de la voluntad de toda carne.
Porque los que predican la Palabra primero son engendrados por la Palabra,
y por lo tanto han sido engendrados según una naturaleza
que es contraria a la voluntad del hombre.
Y esto es evidente en todas las Escrituras,
y en la historia de la persecución en todas las eras hasta este día:
que en cualquier tiempo en que el misterio de la
iniquidad se ha esparcido sobre la tierra,
y la oscuridad ha venido sobre la Semilla,
y el pueblo de Dios ha quebrantado Su pacto y perdido Su Palabra,
entonces Dios (en amor a Su pueblo) enviaba a aquellos quienes tenían Su Palabra en
su interior para testificar de parte del Señor en contra de todas sus rebeliones,
sus caminos carnales y su adoración formal.
Y los ministros del mundo siempre han sido enemigos de estos siervos del Señor,
y han buscado alborotar los poderes de los hombres contra ellos para devorarlos,
llamándolos blasfemos y herejes, destructores de la adoración, quebrantadores de la paz,
y enemigos de la autoridad,
aunque en verdad ellos fueron enviados por Dios para testificar
contra la adoración falsa y para quebrantar la paz del inicuo,
el cual guarda su casa en paz hasta que viene el Hombre más fuerte.
Y ustedes encontrarán que ninguno de los ministros
de Dios jamás podía unirse a la adoración del mundo,
sino más bien clamaba contra sus sacerdotes, sus profetas, sus días, sus tiempos,
sus lugares, etc., que se habían apartado de la Palabra y Espíritu, y vuelto al mundo.

Y como los verdaderos ministros de Cristo son llamados
a salir del mundo y de las cosas del mundo,
así ellos no están preocupados por las cosas del mundo;
porque Aquel que es su maestro es también su sustentador.
Sin duda, ninguno de los ministros de Cristo predicó por precio,
ni profetizaron por dinero, ni vivieron de los diezmos.
Ni tampoco fueron llamados maestros sino más bien siervos y esclavos de Cristo,
no encomendados por los hombres, sino enviados por Dios,
demostrando que son verdaderos ministros de Cristo en mucha paciencia, en tribulaciones,
en necesidades, en angustias, en azotes, en cárceles, en tumultos, en trabajos,
en desvelos, en ayunos; en pureza, en ciencia, en longanimidad, en bondad,
en el Espíritu Santo, en amor sincero, en palabra de verdad, en poder de Dios,
con armas de justicia a diestra y a siniestra; por honra y por deshonra,
por mala fama y por buena fama; como engañadores, pero veraces, como desconocidos,
pero bien conocidos, como moribundos, mas he aquí viven, como castigados, entristecidos,
pobres, no teniendo nada, andando errantes, no teniendo morada fija.

Y estos, teniendo esa Palabra en ellos en la que está toda la plenitud,
no necesitan estudiar qué predicar, ni robar palabras unos de otros,
como aquellos que hablan palabras en su propia voluntad y tiempo,
los cuales hablan contra el orgullo y sin embargo viven en él; predican contra el pecado,
pero no dejan de pecar.
Sí, los ministros del mundo, que son comisionados por los hombres,
confiesan a Cristo en palabras, pero con los hechos lo niegan.
Y debido a su orgullo, placeres, y fines carnales, han cambiado la adoración del Señor,
haciéndola diferente a lo que una vez fue, tanto en su materia como en su manera,
sus medios, y su mantenimiento,
y así han esparcido al pueblo del Señor a sectas y opiniones, formas,
costumbres y tradiciones en toda nación según como mejor se adapten a sus voluntades.
A estos les digo: sus propios caminos testifican a sus rostros,
y delante de todos los hombres,
que ustedes no se parecen más a los ministros de Cristo que aquellos
que caminaron en esos mismos pasos antes que ustedes.
Así que escudriñen las Escrituras, y escudriñen sus corazones con la luz de Cristo,
y no me consideren su enemigo por decirles la verdad.
Yo solo he despejado mi conciencia en amor a sus almas,
aunque los que están engañados debido a un celo y envidia ciegos no lo pueden recibir.
