[short="Biografía de James Nayler"]
== Apéndice. / Una Breve Biografía de James Nayler

[.heading-continuation-blurb]
Que relata su piedad y eminencia en el principio de la Sociedad de Amigos,
su trágica caída demostrada en el incidente de Bristol,
su reconocimiento público de su error, su arrepentimiento sincero delante de todos,
y su subsecuente restauración a la comunión y servicio en el Cuerpo de Cristo.

[.heading-continuation-blurb]
Compilado principalmente de: [.book-title]#La Historia del Surgimiento,
Incremento y Progreso del Pueblo Cristiano Llamado Cuáqueros#--por William
Sewel; [.book-title]#La Vida de James Nayler#--por Joseph Bevan Gurney;
y [.book-title]#Las Memorias de John Whiting.#

James Nayler nació de padres honestos, en la parroquia de Ardesley,
cerca de Wakefield en Yorkshire, alrededor del año 1618.
Su padre era un agricultor de buena reputación,
el cual tenía una propiedad suficiente para sustentarlo en la parte
del país en la que residía. James aprendió algo de literatura,
y se dice (incluso por sus enemigos) que era un orador elocuente,
aunque probablemente esta habilidad no era más que una elocuencia natural,
mejorada por el aprendizaje limitado que un agricultor era
capaz de proveer para su hijo en aquellos días.

Hay muy poca información sobre la vida de James Nayler
antes de que se convirtiera en un Amigo,
pero al parecer se casó cerca del año 1640, y luego se mudó a Wakefield.
Cuando la guerra civil estalló al año siguiente,
se hizo soldado en el ejército de Fairfax,
y luego oficial de intendencia bajo la orden del Mayor General Lambert,
sirviendo en el ejército por un total de ocho o nueve años,
antes de quedar inhabilitado en Escocia debido a
una enfermedad y regresar a casa en 1649.
Durante todo este tiempo, su profesión religiosa estuvo entre los Independientes.

En el año 1651,
George Fox (estando en ese momento dedicado completamente
a su ministerio público) llegó a Wakefield,
donde parece que James Nayler aceptó de corazón las doctrinas que escuchó de Fox.
El diario de Fox nos informa que, en este momento,
"`James Nayler y Thomas Goodyear vinieron a mí, y ambos fueron convencidos,
y recibieron la verdad.`"

Parece que Nayler había sido una persona de tierna conciencia desde su juventud,
que buscaba mantenerse en una postura atenta al Señor. En el año siguiente a su convencimiento,
se sintió movido por un deber religioso, a dejar a su familia,
y a viajar en servicio al Señor según su camino le fuera siendo dado a conocer por Él.
Se dice que él recibió esta comisión mientras iba detrás de su arado en el campo,
meditando en las cosas de Dios.
Él entonces oyó una voz, que le mandaba a salir de su parentela y de la casa de su padre,
con la promesa de que el Señor estaría con él. Él
se regocijó grandemente al escuchar la voz del Señor,
a quien había profesado desde niño, y a quien se había esforzado por servir;
pero después de hacer algunos preparativos iniciales para su viaje,
no cedió rápidamente a ir, sino que fue desobediente a la voz,
por lo que dijo que sintió la ira de Dios sobre él,
e incluso pensó que estaba en peligro de perder su vida.
Finalmente, yendo un poco lejos de casa con un amigo,
sin pensar en un largo viaje (no habiéndose provisto para ello),
le fue ordenado que fuera al oeste.
Él no conocía el propósito de esta misión,
pero al llegar le fue dado lo que había de declarar; y así continuó,
sin saber ni un día lo que había de hacer al siguiente.

No se sabe con certeza si este viaje fue al oeste de Inglaterra,
o solo en dirección oeste de su hogar en Wakefield.
Lo último es lo más probable,
porque en el año 1652 lo encontramos sufriendo mucho abuso personal en Walney Island,
en Lancashire, y disputando con sacerdotes en Westmoreland.
En el onceavo mes del mismo año,
Nayler fue acusado en las audiencias trimestrales de Appleby por
lo que se denominaba "`blasfemia;`" es decir (según su acusación),
por haber dicho que "`Cristo estaba en él,`" y que "`solo había una Palabra de Dios.`"
El mismo año que Nayler fue soltado de la prisión de Appleby (si no fue durante su confinamiento),
el escribió un documento, titulado, _La Verdad Despejada del Escándalo,
Una Respuesta y Declaración de James Nayler Respecto
Algunas de las Cosas Con Las Que Lo Acusaron._
Y como este documento contiene la creencia de James Nayler respecto a Cristo (la cual,
unos pocos años después, se volvió un asunto de mucha controversia),
el siguiente extracto se consideró digno de mención.

[.embedded-content-document.paper]
--

Respecto a Jesucristo: +++[+++dice Nayler]
Él es la Palabra eterna de Dios,
por quien todas las cosas fueron hechas y son sustentadas,
quien era antes de todo tiempo,
pero fue manifestado en el tiempo para la restauración del hombre perdido.
Esta Palabra se hizo carne, y habitó entre los santos, y Él es el mismo ayer,
hoy y por los siglos; quien moró y mora en los santos; quien sufrió y resucitó,
y ascendió al cielo, y está sentado a la diestra de Dios.
A Él se le ha dado toda potestad en el cielo y en la tierra.
Y aunque Él llena todo lugar, y es la luz del mundo, aun así,
Él solo es conocido por aquellos que lo reciben y lo siguen.
A estos Él guía hacia arriba a Dios, fuera de todos los caminos,
obras y adoraciones del mundo, por medio de Su luz pura en ellos,
mediante la cual Él revela el hombre de pecado, y por Su poder lo echa fuera,
y así prepara los cuerpos de los santos como un templo apto para la morada del Dios puro,
con quien ninguna cosa impura puede habitar.
Así Él reconcilia a Dios y al hombre, y renueva la imagen de Dios en pureza y santidad;
y aquí la imagen de Satanás (la cual es todo pecado e inmundicia) es desecha.
Y nadie podrá experimentar redención más allá de
lo que Cristo se haya revelado de este modo en él,
a fin de librarlo del pecado;
y yo doy testimonio de que este Cristo se ha revelado en mí en medida (Gálatas 1:16,
1 Corintios 8:5, Colosenses 1:27).

--

Después de que terminó su confinamiento,
Nayler siguió viajando en el servicio del evangelio en el norte de Inglaterra.
Durante varios años, él fue un miembro eminente de la Sociedad de Amigos,
siendo muy diestro tanto en palabra como por pluma,
de modo que muchos recibieron la Verdad por su ministerio.
Su doctrina era sana, su conducta mostraba sabiduría,
y todos lo reconocían como un hombre de gran discernimiento; y muchos,
incluso entre aquellos que no eran llamados Cuáqueros,
fueron llevados a confesar que él predicaba como uno que tenía autoridad,
y no como las escribas, "`con demostración del Espíritu y de poder.`"^
footnote:[1 Corintios 2:4]
La siguiente anécdota es indicativa del ministerio de Nayler en este tiempo.
Es tomada del diario de James Gough,
y relata un evento que influyó en el convencimiento del honorable ministro y anciano,
James Wilson.

[quote]
____
En los años de juventud +++[+++de James Wilson],
habiendo sido educado en la religión o iglesia establecida de Inglaterra (así llamada),
él había formado una opinión muy despectiva del pueblo llamado Cuáqueros y de sus principios,
y en una casa pública estando en compañía de otros que tenían los mismos sentimientos,
este pueblo se volvió el tema de su conversación. Mientras ellos expresaban sus
sentimientos de desprecio y desagrado respecto a este pueblo muy libremente,
una persona de cierta importancia,
que había sido un oficial bajo el mando de Oliver Cromwell, entró a la habitación,
y escuchando su discurso, les hizo, en esencia, las siguientes observaciones:
Que él percibía que su prejuicio contra este pueblo
se levantaba de su falta de conocimiento del mismo;
"`por mi parte,`" continuó,
"`tengo opiniones muy diferentes a las suyas respecto a ellos.`"
Y percibiendo que estaban llenos de asombró al oírlo a él,
(a quien consideraban como un hombre con inteligencia
e influencia) expresándose de esta manera,
él prosiguió con el siguiente relato:
"`Parecen sorprendidos de que yo exprese una opinión a favor de los Cuáqueros;
les diré la razón. Después de la batalla de Dunbar, cuando estaba cabalgando en Escocia,
delante de mi tropa, vi a alguna distancia del camino, una multitud de personas,
y a uno en un lugar más alto que los demás. Al ver esto,
envié a uno de mis hombres para que investigara y me trajera
información respecto a qué significaba esta reunión;
y al verlo cabalgar y quedarse allí, y no volver, como le había ordenado,
envié a un segundo hombre, el cual se quedó de la misma manera,
y entonces decidí ir yo mismo.
Cuando llegué, descubrí que era James Nayler quien predicaba al pueblo,
con un poder y una energía tan penetrante,
que jamás había experimentado hasta ese día. No pude evitar quedarme por un poco tiempo,
aunque tenía miedo de quedarme; porque fui obligado a convertirme en un Cuáquero^
footnote:[La palabra Quaker en inglés significa uno que tiembla.],
siendo forzado a temblar ante la vista de mí mismo y mi propia condición.
Fui alcanzado con mucho más terror por la predicación de James Nayler,
que cuando estaba en la batalla de Dunbar,
cuando no teníamos ninguna otra expectativa más que
caer como presas de la espada de nuestros enemigos,
sin ninguna capacidad de ayudarnos a nosotros mismos.
Vi claramente que los hombres debían someterse a la cruz;
así que no me atreví a quedarme por más tiempo, sino que me fui,
y llevé mi condenación por ello en mi propio pecho.
Las personas allí, teniendo una clara y poderosa revelación de sus estados,
clamaban contra sí mismas, implorando misericordia,
una transformación absoluta y que se efectuara completamente
la obra de salvación en ellos.
Desde entonces, me he sentido obligado a hablar en favor de este pueblo,
como lo he hecho ahora.`"

James Wilson dijo que esto sirvió como un primer
paso hacia su convencimiento de nuestros principios,
inclinándolo a ir a nuestras reuniones,
lo cual anteriormente solo pensarlo le habría sido repugnante,
debido al prejuicio que se mencionó anteriormente.
En aquellos días las reuniones de Amigos eran favorecidas
con el poder divino de una manera más eminente,
debido a que vivían con más devoción a Cristo;
y consecuentemente tenían más abundancia de Su amor fluyendo en sus corazones.
____

Tenemos otro corto relato de Nayler, tomado del diario de Thomas Ellwood, quien,
antes de convertirse en un miembro de la Sociedad de Amigos,
se había encontrado con él mientras visitaba la casa de Isaac Penington en Chalfont,
Buckinghamshire.
Ellwood escribe:

[quote]
____
Después de la cena, siendo las noches largas,
los siervos de la familia (que eran Cuáqueros) fueron llamados a la sala,
y todos nos sentamos en silencio.
No teníamos mucho tiempo sentados antes de que Edward
Burrough comenzara a hablar entre nosotros.
Y aunque no habló por mucho tiempo, lo que dijo tocó, como supuse,
el nervio religioso de mi padre, como dice el refrán. Porque mi padre,
habiendo sido un profesante religioso desde su juventud (aunque no tenía
una comunión real con ninguna denominación) y valiéndose del conocimiento
que consideraba tener de las diferentes nociones de cada denominación,
pensó que ahora tenía una buena oportunidad para mostrar su conocimiento,
y entonces comenzó a hacer objeciones contra lo que había sido dicho.
El tema del discurso de Burrough era la gracia universal
de Dios ofrecida libremente a toda la humanidad;
a lo cual mi padre se opuso en defensa del dogma
calvinista de predestinación particular y personal.
Pero en su defensa de esta indefendible noción, se vio más perdido de lo que esperaba.
Edward Burrough no le dijo mucho sobre esto, aunque lo que dijo fue directo y convincente.
Pero interponiéndose James Nayler,
manejó el tema con tanta perspicacia y clara demostración,
que su razonamiento se vio irresistible; y así supongo que mi padre lo vio,
lo cual lo hizo querer abandonar el discurso.
En cuanto a Edward Burrough, él era un joven enérgico con mucha preparación,
y podría haber sido, por lo que yo sabía entonces, un erudito,
lo que hizo que yo admirara menos su manera de razonar.
Pero lo que salió de James Nayler tuvo mayor efecto en mí,
porque él se veía como un simple y sencillo hombre del campo,
pues tenía la apariencia de un labrador o de un pastor.
____

James Nayler llegó a Londres a finales de 1654 o a principios de 1655,
y encontró una reunión de Amigos en la ciudad,
que ya había sido establecida por la obra de Edward Burrough y Francis Howgill.
Ahí predicó en una forma tan eminente, que muchos admirando su gran don,
empezaron a estimarlo por encima de sus hermanos;
esta excesiva estima no le trajo ningún bien,
y dio lugar a algo de discordia en la sociedad.
La tensión se elevó a tal punto, que algunas mujeres atrevidas y sin consideración,
de quienes Martha Simmons era la principal,
tenían la osadía de disputar abiertamente con Francis
Howgill y Edward Burrough mientras predicaban,
y así perturbaban las reuniones,^
footnote:["`Podemos suponer que la práctica de estas mujeres era
en cierto modo como la que le dio ocasión al apóstol Pablo de decir:
'`Callen vuestras mujeres en las iglesias,
porque no les está permitido hablar.`' 1 Corintios 14:34. Esta prohibición de hablar,
debe referirse a hablar en nuestra propia voluntad, en forma de razonamiento o discusión,
y no a aquellos momentos en los que se tenía un impulso o carga inmediata de profetizar;
pues el apóstol, en la misma epístola,
ha definido la profecía como '`hablar a los hombres para edificación,
exhortación y consolación.`' 1 Corintios 14:3. Y en el capítulo 11 también
hizo mención expresa de la oración y la profecía de las mujeres,
junto con los hombres.`"--William Sewel]
con lo cual, ellos que eran predicadores verdaderamente excelentes,
no dudaron (según su deber) en reprender esta indiscreción.
Pero estas mujeres se disgustaron tanto,
que Martha y otra mujer fueron y se quejaron con James Nayler,
a fin de encolerizarlo contra F. Howgill y E. Burrough, pero esto no sucedió,
porque él se mostró temeroso de juzgar a sus hermanos como ellas lo deseaban.
En ese momento Martha se dejó llevar por una emoción, una especie de gemido o llanto,
y exclamando amargamente con una voz chillona y afligida decía: "`Esperaba juicio,
y he aquí vileza; justicia, y he aquí clamor`"^
footnote:[Isaías 5:7]
Así lloró, en voz alta, y en una forma tan apasionada y triste,
que entró y penetró el corazón de J. Nayler,
de tal modo que lo hundió en tanto dolor y tristeza,
que quedó muy abatido y desconsolado en espíritu.
Entonces el temor y la duda se apoderaron de él, de modo que su entendimiento se nubló,
y el quedó confundido y sin discernimiento.
Se piensa que los penetrantes lamentos de esta mujer tuvieron
una gran influencia en el distorsionamiento de su juicio;
y lamentablemente él no solo fue engañado por el
lamento exagerado de ella (y de sus asociados),
sino que luego fue aún más desviado por sus halagos.
Así, por prestar su oído a alabanzas lisonjeras de algunas personas caprichosas,
(las cuales debió haber aborrecido y reprendido),
se fue alejando cada vez más de los miembros líderes de la Sociedad de Amigos,
los cuales no podían unirse a su conducta.
Pero su dolorosa caída debe permanecer como una advertencia para todos,
incluso para los que han sido dotados con grandes dones,
a fin de que no se atrevan a exaltarse,
no sea que caigan también. Y que todos se esfuercen por mantenerse en verdadera humildad,
que es la única condición en la que un cristiano puede ser mantenido a salvo.

Hannah Stranger, a quien yo +++[+++William Sewel]
conozco muy bien, y tengo razones para creer que es una mujer de grandes imaginaciones,
en ese tiempo le escribió varias cartas muy extravagantes a James Nayler,
llamándolo el eterno Hijo de Justicia, Príncipe de Paz, el unigénito Hijo de Dios,
el más hermoso de diez mil, etc.
En las cartas de Jane Woodcock, John Stranger y otros,
había expresiones de similares extravagancias, y las mencionadas Hannah Stranger,
Martha Simmos y Dorcas Erbury llegaron a tal nivel de locura,
que en la prisión de Exeter se inclinaron delante de Nayler y besaron sus pies.

Cerca de este tiempo, George Fox,
que había sido liberado recientemente de la cárcel de Launceston,
vino a la prisión de Exeter e intentó hablar con Nayler,
a quien en este momento consideraba como uno que había "`caído
en imaginaciones,`" como lo relata en su diario.
En este encuentro, parece que Nayler menospreció el consejo de Fox, y, sin embargo,
le ofreció un saludo afectuoso, el cual Fox a su vez rechazó, diciendo, que,
puesto que Nayler se había vuelto contra el poder de Dios,
él no quiso recibir su su señal de amabilidad.

Nayler, estando ahora totalmente engañado, se volvió aún más exorbitante.
Al ser liberado de esa prisión, cabalgó hacia Bristol a principios de noviembre,
acompañado por sus halagadores compañeros antes mencionados.
Pasando por los suburbios de Bristol,
un tal Thomas Woodcock caminaba con la cabeza descubierta delante de él^
footnote:[En ese momento,
quitarse el sombrero (o ir "`con la cabeza descubierta`") era una señal de honor y respeto;
una que usaban los Cuáqueros sólo en sus solemnes acercamientos al Señor en oración.]
y una de las mujeres conducía su caballo, y Dorcas,
Martha y Hannah extendían sus bufandas y pañuelos delante de él mientras el grupo cantaba:
"`Santo, santo, santo es el Señor Dios de los ejércitos; hosanna en las alturas.
Santo, santo, santo es el Señor Dios de Israel.`"
Así cantaban estos locos mientras caminaban por el barro y la tierra,
hasta que entraron a Bristol,
donde fueron interrogados por los magistrados y encerrados en prisión;
y no mucho después Nayler fue llevado a Londres para ser interrogado por el Parlamento.
Se puede saber qué sucedió ahí por la impresión que se hizo del juicio,
la cual el Parlamento se complació en publicar.^
footnote:["`Pero lo excesivo de la sentencia que el Parlamento dictó,
provee suficiente razón para suponer que el relato de lo sucedido no fue tomado imparcialmente,
y fue publicado para justificar su crueldad.
Según John Whiting, algunas de sus respuestas fueron suficientemente inocentes,
otras no muy claras, y otras fueron agravadas por sus adversarios;
él negó algunas acusaciones, otras las admitió. Ellos informaron lo peor,
y en algunas cosas, más de lo que era cierto,
aumentando o disminuyendo según les era conveniente.
Faltaba mucho de lo que él había hablado con el comité,
quienes estaban arrancándole palabras y pervirtiéndolas de la manera que podían,
esforzándose por sacarle palabras para atraparlo y quitarle la vida.
Para mostrar la confusión en que se encontraban cuando él estaba frente a ellos,
le mandaron que se arrodillara y se quitara el sombrero ante ellos,
aunque una parte de la acusación contra él era que algunos
se habían arrodillado ante él.`"--William Sewel]
Creo que James Nayler tenía su entendimiento nublado
durante todo el curso de estos eventos.
Pero a pesar de lo grave de su caída, le plació a Dios en Su infinita misericordia,
levantarlo de nuevo y llevarlo a un arrepentimiento tan sincero,
que él (como podemos ver en lo que sigue) aborreció no sólo todo este asunto,
sino que también manifestó su gran pesar con desgarradoras expresiones,
las cuales fueron publicadas, como se mostrará en su debido lugar.

Lo que se ha dicho de los extraños sucesos en la prisión de Exeter,
y de su cabalgata a Bristol, no fue negado por él ni por el resto del grupo,
cuando fueron interrogados por el comité del Parlamento,
quienes dieron su reporte el 5 de diciembre.
En el día 17 del mismo mes (después de mucho debate y contradicción en el parlamento,
habiendo muchos que no aprobaban la severidad que fue usada en su contra),
llegaron a la siguiente resolución:

[quote]
____
"`Que James Nayler será puesto en el cepo, con su cabeza en el cepo,
en el jardín del palacio de Westminster, durante un lapso de dos horas,
y luego será azotado por el verdugo mientras lo transportan por las calles de Londres,
de Westminster a Old Exchange.
Allí también será puesto en el cepo, con su cabeza en el cepo, por un lapso de dos horas,
entre las once y la una del Sábado siguiente,
llevando en cada lugar un papel con la descripción de sus crímenes.
Luego, en Old Exchange,
se le perforará la lengua con un hierro candente y se le estigmatizará su frente con
la letra B. Después será enviado a Bristol y transportado en y a través de dicha ciudad,
en el lomo de un caballo con su rostro viendo hacia atrás,
y allí también será públicamente azotado el siguiente día de mercado.
De ahí será enviado a la prisión en Bridewell, Londres,
no se le permitirá relacionarse con ninguna persona,
y será sometido a trabajos forzados hasta que sea liberado por el Parlamento.
Durante este tiempo se le prohibirá usar pluma, tinta y papel,
y no tendrá asistencia sino la que él gane con su trabajo diario.`"
____

Pasó mucho tiempo antes de que ellos pudieran acordar la sentencia, porque,
aunque suponían que se había cometido blasfemia,
su lengua no parecía propiamente culpable de ello,
dado que nunca se probó que él hubiera dicho palabras blasfemas.^
footnote:["`Si suponemos que era el honor de la religión
cristiana lo que el Parlamento buscaba,
y el aborrecimiento de la blasfemia que se sintió lo que los motivaba,
entonces ¿por qué no persiguieron a los compañeros de Nayler con la misma severidad,
de cuyas bocas procedieron las expresiones que eran consideradas blasfemas;
y cuyos corazones,
manos y rodillas habían sido los medios para convertirlo
a él en un objeto de adoración? Por mi parte,
siempre he sospechado que la selección de la víctima procedía de
un deseo de aplastar el levantamiento de la Sociedad de Amigos,
a través de la caída de un hermano.
Nayler había sido verdaderamente eminente y estimado.
La fama de los otros era solo porque habían actuado injuriosamente
al adorarlo a él.`" --Joseph Gurney Bevan]
En realidad, muchos pensaban que era una sentencia muy severa,
para ser ejecutada sobre alguien cuyo crimen parecía más proceder de un
entendimiento nublado que de una deliberada intención de maldad.
Y aunque varias personas de diferentes persuasiones religiosas,
movidas por la compasión hacia Nayler (considerándolo un
hombre que se había dejado llevar por tontas imaginaciones),
habían hecho peticiones al Parlamento en su favor,
se resolvió no leerlas hasta que la sentencia contra él fuera pronunciada.

Después de que el juicio había sido concluido por el Parlamento,
James Nayler fue llevado al estrado, y cuando el presidente de la Cámara,
sir Thomas Widdrington, estaba a punto de pronunciar la sentencia antes mencionada,
Nayler dijo que él no conocía su delito.
A lo cual el presidente respondió: "`Conocerás tu delito por tu castigo.`"
Nayler soportó con paciencia la lectura de su sentencia,
y en un momento pareció que iba a decir algo, pero le fue negada la libertad.
Sin embargo, se le escuchó decir con una mente serena:
"`Le ruego a Dios que no les tome en cuenta esto.`"

El 18 de diciembre, J. Nayler sufrió parte de la sentencia,
y después de haber permanecido por dos horas completas con la cabeza en el cepo,
fue desnudado,
atado a una carreta y azotado desde el jardín del palacio hasta Old Exchange,
recibiendo trescientos diez azotes.
El verdugo le habría dado uno más (como le confesó al alguacil),
pero su pie resbaló y el golpe cayó sobre su propia mano,
lo cual le provocó un fuerte dolor.
Todo esto Nayler lo soportó con tanta paciencia y tranquilidad,
que asombró a muchos de los espectadores,
a pesar de que su cuerpo estaba en una condición muy lamentable.
También tenía muy heridos sus pies por los pisotones de los caballos,
en los que se podían ver las marcas de sus cascos.
Rebecca Travers, una persona sobria y respetable, y quien lavó sus heridas,
dijo en un certificado que fue presentado ante el Parlamento y luego impreso:

[quote]
____
"`Desde sus hombros hasta cerca de su cintura,
no había el espacio de una uña libre de azotes y sangre.
Su brazo derecho estaba gravemente herido, y sus manos muy lastimadas por las cuerdas,
de modo que sangraban y estaban hinchadas.
A primera vista,
la sangre y las heridas en su espalda apenas se veían
debido a la gran cantidad de tierra que las cubrían,
hasta que fue lavado.`"
____

Su castigo fue tan severo,
que algunos juzgaban que su sentencia habría sido
más benigna si lo hubieran ejecutado en el momento.
Parece que, efectivamente,
había un grupo que al no poder prevalecer lo suficiente
en el Parlamento para sentenciarlo a muerte,
se esforzó al máximo de su fuerza para hundirlo bajo el peso de su castigo.
El 20 de diciembre era el día designado para ejecutar la otra parte de la sentencia,
es decir, la perforación de su lengua y estigmatización de su frente,
pero debido a que la crueldad con que había sido
azotado lo había llevado a una condición muy abatida,
muchas personas importantes, movidas por la compasión,
le presentaron al Parlamento una solicitud en su favor,
y entonces le aplazaron su castigo una semana.

Durante este intervalo de siete días,
varias personas le presentaron otra solicitud al Parlamento,
en la que estaban estas palabras:

[quote]
____
"`La moderación y clemencia que ustedes mostraron
en el aplazamiento del castigo de James Nayler,
en consideración a la condición de su cuerpo,
ha refrescado los corazones de muchos miles en estas ciudades,
que no han tenido ninguna participación en sus actos.
Por tanto,
humildemente les pedimos disculpas por sentirnos constreñidos a comparecer
delante de ustedes otra vez (sin atrevernos a hacer otra cosa),
solicitándoles en esta oportunidad que remitan la
parte restante de su castigo contra J. Nayler,
dejándolo en manos del Señor y a esos remedios evangélicos que Él ha santificado.
Estamos persuadidos de que encontrarán que un rumbo
de amor y tolerancia será más efectivo para rescatarlo,
y dejará un sello de su amor y ternura sobre nuestros espíritus.`"
____

Esta petición presentada en la barra de la casa por
unas cien personas en nombre de la totalidad,
fue respectivamente leída y debatida por ellos;
pero los solicitantes pensaron que era probable que
su petición no produjera el efecto deseado,
así que se consideraron obligados por el deber y la consciencia,
a dirigirse al Protector^
footnote:[Oliver Cromwell]
para que él remitiera la parte restante de la sentencia, quien, en seguida,
envió una carta al Parlamento, lo que provocó cierto debate en la casa.
Sin embargo,
viendo que el día de la ejecución de la parte restante de la sentencia se acercaba,
los solicitantes se dirigieron por segunda vez a Cromwell.
De hecho,
fue muy notable que tantos habitantes de Londres que no
pertenecían a la sociedad de los llamados Cuáqueros,
se mostraran tan interesados en el asunto.
Para mí, esto parece haber salido de la mera compasión hacia la persona de James Nayler,
a quien ellos consideraban como alguien que había caído en un error por descuido,
en lugar de ser culpable de blasfemia deliberada.
Pero a pesar de todas estas humildes peticiones,
los predicadores públicos (parece) se opusieron tanto a Cromwell,
que no pudo resolver ponerle un alto a la ejecución prevista.

Cinco de esos ministros, cuyos nombres eran Carly, Manton, Nye, Griffith y Reynolds,
el 24 de diciembre fueron donde Nayler por orden del Parlamento (según se dijo),
para hablar con él sobre las cosas por las que estaba detenido,
y no permitieron que ningún amigo o cualquier otra persona
estuviera presente en la habitación. Cierta persona imparcial
o neutral deseaba fervientemente que esto fuera permitido,
pero le fue negado.
Sin embargo, este hombre fue a la prisión después de la conferencia,
y le preguntó a Nayler cuál había sido el resultado de la reunión. Nayler le respondió,
que veía que los sacerdotes tenían la intención de hacerlo sufrir como si fuera un malhechor,
y que, por eso,
le habían negado la presencia a cualquiera que pudiera
ser un juez imparcial entre ellos y él. Nayler,
por lo tanto, les dijo que no iba a decir nada,
a menos que lo que pasara entre ellos fuera anotado y le dieran una copia para guardarla,
o dejarla con el carcelero, después de que ellos la hubieran firmado.
Esto al principio fue aceptado, y los ministros le propusieron varias preguntas,
cuyas respuestas las habían puesto por escrito.
Primero le preguntaron que si él lamentaba las blasfemias de las que era acusado,
y si se retractaba y renunciaba a las mismas.
A lo cual él respondió: "`¿Cuáles blasfemias?
Nómbrenlas.`"
Pero como ellos no habían sido capaces de citar una en particular, él continuó:
"`¿Ustedes quieren que yo me retracte y renuncie,
y no saben de qué?`" Después le preguntaron si él creía que había un Jesucristo,
a lo que él respondió que él creía que lo había,
y que Jesús había hecho Su morada en su corazón y espíritu,
y que por el testimonio de Él sufría en ese momento.
Y en seguida uno de los predicadores dijo:
"`Yo creo en un Jesús que nunca ha estado en el corazón
de ningún hombre,`" a lo que Nayler respondió,
que no conocía a ese Cristo,
porque el Cristo del que él testificaba llenaba el cielo y la tierra,
y habitaba en los corazones de los creyentes.
Entonces le pidieron que les dijera la razón por la que les había
permitido a esas mujeres que le rindieran culto y lo adoraran.
A lo que él respondió: "`Rechazo toda reverencia ante la criatura,
pero si ellas veían el poder de Cristo, dondequiera que estuviera,
y se inclinaban ante él, ¿quién soy yo para resistir o contradecirlo.`"^
footnote:["`Lo más que encuentro en su interrogatorio, ya sea en Bristol o en Londres,
ante el comité del Parlamento, según se publicó en el informe de ellos,
es que James Nayler había reconocido que Cristo estaba en él, pero nunca que era Cristo;
y que él había tomado el honor que le habían dado, no para él,
sino para Cristo en él--lo cual, sin embargo,
era más de lo que ningún hombre debía recibir, porque cuando el discípulo amado, Juan,
había caído ante los pies del ángel para adorarlo, él (aunque un ángel) le había dicho:
'`Mira, no lo hagas; yo soy consiervo tuyo,
y de tus hermanos que tienen el testimonio de Jesús. Adora a Dios.`'
Apocalipsis 19:10. Y si un ángel no debe recibir o aceptar adoración,
mucho menos un hombre mortal.
Pero el alegato de que J. Nayler había recibido eso para sí mismo, como criatura,
lo negó rotundamente (ver [.book-title]#Juicio,# pág. 15),
al decir que no podía haber algo más abominable que
tomar del Creador y dárselo a la criatura,
etc.`"
--John Whiting.]
Posteriormente les preguntó a los ministros:
"`¿Por tanto tiempo han profesado las Escrituras
y ahora tropiezan con lo que ellas exponen?`"
Con lo cual, ellos quisieron que él les diera un ejemplo de las Escrituras,
en el que se veía que tal práctica había sido llevada a cabo.
Y él les respondió: "`¿Qué piensan de la sunamita,
cuando se postró a los pies de Elías y se inclinó delante de él?
Así como también de varios que se mencionan en las Escrituras,
tales como Abigail ante David,
y Nabucodonosor ante Daniel`" Ante esto ellos hicieron
una pausa por un rato y finalmente dijeron:
"`Eso no fue más que un acto de cortesía o reconocimiento.`"
Él les dijo: "`Así podrían interpretar el acto de esas mujeres,
si sus ojos no fueran malos, al ver que el acto externo es uno y el mismo.`"
Entonces,
al darse cuenta de que ellos estaban buscando arrancarle
palabras que sirvieran a su propósito,
les dijo: "`¡Cuán pronto han olvidado ustedes las obras de los obispos,
y ahora se encuentran en lo mismo, tratando de atrapar al inocente!`"
Con lo cual,
los ministros se levantaron y con amargura de espíritu quemaron lo que habían escrito,
y lo dejaron con algunas expresiones de lamento.
Y cuando se estaban yendo,
él les pidió que el Parlamento le enviara por escrito
las preguntas que ellos querían que él respondiera,
y que permitieran que él les devolviera las respuestas por escrito también.

Por este relato, parece que Nayler, aunque todavía bajo cierta nube,
estaba un poco más claro en su entendimiento que antes.
Sin embargo, siendo perseguido por enemigos feroces,
no se detuvo la ejecución de su sentencia, sino que se realizó el 27 de diciembre.
Robert Rich, un hombre temerario y desordenado, que era uno de los seguidores de Nayler,
estuvo ese día en la puerta del Parlamento,
desde las ocho de la mañana hasta casi las once,
gritándoles a los hombres del Parlamento cuando pasaban por ahí. A uno,
a quien juzgó inocente en este asunto, le dijo: "`¡El que habita en amor, habita en Dios,
porque Dios es amor!`"
A otro, de quien pensó que estaba siendo movido por la envidia le dijo:
"`El que aborrece a su hermano es un asesino,
y el que odia a su hermano es un homicida.`"
En ese momento, algunos pensaban que Nayler no iba a sufrir más castigo,
porque muchas personas honorables se habían acercado
al Parlamento y al Protector en su nombre.
Pero como Rich sabía cómo estaba el caso,
le decía a la gente que "`un inocente iba a sufrir,`"
y a algunos hombres del Parlamento les gritó,
que él estaba limpio de la sangre de todos los hombres,
y que deseaba que ellos también lo estuvieran.
Después Rich se fue a Exchange y se subió al cepo,
donde sostuvo a Nayler de la mano mientras le quemaban la
frente y le perforaban la lengua con un hierro candente.
Y estando muy afectado por los sufrimientos de Nayler, luego le lamió las heridas,
buscando (por lo que parece) aliviarle el dolor.
Luego lo tomó de la mano y lo ayudó a bajar del cepo.

Algunas cosas particulares en la ejecución de esta
parte de la sentencia son dignas de mencionar.
Tanto el hierro con el que perforaron su lengua como el
que usaron para marcar su frente estaban al rojo vivo.
El primero despues haber perforado su lengua fue dejado ahí por un breve momento,
para que los que pasaban pudieran presenciar claramente la ejecución,
y la letra B de hierro fue presionada contra su frente hasta que echó humo.
Durante todo este tiempo Nayler se mantuvo firme, y cuando fue desatado,
abrazó al verdugo.
Fue muy notable, que, aunque ahí había muchos miles de personas, estaban muy calladas,
y muy pocas lo insultaron o le arrojaron algo.
Cuando Nayler estaba siendo quemado, la gente tanto delante como detrás de él,
y a ambos lados, permanecieron unánimes con la cabeza descubierta,
aparentemente movidos por la compasión y buena voluntad hacia él.

Cerca de tres semanas después de haber sufrido la segunda parte de la sentencia en Londres,
la tercera parte (a saber, ser expuesto en el cepo,
y azotado por segunda vez) fue ejecutada en Bristol.
Según un testigo ocular, estaba allí atado a la parte trasera de un carro de caballos,
y fue azotado desde el medio de la calle Thomas, a lo largo del puente,
subiendo por la calle High, hasta el medio de la calle Broad,
todo lo cual soportó con una impresionante paciencia.^
footnote:["`Mientras Nayler era arrastrado detrás de un carro de caballos,
y seguido por el látigo, Robert Rich cabalgaba delante de él con la cabeza descubierta,
y cantaba, "`Santo, Santo.`"
Sin embargo,
parece que Rich no había sido lo suficientemente eminente
entre los Cuáqueros como para ser censurado por el parlamento,
y seguía sin ser castigado.`"
--Joseph Gurney Bevan]
También fui informado, por una carta de un tal Richard Snead,
un anciano de casi ochenta años,
que Nayler había escrito una carta a los magistrados de Bristol,
en la que desaprobaba y condenaba arrepentido su conducta ahí.

Muchos ahora se regocijaban, con la esperanza de ver la caída de los Cuáqueros,
y con la expectativa de que los Amigos ahora estuvieran divididos entre
sí. Pero cualquiera que haya sido la discordia que hubo entre unos pocos,
rápidamente llegó a su fin,
porque los Cuáqueros hablaron abiertamente contra Nayler y sus hechos,
y aunque procuraron restaurarlo, nunca buscaron defenderlo.^
footnote:[Robert Barclay,
en su artículo titulado "`William Mitchell Desenmascarado,`"
tiene las siguientes expresiones respecto a James Nayler.
(Véase pagina 84) "`Cualquiera puede ver que la historia de James
Nayler fue añadida por Mitchell solo para hacernos aborrecibles,
aunque en verdad esto de ninguna manera nos causa desventaja,
ya que nosotros desaprobamos inmediata y completamente lo que hizo Nayler en aquel momento.
Y desde entonces él ha reconocido abiertamente por escrito su caída en esa hora de tentación;
y hemos recibido muchas señales evidentes de su sincero arrepentimiento
y verdadero regreso a la comunión de la verdad.`"
Y en la página 876 de su libro "`Apología Reivindicada,`"
en su respuesta a una crítica hecha por John Brown,
escribe:
"`Pero el pobre hombre piensa (probablemente) que ha dado en el clavo cuando dijo,
página 54, respecto a este asunto, '`Una cosa le preguntaría,
¿qué piensa de ese honor y adoración que le dieron a James Nayler,
mientras cabalgaba a Bristol,
el 24 de Octubre de 1656?`' A esto respondo que pienso
que fue algo tanto perverso como abominable,
y así también piensa el pueblo llamado Cuáqueros;
quienes en ese entonces lo desaprobaron, junto con todos los que participaron en eso.`"]

Después de esto fue llevado a Bridewell, Londres (de acuerdo con su sentencia),
donde continuó encerrado en prisión cerca de dos años,
durante los cuales llegó a un verdadero arrepentimiento de su transgresión;
y tras obtener permiso para usar pluma y tinta,
escribió varios libros y documentos en los que condenaba su error,
los cuales fueron publicados en forma impresa.
El 8 de septiembre de 1659, fue puesto en libertad por el parlamento,
y fue directamente a Bristol, el lugar principal de su ofensa.
Allí, en una reunión abierta,
hizo una confesión pública de su error de una manera tan conmovedora,
que hizo que salieran lágrimas de la mayoría de los que estaban presentes,
y dio lugar a su reconciliación con muchos que se habían distanciado de él.^
footnote:["`Después de ser puesto en libertad, fue a Bristol,
donde en una reunión pública, hizo una confesión de su ofensa,
en cuanto su caída anterior, declarándola de una manera tan poderosa,
que llenó de ternura la reunión e hizo que rompiera en lágrimas,
de modo que había unos pocos con sus ojos secos,
(como lo contaron algunos que estaban presentes) y muchos
se ablandaron y se reconciliaron con él.`" --John Whiting]
No hay duda de que él hizo un buen uso de la soledad que le proporcionó su confinamiento,
y el cambio que ocurrió en su conducta para con sus amigos, los Cuáqueros,
produjo rápidamente el regreso de su amistad y comunión.

Después de su liberación,
publicó varias declaraciones más de retractación. Una de ellas es la siguiente:

[.embedded-content-document.paper]
--

Gloria al Dios Todopoderoso, quien gobierna en los cielos,
y en cuyas manos están todos los reinos de la tierra;
quien levanta y derriba a Su voluntad;
quien tiene maneras de confundir la exaltación de los hombres,
de castigar a Sus hijos y de hacerles saber a los
hombres que son como hierba delante de Él. Ciertamente,
Sus juicios están por encima de los juicios más altos de los hombres,
Su compasión alcanza la miseria más profunda,
y el brazo de Su misericordia se extiende hasta el
fondo para sacar al prisionero del pozo,
y salvar a los que confían en Él,
de la gran destrucción que el hombre vano trae sobre sí mismo por causa de su insensatez.
Pues Él ha liberado mi alma de las tinieblas,
ha abierto camino para mi libertad de la prisión, y me ha redimido de la gran cautividad.
Él divide el mar delante de Él y remueve de Su camino las montañas,
el día que decide liberar al oprimido de la mano
del que es demasiado poderoso para él en la tierra.
¡Qué su nombre sea exaltado para siempre y que toda carne
tema delante de Aquel cuyo aliento es vida para los Suyos,
pero fuego consumidor para el adversario!

En cuanto al Señor Jesucristo,
Su dominio eterno está sobre la tierra y Su reino
por encima de todos los poderes de las tinieblas;
es decir, el Cristo de quien las Escrituras declaran que era, es y ha de venir,
y es la luz del mundo para todas las generaciones.
De Su venida yo testifico con el resto de los hijos de la luz,
aquellos que son engendrados de la Semilla inmortal;
pues Su verdad y virtud brillan hoy en el mundo,
siendo el Salvador de todo aquel que cree en Él para justicia y vida eterna.
Él ha sido la roca de mi salvación,
y Su Espíritu le ha dado tranquilidad y paciencia a mi alma en profunda aflicción,
por amor de Su nombre.
¡Alabado sea Él para siempre!

¡Pero condenada sea para siempre toda falsa adoración con la que
alguien haya idolatrado mi persona en la noche de mi tentación,
cuando el poder de las tinieblas se había levantado sobre mí! ¡Condenado
sea el lanzamiento de sus vestidos en el camino,
sus inclinaciones y cantos, y el resto de sus extravagantes acciones,
que de alguna manera tendieron a deshonrar al Señor,
o a desviar las mentes de la medida de Jesucristo en ellos,
para mirar la carne (que es como hierba),
o atribuirle a algo visible lo que le pertenece a Cristo Jesús! ¡Condeno todo aquello,
por medio de lo cual el nombre puro del Señor ha sido en alguna
forma blasfemado a través de mí en el tiempo de mi tentación,
o por medio de lo cual los espíritus de los que verdaderamente
aman al Señor Jesús en todo el mundo,
de cualquier profesión, han sido afligidos!
Confieso esta ofensa, la cual ha sido un dolor en mi corazón,
que el enemigo de la paz del hombre en Cristo haya
obtenido ventaja en la noche de mi prueba,
y haya causado ira y ofensas en la creación de Dios--algo
que la sencillez de mi corazón no pretendía,
el Señor lo sabe;
quien en Su infinito amor hoy me ha dado poder sobre tal cosa para condenarla.

Y con respecto a la carta que me envió John Stranger
a Exeter cuando estaba en prisión y que decía:
"`Tu nombre no será más James Nayler, sino Jesús,`" a mi juicio,
fue escrita desde la imaginación; y un temor me asaltó cuando la vi por primera vez,
así que la guardé en mi bolsillo con la intención de que nadie la viera.
Pero me la encontraron y la divulgaron,
lo que la sencillez de mi corazón nunca aprobó. Así que también niego
haber recibido el nombre de Cristo Jesús en lugar de James Nayler,
o habérmelo adjudicado,
porque ese nombre es para la Semilla prometida a todas las generaciones;
el que tiene al Hijo, tiene el nombre, el cual es Su vida y poder,
la salvación y la unción, en cuyo nombre son bautizados todos los hijos de luz.
Por tanto, confieso delante de los hombres el nombre de Cristo,
cuyo nombre ha sido para mí una torre fuerte de noche
y de día. Este es el nombre de Jesucristo,
que yo confieso, el Hijo y el Cordero, la Semilla prometida,
dondequiera que hable en varón y hembra; pero el que no tiene al Hijo en él,
no tiene la vida, ni puede tenerlo idolatrando mi persona,
o la persona de cualquier carne.

Y todos aquellos espíritus desenfrenados y extravagantes,
que luego se reunieron a mi alrededor en ese tiempo de tinieblas,
y todos sus descabellados actos y malvadas palabras contra el honor de Dios,
Su Espíritu puro y Su pueblo--niego ese espíritu malo, junto con su poder y sus obras.
Y en la medida que por falta de juicio le haya dado ventaja
a ese espíritu malo para que se levante en alguno,
en esa medida acepto la vergüenza de ello,
porque antes tenía poder sobre ese espíritu en juicio y discernimiento,
dondequiera que se levantara.
Esta oscuridad se apoderó de mí por falta de vigilancia y obediencia al ojo puro de Dios,
y por no atender diligentemente la reprensión de la vida,
la cual condena al espíritu adúltero.
Así tomó ventaja el adversario, quien siempre busca devorar,
y tras ser tomado cautivo de la verdadera luz,
empecé a caminar en la noche en la que nadie puede trabajar,
como un ave errante apta para presa.
De seguro que, si el Señor de todas mis misericordias no me hubiera rescatado,
yo habría perecido; porque era como un hombre destinado a la muerte y destrucción,
y no había nadie que pudiera liberarme.
Todo esto lo confieso,
para que Dios sea justificado en Su juicio y magnificado en Sus infinitas misericordias,
pues no abandonó a Su cautivo en la noche,
aun cuando Su Espíritu era diariamente provocado y contristado;
sino que me ha liberado para dar gloria a Su nombre para siempre.

Está en mi corazón confesar ante Dios y ante los hombres,
mi insensatez y ofensa de aquel tiempo.
Aunque también,
se habían levantado muchas cosas contra mí en ese día (para
quitarme la vida y traer escándalo sobre la Verdad),
de las que no soy culpable en absoluto;
tales como la acusación de que cometí adulterio con algunas de
las mujeres que llegaron con nosotros desde la prisión de Exeter,
y con las que estaban conmigo en Bristol la noche anterior a mi sufrimiento
ahí. Con respecto a estas dos acusaciones estoy limpio delante de Dios,
quien me guardó en ese día, tanto en pensamiento como en obra,
en lo que se refiere a todas las mujeres, como un niño; Dios es mi testigo.
Esto lo menciono en particular (al oír de algunos que no
dejan de criticar la Verdad de Dios y a Su pueblo con ella),
para que la boca del enemigo sea cerrada y deje de hablar mal,
aunque esto no toque mi consciencia.

Con respecto al informe de que yo levanté a Dorcas Erbury de la muerte física, lo niego,
y condeno ese testimonio por estar fuera de la Verdad;
aunque no niego el poder que da vida a los muertos, el cual es la Palabra de vida eterna.
Esto lo digo,
para que llegue tan lejos como la ofensa contra el Espíritu de Verdad se haya extendido,
y para que todas las cargas de la Verdad sean quitadas; para que la Verdad,
la verdadera luz,
y todos los que caminan en ella sean absueltos y las obras de las tinieblas sean condenadas;
y también, para que todos los que todavía están en tinieblas no actúen en la noche,
sino que mantengan sus mentes quietas en Dios,
quien habita en la luz y no tiene comunión con los hacedores de iniquidad.
Pues si yo hubiera hecho esto cuando las tinieblas vinieron por primera vez sobre mí,
y no me hubiera dejado llevar por otros,
no habría corrido contra la Roca para ser quebrantado
(la Roca que me había sustentado por tanto tiempo,
de la que había bebido mucho, y de la que ahora bebo en medida).
¡A Él sea toda la gloria, y toda lengua Lo confiese Juez y Salvador y Dios sobre todo,
bendito para siempre!

--

[.offset]
Nayler le agregó a esto,
una exhortación al lector sobre cómo comportarse
si en algún momento llegaba a ser tentado a pecar,
y una advertencia a no confiar demasiado en dones, sabiduría y conocimiento;
luego concluyó con las siguientes palabras:

[.embedded-content-document.paper]
--

Estas cosas las aprendí en las profundidades y en secreto, cuando estaba solo,
y ahora las declaro abiertamente en el día de Tu misericordia,
oh Señor. ¡Gloria al Altísimo para siempre,
Al que hasta ahora me ha hecho libre para alabar Su justicia y Su misericordia;
y al Dios eterno, invisible, puro y que está sobre todo, sean el temor,
la obediencia y la gloria para siempre.
Amén!

[.signed-section-signature]
James Nayler

--

[.offset]
Él escribió otro documento en el que relata ampliamente,
cómo había llegado a caer por falta de vigilancia,
después de que había obtenido una gran medida de victoria
sobre el poder de Satanás por la gracia de Dios,
cuando caminaba diaria y humildemente en Su temor;
porque él había trabajado fielmente en el ministerio
del evangelio por algunos años. Pero lo notable es,
que, aunque él solía atravesar con gran audacia toda oposición,
al llegar a la ciudad de Londres (justo previo a su caída),
entró en ella con un temor muy grande, que nunca antes había experimentado en otro lugar,
al prever en el espíritu (como relata él) que algo le iba a suceder ahí,
pero no sabía qué:

[.embedded-content-document.paper]
--

Sin embargo,
yo en ese momento tenía (continúa él) la misma presencia
y poder que había experimentado antes,
en cada lugar o servicio al que había sido guiado por el Espíritu;
y al mantenerme en esa vida nunca había regresado sin la victoria en el Señor Jesucristo.
Pero al no tener cuidado de permanecer puro en todas las cosas,
de mantenerme humilde ante los movimientos de esa vida indestructible,
y de ser guiado por Él en todas las cosas internas y externas, y en su lugar,
al darle paso al razonamiento con respecto a algunas
cosas que en sí mismas no tenían aparente maldad,
mi mente fue arrastrada poco a poco tras bagatelas, vanidades y personas,
lo cual se afianzó en la parte de los afectos.
Así fue sacada mi mente de la constante vigilancia y del temor puro,
en el que yo había sido engendrado una vez.
Y tras haber perdido en gran medida mi propia guía, habiendo caído sobre mí la oscuridad,
busqué un lugar donde estar solo para llorar y clamar delante del Señor,
para poder encontrar Su rostro y recobrar mi condición.

Pero para entonces, mi adversario,
que había esperado durante mucho tiempo su oportunidad,
había entrado y se movía en todos los sentidos, de modo que no pude esconderme,
y recibí varios mensajes, unos verdaderos y otros falsos, como he visto desde entonces.
Y así, sabiendo que unos eran ciertos (a saber, que yo había perdido mi condición),
dejé entrar los falsos también,
y dejando ir lo poco que quedaba de la verdadera luz en mí,
me entregué por completo a ser conducido por otros,
cuya obra era en ese momento separarme de los hijos de luz,^
footnote:[Es decir, la Sociedad de Amigos.]
la cual fue hecha; aunque varios de ellos hicieron mucho para prevenirla,
y en amor tierno muchos se esforzaron por ayudarme.
Y después de que fui apartado de ellos,
el Señor Dios de mi vida envió a varios de Sus siervos con Su palabra tras de mí,
pidiéndome que regresara, todo lo cual fue rechazado.
Sí,
mi provocación contra el amor puro de Dios en ese
tiempo de tentación era sumamente grande;
sin embargo,
Él no me dejó. Y después de que me entregué bajo el poder de mi
adversario y las tinieblas se habían levantado sobre mí,
él prevaleció de manera tal,
que todas las cosas fueron torcidas y pervertidas haciéndome perder mi capacidad de ver,
oír o entender correctamente; únicamente tenía una esperanza y fe secretas en mi Dios,
a quien había servido anteriormente,
de que Él me llevaría a través y hasta el final de esto,
y que yo vería de nuevo el día de mi redención de debajo de todo ello.
Esto tranquilizaba mi alma en mi más grande tribulación.

--

[.offset]
El autor entonces,
exhortando seriamente a otros que podían caer también en gran tentación,
concluye con estas palabras:

[.embedded-content-document.paper]
--

¡Al que ha salvado mi alma de la muerte hasta ahora, y ha levantado mis pies del pozo,
sea la gloria por los siglos de los siglos! ¡Que toda alma atribulada confíe en Él,
pues Su misericordia permanece para siempre!

[.signed-section-signature]
James Nayler

--

[.offset]
Que él llegó a una recuperación perfecta después de haber sido tan engañado,
parece quedar claro por la siguiente acción de gracias a Dios por Sus misericordias,
la cual también publicó después de su caída:

[.embedded-content-document]
--

¡Mi corazón te alaba, oh mi Dios!
No permitas que Te olvide; que olvide lo que Tú has sido para mí en la noche,
por medio de Tu presencia en el día de prueba.
Cuando era acosado en las tinieblas, cuando había sido echado como un ave errante,
cuando era asaltado por fuertes tentaciones, Tu presencia me preservaba en secreto,
y en ese estado abatido Te sentía cerca de mí. Cuando las inundaciones intentaban arrastrarme,
Tú les ponías un límite hasta el que debían pasar.
Cuando mi camino atravesaba el mar y pasaba bajo las montañas, Tu presencia me acompañaba.
Cuando el peso de las colinas estaba sobre mí, Tú me sostenías, de lo contrario,
me habría hundido bajo la tierra.
Cuando me sentía completamente desamparado,
cuando la tribulación y la angustia estaban sobre mí día y noche,
y la tierra se había quedado sin fundamento;
cuando yo continuaba en el camino de ira y había cruzado las puertas del infierno;
cuando todos los consuelos estaban lejos y el que es mi enemigo había tomado dominio;
cuando había sido echado al pozo y era como alguien destinado a la muerte;
cuando estaba entre las piedras de molino y me sentía aplastado por el peso del adversario;
como un padre, Tú estabas conmigo, sí, la roca de Tu presencia estaba conmigo.
Cuando las bocas de los leones rugían contra mí y
el temor se apoderaba de mi alma en el pozo,
entonces yo te invocaba en la noche y mis clamores eran fuertes delante de Ti todos
los días. Tú me respondías desde Tu habitación y me liberabas desde Tu morada diciendo:
"`Yo te pondré sobre todos tus temores y levantaré tus pies sobre
la cabeza de opresión.`" Entonces yo creía y era fortalecido,
y Tu palabra era mi salvación.

Tú peleabas por mí cuando yo luchaba con la muerte,
y cuando las tinieblas querían encerrarme,
Tu luz brillaba sobre mí y Tu bandera se posaba sobre mi cabeza.
Cuando mi obra estaba en el horno y yo pasaba a través del fuego,
no fui consumido por Ti, aunque las llamas subían sobre mi cabeza.
Cuando contemplaba las espantosas visiones y estaba entre los espíritus feroces,
Tu fe me sostenía; de lo contrario, habría caído por el miedo.
Yo te veía y creía, y así el enemigo no podía prevalecer.

Cuando miro hacia atrás Tus obras, me asombro, y no veo fin a Tus alabanzas.
¡Gloria, gloria a Ti, dice mi alma;
que mi corazón siempre esté lleno de acción de gracias!
Mientras Tus obras permanezcan, ellas manifestarán Tu poder.
Luego colocaste el fundamento de la tierra y me guiaste bajo las aguas,
y en lo profundo me mostraste maravillas y Tu creación del mundo.
Me guiaste a salvo con Tu mano, mientras me mostrabas las columnas de la tierra.
Luego los cielos dieron lluvias, fueron cubiertos de tinieblas,
sus poderes fueron sacudidos y Tu gloria descendió. Sí,
Tú llenaste de alegría las partes bajas de la tierra
y se abrieron los manantiales de los valles,
y Tu lluvia descendió abundantemente, de modo que la tierra se llenó de virtud.
Hiciste brotar Tu planta y el alma sedienta se volvió como un huerto regado.
Entonces me sacaste del pozo y me colocaste a la vista de mis enemigos.
Proclamaste libertad para el cautivo y llamaste a mis conocidos
cerca de mí. Aquellos para quienes había sido un prodigio,
me miraron, y en Tu amor obtuve favor de los que me habían abandonado.
Entonces la alegría se tragó el dolor y abandoné todas mis dificultades, y dije:
"`Cuán bueno es que el hombre sea probado en la noche, para que conozca su insensatez;
para que toda boca se quede en silencio en Tu mano,
hasta que hagas que el hombre se conozca a sí mismo, hayas matado al jactancioso,
y le muestres la vanidad que aflige a Tu Espíritu.`"

[.signed-section-signature]
James Nayler

--

Esto claramente se muestra como una pieza poética,
ya que el autor hace uso de expresiones alegóricas en todo momento,
para indicar la gran angustia y tribulación bajo las que había estado,
al declarar cómo los poderes de las tinieblas habían prevalecido en él,
al punto de contristar al Espíritu de Dios,
poner una piedra de tropiezo en el camino del simple,
y hacer que el camino de la Verdad sea blasfemado.
Porque por los engaños de Satanás,
aceptó el honor idólatra de los que él debió haber reprendido inmediatamente;
y estaba tan atontado en su entendimiento,
que imaginaba que la inclinación y postración delante de él no era por su persona,
sino por Cristo.
Con esta opinión falsa se cegó por un tiempo,
hasta que le plació a Dios compadecerse de él y darle nuevamente luz,
después de que había sufrido un castigo inaudito por su transgresión,
como ya se ha relatado.
Y debido a que su pasada predicación contra la injusticia
había caído muy severamente sobre toda clase de personas,
en la que demostraba claramente y sin disfraz el deber cristiano de los gobernantes,
predicadores y abogados, el odio de sus enemigos era más fiero.
En realidad, varios que llevaban mucho tiempo enojados con él,
se aprovecharon de su crimen para vengarse bárbaramente de él,
haciéndolo sufrir un castigo cruel que en ninguna forma era proporcional a su transgresión.

Mientras él estaba en la casa de corrección,
escribió varios artículos manifestando su pesar y arrepentimiento por su crimen,
algunos de los cuales ya han sido insertados,
pero la siguiente carta hasta ahora llega a mi mano.
Es una carta a sus amigos, escrita con su propia mano:

[.embedded-content-document.letter]
--

[.salutation]
Queridos hermanos,

Mi corazón está quebrantado en este día por la ofensa que
les he ocasionado a la verdad y al pueblo de Dios,
y especialmente a ustedes, que me siguieron con tierno amor,
buscándome en fidelidad a Dios,
y cuyo amor rechacé. Pues estaba atado en aquello de lo que no podía salir,
hasta que la mano de Dios me sacó; Cuyo amor confieso ahora.
Les ruego que perdonen la manera con la que yo perversamente les pagué su amor
ese día. Dios conoce mi dolor por eso (desde que Él me dio la capacidad de verlo),
pues nunca debí ofender al Espíritu de Dios en ninguno o rechazar Su consejo.
Y ahora, ese artículo que ustedes han visto pesa mucho sobre mí,
y temo en gran manera ofender más o hacer algo incorrecto,
por medio de lo cual la inocente Verdad o el pueblo de Dios sufran,
o que yo desobedezca en ello.

A menos que el Señor los mantenga alejados de mí,
les ruego que no dejen que nada más les impida venir a mí,
para que yo pueda recibir la ayuda de ustedes en el Señor. En las misericordias de Jesucristo,
se los ruego, como si esta fuera su propia condición; no me olviden.

Les ruego que hablen con Henry Clarke o con cualquier otro a quien yo haya ofendido;
y por el poder de Dios y en el Espíritu de Jesucristo,
estoy dispuesto a confesar mi ofensa,
para que el amor de Dios se levante en todos los corazones como antes, si es Su voluntad,
pues Él es el único que puede remover lo que se interpone en el camino.
No pretendo encubrir nada; Dios es mi testigo en esto.

--

[.offset]
Él también escribió otras confesiones de sus faltas en ese tiempo, en una de las cuales,
entre otras, encuentro estas palabras:

[.embedded-content-document]
--

En cuanto a ustedes, tiernas plantas de mi Padre, que han sufrido debido a mí o conmigo,
en lo que el Señor ha permitido que se haga conmigo
en este tiempo de gran tribulación y tentación:
Que el Todopoderoso Dios de amor,
que ha contado cada suspiro y puesto cada lágrima en Su redoma,
se los recompense mil veces en sus pechos, en el día de necesidad,
cuando sean tratados y tentados.
Y mientras tanto, que Él cumpla nuestro gozo con Su amor, el cual ustedes buscan.
El Señor sabe que nunca estuvo en mi corazón hacerlos llorar;
el sufrimiento de ustedes es el más grande dolor que alguna vez me haya sobrevenido,
pues ustedes son inocentes en esto.

--

[.offset]
Cuando había terminado esta carta y puesto su nombre, escribió la siguiente posdata:

[.embedded-content-document]
--

Les ruego (a todos los que puedan) recibir esto como
desearían ser recibidos por el Señor;
y en cuanto a los demás,
que el Señor me dé paciencia para sufrir hasta que Él repare la brecha.

--

[.offset]
Mientras estaba en Bridewell,
le escribió al Parlamento que lo había castigado como blasfemo,
para hacerle saber su verdadera opinión acerca de Jesucristo.

[.embedded-content-document]
--

Sólo a Jesucristo (el Emanuel,
de cuyos sufrimientos declaran las Escrituras) confieso delante de los hombres.
Por Su causa he negado todo lo que era estimado para mí en este mundo,
a fin de poder ganarlo a Él, y ser hallado en Él y no en mí. Procuro servirle sólo a Él,
en espíritu, alma y cuerpo, noche y día, según la medida de gracia que obra en mí,
para que en mí Él sea glorificado, sea por la vida o por la muerte.

Pero atribuirle este nombre, poder y virtud a James Nayler,
o a lo que tuvo un principio y debe regresar al polvo,
o para que eso sea exaltado o adorado, para mí es gran idolatría,
y con el Espíritu de Jesucristo en mí, es condenado; cuyo Espíritu conduce a la humildad,
mansedumbre y paciencia.

Por tanto, habiendo recibido una oportunidad, estoy dispuesto con presteza,
en el temor de Dios el Padre y en honor a Jesucristo,
y con el fin de quitar todas las ofensas de cada corazón sencillo,
a declarar esto ante todo el mundo, sin malicia ni engaño, al encontrar diariamente,
que mi trabajo es buscar la paz en la verdad con todos los hombres, en dicho Espíritu.

[.signed-section-signature]
James Nayler

--

Después de esto,
al enterarse de que algunos lo habían perjudicado
por algo que él le había dicho al comité del Parlamento,
y entender la manera en que los hombres habían pervertido sus palabras,
escribió un documento en el que además hacía una
declaración acerca de su creencia en Cristo,
Sus sufrimientos, muerte, etc.
También denunció un artículo que alguien había publicado en forma anónima,
bajo el título [.book-title]#James Nayler`'s Recantation,#^
footnote:[Es decir, '`Retractación de James Nayler.`']
en el que se habían pervertido mucho sus palabras.

[.embedded-content-document.paper]
--

Con respecto +++[+++escribe él]
a la publicación de ese artículo llamado [.book-title]#James Nayler`'s Recantation,#
declaro que no fue escrito por mí, ni con mi conocimiento, y que no conozco, en absoluto,
al hombre que lo ha hecho.
Sé que fue hecho fuera de la Verdad y contra la Verdad, y por maldad hacia mí,
quienquiera que sea.
¡Qué el Señor Dios de mi vida, quien me ha preservado con vida en toda angustia,
vuelva esto para bien y perdone el mal!
Sin embargo, reconozco la medida de verdad que hay en este artículo,
porque después de que fui puesto en el hoyo en Bridewell,
me enteré de que ciertas personas que pretendían estar de mi lado,
habían realizado muchas actos desenfrenados.
Estas fueron afanosamente incitadas en aquel momento,
y con mucha violencia y actos indecorosos entraban
en las reuniones del pueblo del Señor llamado Cuáqueros,
con el propósito de entorpecer sus reuniones pacíficas.
Y sin embargo,
tomaban frecuentemente el nombre puro y santo de Dios y de Cristo en sus bocas,
por lo que el nombre del Señor fue muy deshonrado y Su Espíritu puro afligido,
porque causaban mucho desorden en muchos lugares de la nación para la deshonra de Jesucristo,
por lo cual sentí la ira de Dios.
Pero cuando comprendí que ellos tenían cierta influencia a través de mí,
usé todos los medios que pude para manifestarme contra ese espíritu maligno,
que bajo el nombre de Dios y de Cristo, estaba contra Dios y Cristo,
y contra Su verdad y Su pueblo.
Hace aproximadamente un año y medio escribí algo en rechazo a esos espíritus,
que me parece que el autor de ese artículo ha visto,
al que él le añadió los pensamientos de su propio corazón,
y así publicó su obra de tinieblas, y el pueblo no sabe qué hacer con eso.

Por tanto,
reconozco ese artículo hasta donde testifica contra esos espíritus inmundos y alborotadores,
y contra todas las acciones con las que el nombre
de Dios era deshonrado y Su Espíritu afligido.
Pero niego,
cuando sugiere que yo negué al Señor Jesucristo y
Su verdad que me llamó a salir del mundo,
o a Su pueblo a quien Él llamó a la luz.
Porque en la paciencia y tribulación de Jesucristo,
y con todos aquellos que tienen el poder de testificar hoy
contra todas las perversidades de este mundo presente,
soy uno en corazón y alma al máximo de mi fuerza,
hasta la venida del Señor Jesús sobre todo.
¡Qué el trono de mansedumbre y verdad sea puesto
encima de toda enemistad y engaño! Y ahora,
en la fe y poder de Cristo, me rindo para vivir o morir, para sufrir o regocijarme,
según el deseo de Dios, así sea, sin murmuración.

[.signed-section-signature]
James Nayler

--

Es innegable, que James Nayler sufrió un gran dolor y profunda humillación interna, y,
por tanto, debido a que Dios perdona las transgresiones del arrepentido,
las borra y no las recuerda más,
los amigos de James Nayler no pudieron hacer otra cosa más que perdonar su crimen,
y así recibir de nuevo en su sociedad a la oveja perdida.
Y tras obtener su libertad,
se comportó como un verdadero Cristiano--honesto e irreprensible en conducta,
y soportando pacientemente el oprobio de sus anteriores ofensas.

Cuando el rey Carlos II había ascendido al trono,
un hombre llamado Richard Blome publicó un libro
titulado, [.book-title]#The Fanatic History,#^
footnote:[Es decir, Historia de los Fanáticos.]
del que se decía que había sido publicado con la
aprobación de los teólogos ortodoxos (así llamados),
y dedicado por él al rey.
El libro atacaba principalmente a los Cuáqueros,
y estaba repleto de una gran cantidad de historias falsas,
junto con un relato muy exagerado de la caída de James Nayler.
Dado que Nayler estaba vivo para entonces,
cogió la pluma y respondió a las mentiras que contenía el libro
y que estaban relacionadas con él. Y como Richard Blome,
en su dedicación al rey había dicho:
"`Si su majestad no extiende su mano real de poder rápidamente para detenerlos,
ellos son tan numerosos y seductores, que, en poco tiempo,
esparcirán su veneno sobre la mayor parte de su reino,
lo que nadie sino una autoridad real podrá reprimir;`"
Nayler respondió con las siguientes palabras:

[.embedded-content-document]
--

¿Qué ha sucedido con tus armas espirituales?
¿No les han hablado tus maestros a las personas de
la fuerza de la Verdad y del poder de la piedad?
¿Has perdido ambos y ahora recurres al brazo de la carne,
para que los errores (como los llamas) sean reprimidos,
o de lo contrario tu esperanza se pierde y tu fe te falla?
¿Se despojaron alguna vez los ministros de Cristo de las
armas espirituales y recurrieron al brazo de la carne,
o a un arma carnal, para detener a los seductores?
Yo digo, no.
Los ministros de Cristo nunca hicieron esto,
sino que lucharon y vencieron la maldad espiritual con armas espirituales;
cortaron herejías, blasfemias y adoración falsa con armas espirituales;
y recorrieron el mundo limpiando las iglesias de Cristo
de todas esas cosas y derribándolas delante de ellos,
porque en realidad, nadie podía resistir el Espíritu por el que ellos hablaban.
Pero, los falsos sacerdotes y los falsos adoradores clamaban
a los gobernantes y al pueblo (como tú ahora) diciendo:
"`¡Ayúdennos, o todo será invadido,
porque estos que trastornan al mundo han llegado aquí!`"^
footnote:[Hechos 17:6; 21:28]
Y luego, la violenta multitud corría sobre ellos y se abalanzaba con varas y puños,
y asaltaba las casas que los hospedaban, tal como hacen ustedes,
y así los arrastraban delante de los gobernantes,
los ponían en prisión y a menudo los azotaban.
¿Es este tu clamor pidiendo ayuda contra un pueblo tan despreciable (según tu consideración)?
¡Qué! ¿Han predicado y luchado ustedes hasta quedar sin ninguna esperanza y fe,
de modo que ahora deben recibir una ayuda inmediata del rey,
o todo se perderá y será arrasado?
En verdad puede decirse entonces, que ustedes han sido malos atalayas y pastores ociosos.

Considerando que tú dices que tu libro es de gran importancia,
y por eso presumes haber nombrado al rey Carlos patrocinador del mismo,
y luego pides perdón por tu presunción; yo digo,
tú en verdad necesitas su perdón. Porque la esencia
de tu libro se compone de falsas acusaciones,
recogidas de libros escritos anteriormente contra nosotros,
todas las cuales han sido refutadas con respuestas claras e impresas varias veces.
A estas viejas acusaciones les has añadido unas cuantas nuevas,
tan falsas como las antiguas, y has espiado las fallas de unos pocos,
que se han lamentado delante de Dios por pecar y por darles
oportunidad a los enemigos de Dios de blasfemar.
Y en todo esto has incluido muchas cosas que fueron hechas y dichas por otros,
que no son de nuestra sociedad, ni lo fueron nunca.

En cuanto a los cargos que tienes contra James Nayler,
por la eterna misericordia de mi Dios,
todavía tengo existencia entre los vivos y aliento para responder por mí mismo,
a pesar de las intenciones de muchos espíritus crueles y sanguinarios,
que en el día de mi calamidad persiguieron mi alma
hasta la muerte (tanto como estaba en su poder),
cuando el adversario se había levantado sobre mí
y yo fui hecho una señal para una generación apóstata.
Estos se regocijaron contra este pedazo de polvo y tuvieron
poca piedad hacia el que había caído en sus manos;
en aquel momento Dios fue justo al entregarme por
causa de mi desobediencia (por un tiempo,
como un padre), para corregirme.
Sin embargo, estos no debieron haber buscado agravar las cosas contra mí,
como lo haces tú ahora, pues ese fue un día de profunda angustia,
que causó mucho dolor a mi alma, y el Dios misericordioso lo vio, quien,
aunque en ese momento estaba disgustado conmigo,
aun así Sus pensamientos no eran echarme para siempre, sino extender misericordia,
como lo ha hecho en este día. ¡Gloria eterna sea dada a Su nombre desde mi alma liberada!

Pero, oh hombre, u hombres, quienquiera que seas tú,
cuya obra es reunir los fallos del pueblo de Dios en el tiempo de su tentación,
o en la noche de su prueba, y agravarlos,
añadiéndoles la maldad y las mentiras maliciosas de tu propio corazón,
como has hecho en tu libro,
para así criticar la eterna y santa Verdad de Dios--yo te digo,
un espíritu maligno te ha puesto a trabajar,
y no haces más que mostrarte enemigo de Dios y de Sus hijos.
Porque es de gran tristeza para nosotros,
que alguno de nosotros haya dado razones para que se hable contra la Verdad;
y ha sido angustia de alma para todo el pueblo de Dios que siempre ha amado la justicia,
cuando causan así el gozo del malvado,
o alimentan al hombre que vigila la iniquidad y se sustenta de maldad.
Sin embargo, sepan esto los que son de ese linaje, Dios no desechará a Su pueblo,
y aunque a veces provoquen que Él los corrija,
incluso delante de sus adversarios (lo cual es una señal para ellos),
aun así Su enojo es sólo por un momento, y Su favor volverá como corrientes de vida.

Pero eso que era y es la tristeza de mi corazón,
fue la ventaja que tomó el enemigo en el tiempo de mi tentación,
contra el nombre de Cristo, Su Verdad y Su pueblo despreciado,
la cual ahora persigues con odio y mentiras,
al decir que se sospechaba que yo había tenido una mujer en la
cama conmigo la noche antes de mi sufrimiento en Bristol.
Pero en cuanto a esto, y de varias otras cosas falsas que has escrito en tu libro,
estoy limpio delante del Señor, de modo que no me afectan.
Y sólo busco a Dios, para en Su tiempo, ser limpiado de todas las ofensas ante Su vista,
el Único que conoce mi corazón en este asunto y en Cuya presencia puedo decir,
que nada es más odioso y gravoso para mi alma que algo de
la gloria o adoración que pertenece a Dios o a Cristo,
sea dada a carne y sangre, ya sea en mí o en otros.
En cuanto a qué me sucedió en ese tiempo, muchos hablan, pero pocos saben;
de modo que llevo el juicio de los tales, deseando que nadie, al juzgarme,
se condene ante los ojos de Dios, pues Sus consejos son grandes y profundos,
y el fin de Su obra es inescrutable, hasta que Él los revele.

A pesar de que yo o cualquier otro todavía puede
ser dejado sólo para ser tratado en la noche,
o alguno de nosotros caer completamente,
o cualquier otra cosa que no es correcta ante los
ojos de Dios ser hecha por algún hombre o mujer,
en vano recoges el pecado y vigilas la iniquidad
con el fin de arrojar eso sobre la luz de Cristo.
Pues la luz de Cristo es la que condena el pecado en toda mente alumbrada.
Sé por el Espíritu de Jesús, el cual he recibido y obra en mí, que tu obra no es Su obra,
ni es de Su semilla.
Tú no estás en Aquel que ama a Sus enemigos,
sino que el antiguo acusador de los hermanos es el que obra fuertemente en ti.
Y en esa luz que tú censuras,
eres visto como el hombre que fabrica mentiras y lleva '`calumnias
para derramar sangre.`' (Ezequiel 22:9)

--

Esto y mucho más escribió James Nayler para responder
a las mentiras de las que era acusado,
y para mostrar que la culpa de su crimen no debía ser en
ninguna forma atribuida a la doctrina que él profesaba,
como muchas personas envidiosas afirmaban en esos tiempos; a saber,
que su caída era consecuencia de la doctrina de que los hombres
deben prestarles atención a la gracia salvadora de Dios,
a la unción interna,
o a la luz con la que todo hombre que viene al mundo es alumbrado por Dios.

Después de su caída y restauración,
James Nayler escribió muchos documentos y cartas edificantes,
y siempre se mostró como un hombre de gran abnegación,
teniendo mucho cuidado de sus pasos.
George Whitehead, quien vivió con él en una casa en Londres en 1659 y 1660,
da el siguiente testimonio de él, "`que él fue revivido por el poder del Señor, y,
en una medida, restaurado a su antiguo testimonio,
el cual dio públicamente en varios lugares de la nación según el Señor lo capacitaba,
tanto en su ministerio como en sus escritos.
Y,`" añade Whitehead,
"`anduvo con mucho amor fraternal y simplicidad entre nosotros hasta el día de su muerte.`"

Finalmente, partiendo de la ciudad de Londres, cerca del fin del octavo mes de 1660,
se dirigió hacia el norte,
con la intención de regresar a casa con su esposa e hijos en Wakefield, en Yorkshire.
Un Amigo de Hertford lo vio en el camino,
sentado junto a la carretera en una postura muy seria y espiritual,
y lo invitó a su casa, pero Nayler dijo que no,
indicándole que estaba en su corazón seguir adelante.
Continuó a pie hasta Huntingdonshire donde otro Amigo lo
vio pasando por el pueblo en esa misma postura celestial,
a quien le parecía como si él hubiera sido redimido de la tierra,
y fuera un extranjero sobre ella, que buscaba una mejor patria y herencia.
Pero yendo algunas millas más allá de Huntingdon, se enfermó, habiendo sido,
como se dijo, robado en el camino y dejado atado.
No se sabe con certeza si él recibió algún daño físico,
pero al ser hallado en un campo por un campesino, cuando caía la noche,
lo llevaron o fue a casa de un Amigo en Holm, no muy lejos de King`'s Rippon,
donde Thomas Parnel, un médico, lo fue a visitar.
Cuando le preguntaron si quería que algunos amigos
de Londres fueran llamados a venir y verlo;
él dijo "`No,`" pero manifestó su interés y amor por ellos.
Cuando lo ayudaron a cambiar de posición en la cama, dijo,
"`ustedes han refrescado mi cuerpo, que el Señor refresque sus almas.`"
Aproximadamente dos horas antes de su muerte,
dijo las siguientes palabras en presencia de varios testigos:

[.embedded-content-document]
--

Hay un Espíritu que siento en mí, el cual se deleita en no hacer mal,
ni en vengar ningún mal, sino en soportar todas las cosas,
con la esperanza de disfrutar Lo suyo al final.
Su esperanza es sobrevivir a toda ira y conflicto, y fatigar toda exaltación y crueldad,
o cualquier cosa que sea de una naturaleza contraria a la Suya.
Él ve hasta el final de todas las tentaciones.
Así como no tiene mal en Sí mismo,
tampoco concibe ninguno en pensamiento contra alguien más. Si es traicionado, lo soporta;
porque Su fundamento y Su manantial es la misericordia y el perdón de Dios.
Su corona es la mansedumbre, su vida es el amor eterno no fingido.
Él toma Su reino con súplica y no con contienda, y lo guarda con humildad.
Sólo en Dios se regocija, aunque nadie más considere o reconozca Su vida.
Es concebido en aflicción y dado a luz sin que nadie lo compadezca;
no murmura en la angustia ni en la opresión. Nunca
se regocija sino a través de los sufrimientos,
porque el gozo del mundo lo asesina.
Lo encontré solo, abandonado.
Tengo comunión en Él con los que vivieron en cuevas y lugares desolados en la tierra,
quienes a través de la muerte obtuvieron esta resurrección y vida santa y eterna.

--

[.asterism]
'''

Así él partió de esta vida en paz con el Señor, cerca del Noveno mes de 1660,
a los 44 años de edad,
y fue enterrado en el cementerio de Thomas Parnel en King`'s Rippon.

[.offset]
Para concluir, tomo prestadas las palabras de Joseph Wyeth,
de cuyos escritos se extrae lo siguiente:

[.embedded-content-document]
--

James Nayler fue un hombre altamente favorecido por Dios con un buen grado de gracia,
la cual habría sido suficiente para él, si se hubiera mantenido en sus enseñanzas.
Mientras lo hizo, fue ejemplar en piedad y gran humildad,
fue poderoso en palabra y doctrina, y por tanto,
un instrumento en la mano de Dios para volver a muchos de las tinieblas a la luz,
y del poder de Satanás al poder de Dios.
Pero él, pobre hombre, por la grandeza de las revelaciones se exaltó desmedidamente,
y en dicha exaltación se desvió de la gracia y del Espíritu Santo de Dios,
quien había sido suficiente maestro para él. Entonces,
la ceguera se apoderó de él y se dejó estimar por
encima de lo que debía. Aquí se resbaló y cayó,
pero no de manera irrecuperable, pues le plació al Dios de infinita misericordia,
darle en el día de su aflicción una visión y un sentido de sus extravíos y caída,
y también un lugar de arrepentimiento.
Y él, con el pródigo, se humilló por su transgresión,
y le suplicó a Dios con verdadera contrición de alma,
que perdonara sus ofensas por medio de Jesucristo.
Yo creo firmemente que Dios lo perdonó, porque Él perdona al verdaderamente arrepentido.
Su pueblo lo recibió con gran gozo, porque el que se había descarriado de Dios,
regresaba a la casa del Padre,
y el que se había separado de ellos por causa de su iniquidad,
por medio del arrepentimiento y abandono de ella,
regresaba a la unidad de la fe y a la santa comunión con ellos en el evangelio de Cristo.
Y por este medio testifico,
que considero una señal particular del reconocimiento de Dios a Su pueblo,
traer de regreso a la unidad con ellos,
a un hombre que había caído tan peligrosamente como sucedió con James Nayler.
¡Aquí que nadie vitupere, sino que preste atención, no sea que, en la hora de tentación,
también se aparte! ¡Ni nadie diga con jactancia:
¡Dónde está tu Dios! ¡Ni nadie blasfeme suponiendo que Su
gracia no es suficiente para un hombre en tentación,
porque el tentado puede apartarse o descuidar la enseñanza de ella!
Porque vemos en David y en Pedro,
que así como sus transgresiones ocurrieron por haberse apartado de este guía infalible,
el Espíritu Santo, así su recuperación solo ocurriría por medio de Él.`"

--
